### ISSUE TITLE
Anbox can't launch in Ubuntu 16.10

### ISSUE THREAD

**Issue by edopudiyoraharjo** [anbox/anbox#104]
#Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the
list of open bugs at https://github.com/anbox/anbox/issues

**Anbox release (`anbox version`) and system info (`anbox system-info`):**

anbox system-info
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.10.5-041005-generic (kernel@tangerine) (gcc version 6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12) ) #201703220931 SMP Wed Mar 22 13:33:57 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp

**Description of the problem:**
anbox launch
[WW 2017-04-15 03:49:26] [launch.cpp:115@operator()] Stop waiting as we're already waiting for too long. Something is wrong
[WW 2017-04-15 03:49:26] [launch.cpp:116@operator()] with your setup and the container may have failed to boot.

**Expected:**

**Additional info:**
anbox session-manager
[EE 2017-04-15 03:48:48] [daemon.cpp:58@Run] bind: Address already in use

snap --version
snap    2.23.6
snapd   2.23.6
series  16
ubuntu  16.10
kernel  4.10.5-041005-generic
based : Ubuntu MATE but using KDE for daily used

**Comment by Gazzasore** [comment]
I have the exact same thing 

gazza@gazza-Alienware-18 ~ $ anbox system-info
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.10.10-041010-generic (kernel@gloin) (gcc version 6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12) ) #201704120813 SMP Wed Apr 12 12:15:07 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_cl_event2
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_swap_region
      - EGL_NOK_texture_from_pixmap
      - EGL_NV_post_sub_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: nouveau
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp

GTX 770 nVidia x 2 
Linux Mint Cinnamon 18.1

**Comment by freundTech** [comment]
> [EE 2017-04-15 03:48:48] [daemon.cpp:58@Run] bind: Address already in use

Sounds like another program is already using a port anbox is trying to use. 
Can you check `netstat -lnp` to see if any programm is bound to 127.0.0.1:6664 or 0.0.0.0:6664?
That's what anbox is using on my PC.

**Comment by Gazzasore** [comment]
This is what I found

Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 10.0.6.1:53             0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:8000          0.0.0.0:*               LISTEN      -               
tcp6       0      0 fd9d:e4dc:4e00:9e98::53 :::*                    LISTEN      -               
tcp6       0      0 fe80::4cb9:d1ff:fec7:53 :::*                    LISTEN      -               
tcp6       0      0 ::1:631                 :::*                    LISTEN      -               
udp        0      0 10.0.6.1:53             0.0.0.0:*                           -               
udp        0      0 127.0.1.1:53            0.0.0.0:*                           -               
udp        0      0 0.0.0.0:67              0.0.0.0:*                           -               
udp        0      0 0.0.0.0:68              0.0.0.0:*                           -               
udp        0      0 10.0.6.1:123            0.0.0.0:*                           -               
udp        0      0 192.168.1.51:123        0.0.0.0:*                           -               
udp        0      0 127.0.0.1:123           0.0.0.0:*                           -               
udp        0      0 0.0.0.0:123             0.0.0.0:*                           -               
udp        0      0 0.0.0.0:631             0.0.0.0:*                           -               
udp        0      0 0.0.0.0:45487           0.0.0.0:*                           -               
udp        0      0 0.0.0.0:45745           0.0.0.0:*                           -               
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           -               
udp6       0      0 fd9d:e4dc:4e00:9e98::53 :::*                                -               
udp6       0      0 fe80::4cb9:d1ff:fec7:53 :::*                                -               
udp6       0      0 fe80::4cb9:d1ff:fec:123 :::*                                -               
udp6       0      0 fd9d:e4dc:4e00:9e98:123 :::*                                -               
udp6       0      0 fe80::cf22:c2ba:da5:123 :::*                                -               
udp6       0      0 ::1:123                 :::*                                -               
udp6       0      0 :::123                  :::*                                -               
udp6       0      0 :::547                  :::*                                -               
udp6       0      0 :::49766                :::*                                -               
udp6       0      0 :::5353                 :::*                                -               
raw6       0      0 :::58                   :::*                    7           -               
raw6       0      0 :::58                   :::*                    7           -               
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path
unix  2      [ ACC ]     STREAM     LISTENING     34407    2731/cinnamon-sessi @/tmp/.ICE-unix/2731
unix  2      [ ACC ]     STREAM     LISTENING     36866    -                   /run/user/1000/keyring/pkcs11
unix  2      [ ACC ]     STREAM     LISTENING     28347    -                   @/tmp/dbus-j2wmj7Arji
unix  2      [ ACC ]     STREAM     LISTENING     28086    -                   @/tmp/.X11-unix/X0
unix  2      [ ACC ]     STREAM     LISTENING     560      -                   /run/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     11838    -                   /run/systemd/fsck.progress
unix  2      [ ACC ]     SEQPACKET  LISTENING     11846    -                   /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     35929    2825/dbus-daemon    @/tmp/dbus-hD4OXvJ153
unix  2      [ ACC ]     STREAM     LISTENING     11858    -                   /run/lvm/lvmetad.socket
unix  2      [ ACC ]     STREAM     LISTENING     11861    -                   /run/lvm/lvmpolld.socket
unix  2      [ ACC ]     STREAM     LISTENING     11863    -                   /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     LISTENING     29786    -                   /var/run/NetworkManager/private-dhcp
unix  2      [ ACC ]     STREAM     LISTENING     32860    -                   /run/anbox-container.socket
unix  2      [ ACC ]     STREAM     LISTENING     24926    -                   /var/run/clamav/clamav-milter.ctl
unix  2      [ ACC ]     STREAM     LISTENING     15206    -                   /sys/fs/cgroup/cgmanager/sock
unix  2      [ ACC ]     STREAM     LISTENING     35904    -                   /tmp/ssh-gIC6W9NnvQgE/agent.2731
unix  2      [ ACC ]     STREAM     LISTENING     28548    2627/systemd        /run/user/1000/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     28556    -                   /run/user/1000/keyring/control
unix  2      [ ACC ]     STREAM     LISTENING     21902    -                   /run/uuidd/request
unix  2      [ ACC ]     STREAM     LISTENING     21905    -                   /var/run/avahi-daemon/socket
unix  2      [ ACC ]     STREAM     LISTENING     21908    -                   /var/run/cups/cups.sock
unix  2      [ ACC ]     STREAM     LISTENING     21911    -                   /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     21914    -                   /run/snapd.socket
unix  2      [ ACC ]     STREAM     LISTENING     21916    -                   /run/snapd-snap.socket
unix  2      [ ACC ]     STREAM     LISTENING     35999    2849/pulseaudio     /run/user/1000/pulse/native
unix  2      [ ACC ]     STREAM     LISTENING     21919    -                   /run/acpid.socket
unix  2      [ ACC ]     STREAM     LISTENING     33186    -                   /run/user/1000/keyring/ssh
unix  2      [ ACC ]     STREAM     LISTENING     29867    -                   /var/run/gdm_socket
unix  2      [ ACC ]     STREAM     LISTENING     29366    2807/dbus-daemon    @/tmp/dbus-OXcNhB5h7Z
unix  2      [ ACC ]     STREAM     LISTENING     28087    -                   /tmp/.X11-unix/X0
unix  2      [ ACC ]     STREAM     LISTENING     34408    2731/cinnamon-sessi /tmp/.ICE-unix/2731

**Comment by Gazzasore** [comment]
I also get this 

~ $ systemctl status snap.anbox.container-manager
● snap.anbox.container-manager.service - Service for snap application anbox.cont
   Loaded: loaded (/etc/systemd/system/snap.anbox.container-manager.service; ena
   Active: active (running) since Sat 2017-04-15 20:15:44 ICT; 2min 1s ago
 Main PID: 1745 (anbox)
   CGroup: /system.slice/snap.anbox.container-manager.service
           ├─1745 /snap/anbox/15/usr/bin/anbox container-manager --data-path=/va
           └─2385 dnsmasq -u dnsmasq --strict-order --bind-interfaces --pid-file

Apr 15 20:15:44 gazza-Alienware-18 snap[1745]: tee: /sys/module/fuse/parameters/
Apr 15 20:15:44 gazza-Alienware-18 snap[1745]: Y
Apr 15 20:15:44 gazza-Alienware-18 snap[1745]: + echo WARNING: kernel doesn't su
Apr 15 20:15:44 gazza-Alienware-18 snap[1745]: WARNING: kernel doesn't support f
Apr 15 20:15:44 gazza-Alienware-18 snap[1745]: + exec /snap/anbox/15/usr/sbin/aa
Apr 15 20:15:47 gazza-Alienware-18 dnsmasq-dhcp[2385]: RTR-ADVERT(anboxbr0) fd9d
Apr 15 20:16:05 gazza-Alienware-18 dnsmasq-dhcp[2385]: RTR-ADVERT(anboxbr0) fd9d
Apr 15 20:16:11 gazza-Alienware-18 dnsmasq-dhcp[2385]: RTR-ADVERT(anboxbr0) fd9d
Apr 15 20:16:28 gazza-Alienware-18 dnsmasq-dhcp[2385]: RTR-ADVERT(anboxbr0) fd9d
Apr 15 20:16:46 gazza-Alienware-18 dnsmasq-dhcp[2385]: RTR-ADVERT(anboxbr0) fd9d
...skipping...
● snap.anbox.container-manager.service - Service for snap application anbox.cont
   Loaded: loaded (/etc/systemd/system/snap.anbox.container-manager.service; ena
   Active: active (running) since Sat 2017-04-15 20:15:44 ICT; 2min 1s ago
 Main PID: 1745 (anbox)
   CGroup: /system.slice/snap.anbox.container-manager.service
           ├─1745 /snap/anbox/15/usr/bin/anbox container-manager --data-path=/va
           └─2385 dnsmasq -u dnsmasq --strict-order --bind-interfaces --pid-file

Apr 15 20:15:44 gazza-Alienware-18 snap[1745]: tee: /sys/module/fuse/parameters/
Apr 15 20:15:44 gazza-Alienware-18 snap[1745]: Y
Apr 15 20:15:44 gazza-Alienware-18 snap[1745]: + echo WARNING: kernel doesn't su
Apr 15 20:15:44 gazza-Alienware-18 snap[1745]: WARNING: kernel doesn't support f
Apr 15 20:15:44 gazza-Alienware-18 snap[1745]: + exec /snap/anbox/15/usr/sbin/aa
Apr 15 20:15:47 gazza-Alienware-18 dnsmasq-dhcp[2385]: RTR-ADVERT(anboxbr0) fd9d
Apr 15 20:16:05 gazza-Alienware-18 dnsmasq-dhcp[2385]: RTR-ADVERT(anboxbr0) fd9d
Apr 15 20:16:11 gazza-Alienware-18 dnsmasq-dhcp[2385]: RTR-ADVERT(anboxbr0) fd9d
Apr 15 20:16:28 gazza-Alienware-18 dnsmasq-dhcp[2385]: RTR-ADVERT(anboxbr0) fd9d
Apr 15 20:16:46 gazza-Alienware-18 dnsmasq-dhcp[2385]: RTR-ADVERT(anboxbr0) fd9d
~
~
~
~
~
log file: tatus anbox



And 


~ $ anbox container-manager
[EE 2017-04-15 13:19:39] [container_manager.cpp:90@setup_mounts] Android image does not exist at path "/var/lib/anbox/android.img"


And 


~ $ sudo anbox session-manager
[sudo] password for gazza: 
[EE 2017-04-15 13:17:13] [daemon.cpp:58@Run] org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message

And


~ $ /snap/bin/anbox launch
[WW 2017-04-15 13:17:06] [launch.cpp:115@operator()] Stop waiting as we're already waiting for too long. Something is wrong
[WW 2017-04-15 13:17:06] [launch.cpp:116@operator()] with your setup and the container may have failed to boot.


And 

~ $ /snap/bin/anbox launch
[EE 2017-04-15 13:18:11] [launch.cpp:76@operator()] Anbox session manager service isn't running!

**Comment by arzenstar** [comment]
**i got, this "dnsmasq: failed to create listening socket for 10.0.6.1: Address already in use"**

-- Logs begin at Sun 2017-04-23 04:13:51 WIB, end at Sun 2017-04-23 04:39:41 WIB. --
Apr 23 04:39:00 putra-noted /usr/bin/snap[15330]: cmd.go:111: DEBUG: restarting into "/snap/core/current/usr/bin/snap"
Apr 23 04:39:00 putra-noted snap[15330]: + DATA_PATH=/var/snap/anbox/common/
Apr 23 04:39:00 putra-noted snap[15330]: + ROOTFS_PATH=/var/snap/anbox/common//rootfs
Apr 23 04:39:00 putra-noted snap[15330]: + ANDROID_IMG=/snap/anbox/15/android.img
Apr 23 04:39:00 putra-noted snap[15330]: + [ ! -e /snap/anbox/15/android.img ]
Apr 23 04:39:00 putra-noted snap[15330]: + start
Apr 23 04:39:00 putra-noted snap[15330]: + mkdir -p /var/snap/anbox/common/lxc
Apr 23 04:39:00 putra-noted snap[15330]: + /snap/anbox/15/bin/anbox-bridge.sh start
Apr 23 04:39:01 putra-noted snap[15330]: dnsmasq: failed to create listening socket for 10.0.6.1: Address already in use
Apr 23 04:39:01 putra-noted snap[15330]: Failed to setup anbox-bridge.
Apr 23 04:39:01 putra-noted snap[15330]: + echo Y
Apr 23 04:39:01 putra-noted snap[15330]: + sudo tee /sys/module/fuse/parameters/userns_mounts
Apr 23 04:39:01 putra-noted snap[15330]: tee: /sys/module/fuse/parameters/userns_mounts: Permission denied
Apr 23 04:39:01 putra-noted snap[15330]: Y
Apr 23 04:39:01 putra-noted snap[15330]: + echo WARNING: kernel doesn't support fuse in user namespaces
Apr 23 04:39:01 putra-noted snap[15330]: WARNING: kernel doesn't support fuse in user namespaces
Apr 23 04:39:01 putra-noted snap[15330]: + exec /snap/anbox/15/usr/sbin/aa-exec -p unconfined -- /snap/anbox/15/bin/anbox-wrapper.sh container-manager --data-path=/var/
Apr 23 04:39:01 putra-noted audit[15330]: AVC apparmor="ALLOWED" operation="open" profile="snap.anbox.container-manager" name="/proc/15330/attr/exec" pid=15330 comm="aa
Apr 23 04:39:01 putra-noted audit[15330]: AVC apparmor="ALLOWED" operation="change_onexec" profile="snap.anbox.container-manager" name="unconfined" pid=15330 comm="aa-e
lines 1-20/20 (END)

**Comment by mbnoimi** [comment]
I've similar issue on Linux Mint 18.1 x64

```
mbnoimi@mbnoimi-laptop ~ $ env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/anbox_anbox.desktop /snap/bin/anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
[WW 2017-05-14 17:10:05] [launch.cpp:115@operator()] Stop waiting as we're already waiting for too long. Something is wrong
[WW 2017-05-14 17:10:05] [launch.cpp:116@operator()] with your setup and the container may have failed to boot.
[EE 2017-05-14 17:10:05] [runtime.cpp:41@exception_safe_run] org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
mbnoimi@mbnoimi-laptop ~ $ anbox version
anbox 0.1.0
mbnoimi@mbnoimi-laptop ~ $ anbox system-info
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.4.0-38-generic (buildd@lgw01-58) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) ) #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_swap_region
      - EGL_NOK_texture_from_pixmap
      - EGL_NV_post_sub_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
mbnoimi@mbnoimi-laptop ~ $ 
```
