### ISSUE TITLE
No network if change bridge network

### ISSUE THREAD

**Issue by dacrhu** [anbox/anbox#1052]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: ` 
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
version: 4
snap-revision: 170
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Fedora
  version: 29 (Workstation Edition)
  snap-based: true
kernel:
  version: Linux version 4.20.7-200.fc29.x86_64 (mockbuild@bkernel04.phx2.fedoraproject.org) (gcc version 8.2.1 20181215 (Red Hat 8.2.1-6) (GCC)) #1 SMP Wed Feb 6 19:16:42 UTC 2019
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 3.2 Mesa 18.0.5
    extensions:
      - GL_ANDROID_extension_pack_es31a
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_disjoint_timer_query
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_read_format_bgra
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_framebuffer_fetch
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_shader_samples_identical
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_INTEL_conservative_rasterization
      - GL_INTEL_performance_query
      - GL_KHR_blend_equation_advanced
      - GL_KHR_blend_equation_advanced_coherent
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_KHR_texture_compression_astc_ldr
      - GL_KHR_texture_compression_astc_sliced_3d
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_image_formats
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_get_program_binary
      - GL_OES_gpu_shader5
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_primitive_bounding_box
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array
```

**Please describe your problem:**
If I change the ip range of bridge then anbox can not working with external networks.

- Can ping from anbox to bridge
- can't ping eth0 in host
- can ping from host to anbox

If I not change bridge IP (so I keep the 192.168.250.0/24), then working fine.
If I change the bridge IP then yes, I change the container parameters too.
```
snap set anbox bridge.address=192.168.249.1
snap set anbox bridge.netmask=255.255.249.0
snap set anbox bridge.network=192.168.249.1/24
snap set anbox container.network.address=192.168.249.2
snap set anbox container.network.gateway=192.168.249.1
snap set anbox container.network.dns=8.8.8.8

systemctl restart snap.anbox.container-manager.service

anbox0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.249.1  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fe80::66:3fff:fe8a:9ba  prefixlen 64  scopeid 0x20<link>
        ether 02:66:3f:8a:09:ba  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 70  bytes 7004 (6.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

x86_64:/ # ping 8.8.8.8 
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
From 192.168.249.2: icmp_seq=1 Destination Host Unreachable
From 192.168.249.2: icmp_seq=2 Destination Host Unreachable
^C
--- 8.8.8.8 ping statistics ---
4 packets transmitted, 0 received, +2 errors, 100% packet loss, time 3102ms
pipe 2
1|x86_64:/ # ping 192.168.249.1
PING 192.168.249.1 (192.168.249.1) 56(84) bytes of data.
64 bytes from 192.168.249.1: icmp_seq=1 ttl=64 time=0.260 ms
64 bytes from 192.168.249.1: icmp_seq=2 ttl=64 time=0.162 ms
64 bytes from 192.168.249.1: icmp_seq=3 ttl=64 time=0.164 ms


#Change to original

snap set anbox bridge.address=192.168.250.1
snap set anbox bridge.netmask=255.255.250.0
snap set anbox bridge.network=192.168.250.1/24
snap set anbox container.network.address=192.168.250.2
snap set anbox container.network.gateway=192.168.250.1
snap set anbox container.network.dns=8.8.8.8

# systemctl restart snap.anbox.container-manager.service

anbox0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.250.1  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fe80::8c79:7fff:fe70:32a0  prefixlen 64  scopeid 0x20<link>
        ether fe:ab:47:f3:1d:87  txqueuelen 1000  (Ethernet)
        RX packets 7  bytes 488 (488.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 224  bytes 14982 (14.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

x86_64:/ # ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=120 time=11.1 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=120 time=13.3 ms


```

**What were you expecting?:**

**Additional info:**
