### ISSUE TITLE
DKMS Binder Failed Linux Kernel 5.1

### ISSUE THREAD

**Issue by JoshuaDoes** [anbox/anbox#1130]
:heavy_check_mark: 1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
:heavy_check_mark: 2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
:heavy_check_mark: 3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
:heavy_check_mark: 4. Reproduce the error while debug logs enabled.
:heavy_check_mark: 5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

:heavy_check_mark: 
[anbox-system-diagnostics-2019-05-07.zip](https://github.com/anbox/anbox/files/3154388/anbox-system-diagnostics-2019-05-07.zip)
6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
joshuadoes@JoshuaX:~$ anbox system-info
libEGL warning: DRI2: failed to authenticate
version: 4
snap-revision: 173
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Linux Mint
  version: 19.1 (Tessa)
  snap-based: true
kernel:
  version: Linux version 5.1.0-050100-generic (kernel@gloin) (gcc version 8.3.0 (Ubuntu 8.3.0-7ubuntu1)) #201905052130 SMP Mon May 6 01:32:59 UTC 2019
  binder: false
  ashmem: false
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_context_flush_control
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image_base
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
  gles2:
    vendor: VMware, Inc.
    vendor: OpenGL ES 3.0 Mesa 18.0.5
    extensions:
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_base_instance
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_read_format_bgra
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_integer_mix
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_get_program_binary
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
```
</details>

**Please describe your problem:**
After installing the Linux kernel 5.1 on my Linux Mint 19.1 installation (where previously everything worked on the Linux kernel 5.0.9), I noticed a strange error during init where the service `Load Kernel Modules` did not start properly. I proceeded to run the command `systemctl status systemd-modules-load.service` as instructed and noticed that the `ashem` and `binder` kernel modules failed to load.

At this point I had to actually look up what they were as I had forgotten they were used for Anbox, and upon figuring out their use I proceeded to run the commands ``sudo apt purge anbox-modules-dkms` and `sudo apt install anbox-modules-dkms`.

```
joshuadoes@JoshuaX:~$ sudo apt install anbox-modules-dkms
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  anbox-modules-dkms
0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.
Need to get 38.0 kB of archives.
After this operation, 212 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/morphis/anbox-support/ubuntu bionic/main amd64 anbox-modules-dkms all 13 [38.0 kB]
Fetched 38.0 kB in 1s (62.1 kB/s)             
Selecting previously unselected package anbox-modules-dkms.
(Reading database ... 434254 files and directories currently installed.)
Preparing to unpack .../anbox-modules-dkms_13_all.deb ...
Unpacking anbox-modules-dkms (13) ...
Setting up anbox-modules-dkms (13) ...
Loading new anbox-1 DKMS files...
Building for 5.1.0-050100-generic
Building initial module for 5.1.0-050100-generic
ERROR (dkms apport): kernel package linux-headers-5.1.0-050100-generic is not supported
Error! Bad return status for module build on kernel: 5.1.0-050100-generic (x86_64)
Consult /var/lib/dkms/anbox/1/build/make.log for more information.
```

And the results of `make.log`:
```
DKMS make.log for anbox-1 for kernel 5.1.0-050100-generic (x86_64)
Tue May  7 16:03:53 EDT 2019
make: Entering directory '/var/lib/dkms/anbox/1/build/ashmem'
make -C /lib/modules/5.1.0-050100-generic/build V=0 M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-5.1.0-050100-generic'
  CC [M]  /var/lib/dkms/anbox/1/build/ashmem/deps.o
  CC [M]  /var/lib/dkms/anbox/1/build/ashmem/ashmem.o
  LD [M]  /var/lib/dkms/anbox/1/build/ashmem/ashmem_linux.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /var/lib/dkms/anbox/1/build/ashmem/ashmem_linux.mod.o
  LD [M]  /var/lib/dkms/anbox/1/build/ashmem/ashmem_linux.ko
make[1]: Leaving directory '/usr/src/linux-headers-5.1.0-050100-generic'
make: Leaving directory '/var/lib/dkms/anbox/1/build/ashmem'
make: Entering directory '/var/lib/dkms/anbox/1/build/binder'
make -C /lib/modules/5.1.0-050100-generic/build V=0 M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-5.1.0-050100-generic'
  CC [M]  /var/lib/dkms/anbox/1/build/binder/deps.o
  CC [M]  /var/lib/dkms/anbox/1/build/binder/binder.o
/var/lib/dkms/anbox/1/build/binder/binder.c:3382:11: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .fault = binder_vm_fault,
           ^~~~~~~~~~~~~~~
/var/lib/dkms/anbox/1/build/binder/binder.c:3382:11: note: (near initialization for ‘binder_vm_ops.fault’)
cc1: some warnings being treated as errors
scripts/Makefile.build:275: recipe for target '/var/lib/dkms/anbox/1/build/binder/binder.o' failed
make[2]: *** [/var/lib/dkms/anbox/1/build/binder/binder.o] Error 1
Makefile:1571: recipe for target '_module_/var/lib/dkms/anbox/1/build/binder' failed
make[1]: *** [_module_/var/lib/dkms/anbox/1/build/binder] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.1.0-050100-generic'
Makefile:8: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/var/lib/dkms/anbox/1/build/binder'
```

I have noticed that this issue exists with previous Linux kernels, including the exact error `error: initialization from incompatible pointer type` in relation to `binder_vm_fault`. I don't wish to proceed with attempting any patches previously made available for Linux kernels such as 4.11 which these issues were made for until I'm given the go-ahead to do something like that.

**What were you expecting?:**
I expected the package `anbox-modules-dkms` to compile and install the kernel module `binder` with success.

**Additional info:**
The sooner I can get this resolved, the saner I'll be about my system :P
