### ISSUE TITLE
Failed to start container, packaging Anbox for postmarketOS

### ISSUE THREAD

**Issue by PureTryOut** [anbox/anbox#1207]
<details>
<summary>anbox system-info output</summary>

```
version: local-/bin/sh: git: not found
cpu:
  arch:  x86
  brand: QEMU Virtual CPU version 2.5+
  features: 
os:
  name: postmarketOS
  version: 1.7.0-e2b8a72d
  snap-based: false
kernel:
  version: Linux version 5.1.5 (pmos@spaceblade) (gcc version 8.3.0 (Alpine 8.3.0)) #2-postmarketOS PREEMPT Mon Jul 29 11:08:10 UTC 2019
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_EXT_buffer_age
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_swap_buffers_with_damage
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image_base
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_swap_buffers_with_damage
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_WL_bind_wayland_display
      - EGL_WL_create_wayland_buffer_from_image
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

```
</details>

I'm porting/packaging Anbox for [postmarketOS](https://postmarketos.org). Progress is tracked [here](https://gitlab.com/postmarketOS/pmaports/merge_requests/432), and the steps we use to start Anbox is documented [here](https://gitlab.com/postmarketOS/pmaports/blob/feature/anbox/main/anbox/README-Anbox.md).

Currently I'm stuck starting the session manager.

```
[Renderer.cpp:141@initialize] Failed to create context: error=0x3005
[client.cpp:49@start] Failed to start container: Failed to start container: Failed to start container
[session_manager.cpp:148@operator()] Lost connection to container manager, terminating.
[daemon.cpp:61@Run] Container is not running
```

`Failed to start container` times 3 doesn't really tell me anything sadly. I'm not sure how to enable any debug mode.
