### ISSUE TITLE
Run anbox -> Settings app make ubuntu OS crash

### ISSUE THREAD

**Issue by jimupon** [anbox/anbox#1225]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
version: 4
snap-revision: 179
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
  features:
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 19.04 (Disco Dingo)
  snap-based: true
kernel:
  version: Linux version 5.0.0-27-generic (buildd@lgw01-amd64-016) (gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1)) #28-Ubuntu SMP Tue Aug 20 19:53:07 UTC 2019
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 3.2 Mesa 18.0.5
    extensions:
      - GL_ANDROID_extension_pack_es31a
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_disjoint_timer_query
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_read_format_bgra
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_framebuffer_fetch
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_shader_samples_identical
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_INTEL_conservative_rasterization
      - GL_INTEL_performance_query
      - GL_KHR_blend_equation_advanced
      - GL_KHR_blend_equation_advanced_coherent
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_KHR_texture_compression_astc_ldr
      - GL_KHR_texture_compression_astc_sliced_3d
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_image_formats
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_get_program_binary
      - GL_OES_gpu_shader5
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_primitive_bounding_box
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array

```
</details>

**Please describe your problem:**

Anbox ->  tap Settings app,  ubuntu crash and restart.

**What were you expecting?:**

make sure the anbox will not affect host OS.

**Additional info:**
The logcat logs while running settings app:

```
09-06 02:32:14.636   110   366 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.android.settings cmp=com.android.settings/.Settings} from uid 10000 on display 0
09-06 02:32:14.645    43    43 I MediaPlayerService: MediaPlayerService::getOMX
09-06 02:32:14.646   110   576 I OMXClient: MuxOMX ctor
09-06 02:32:14.646   110   576 E ACodec  : Unable to instantiate a decoder for type 'audio/vorbis' with err 0xfffffffe.
09-06 02:32:14.646   110   576 E ACodec  : signalError(omxError 0xfffffffe, internalError -2)
09-06 02:32:14.646   110   576 E MediaCodec: Codec reported err 0xfffffffe, actionCode 0, while in state 1
09-06 02:32:14.646   110   574 E SoundPool: Unable to load sample
09-06 02:32:14.649    43    98 I MediaPlayerService: MediaPlayerService::getOMX
09-06 02:32:14.649   110   577 I OMXClient: MuxOMX ctor
09-06 02:32:14.649   110   577 E ACodec  : Unable to instantiate a decoder for type 'audio/vorbis' with err 0xfffffffe.
09-06 02:32:14.649   110   577 E ACodec  : signalError(omxError 0xfffffffe, internalError -2)
09-06 02:32:14.649   110   577 E MediaCodec: Codec reported err 0xfffffffe, actionCode 0, while in state 1
09-06 02:32:14.650   110   574 E SoundPool: Unable to load sample
09-06 02:32:14.658   110   166 W AudioService: onLoadSoundEffects(), Error -2147483648 while loading samples
09-06 02:32:14.661    43    43 I MediaPlayerService: MediaPlayerService::getOMX
09-06 02:32:14.661   110   578 I OMXClient: MuxOMX ctor
09-06 02:32:14.661   110   578 E ACodec  : Unable to instantiate a decoder for type 'audio/vorbis' with err 0xfffffffe.
09-06 02:32:14.661   110   578 E ACodec  : signalError(omxError 0xfffffffe, internalError -2)
09-06 02:32:14.661   110   578 E MediaCodec: Codec reported err 0xfffffffe, actionCode 0, while in state 1
09-06 02:32:14.661   110   574 E SoundPool: Unable to load sample
09-06 02:32:14.796   254   580 W System  : ClassLoader referenced unknown path:
09-06 02:32:14.796   254   580 W System  : ClassLoader referenced unknown path: /system/priv-app/TeleService/lib/x86_64
09-06 02:32:14.803   254   580 D ApplicationLoaders: ignored Vulkan layer search path /system/priv-app/TeleService/lib/x86_64:/system/lib64:/vendor/lib64 for namespace 0x7facb5bf90f0
09-06 02:32:14.819   254   581 I IndexDatabaseHelper: Using schema version: 115
09-06 02:32:14.830   254   581 I IndexDatabaseHelper: Index is fine
09-06 02:32:14.837   254   581 D Index   : Locale 'en_US' is already indexed
09-06 02:32:14.844   254   583 V NFC     : this device does not have NFC support
09-06 02:32:14.910   254   585 W StorageManager: Could not read /sys/block/mmcblk0/size
09-06 02:32:14.910   254   585 W StorageManager: java.io.FileNotFoundException: /sys/block/mmcblk0/size (No such file or directory)
09-06 02:32:14.910   254   585 W StorageManager:        at java.io.FileInputStream.open(Native Method)
09-06 02:32:14.910   254   585 W StorageManager:        at java.io.FileInputStream.<init>(FileInputStream.java:146)
09-06 02:32:14.910   254   585 W StorageManager:        at java.io.FileInputStream.<init>(FileInputStream.java:99)
09-06 02:32:14.910   254   585 W StorageManager:        at android.os.storage.StorageManager.readLong(StorageManager.java:944)
09-06 02:32:14.910   254   585 W StorageManager:        at android.os.storage.StorageManager.getPrimaryStorageSize(StorageManager.java:935)
09-06 02:32:14.910   254   585 W StorageManager:        at com.android.settings.deviceinfo.StorageSettings$SummaryProvider.updateSummary(StorageSettings.java:510)
09-06 02:32:14.910   254   585 W StorageManager:        at com.android.settings.deviceinfo.StorageSettings$SummaryProvider.setListening(StorageSettings.java:502)
09-06 02:32:14.910   254   585 W StorageManager:        at com.android.settings.dashboard.SummaryLoader.setListeningW(SummaryLoader.java:192)
09-06 02:32:14.910   254   585 W StorageManager:        at com.android.settings.dashboard.SummaryLoader.-wrap2(SummaryLoader.java)
09-06 02:32:14.910   254   585 W StorageManager:        at com.android.settings.dashboard.SummaryLoader$Worker.handleMessage(SummaryLoader.java:253)
09-06 02:32:14.910   254   585 W StorageManager:        at android.os.Handler.dispatchMessage(Handler.java:102)
09-06 02:32:14.910   254   585 W StorageManager:        at android.os.Looper.loop(Looper.java:154)
09-06 02:32:14.910   254   585 W StorageManager:        at android.os.HandlerThread.run(HandlerThread.java:61)
09-06 02:32:14.920   254   580 W Bundle  : Key com.android.settings.dismiss expected String but value was a java.lang.Integer.  The default value <null> was returned.
09-06 02:32:14.920   254   580 W Bundle  : Attempt to cast generated internal exception:
09-06 02:32:14.920   254   580 W Bundle  : java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
09-06 02:32:14.920   254   580 W Bundle  :      at android.os.BaseBundle.getString(BaseBundle.java:995)
09-06 02:32:14.920   254   580 W Bundle  :      at com.android.settingslib.SuggestionParser.dismissSuggestion(SuggestionParser.java:104)
09-06 02:32:14.920   254   580 W Bundle  :      at com.android.settings.dashboard.DashboardAdapter.disableSuggestion(DashboardAdapter.java:294)
09-06 02:32:14.920   254   580 W Bundle  :      at com.android.settings.dashboard.DashboardSummary$SuggestionLoader.doInBackground(DashboardSummary.java:244)
09-06 02:32:14.920   254   580 W Bundle  :      at com.android.settings.dashboard.DashboardSummary$SuggestionLoader.doInBackground(DashboardSummary.java:238)
09-06 02:32:14.920   254   580 W Bundle  :      at android.os.AsyncTask$2.call(AsyncTask.java:305)
09-06 02:32:14.920   254   580 W Bundle  :      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-06 02:32:14.920   254   580 W Bundle  :      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
09-06 02:32:14.920   254   580 W Bundle  :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-06 02:32:14.920   254   580 W Bundle  :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-06 02:32:14.920   254   580 W Bundle  :      at java.lang.Thread.run(Thread.java:761)
09-06 02:32:14.968   254   585 W ProcStatsManager: No process com.android.providers.calendar/10003 for service com.android.providers.calendar.EmptyService
09-06 02:32:14.968   254   585 W ProcStatsManager: No process com.android.providers.calendar/10003 for service com.android.providers.calendar.CalendarProviderIntentService
09-06 02:32:14.968   254   585 W ProcStatsManager: No process android.process.media/10008 for service com.android.providers.media.MediaScannerService
09-06 02:32:14.968   254   585 W ProcStatsManager: No process com.android.calendar/10027 for service com.android.calendar.alerts.InitAlarmsService
09-06 02:32:14.968   254   585 W ProcStatsManager: No process com.android.calendar/10027 for service com.android.calendar.alerts.AlertService
09-06 02:32:14.968   254   585 W ProcStatsManager: No process com.android.onetimeinitializer/10013 for service com.android.onetimeinitializer.OneTimeInitializerService
09-06 02:32:14.968   254   585 W ProcStatsManager: No process android.ext.services/10009 for service android.ext.services.notification.Ranker
09-06 02:32:14.968   254   585 W ProcStatsManager: No process org.anbox.appmgr/10000 for service org.anbox.appmgr.LauncherService
09-06 02:32:14.968   254   585 W ProcStatsManager: No process com.android.smspush/10047 for service com.android.smspush.WapPushManager
09-06 02:32:14.968   254   585 W ProcStatsManager: No process com.android.email/10034 for service com.android.email.service.EmailBroadcastProcessorService
09-06 02:32:14.970   110   155 D WifiNative-HAL: Failing getSupportedFeatureset because HAL isn't started
09-06 02:32:14.970   110   367 E BluetoothAdapter: Bluetooth binder is null
09-06 02:32:14.970   110   367 E BatteryStatsService: no controller energy info supplied
09-06 02:32:14.971   239   239 E PhoneInterfaceManager: [PhoneIntfMgr] queryModemActivityInfo: Empty response
09-06 02:32:14.971   110   367 E KernelCpuSpeedReader: Failed to read cpu-freq: /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state (No such file or directory)
09-06 02:32:14.971   110   367 E KernelUidCpuTimeReader: Failed to read uid_cputime: /proc/uid_cputime/show_uid_stat (No such file or directory)
09-06 02:32:14.971   110   367 E BatteryStatsService: modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}

```
