### ISSUE TITLE
Anbox session doesn't start

### ISSUE THREAD

**Issue by TrevtheForthDev** [anbox/anbox#1284]
** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
version: local-/bin/sh: git: not found
cpu:
  arch:  x86
  brand:        Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
os:
  name: NixOS
  version: 19.09.1160.a22b0189002 (Loris)
  snap-based: false
kernel:
  version: Linux version 5.3.9 (nixbld@localhost) (gcc version 8.3.0 (GCC)) #1-NixOS SMP Wed Nov 6 12:09:35 UTC 2019
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 3.0 Mesa 19.1.5
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_rgtc
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_texture_3D
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float
      - GL_EXT_texture_sRGB_decode
      - GL_OES_EGL_image
      - GL_OES_depth_texture
      - GL_OES_packed_depth_stencil
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_NV_conditional_render
      - GL_OES_get_program_binary
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_EXT_frag_depth
      - GL_NV_fbo_color_attachments
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_robustness
      - GL_EXT_texture_rg
      - GL_EXT_unpack_subimage
      - GL_NV_draw_buffers
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_EXT_draw_buffers
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_KHR_robustness
      - GL_OES_depth_texture_cube_map
      - GL_OES_required_internalformat
      - GL_OES_surfaceless_context
      - GL_EXT_color_buffer_float
      - GL_EXT_sRGB_write_control
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_integer_mix
      - GL_INTEL_performance_query
      - GL_EXT_base_instance
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_texture_border_clamp
      - GL_KHR_blend_equation_advanced
      - GL_KHR_context_flush_control
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_multisample_interpolation
      - GL_OES_texture_border_clamp
      - GL_EXT_blend_func_extended
      - GL_EXT_float_blend
      - GL_KHR_no_error
      - GL_OES_EGL_image_external_essl3
      - GL_EXT_clip_cull_distance
      - GL_EXT_disjoint_timer_query
      - GL_EXT_texture_compression_s3tc_srgb
      - GL_MESA_shader_integer_functions
      - GL_KHR_parallel_shader_compile
      - GL_EXT_shader_framebuffer_fetch_non_coherent
      - GL_EXT_texture_sRGB_R8
      - GL_EXT_depth_clamp
      - GL_EXT_texture_query_lod
```
</details>

**Please describe your problem:**
I have all the kernel modules loaded, an android image, etc, but when I run `anbox session-manager` I get the output
 ``` [ 2019-11-10 16:12:04] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to start container
[ 2019-11-10 16:12:04] [session_manager.cpp:148@operator()] Lost connection to container manager, terminating.
[ 2019-11-10 16:12:04] [daemon.cpp:61@Run] Container is not running
[WW 2019-11-10 16:12:04] [session_manager.cpp:148@operator()] Lost connection to container manager, terminating.
Stack trace (most recent call last) in thread 2799:
#7    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in
#6    Object "/nix/store/pnd2kl27sag76h23wa5kl95a76n3k9i3-glibc-2.27/lib/libc.so.6", at 0x7f2aedcae22e, in clone
#5    Object "/nix/store/pnd2kl27sag76h23wa5kl95a76n3k9i3-glibc-2.27/lib/libpthread.so.0", at 0x7f2aee427ef6, in
#4    Object "/nix/store/4l35nqpaiwzhfafrpby1xf7kfik7ai7c-gcc-8.3.0-lib/lib/libstdc++.so.6", at 0x7f2aee1e0b0e, in
#3    Object "/run/current-system/sw/bin/anbox", at 0x54c467, in
#2    Object "/run/current-system/sw/bin/anbox", at 0x5736fd, in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, std::function<void (boost::system::error_code const&, unsigned long)> >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long)
#1    Object "/run/current-system/sw/bin/anbox", at 0x50a057, in anbox::container::Client::on_read_size(boost::system::error_code const&, unsigned long)
#0    Object "/run/current-system/sw/bin/anbox", at 0x4f89eb, in
Segmentation fault (Address not mapped to object [0x6])
```

When I run `anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity` it yields the error:
 ```[ 2019-11-10 16:14:00] [daemon.cpp:61@Run] Application manager service is not running yet```

**What were you expecting?:**
Anbox to work I suppose

**Additional info:**
- system: `"x86_64-linux"`
 - host os: `Linux 5.3.9, NixOS, 19.09.1160.a22b0189002 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(trev): `""`
 - channels(root): `"nixos-19.09.1160.a22b0189002, unstable-19.09pre186857.239fffc90d7, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
