### ISSUE TITLE
No ADB devices listed

### ISSUE THREAD

**Issue by yalok** [anbox/anbox#130]
**Anbox release (`anbox version`) and system info (`anbox system-info`):**
```
anbox 0.1.0
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.10.0-19-generic (buildd@lcy01-13) (gcc version 6.3.0 20170321 (Ubuntu 6.3.0-10ubuntu1) ) #21-Ubuntu SMP Thu Apr 6 17:04:57 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
```

**Description of the problem:**
No ADB devices found
```
 ~  adb devices
List of devices attached
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
 ~  sudo adb devices
List of devices attached


```

**Expected:**
Be able to see one device.

**Additional info:**
```
# sudo ANBOX_LOG_LEVEL=debug anbox container-manager --data-path=/var/snap/anbox/common/ --android-image=/snap/anbox/15/android.img
[DD 2017-04-17 14:55:30] [service.cpp:49@create] Everything setup. Waiting for incoming connections.

[DD 2017-04-17 14:57:25] [service.cpp:76@new_client] Got connection from pid 6699
[DD 2017-04-17 14:57:45] [service.cpp:76@new_client] Got connection from pid 6721
```
These connection lines above appeared after I tried launching session-amanger:
```
# sudo ANBOX_LOG_LEVEL=debug anbox session-manager
[DD 2017-04-17 14:57:46] [gl_renderer_server.cpp:82@GLRendererServer] Using GLES-to-GL translator for rendering
[DD 2017-04-17 14:57:46] [Renderer.cpp:113@initialize] EGL doesn't support surfaceless context
[DD 2017-04-17 14:57:46] [Renderer.cpp:249@initialize] Successfully initialized EGL
[EE 2017-04-17 14:57:46] [daemon.cpp:58@Run] org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
```
Strange things noticed:
```
# sudo ls -l /var/snap/anbox/common/logs/container.log 
ls: cannot access '/var/snap/anbox/common/logs/container.log': No such file or directory
```
No logs and **anbox** command not found without sudo.
