### ISSUE TITLE
Please update anbox-support PPA for Ubuntu 19.10

### ISSUE THREAD

**Issue by blackoutworm** [anbox/anbox#1316]
PPA only supports distro versions Disco and lower.
Please fix this as I really would like to install Anbox. Thank you.

**Comment by lengau** [comment]
I'm not an anbox developer, but [the documentation](https://docs.anbox.io/userguide/install_kernel_modules.html) says:

> Starting with Ubuntu 19.04 binder and ashmem are now build with the standard Ubuntu kernel (>= 5.0) and you don’t have to install the modules from the PPA anymore.

Does anbox not work when you install the snap?

**Comment by morphis** [comment]
Please use the latest snap from the edge or beta channel which comes with support for binderfs (https://brauner.github.io/2019/01/09/android-binderfs.html) which is included in the generic Ubuntu kernel since 19.04. The PPA isn't going to be updated for 19.10 or later.

**Comment by Entropy512** [comment]
The latest snap from the edge channel does not have the binderfs support that was merged seven days ago despite your comment that it does.  Even after removing and reinstalling the anbox snap and rebooting the machine, anbox system-info still reports that binder capability is false on an Ubuntu 19.10 machine with both binder and ashmem modules loaded:

```
version: 4
snap-revision: 186
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 19.10 (Eoan Ermine)
  snap-based: true
kernel:
  version: Linux version 5.3.0-26-generic (buildd@lgw01-amd64-013) (gcc version 9.2.1 20191008 (Ubuntu 9.2.1-9ubuntu2)) #28-Ubuntu SMP Wed Dec 18 05:37:46 UTC 2019
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

```
