### ISSUE TITLE
Can't start app manager on a laptop with Nvidia On-Demand configured

### ISSUE THREAD

**Issue by petevg** [anbox/anbox#1337]
[anbox-system-diagnostics-2020-01-21.zip](https://github.com/anbox/anbox/files/4089711/anbox-system-diagnostics-2020-01-21.zip)

<details>
<summary>anbox system-info output</summary>

```
version: 4
snap-revision: 186
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 20.04 LTS (Focal Fossa)
  snap-based: true
kernel:
  version: Linux version 5.4.0-9-generic (buildd@lcy01-amd64-023) (gcc version 9.2.1 20191130 (Ubuntu 9.2.1-21ubuntu1)) #12-Ubuntu SMP Mon Dec 16 22:34:19 UTC 2019
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
```
</details>

**Description:**

I haven't been able to successfully launch anbox appmgr since upgrading to Eoan and setting up Nvidia On-demand (allows on the fly, per application switching between my laptop's discrete and integrated gpu).

**What were you expecting?:**

I was expecting to be able to launch anbox's app manager and experiment with android apps :-)

**Additional info:**

I'm able to get the appmgr splash screen to come up if I run it in a wrapper script that tells it to use my discrete gpu. It crashes before displaying my android "desktop", however.

The wrapper script just contains the following invocation:

__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME="nvidia" __VK_LAYER_NV_optimus=NVIDIA_only TERM=xterm $@
