### ISSUE TITLE
Random Crashes and Errors (Looks like memory errors)

### ISSUE THREAD

**Issue by CodeJoule** [anbox/anbox#1341]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
Nope, haven't found anything else.
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `
I have the directory `/snap/bin/` but nothing is there.
6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
version: local-56c25f1
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Manjaro Linux
  version: 
  snap-based: false
kernel:
  version: Linux version 4.19.97-1-MANJARO (builder@3e86ad599b2d) (gcc version 9.2.0 (GCC)) #1 SMP Sat Jan 18 00:17:24 UTC 2020
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 3.2 Mesa 19.3.2
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_rgtc
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_texture_3D
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float
      - GL_EXT_texture_sRGB_decode
      - GL_OES_EGL_image
      - GL_OES_depth_texture
      - GL_OES_packed_depth_stencil
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_NV_conditional_render
      - GL_OES_get_program_binary
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_EXT_frag_depth
      - GL_NV_fbo_color_attachments
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_OES_viewport_array
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_robustness
      - GL_EXT_texture_rg
      - GL_EXT_unpack_subimage
      - GL_NV_draw_buffers
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_EXT_draw_buffers
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_KHR_robustness
      - GL_KHR_texture_compression_astc_ldr
      - GL_OES_depth_texture_cube_map
      - GL_OES_required_internalformat
      - GL_OES_surfaceless_context
      - GL_EXT_color_buffer_float
      - GL_EXT_sRGB_write_control
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_framebuffer_fetch
      - GL_EXT_shader_implicit_conversions
      - GL_EXT_shader_integer_mix
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_INTEL_conservative_rasterization
      - GL_INTEL_performance_query
      - GL_ANDROID_extension_pack_es31a
      - GL_EXT_base_instance
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_gpu_shader5
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_render_snorm
      - GL_EXT_shader_io_blocks
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_norm16
      - GL_EXT_texture_view
      - GL_KHR_blend_equation_advanced
      - GL_KHR_blend_equation_advanced_coherent
      - GL_KHR_context_flush_control
      - GL_KHR_robust_buffer_access_behavior
      - GL_NV_image_formats
      - GL_OES_copy_image
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_gpu_shader5
      - GL_OES_primitive_bounding_box
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_texture_view
      - GL_EXT_blend_func_extended
      - GL_EXT_buffer_storage
      - GL_EXT_float_blend
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_shader_samples_identical
      - GL_KHR_no_error
      - GL_KHR_texture_compression_astc_sliced_3d
      - GL_NV_fragment_shader_interlock
      - GL_OES_EGL_image_external_essl3
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_shader_image_atomic
      - GL_EXT_clip_cull_distance
      - GL_EXT_disjoint_timer_query
      - GL_EXT_texture_compression_s3tc_srgb
      - GL_MESA_shader_integer_functions
      - GL_EXT_clip_control
      - GL_EXT_texture_compression_bptc
      - GL_KHR_parallel_shader_compile
      - GL_EXT_shader_framebuffer_fetch_non_coherent
      - GL_EXT_texture_sRGB_R8
      - GL_EXT_texture_shadow_lod
      - GL_MESA_framebuffer_flip_y
      - GL_NV_compute_shader_derivatives
      - GL_EXT_demote_to_helper_invocation
      - GL_EXT_depth_clamp
      - GL_EXT_texture_query_lod
```
</details>

**Please describe your problem:**
I started installing many miscellaneous apps from Google Play, then it crashed and it keeps crashing every time I run `anbox session-manager --single-window --window-size=1366,713`. In the terminal, many weird memory-related errors appear. Because of this, Anbox crashes and I am unable to use it.

**What were you expecting?:**
No errors. :slightly_smiling_face: 

**Additional info:**
Could you guys also help me figure out how to reset the Anbox filesystem? I think something I installed may be causing the problem, so if someone could tell me how to "factory reset" Anbox, I would appreciate it. If needed I could try installing the snap version. Previously, before installing these extra apps, everything worked absolutely fine (and it impressively outdoes Bluestacks in terms of speed!)

I can click on a few things right after I start it up again, but it crashes very soon afterwards.
Here are a few examples of the various errors:
<details>
<summary>Example 1</summary>

```
user@system ~> anbox session-manager --single-window --window-size=1366,713
Stack trace (most recent call last) in thread 21313:
#9    Object "", at 0xffffffffffffffff, in 
#8    Object "/usr/lib/libc-2.30.so", at 0x7fb0270402d2, in __clone
#7    Object "/usr/lib/libpthread-2.30.so", at 0x7fb0273f34ce, in start_thread
double free or corruption (out)
malloc(): invalid size (unsorted)
fish: “anbox session-manager --single-…” terminated by signal SIGABRT (Abort)
user@system ~>
```
</details>
<details>
<summary>Example 2</summary>

```
user@system ~> anbox session-manager --single-window --window-size=1366,713
Stack trace (most recent call last) in thread 22155:
#9    Object "", at 0xffffffffffffffff, in 
#8    Object "/usr/lib/libc-2.30.so", at 0x7fca587932d2, in __clone
#7    Object "/usr/lib/libpthread-2.30.so", at 0x7fca58b464ce, in start_thread
#6    Source "/build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc", line 80, in execute_native_thread_routine [0x7fca58944ee3]
#5    Object "/usr/bin/anbox", at 0x556fe2e4d8b5, in 
#4    Object "/usr/bin/anbox", at 0x556fe2dfe55e, in boost::asio::detail::scheduler::run(boost::system::error_code&)
#3    Object "/usr/bin/anbox", at 0x556fe2e76c1d, in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, std::function<void (boost::system::error_code const&, unsigned long)>, boost::asio::detail::io_object_executor<boost::asio::executor> >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long)
#2    Object "/usr/bin/anbox", at 0x556fe2e34e14, in anbox::network::SocketConnection::on_read_size(boost::system::error_code const&, unsigned long)
#1    Object "/usr/bin/anbox", at 0x556fe2e44da2, in anbox::rpc::MessageProcessor::process_data(std::vector<unsigned char, std::allocator<unsigned char> > const&)
#0    Object "/usr/lib/libc-2.30.so", at 0x7fca587f89de, in __memmove_avx_unaligned_erms
Segmentation fault (Invalid permissions for mapped object [0x7fca041f8000])
fish: “anbox session-manager --single-…” terminated by signal SIGSEGV (Address boundary error)
user@system ~>
```
</details>
<details>
<summary>Example 3</summary>

```
user@system ~> anbox session-manager --single-window --window-size=1366,713
Stack trace (most recent call last) in thread 22934:
#9    Object "", at 0xffffffffffffffff, in 
#8    Object "/usr/lib/libc-2.30.so", at 0x7fc1238322d2, in __clone
#7    Object "/usr/lib/libpthread-2.30.so", at 0x7fc123be54ce, in start_thread
#6    Source "/build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc", line 80, in execute_native_thread_routine [0x7fc1239e3ee3]
#5    Object "/usr/bin/anbox", at 0x55cc476f38b5, in 
#4    Object "/usr/bin/anbox", at 0x55cc476a455e, in boost::asio::detail::scheduler::run(boost::system::error_code&)
#3    Object "/usr/bin/anbox", at 0x55cc4771cc1d, in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, std::function<void (boost::system::error_code const&, unsigned long)>, boost::asio::detail::io_object_executor<boost::asio::executor> >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long)
#2    Object "/usr/bin/anbox", at 0x55cc476dae14, in anbox::network::SocketConnection::on_read_size(boost::system::error_code const&, unsigned long)
#1    Object "/usr/bin/anbox", at 0x55cc476eada2, in anbox::rpc::MessageProcessor::process_data(std::vector<unsigned char, std::allocator<unsigned char> > const&)
#0    Object "/usr/lib/libc-2.30.so", at 0x7fc1238979e3, in __memmove_avx_unaligned_erms
Segmentation fault (Invalid permissions for mapped object [0x7fc0cc6e3000])
fish: “anbox session-manager --single-…” terminated by signal SIGSEGV (Address boundary error)
user@system ~>
```
</details>
By the way, that "fish" stuff is the shell I'm using.
