### ISSUE TITLE
Anbox won't launch : error with cmd_run.go:529: WARNING: XAUTHORITY

### ISSUE THREAD

**Issue by Francefire** [anbox/anbox#1373]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
No protocol specified
version: 4
snap-revision: 187
cpu:
  arch:  x86
  brand:        Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
os:
  name: KDE neon
  version: 5.18
  snap-based: true
kernel:
  version: Linux version 5.3.0-40-generic (buildd@lcy01-amd64-024) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

```
</details>

**Please describe your problem:**
When I try to launch anbox's app manager I get the error listed above. 

**What were you expecting?:**
I was expecting anbox to launch the app manager

**Additional info:**
When I launch anbox app manager via the command 
`anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity`
The app shows up displaying "Starting..." and closes itself

[anbox-system-diagnostics-2020-02-27.zip](https://github.com/anbox/anbox/files/4263829/anbox-system-diagnostics-2020-02-27.zip)
