### ISSUE TITLE
Chrome launches and only displays white screen. Cannot close window.

### ISSUE THREAD

**Issue by trumpjk** [anbox/anbox#1393]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
version: 4
snap-revision: 186
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  features:
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 18.04.4 LTS (Bionic Beaver)
  snap-based: true
kernel:
  version: Linux version 5.3.0-42-generic (buildd@lcy01-amd64-019) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions:
      - n/a
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

```
</details>

**Please describe your problem:**
Installed Google Play. Used Google Play to install Google Chrome. When I launch Chrome I get a white screen. I am not able to close the white screen. I tried using Firefox and it works without issue.

**What were you expecting?:**
Expect to launch Chrome and be able to use it.

**Additional info:**
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
[anbox-system-diagnostics-2020-03-20.zip](https://github.com/anbox/anbox/files/4360110/anbox-system-diagnostics-2020-03-20.zip)
