### ISSUE TITLE
Anbox doesn't work with new version of lxc on Arch Linux

### ISSUE THREAD

**Issue by Milkysilk** [anbox/anbox#1397]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
There are a few, but they're different problems
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
I use Pacman, the package manager for Arch Linux, and install anbox from aur
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
Ditto
4. Reproduce the error while debug logs enabled.
[launch.cpp:214@operator()] Session manager failed to become ready
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `
The same as 2 and 3
6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
version: local-3ed2e6d
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Arch Linux
  version: 
  snap-based: false
kernel:
  version: Linux version 5.4.28-1-lts (linux-lts@archlinux) (gcc version 9.3.0 (Arch Linux 9.3.0-1)) #1 SMP Wed, 25 Mar 2020 13:04:22 +0000
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 3.2 Mesa 19.3.4
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_rgtc
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_texture_3D
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float
      - GL_EXT_texture_sRGB_decode
      - GL_OES_EGL_image
      - GL_OES_depth_texture
      - GL_OES_packed_depth_stencil
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_NV_conditional_render
      - GL_OES_get_program_binary
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_EXT_frag_depth
      - GL_NV_fbo_color_attachments
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_OES_viewport_array
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_robustness
      - GL_EXT_texture_rg
      - GL_EXT_unpack_subimage
      - GL_NV_draw_buffers
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_EXT_draw_buffers
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_KHR_robustness
      - GL_KHR_texture_compression_astc_ldr
      - GL_OES_depth_texture_cube_map
      - GL_OES_required_internalformat
      - GL_OES_surfaceless_context
      - GL_EXT_color_buffer_float
      - GL_EXT_sRGB_write_control
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_framebuffer_fetch
      - GL_EXT_shader_implicit_conversions
      - GL_EXT_shader_integer_mix
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_INTEL_conservative_rasterization
      - GL_INTEL_performance_query
      - GL_ANDROID_extension_pack_es31a
      - GL_EXT_base_instance
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_gpu_shader5
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_render_snorm
      - GL_EXT_shader_io_blocks
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_norm16
      - GL_EXT_texture_view
      - GL_KHR_blend_equation_advanced
      - GL_KHR_blend_equation_advanced_coherent
      - GL_KHR_context_flush_control
      - GL_KHR_robust_buffer_access_behavior
      - GL_NV_image_formats
      - GL_OES_copy_image
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_gpu_shader5
      - GL_OES_primitive_bounding_box
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_texture_view
      - GL_EXT_blend_func_extended
      - GL_EXT_buffer_storage
      - GL_EXT_float_blend
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_shader_samples_identical
      - GL_KHR_no_error
      - GL_KHR_texture_compression_astc_sliced_3d
      - GL_NV_fragment_shader_interlock
      - GL_OES_EGL_image_external_essl3
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_shader_image_atomic
      - GL_EXT_clip_cull_distance
      - GL_EXT_disjoint_timer_query
      - GL_EXT_texture_compression_s3tc_srgb
      - GL_MESA_shader_integer_functions
      - GL_EXT_clip_control
      - GL_EXT_texture_compression_bptc
      - GL_KHR_parallel_shader_compile
      - GL_EXT_shader_framebuffer_fetch_non_coherent
      - GL_EXT_texture_sRGB_R8
      - GL_EXT_texture_shadow_lod
      - GL_MESA_framebuffer_flip_y
      - GL_NV_compute_shader_derivatives
      - GL_EXT_demote_to_helper_invocation
      - GL_EXT_depth_clamp
      - GL_EXT_texture_query_lod
```
</details>

**Please describe your problem:**
Anbox doesn't work with new version of lxc on Arch Linux

```
[2020-03-26T23:17:48+0800] [ALPM] upgraded lxc (1:3.2.1-2 -> 1:4.0.0-1)
```

When I issued `anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity` it said `[launch.cpp:214@operator()] Session manager failed to become ready`
And it just stayed on black screen when I issued `anbox session-manager --single-window --window-size=1024,576`
As shown below

<details>
<summary>screenshot</summary>

![Screenshot_20200327_201743](https://user-images.githubusercontent.com/59396128/77808423-3304a780-70c6-11ea-8225-a600c2d3bfe3.png)
</details>

After downgrading lxc, anbox works again, as shown below

<details>
<summary>console</summary>

```console
qhj@arch:~$ downgrade lxc
Available packages:

-  1)  lxc  1  3.1.0  1  x86_64  (remote)
-  2)  lxc  1  3.1.0  2  x86_64  (remote)
-  3)  lxc  1  3.1.0  2  x86_64  (local)
-  4)  lxc  1  3.2.1  1  x86_64  (remote)
-  5)  lxc  1  3.2.1  1  x86_64  (local)
-  6)  lxc  1  3.2.1  2  x86_64  (remote)
-  7)  lxc  1  3.2.1  2  x86_64  (local)
+  8)  lxc  1  4.0.0  1  x86_64  (remote)
+  9)  lxc  1  4.0.0  1  x86_64  (local)

select a package by number: 7
[sudo] password for qhj: 
loading packages...
warning: downgrading package lxc (1:4.0.0-1 => 1:3.2.1-2)
resolving dependencies...
looking for conflicting packages...

Package (1)  Old Version  New Version  Net Change

lxc          1:4.0.0-1    1:3.2.1-2      0.09 MiB

Total Installed Size:  2.22 MiB
Net Upgrade Size:      0.09 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                            [#########################################] 100%
(1/1) checking package integrity                                          [#########################################] 100%
(1/1) loading package files                                               [#########################################] 100%
(1/1) checking for file conflicts                                         [#########################################] 100%
(1/1) checking available disk space                                       [#########################################] 100%
:: Processing package changes...
(1/1) downgrading lxc                                                     [#########################################] 100%
:: Running post-transaction hooks...
(1/3) Reloading system manager configuration...
(2/3) Creating temporary files...
(3/3) Arming ConditionNeedsUpdate...
add lxc to IgnorePkg? [y/n] y
qhj@arch:~$ sudo systemctl restart anbox-container-manager.service
qhj@arch:~$ systemctl status anbox-container-manager.service      
● anbox-container-manager.service - Anbox Container Manager
     Loaded: loaded (/usr/lib/systemd/system/anbox-container-manager.service; enabled; vendor preset: disabled)
     Active: active (running) since Sat 2020-03-28 06:17:12 CST; 2s ago
   Main PID: 1768 (anbox)
      Tasks: 9 (limit: 19069)
     Memory: 2.2M
     CGroup: /system.slice/anbox-container-manager.service
             └─1768 /usr/bin/anbox container-manager --daemon --privileged --data-path=/var/lib/anbox

Mar 28 06:17:12 arch systemd[1]: Started Anbox Container Manager.
qhj@arch:~$ 
```

</details>

<details>
<summary>screenshot</summary>

![Screenshot_20200328_062320](https://user-images.githubusercontent.com/59396128/77807821-f89a0b00-70c3-11ea-9dc6-c50bf70ffff3.png)
</details>

**What were you expecting?:**
Although I solved the problem temporarily, I still hope that anbox will adapt to the new version of lxc. Thanks!

**Additional info:**
All in the description above
