### ISSUE TITLE
Cannot start anbox on Ubuntu 18.04 x64

### ISSUE THREAD

**Issue by blackchineykh** [anbox/anbox#1399]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
[Checked]
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
[Done]
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
[Done]
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `
[anbox-system-diagnostics-2020-03-29.zip](https://github.com/anbox/anbox/files/4400178/anbox-system-diagnostics-2020-03-29.zip)
6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
 anbox system-info
version: 4
snap-revision: 191
cpu:
  arch:  x86
  brand: Virtual CPU a7769a6388d5
  features:
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 18.04.4 LTS (Bionic Beaver)
  snap-based: true
kernel:
  version: Linux version 4.15.0-91-generic (buildd@lgw01-amd64-013) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions:
      - n/a
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

```
</details>

**Please describe your problem:**
Cannot start anbox

**What were you expecting?:**
Anbox to start

**Additional info:**
Im running on a virtual machine
