### ISSUE TITLE
Anbox run on centos 8

### ISSUE THREAD

**Issue by chuanzhi** [anbox/anbox#1403]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `
[anbox-system-diagnostics-2020-03-31.zip](https://github.com/anbox/anbox/files/4408027/anbox-system-diagnostics-2020-03-31.zip)

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
[please paste printout of `anbox system-info` here]
version: 4
snap-revision: 186
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: CentOS Linux
  version: 8 (Core)
  snap-based: true
kernel:
  version: Linux version 4.18.0-147.5.1.el8_1.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 8.3.1 20190507 (Red Hat 8.3.1-4) (GCC)) #1 SMP Wed Feb 5 02:00:39 UTC 2020
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions:
      - n/a
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
```
</details>

**Please describe your problem:**
```
Stack trace (most recent call last):
#26   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#25   Object "/snap/anbox/186/usr/bin/anbox", at 0x4aa008, in _start
#24   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fd8bc74382f, in __libc_start_main
#23   Object "/snap/anbox/186/usr/bin/anbox", at 0x4a524e, in main
#22   Object "/snap/anbox/186/usr/bin/anbox", at 0x4bc337, in anbox::Daemon::Run(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
#21   Object "/snap/anbox/186/usr/bin/anbox", at 0x4b153f, in anbox::cli::CommandWithSubcommands::run(anbox::cli::Command::Context const&)
#20   Object "/snap/anbox/186/usr/bin/anbox", at 0x4b1001, in anbox::cli::CommandWithFlagsAndAction::run(anbox::cli::Command::Context const&)
#19   Object "/snap/anbox/186/usr/bin/anbox", at 0x4df55d, in 
#18   Object "/snap/anbox/186/usr/bin/anbox", at 0x51e3f7, in anbox::platform::create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<anbox::input::Manager> const&, anbox::platform::Configuration const&)
#17   Object "/snap/anbox/186/usr/bin/anbox", at 0x5247a9, in anbox::platform::sdl::Platform::Platform(std::shared_ptr<anbox::input::Manager> const&, anbox::platform::Configuration const&)
#16   Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fd8bdfdb3e6, in 
#15   Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fd8be0740c0, in 
#14   Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fd8be08799c, in 
#13   Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fd8be0863a0, in 
#12   Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fd8be075102, in 
#11   Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7fd8bd6d2fa0, in dlopen
#10   Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7fd8bd6d3570, in 
#9    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fd8bec7f573, in 
#8    Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7fd8bd6d2f08, in 
#7    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fd8bec83db8, in 
#6    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fd8bec7f573, in 
#5    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fd8bec848f1, in 
#4    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fd8bec7f7da, in 
#3    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fd8bec7f6c9, in 
#2    Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3", at 0x7fd8b3630408, in 
#1    Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9", at 0x7fd8bd4af832, in google::protobuf::internal::OnShutdown(void (*)())
#0    Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9", at 0x7fd8bd4af516, in google::protobuf::internal::Mutex::Lock()
Segmentation fault (Address not mapped to object [(nil)])
```

**What were you expecting?:**

**Additional info:**
