### ISSUE TITLE
snapcraft build failed

### ISSUE THREAD

**Issue by oyzw0720** [anbox/anbox#1411]
Hi all,
  I've built the anbox source code and followed the README to build anbox snap with 'snapcraft'.
But recently snapcraft keep report ERROR when pulling code from swiftshader.
I've checked the anbox/snap/snapcraft.yaml on line 208:
  swiftshader:
    plugin: cmake
    source: https://swiftshader.googlesource.com/SwiftShader
    source-type: git
    # Points to latest head of branch android-emulator-current-release
    source-commit: 79acc73de8a455f79fb7e458719adc86aa798f07
Now on "https://swiftshader.googlesource.com/SwiftShader" git repo there is no branch named "android-emulator-current-release" and cannot find commit id "79acc73de8a455f79fb7e458719adc86aa798f07".
Does the branch have been removed? Or is it just my local error?

**Comment by chuanzhi** [comment]
anbox/snap/snapcraft.yaml
``` 
swiftshader:
    plugin: cmake
    # https://swiftshader.googlesource.com/SwiftShader
    source: https://gitee.com/zhengy88/swiftshader.git
````
