### ISSUE TITLE
Black Screen when launch Princess Connect

### ISSUE THREAD

**Issue by BoringCat** [anbox/anbox#1449]
<details>
<summary>anbox system-info output</summary>

```
version: local-73804a3
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Arch Linux
  version: 
  snap-based: false
kernel:
  version: Linux version 5.6.10-arch1-1 (linux@archlinux) (gcc version 9.3.0 (Arch Linux 9.3.0-1)) #1 SMP PREEMPT Sat, 02 May 2020 19:11:54 +0000
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: NVIDIA
    version: 1.5
    extensions:
      - EGL_EXT_buffer_age
      - EGL_EXT_client_sync
      - EGL_EXT_create_context_robustness
      - EGL_EXT_output_base
      - EGL_EXT_stream_acquire_mode
      - EGL_EXT_sync_reuse
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context_no_error
      - EGL_KHR_context_flush_control
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_partial_update
      - EGL_KHR_swap_buffers_with_damage
      - EGL_KHR_no_config_context
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_stream
      - EGL_KHR_stream_attrib
      - EGL_KHR_stream_consumer_gltexture
      - EGL_KHR_stream_cross_process_fd
      - EGL_KHR_stream_fifo
      - EGL_KHR_stream_producer_eglsurface
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_NV_nvrm_fence_sync
      - EGL_NV_post_sub_buffer
      - EGL_NV_quadruple_buffer
      - EGL_NV_stream_cross_display
      - EGL_NV_stream_cross_object
      - EGL_NV_stream_cross_process
      - EGL_NV_stream_cross_system
      - EGL_NV_stream_dma
      - EGL_NV_stream_flush
      - EGL_NV_stream_metadata
      - EGL_NV_stream_remote
      - EGL_NV_stream_reset
      - EGL_NV_stream_socket
      - EGL_NV_stream_socket_inet
      - EGL_NV_stream_socket_unix
      - EGL_NV_stream_sync
      - EGL_NV_stream_fifo_next
      - EGL_NV_stream_fifo_synchronous
      - EGL_NV_stream_consumer_gltexture_yuv
      - EGL_NV_stream_attrib
      - EGL_NV_stream_origin
      - EGL_NV_system_time
      - EGL_NV_output_drm_flip_event
      - EGL_NV_triple_buffer
      - EGL_WL_bind_wayland_display
      - EGL_WL_wayland_eglstream
  gles2:
    vendor: NVIDIA Corporation
    vendor: OpenGL ES 3.2 NVIDIA 440.82
    extensions:
      - GL_EXT_base_instance
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clear_texture
      - GL_EXT_clip_control
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_color_buffer_half_float
      - GL_EXT_conservative_depth
      - GL_EXT_copy_image
      - GL_EXT_depth_clamp
      - GL_EXT_debug_label
      - GL_EXT_discard_framebuffer
      - GL_EXT_disjoint_timer_query
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_EGL_image_array
      - GL_EXT_EGL_image_storage
      - GL_EXT_EGL_image_external_wrap_modes
      - GL_EXT_float_blend
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_indirect
      - GL_EXT_multisample_compatibility
      - GL_EXT_multisampled_render_to_texture
      - GL_EXT_multisampled_render_to_texture2
      - GL_EXT_multiview_texture_multisample
      - GL_EXT_multiview_timer_query
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_post_depth_coverage
      - GL_EXT_primitive_bounding_box
      - GL_EXT_raster_multisample
      - GL_EXT_render_snorm
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_group_vote
      - GL_EXT_shader_implicit_conversions
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_shader_non_constant_global_initializers
      - GL_EXT_shader_texture_lod
      - GL_EXT_shadow_samplers
      - GL_EXT_sparse_texture
      - GL_EXT_sparse_texture2
      - GL_EXT_sRGB
      - GL_EXT_sRGB_write_control
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_bptc
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_rgtc
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_filter_minmax
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_mirror_clamp_to_edge
      - GL_EXT_texture_norm16
      - GL_EXT_texture_rg
      - GL_EXT_texture_shadow_lod
      - GL_EXT_texture_sRGB_R8
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_storage
      - GL_EXT_texture_view
      - GL_EXT_draw_transform_feedback
      - GL_EXT_unpack_subimage
      - GL_EXT_window_rectangles
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_EXT_memory_object
      - GL_EXT_memory_object_fd
      - GL_KHR_parallel_shader_compile
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_EXT_semaphore
      - GL_EXT_semaphore_fd
      - GL_KHR_shader_subgroup
      - GL_NV_bgr
      - GL_NV_bindless_texture
      - GL_NV_blend_equation_advanced
      - GL_NV_blend_equation_advanced_coherent
      - GL_NVX_blend_equation_advanced_multi_draw_buffers
      - GL_NV_blend_minmax_factor
      - GL_NV_clip_space_w_scaling
      - GL_NV_conditional_render
      - GL_NV_conservative_raster
      - GL_NV_conservative_raster_pre_snap_triangles
      - GL_NV_copy_buffer
      - GL_NV_copy_image
      - GL_NV_draw_buffers
      - GL_NV_draw_instanced
      - GL_NV_draw_texture
      - GL_NV_draw_vulkan_image
      - GL_NV_EGL_stream_consumer_external
      - GL_NV_explicit_attrib_location
      - GL_NV_fbo_color_attachments
      - GL_NV_fill_rectangle
      - GL_NV_fragment_coverage_to_color
      - GL_NV_fragment_shader_interlock
      - GL_NV_framebuffer_blit
      - GL_NV_framebuffer_mixed_samples
      - GL_NV_framebuffer_multisample
      - GL_NV_generate_mipmap_sRGB
      - GL_NV_geometry_shader_passthrough
      - GL_NV_instanced_arrays
      - GL_NV_internalformat_sample_query
      - GL_NV_gpu_shader5
      - GL_NV_image_formats
      - GL_NV_memory_attachment
      - GL_NV_occlusion_query_samples
      - GL_NV_non_square_matrices
      - GL_NV_pack_subimage
      - GL_NV_packed_float
      - GL_NV_packed_float_linear
      - GL_NV_path_rendering
      - GL_NV_path_rendering_shared_edge
      - GL_NV_pixel_buffer_object
      - GL_NV_polygon_mode
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_NV_sample_locations
      - GL_NV_sample_mask_override_coverage
      - GL_NV_shader_atomic_fp16_vector
      - GL_NV_shader_noperspective_interpolation
      - GL_NV_shader_subgroup_partitioned
      - GL_NV_shadow_samplers_array
      - GL_NV_shadow_samplers_cube
      - GL_NV_sRGB_formats
      - GL_NV_stereo_view_rendering
      - GL_NV_texture_array
      - GL_NV_texture_barrier
      - GL_NV_texture_border_clamp
      - GL_NV_texture_compression_latc
      - GL_NV_texture_compression_s3tc
      - GL_NV_texture_compression_s3tc_update
      - GL_NV_timer_query
      - GL_NV_viewport_array
      - GL_NV_viewport_array2
      - GL_NV_viewport_swizzle
      - GL_KHR_blend_equation_advanced
      - GL_KHR_blend_equation_advanced_coherent
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_OES_depth24
      - GL_OES_depth32
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_copy_image
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_texture_border_clamp
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_buffer
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_gpu_shader5
      - GL_OES_shader_io_blocks
      - GL_OES_texture_view
      - GL_OES_primitive_bounding_box
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_image_external_essl3
      - GL_OES_EGL_sync
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_get_program_binary
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_surfaceless_context
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_npot
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array
      - GL_OVR_multiview
      - GL_OVR_multiview2
      - GL_OVR_multiview_multisampled_render_to_texture
      - GL_ANDROID_extension_pack_es31a
```
</details>

**Please describe your problem:**

Get Black Screen when launch Princess Connect.

But i can still get the touch effect.

I think it just happen on NVIDIA graphics card. Beacuse it work on my GPD P2MAX with Intel build in graphics card.

**What were you expecting?:**

Run normally.

**Additional info:**

Here is some log from /var/log/anbox/logs/console.log
<details>
<summary>At launch com.bilibili.priconne</summary>

```
05-06 15:03:09.411   110   385 I ActivityManager: Start proc 573:com.bilibili.priconne/u0a49 for activity com.bilibili.priconne/com.bilibili.princonne.permission.PermissionActivity
05-06 15:03:09.417    29    62 D PermissionCache: checking android.permission.READ_FRAME_BUFFER for uid=1000 => granted (61 us)
05-06 15:03:09.419   110   385 D         : HostConnection::get() New Host Connection established 0x7f935a3219c0, tid 385
05-06 15:03:09.420    29    59 D         : HostConnection::get() New Host Connection established 0x7fa29d01e300, tid 59
05-06 15:03:09.421    29    29 E EGL_emulation: tid 29: eglCreateSyncKHR(1315): error 0x3004 (EGL_BAD_ATTRIBUTE)
05-06 15:03:09.475   415   447 V MediaScanner: pruneDeadThumbnailFiles... android.content.ContentProviderClient$CursorWrapperInner@670acb1
05-06 15:03:09.475   415   447 V MediaScanner: /pruneDeadThumbnailFiles... android.content.ContentProviderClient$CursorWrapperInner@670acb1
05-06 15:03:09.497   573   573 E PermissionActivity: PermissionActivity
05-06 15:03:09.500   573   573 D PermissionActivity: 25
05-06 15:03:09.500   573   573 I PermissionActivity: checkPermission()
05-06 15:03:09.501   110   384 I ActivityManager: START u0 {cmp=com.bilibili.priconne/com.bilibili.princonne.bili.MainActivity} from uid 10049 on display 0
05-06 15:03:09.584   429   443 D OpenGLRenderer: endAllActiveAnimators on 0x7f9364037c00 (GridView) with handle 0x7f935be39860
05-06 15:03:10.161   110   132 W WindowManager: App freeze timeout expired.
05-06 15:03:10.313   573   600 D NetworkSecurityConfig: No Network Security Config specified, using platform default
05-06 15:03:10.322   573   604 I TDLog   : TalkingData AppCpa SDK init...
05-06 15:03:10.322   573   604 I TDLog   : 	SDK_VERSION is: Android+TD+V4.0.40 gp Type:Native  Build_Num:1127
05-06 15:03:10.322   573   604 I TDLog   : 	App ID is: 75973F6A05E84E02BA875AFDDDC10F06
05-06 15:03:10.322   573   604 I TDLog   : 	App Channel is: 公主连结
05-06 15:03:10.322   573   604 I TDLog   : 	SDK_OVC is: TDOVC+5a5b3495d4c174cdfc17105fc9a48b15+SaaS
05-06 15:03:10.327   267   339 E PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
05-06 15:03:10.331   573   624 W Settings: Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
05-06 15:03:10.333   267   280 E PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
05-06 15:03:10.337   267   280 E PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
05-06 15:03:10.341   267   279 E PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
05-06 15:03:10.354   573   604 V NFC     : this device does not have NFC support
05-06 15:03:10.368   573   637 D         : HostConnection::get() New Host Connection established 0xf3bb6f80, tid 637
05-06 15:03:10.370   573   637 I OpenGLRenderer: Initialized EGL, version 1.4
05-06 15:03:10.370   573   637 D OpenGLRenderer: Swap behavior 1
05-06 15:03:10.430   573   614 I TDLog   : [TRACKING] Submit local data to collector server ...
05-06 15:03:10.431   573   604 I TDLog   : [Session] - New session!
05-06 15:03:10.431   573   604 I TDLog   : [Session] - Id: fa95155d-b943-43c1-83ef-c571c84295e1
05-06 15:03:10.463   110   132 I ActivityManager: Displayed com.bilibili.priconne/com.bilibili.princonne.bili.MainActivity: +961ms (total +1s63ms)
05-06 15:03:10.541   573   602 I Unity   : SystemInfo CPU = Intel x86 SSE3, Cores = 8, Memory = 15969mb
05-06 15:03:10.541   573   602 I Unity   : ApplicationInfo com.bilibili.priconne version 2.4.6 build ae5c6536-3ae6-4071-93eb-f9516eb62d6d
05-06 15:03:10.541   573   602 I Unity   : Built from '2017.4/china_unity/release' branch, Version '2017.4.37c2 (d0293ca7c138)', Build type 'Release', Scripting Backend 'il2cpp'
05-06 15:03:10.603   573   614 I TDLog   : [TRACKING] Data submitted successfully!
05-06 15:03:10.604   573   614 I TDLog   : [TRACKING] Submit local data to collector server ...
05-06 15:03:10.647   573   614 I TDLog   : [TRACKING] Data submitted successfully!
05-06 15:03:10.828   573   602 D         : HostConnection::get() New Host Connection established 0xcf645a80, tid 602
05-06 15:03:10.830   573   602 E EGL_emulation: tid 602: eglCreateContext(919): error 0x3005 (EGL_BAD_CONFIG)
05-06 15:03:10.832   573   602 E EGL_emulation: [getAttribValue] Bad attribute idx
05-06 15:03:10.832   573   602 E EGL_emulation: tid 602: eglGetConfigAttrib(613): error 0x3004 (EGL_BAD_ATTRIBUTE)
05-06 15:03:10.832   573   602 E EGL_emulation: [getAttribValue] Bad attribute idx
05-06 15:03:10.832   573   602 E EGL_emulation: tid 602: eglGetConfigAttrib(613): error 0x3004 (EGL_BAD_ATTRIBUTE)
05-06 15:03:10.832   573   602 E EGL_emulation: [getAttribValue] Bad attribute idx
05-06 15:03:10.832   573   602 E EGL_emulation: tid 602: eglGetConfigAttrib(613): error 0x3004 (EGL_BAD_ATTRIBUTE)
05-06 15:03:10.832   573   602 E EGL_emulation: tid 602: eglCreateContext(919): error 0x3005 (EGL_BAD_CONFIG)
05-06 15:03:10.832   573   602 E Unity   : [EGL] Unable to create context!: EGL_BAD_CONFIG: An EGLConfig argument does not name a valid EGL frame buffer configuration.
05-06 15:03:10.832   573   602 E Unity   :  
05-06 15:03:10.832   573   602 E Unity   : (Filename: /Users/builduser/buildslave/unity/build/Runtime/GfxDevice/egl/ContextEGL.cpp Line: 111)
05-06 15:03:10.832   573   602 E Unity   : 
05-06 15:03:10.835   573   602 E EGL_emulation: tid 602: eglCreateContext(919): error 0x3005 (EGL_BAD_CONFIG)
05-06 15:03:10.835   573   602 E Unity   : [EGL] Unable to create context!: EGL_BAD_CONFIG: An EGLConfig argument does not name a valid EGL frame buffer configuration.
05-06 15:03:10.835   573   602 E Unity   :  
05-06 15:03:10.835   573   602 E Unity   : (Filename: /Users/builduser/buildslave/unity/build/Runtime/GfxDevice/egl/ContextEGL.cpp Line: 111)
05-06 15:03:10.835   573   602 E Unity   : 
05-06 15:03:10.866   573   602 D Unity   : GL_EXT_debug_marker GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_depth32 GL_OES_depth_texture GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_element_index_uint GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_npot GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_vertex_half_float
05-06 15:03:11.065   573   602 V MediaRouter: Adding route: RouteInfo{ name=手机, description=null, status=null, category=RouteCategory{ name=null types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
05-06 15:03:11.066   573   602 V MediaRouter: Updating audio routes: AudioRoutesInfo{ type=SPEAKER }
05-06 15:03:11.066   573   602 V MediaRouter: Selecting route: RouteInfo{ name=手机, description=null, status=null, category=RouteCategory{ name=null types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
05-06 15:03:11.108   573   602 I libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
05-06 15:03:11.108   573   602 W AudioTrack: notificationFrames=-55 clamped to the range -1 to -8
05-06 15:03:11.108    32    75 W AudioFlinger: createTrack_l(): mismatch between requested flags (00000104) and output flags (00000002)
05-06 15:03:11.108   573   602 W AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 8192
05-06 15:03:11.108   573   602 D AudioTrack: Client defaulted notificationFrames to 4096 for frameCount 8192
05-06 15:03:11.952    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(759)
05-06 15:03:12.021   573   573 W System  : ClassLoader referenced unknown path: /system/app/webview/lib/x86
05-06 15:03:12.021   573   573 D ApplicationLoaders: ignored Vulkan layer search path /system/app/webview/lib/x86:/system/app/webview/webview.apk!/lib/x86:/system/lib:/vendor/lib for namespace 0xf7c7f090
05-06 15:03:12.022   573   573 I WebViewFactory: Loading com.android.webview version 52.0.2743.100 (code 275610060)
05-06 15:03:12.027   573   573 I cr_LibraryLoader: Time to load native libraries: 1 ms (timestamps 9475-9476)
05-06 15:03:12.028   573   573 I cr_LibraryLoader: Expected native library version number "52.0.2743.100", actual native library version number "52.0.2743.100"
05-06 15:03:12.030   573   573 V WebViewChromiumFactoryProvider: Binding Chromium to main looper Looper (main, tid 1) {30f4723}
05-06 15:03:12.030   573   573 I cr_LibraryLoader: Expected native library version number "52.0.2743.100", actual native library version number "52.0.2743.100"
05-06 15:03:12.030   573   573 I chromium: [INFO:library_loader_hooks.cc(143)] Chromium logging enabled: level = 0, default verbosity = 0
05-06 15:03:12.033   573   573 I cr_BrowserStartup: Initializing chromium process, singleProcess=true
05-06 15:03:12.037   573   573 D         : HostConnection::get() New Host Connection established 0xc9419350, tid 573
05-06 15:03:12.071   573   711 W cr_media: Requires BLUETOOTH permission
05-06 15:03:12.073   573   573 I cr_DRP  : No DRP key due to exception:java.lang.ClassNotFoundException: com.android.webview.chromium.Drp
05-06 15:03:12.112   573   573 W cr_AwContents: onDetachedFromWindow called when already detached. Ignoring
05-06 15:03:12.453    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(473)
05-06 15:03:12.456    40    80 I MediaPlayerService: MediaPlayerService::getOMX
05-06 15:03:12.456   573   727 I OMXClient: MuxOMX ctor
05-06 15:03:12.456   573   727 E ACodec  : Unable to instantiate a decoder for type 'video/avc' with err 0xfffffffe.
05-06 15:03:12.456   573   727 E ACodec  : signalError(omxError 0xfffffffe, internalError -2)
05-06 15:03:12.456   573   726 E MediaCodec: Codec reported err 0xfffffffe, actionCode 0, while in state 1
05-06 15:03:12.456   573   686 W MediaCodec-JNI: try to release MediaCodec from JMediaCodec::~JMediaCodec()...
05-06 15:03:12.456   573   686 W MediaCodec-JNI: done releasing MediaCodec from JMediaCodec::~JMediaCodec().
05-06 15:03:12.642    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(165)
05-06 15:03:12.706   573   733 W Settings: Setting adb_enabled has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
05-06 15:03:12.832    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(165)
05-06 15:03:13.133   110   264 D SntpClient: round trip: 235ms, clock offset: -3ms
05-06 15:03:13.133   110   264 W AlarmManager: Not setting time since no alarm driver is available.
05-06 15:03:13.339   477   477 E BroadcastReceiver: BroadcastReceiver trying to return result during a non-ordered broadcast
05-06 15:03:13.339   477   477 E BroadcastReceiver: java.lang.RuntimeException: BroadcastReceiver trying to return result during a non-ordered broadcast
05-06 15:03:13.339   477   477 E BroadcastReceiver: 	at android.content.BroadcastReceiver.checkSynchronousHint(BroadcastReceiver.java:785)
05-06 15:03:13.339   477   477 E BroadcastReceiver: 	at android.content.BroadcastReceiver.setResultCode(BroadcastReceiver.java:551)
05-06 15:03:13.339   477   477 E BroadcastReceiver: 	at com.android.providers.calendar.CalendarProviderBroadcastReceiver.onReceive(CalendarProviderBroadcastReceiver.java:40)
05-06 15:03:13.339   477   477 E BroadcastReceiver: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3040)
05-06 15:03:13.339   477   477 E BroadcastReceiver: 	at android.app.ActivityThread.-wrap18(ActivityThread.java)
05-06 15:03:13.339   477   477 E BroadcastReceiver: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1561)
05-06 15:03:13.339   477   477 E BroadcastReceiver: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-06 15:03:13.339   477   477 E BroadcastReceiver: 	at android.os.Looper.loop(Looper.java:154)
05-06 15:03:13.339   477   477 E BroadcastReceiver: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
05-06 15:03:13.339   477   477 E BroadcastReceiver: 	at java.lang.reflect.Method.invoke(Native Method)
05-06 15:03:13.339   477   477 E BroadcastReceiver: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
05-06 15:03:13.339   477   477 E BroadcastReceiver: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
05-06 15:03:13.692    32    69 W AudioFlinger: write blocked for 759 msecs, 1 delayed writes, thread 0xf6903180
05-06 15:03:13.692    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(99)
05-06 15:03:14.037    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(319)
05-06 15:03:14.274   456   564 I GlobalDismissManager: no sender configured
05-06 15:03:14.274   456   564 D AlertService: Beginning updateAlertNotification
05-06 15:03:14.277   456   564 D AlertService: No fired or scheduled alerts
05-06 15:03:14.278   456   564 D AlertService: Scheduling next alarm with AlarmScheduler. sEventReminderReceived: null
05-06 15:03:14.280   456   564 D AlarmScheduler: No events found starting within 1 week.
05-06 15:03:15.130    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(341)
05-06 15:03:15.335   573   614 I TDLog   : [TRACKING] Submit local data to collector server ...
05-06 15:03:15.379   573   614 I TDLog   : [TRACKING] Data submitted successfully!
05-06 15:03:15.455    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(297)
05-06 15:03:15.645    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(165)
05-06 15:03:15.672   267   279 E PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
05-06 15:03:15.678   267   339 E PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
05-06 15:03:15.690   267   279 E PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
05-06 15:03:15.693   267   279 E PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
05-06 15:03:15.703   267   280 E PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
05-06 15:03:15.707   267   279 E PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
05-06 15:03:15.720   267   280 E PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
05-06 15:03:15.720   267   339 E PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
05-06 15:03:15.836    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(165)
05-06 15:03:16.620    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(33)
05-06 15:03:16.945    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(297)
05-06 15:03:17.136    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(165)
05-06 15:03:17.326    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(165)
05-06 15:03:17.881   110   161 D ConnectivityService: NetworkAgentInfo [Ethernet () - 100] validation failed
05-06 15:03:18.105    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(33)
05-06 15:03:18.785    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(649)
05-06 15:03:19.542    32    69 W AudioFlinger: write blocked for 746 msecs, 5 delayed writes, thread 0xf6903180
05-06 15:03:19.542    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(11)
05-06 15:03:20.202    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(627)
05-06 15:03:20.984    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(33)
05-06 15:03:21.664    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(649)
05-06 15:03:22.423    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(11)
05-06 15:03:22.769    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(319)
05-06 15:03:23.242   110   125 I ActivityManager: Waited long enough for: ServiceRecord{5833321 u0 com.android.calendar/.alerts.InitAlarmsService}
05-06 15:03:23.862    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(341)
05-06 15:03:24.186    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(297)
05-06 15:03:24.377    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(165)
05-06 15:03:24.568    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(165)
05-06 15:03:25.348    32    69 W AudioFlinger: write blocked for 746 msecs, 9 delayed writes, thread 0xf6903180
05-06 15:03:25.348    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(33)
05-06 15:03:25.672    32    69 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(297)
```
</details>
