### ISSUE TITLE
Anbox startup error "Application manager service is not running yet"

### ISSUE THREAD

**Issue by TitusLabienus** [anbox/anbox#1450]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
The issue might be related to #1397. However, the error occurs also using lxc versions 3.2.1 and 4.0.2, which were reported to resolve #1397 
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
Cleanly installed latest version via AUR.
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
Ditto
4. Reproduce the error while debug logs enabled.
[ 2020-05-07 09:19:54] [daemon.cpp:61@Run] Application manager service is not running yet
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `
Ditto as 2.
6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
version: local-73804a3
cpu:
  arch:  x86
  brand: Intel(R) Core(TM)2 Duo CPU     P8400  @ 2.26GHz
  features: 
    - sse4_1
os:
  name: Manjaro Linux
  version: 
  snap-based: false
kernel:
  version: Linux version 5.4.31-1-MANJARO (builduser@development) (gcc version 9.3.0 (Arch Linux 9.3.0-1)) #1 SMP PREEMPT Wed Apr 8 10:25:32 UTC 2020
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 2.0 Mesa 20.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_texture_3D
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float
      - GL_OES_EGL_image
      - GL_OES_depth_texture
      - GL_OES_packed_depth_stencil
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_NV_conditional_render
      - GL_OES_get_program_binary
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_EXT_frag_depth
      - GL_NV_fbo_color_attachments
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_robustness
      - GL_EXT_texture_rg
      - GL_EXT_unpack_subimage
      - GL_NV_draw_buffers
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_EXT_draw_buffers
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_KHR_robustness
      - GL_OES_required_internalformat
      - GL_OES_surfaceless_context
      - GL_EXT_separate_shader_objects
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_texture_border_clamp
      - GL_KHR_blend_equation_advanced
      - GL_KHR_context_flush_control
      - GL_OES_draw_elements_base_vertex
      - GL_OES_texture_border_clamp
      - GL_KHR_no_error
      - GL_EXT_texture_compression_s3tc_srgb
      - GL_EXT_clip_control
      - GL_KHR_parallel_shader_compile
      - GL_EXT_shader_framebuffer_fetch_non_coherent
      - GL_EXT_demote_to_helper_invocation
      - GL_EXT_depth_clamp
```
</details>

**Please describe your problem:**
Anbox startup fails with "Application manager service is not running yet". I've tried it using lxc on both v4.0.2 and v3.2.1 to avoid #1397. Also, to avoid issues from the other images, 'anbox-image' was used. Reproduced the issue on two seperate host machines (Archlinux and Manjaro).

**What were you expecting?:**
Anbox starts normally.

**Additional info:**
