### ISSUE TITLE
Anbox not opening in Ubuntu

### ISSUE THREAD

**Issue by ChinkyPrinceCarey** [anbox/anbox#1462]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
root@162-aaa-bb-ccc:~# anbox system-info
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
No protocol specified
No protocol specified
No protocol specified
No protocol specified
version: 4
snap-revision: 191
cpu:
  arch:  x86
  brand: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 16.04.6 LTS (Xenial Xerus)
  snap-based: true
kernel:
  version: Linux version 4.4.0-179-generic (buildd@lcy01-amd64-014) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) ) #209-Ubuntu SMP Fri Apr 24 17:48:44 UTC 2020
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions:
      - n/a
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
```
</details>

**Please describe your problem:**
After installing Anbox from Docs, there is no Anbox icon found in the application manager, so I tried to open/launch Anbox from Terminal using following command: ```anbox session-manager``` but this gave me the following error: ```root@162-aaa-bb-ccc:~# anbox session-manager
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
No protocol specified
Stack trace (most recent call last):
#26   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#25   Object "/snap/anbox/191/usr/bin/anbox", at 0x4aa008, in _start
#24   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fab78a1e82f, in __libc_start_main
#23   Object "/snap/anbox/191/usr/bin/anbox", at 0x4a524e, in main
#22   Object "/snap/anbox/191/usr/bin/anbox", at 0x4bc337, in anbox::Daemon::Run(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
#21   Object "/snap/anbox/191/usr/bin/anbox", at 0x4b153f, in anbox::cli::CommandWithSubcommands::run(anbox::cli::Command::Context const&)
#20   Object "/snap/anbox/191/usr/bin/anbox", at 0x4b1001, in anbox::cli::CommandWithFlagsAndAction::run(anbox::cli::Command::Context const&)
#19   Object "/snap/anbox/191/usr/bin/anbox", at 0x4df55d, in 
#18   Object "/snap/anbox/191/usr/bin/anbox", at 0x51e3f7, in anbox::platform::create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<anbox::input::Manager> const&, anbox::platform::Configuration const&)
#17   Object "/snap/anbox/191/usr/bin/anbox", at 0x5247a9, in anbox::platform::sdl::Platform::Platform(std::shared_ptr<anbox::input::Manager> const&, anbox::platform::Configuration const&)
#16   Object "/snap/anbox/191/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fab7a2b63e6, in 
#15   Object "/snap/anbox/191/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fab7a34f0c0, in 
#14   Object "/snap/anbox/191/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fab7a36299c, in 
#13   Object "/snap/anbox/191/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fab7a3613a0, in 
#12   Object "/snap/anbox/191/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fab7a350102, in 
#11   Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7fab799adfa0, in dlopen
#10   Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7fab799ae570, in 
#9    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fab7af5a573, in 
#8    Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7fab799adf08, in 
#7    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fab7af5edb8, in 
#6    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fab7af5a573, in 
#5    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fab7af5f8f1, in 
#4    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fab7af5a7da, in 
#3    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fab7af5a6c9, in 
#2    Object "/snap/anbox/191/usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3", at 0x7fab6f6f9408, in 
#1    Object "/snap/anbox/191/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9", at 0x7fab7978a832, in google::protobuf::internal::OnShutdown(void (*)())
#0    Object "/snap/anbox/191/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9", at 0x7fab7978a516, in google::protobuf::internal::Mutex::Lock()
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault (core dumped)```

Even I tried executing the following command: ```anbox.appmgr``` but this also gave me error: ```root@162-aaa-bb-ccc:~# anbox.appmgr
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
[ 2020-05-19 18:03:47] [daemon.cpp:61@Run] Failed to connect to DBus
root@162-241-29-225:~# ```

I thought my system may not supporting the Anbox Requirements, so to check I ran following command: ```anbox check-features``` and the output was: 
```realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
Your computer does meet all requirements to run Anbox```

**What were you expecting?:**
Anbox opening, and running android apps

**Additional info:**
I am using Linux VPS Server

**Comment by Polisson** [comment]
Same situation.

<details>
<summary>anbox system-info output</summary>

```
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
version: 4
snap-revision: 191
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 20.04 LTS (Focal Fossa)
  snap-based: true
kernel:
  version: Linux version 5.4.0-29-generic (buildd@lgw01-amd64-035) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)) #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 3.2 Mesa 18.0.5
    extensions:
      - GL_ANDROID_extension_pack_es31a
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_disjoint_timer_query
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_read_format_bgra
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_framebuffer_fetch
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_shader_samples_identical
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_INTEL_conservative_rasterization
      - GL_INTEL_performance_query
      - GL_KHR_blend_equation_advanced
      - GL_KHR_blend_equation_advanced_coherent
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_KHR_texture_compression_astc_ldr
      - GL_KHR_texture_compression_astc_sliced_3d
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_image_formats
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_get_program_binary
      - GL_OES_gpu_shader5
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_primitive_bounding_box
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array
```
</details>

**Please describe your problem:**
When Anbox is started, the splash-screen is shown, but after few second it quits. 

**What were you expecting?:**
Working app obviously ;-)

**Additional info:**
On previous Ubuntu ver (19.10) it worked. Don't know when stopped.
