### ISSUE TITLE
Anbox crashes in Ubuntu 20.04

### ISSUE THREAD

**Issue by j75** [anbox/anbox#1486]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
Similar issues: #1461 (but here crashes instantly), #1462
[anbox-system-diagnostics-2020-06-07.zip](https://github.com/anbox/anbox/files/4742733/anbox-system-diagnostics-2020-06-07.zip)

2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>
```
realpath: /home/marian/Downloads: No such file or directory
version: 4
snap-revision: 191
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i3 CPU         550  @ 3.20GHz
  features: 
os:
  name: Ubuntu
  version: 20.04 LTS (Focal Fossa)
  snap-based: true
kernel:
  version: Linux version 5.4.0-33-generic (buildd@lcy01-amd64-022) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)) #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: NVIDIA
    version: 1.4
    extensions:
      - EGL_NV_system_time
      - EGL_KHR_surfaceless_context
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_config_attribs
      - EGL_KHR_fence_sync
      - EGL_NV_sync
      - EGL_KHR_reusable_sync
      - EGL_KHR_create_context
      - EGL_EXT_create_context_robustness
      - EGL_KHR_stream
      - EGL_KHR_stream_fifo
      - EGL_KHR_stream_producer_eglsurface
      - EGL_KHR_stream_consumer_gltexture
      - EGL_NV_stream_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_IMG_context_priority
      - EGL_NV_post_sub_buffer
      - EGL_KHR_image_pixmap
      - EGL_EXT_buffer_age
  gles2:
    vendor: NVIDIA Corporation
    vendor: OpenGL ES 2.0 340.108
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_color_buffer_half_float
      - GL_EXT_debug_label
      - GL_EXT_frag_depth
      - GL_EXT_map_buffer_range
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_integer_mix
      - GL_EXT_shadow_samplers
      - GL_EXT_sRGB
      - GL_EXT_sRGB_write_control
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_storage
      - GL_EXT_unpack_subimage
      - GL_KHR_debug
      - GL_NV_bgr
      - GL_NV_copy_buffer
      - GL_NV_copy_image
      - GL_NV_draw_buffers
      - GL_NV_draw_instanced
      - GL_NV_EGL_stream_consumer_external
      - GL_NV_explicit_attrib_location
      - GL_NV_fbo_color_attachments
      - GL_NV_framebuffer_blit
      - GL_NV_framebuffer_multisample
      - GL_NV_generate_mipmap_sRGB
      - GL_NV_instanced_arrays
      - GL_NV_occlusion_query_samples
      - GL_NV_non_square_matrices
      - GL_NV_pack_subimage
      - GL_NV_packed_float
      - GL_NV_packed_float_linear
      - GL_NV_pixel_buffer_object
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_NV_shadow_samplers_array
      - GL_NV_shadow_samplers_cube
      - GL_NV_sRGB_formats
      - GL_NV_texture_array
      - GL_NV_texture_border_clamp
      - GL_NV_texture_compression_latc
      - GL_NV_texture_compression_s3tc
      - GL_NV_texture_compression_s3tc_update
      - GL_NV_timer_query
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_depth32
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_EGL_image
      - GL_OES_EGL_sync
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_get_program_binary
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_surfaceless_context
      - GL_OES_texture_npot
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
```
</details>

**Please describe your problem:**
The application starts, and after the splash screen it briefly displays the "Anbox application Manager" then crashes!

**What were you expecting?:**
Anbox application Manager to be opened!

**Additional info:**
1. Please note in the **anbox system-info** output the line with `realpath: /home/marian/Downloads: No such file or directory` => the path actually exists!
1. **anbox check-features** => ```realpath: /home/marian/Downloads: No such file or directory
Your computer does meet all requirements to run Anbox```
