### ISSUE TITLE
realpath: '': No such file or directory

### ISSUE THREAD

**Issue by tballantyne** [anbox/anbox#1501]
<details>
<summary>anbox system-info output</summary>

```
snap info anbox
name:      anbox
summary:   Android in a Box
publisher: morphis
store-url: https://snapcraft.io/anbox
contact:   https://anbox.io
license:   unset
description: |
  Runtime for Android applications which runs a full Android system
  in a container using Linux namespaces (user, ipc, net, mount) to
  separate the Android system fully from the host.
  
  You can find further details in our documentation at
  https://github.com/anbox/anbox/blob/master/README.md
commands:
  - anbox
  - anbox.android-settings
  - anbox.appmgr
  - anbox.collect-bug-info
  - anbox.shell
services:
  anbox.container-manager: simple, enabled, active
snap-id:      Nr9K6UJaIOD8wHpDEQl16nabFFt9LLEQ
tracking:     latest/beta
refresh-date: today at 15:53 PDT
channels:
  latest/stable:    –                                
  latest/candidate: –                                
  latest/beta:      4-56c25f1 2020-01-02 (186) 391MB devmode
  latest/edge:      4-6a3f886 2020-03-27 (191) 391MB devmode
installed:          4-56c25f1            (186) 391MB devmode

```
</details>

**Please describe your problem:**
On debian 9 /stretch trying to start the anbox container complains about missing file or directory -

# anbox.appmgr
realpath: '': No such file or directory                                                 
realpath: '': No such file or directory                                                 
realpath: '': No such file or directory                                                 
realpath: '': No such file or directory                                                 
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
[ 2020-06-15 23:13:46] [daemon.cpp:61@Run] Failed to connect to DBus

**What were you expecting?:**
anbox to start.

**Comment by ElliotCambo** [comment]
same issue, absolutely no idea what on earth this is talking about. Ive tried to go through the source to understand what this is even in relation too but to no avail.

**Comment by JonasVautherin** [comment]
Same, on Ubuntu 20.04.

**Comment by matiux** [comment]
Same problem on Arch Linux

**Comment by marcuskelly123** [comment]
Still no answers? Having the same problem

**Comment by PhynX404** [comment]
Same Problem on Ubuntu 20.04 LTS (x86_64).

**Comment by atom7890** [comment]
same kali

**Comment by kotx** [comment]
Same problem on focal.

**Comment by random23715** [comment]
Fedora 30, same issue.
strace shows that before that it tries to access ~/.config/user-dirs.dirs which was missing on my machine
proper ~/.config/user-dirs.dirs can be created by xdg-user-dirs-update
=>
sudo dnf install xdg-user-dirs
xdg-user-dirs-update

**Comment by TheGreatCatAdorer** [comment]
Same issue, Debian Testing/bookworm.

**Comment by babbaranish** [comment]
Same issue, Ubuntu 21.10

**Comment by Fuseteam** [comment]
what same issue? what does `anbox session-manager` say?

**Comment by babbaranish** [comment]
> what same issue? what does `anbox session-manager` say?

`sudo anbox session-manager
[sudo] password for anish: 
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
/usr/share/libdrm/amdgpu.ids: No such file or directory
ALSA lib conf.c:4120:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
[ 2021-11-27 06:02:08] [Renderer.cpp:128@initialize] Failed to select EGL configuration
[ 2021-11-27 06:02:09] [daemon.cpp:61@Run] [org.freedesktop.DBus.Error.FileNotFound] Failed to open bus (No such file or directory)
`

**Comment by Fuseteam** [comment]
try this https://github.com/anbox/anbox/issues/1943#issuecomment-972905105

**Comment by Valwoe** [comment]
Same problem as above.

Fuseteam's proposal did not work.

**Comment by Fuseteam** [comment]
@Valwoe can you at least share your output, my proprosal should address this error message: `Failed to select EGL configuration`

**Comment by Fuseteam** [comment]
@babbaranish did you try my proposal yet?

**Comment by Valwoe** [comment]
@Fuseteam  I tried `systemctl --user status anbox-session-manager`
I got : 
```
● anbox-session-manager.service - Anbox Session Manager
     Loaded: loaded (/etc/xdg/systemd/user/anbox-session-manager.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-12-01 22:02:28 CET; 26min ago
    Process: 14128 ExecStart=/snap/bin/anbox session-manager (code=exited, status=1/FAILURE)
   Main PID: 14128 (code=exited, status=1/FAILURE)

déc. 01 22:02:28 Valentin-Latitude3570-Xubuntu systemd[1784]: Started Anbox Session Manager.
déc. 01 22:02:28 Valentin-Latitude3570-Xubuntu systemd[1784]: anbox-session-manager.service: Main process exited, code=exited, status=1/FAILURE
déc. 01 22:02:28 Valentin-Latitude3570-Xubuntu systemd[1784]: anbox-session-manager.service: Failed with result 'exit-code'.
```
![image](https://user-images.githubusercontent.com/45520322/144317196-09ca4742-f7bf-42fe-83f3-39c8a79a247c.png)

**Comment by Fuseteam** [comment]
Oh you're the guy i told in telegram to try a fresh reboot

**Comment by KleinhansDa** [comment]
Same issue

NAME="Linux Mint"
VERSION="20.3 (Una)"

**Comment by Fuseteam** [comment]
@KleinhansDa checkout #1260 for the workaround

**Comment by KleinhansDa** [comment]
@Fuseteam Unfortunately it did not help. Thanks anyway.

**Comment by Fuseteam** [comment]
@KleinhansDa what error did you encounter?

**Comment by KleinhansDa** [comment]
@Fuseteam 

`systemctl --user status anbox-session-manager` gives me this ..

● anbox-session-manager.service - Anbox Session Manager
     Loaded: loaded (/home/{name}/.config/systemd/user/anbox-session-manager.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2022-04-29 20:41:55 CEST; 2h 58min ago
   Main PID: 149655 (code=exited, status=1/FAILURE)

Apr 29 20:41:54 {name} systemd[1526]: Started Anbox Session Manager.
Apr 29 20:41:55 {name} systemd[1526]: anbox-session-manager.service: Main process exited, code=exited, status=1/FAILURE
Apr 29 20:41:55 {name} systemd[1526]: anbox-session-manager.service: Failed with result 'exit-code'.

**Comment by Fuseteam** [comment]
oh it fails but doesn't say why.......i wonder if i can improve that somehow........what does it say i you just run `anbox session-manager`?

**Comment by KleinhansDa** [comment]
@Fuseteam 

`{name}:~$ anbox session-manager
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
[ 2022-04-30 19:10:13] [session_manager.cpp:133@operator()] Failed to start as either binder or ashmem kernel drivers are not loaded
`

**Comment by KleinhansDa** [comment]
@Fuseteam 

I also cloned anbox-modules and tried to install

```
{name}:~$ git clone https://github.com/anbox/anbox-modules
Cloning into 'anbox-modules'...
remote: Enumerating objects: 132, done.
remote: Total 132 (delta 0), reused 0 (delta 0), pack-reused 132
Receiving objects: 100% (132/132), 68.65 KiB | 1.40 MiB/s, done.
Resolving deltas: 100% (48/48), done.
{name}:~$ cd anbox-modules
{name}:~/anbox-modules$ ./INSTALL.sh

Creating symlink /var/lib/dkms/anbox-ashmem/1/source ->
                 /usr/src/anbox-ashmem-1

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j8 KERNELRELEASE=5.4.0-109-generic all KERNEL_SRC=/lib/modules/5.4.0-109-generic/build...
Signing module:
 - /var/lib/dkms/anbox-ashmem/1/5.4.0-109-generic/x86_64/module/ashmem_linux.ko
Adding '/var/lib/shim-signed/mok/MOK.der' to shim:
cleaning build area...

DKMS: build completed.

ashmem_linux.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.0-109-generic/updates/

depmod...

DKMS: install completed.

Creating symlink /var/lib/dkms/anbox-binder/1/source ->
                 /usr/src/anbox-binder-1

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j8 KERNELRELEASE=5.4.0-109-generic all KERNEL_SRC=/lib/modules/5.4.0-109-generic/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.4.0-109-generic (x86_64)
Consult /var/lib/dkms/anbox-binder/1/build/make.log for more information.
modprobe: ERROR: could not insert 'ashmem_linux': Operation not permitted
binder_linux          180224  0
ls: cannot access '/dev/binder': No such file or directory
ls: cannot access '/dev/ashmem': No such file or directory
```

**Comment by Fuseteam** [comment]
@KleinhansDa looks like the modules aren't loaded correctly what does `anbox system-info` say?

**Comment by KleinhansDa** [comment]
@Fuseteam 

```
{name}:~$ anbox system-info
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
pci id for fd 5: 8086:9b41, driver (null)
pci id for fd 5: 8086:9b41, driver (null)
version: 4
snap-revision: 186
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Linux Mint
  version: 20.3 (Una)
  snap-based: true
kernel:
  version: Linux version 5.4.0-109-generic (buildd@ubuntu) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)) #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022
  binder: false
  ashmem: false
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_context_flush_control
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image_base
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
  gles2:
    vendor: VMware, Inc.
    vendor: OpenGL ES 3.0 Mesa 18.0.5
    extensions:
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_base_instance
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_read_format_bgra
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_integer_mix
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_get_program_binary
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
```
