### ISSUE TITLE
X Error:  BadWindow

### ISSUE THREAD

**Issue by damian101** [anbox/anbox#1530]
<summary>anbox system-info output</summary>
```
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
version: 4
snap-revision: 186
cpu:
  arch:  x86
  brand: Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Feren OS Classic
  version: 2020.04
  snap-based: true
kernel:
  version: Linux version 5.3.0-62-generic (buildd@lcy01-amd64-004) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #56~18.04.1-Ubuntu SMP Wed Jun 24 16:17:03 UTC 2020
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
```

**Please describe your problem:**
When running `anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity` I get the following output:
```
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
X Error:  BadWindow
  Request Major code 4 ()
  ResourceID 0x8800008
  Error Serial #175
  Current Serial #191
```

**What were you expecting?:**
The Anbox Application Manager to start

[anbox-system-diagnostics-2020-07-09.zip](https://github.com/anbox/anbox/files/4897866/anbox-system-diagnostics-2020-07-09.zip)
