### ISSUE TITLE
OsmAnd SIGSEGV

### ISSUE THREAD

**Issue by 532910** [anbox/anbox#1546]
SIGSEGV trying to launch https://f-droid.org/repo/net.osmand.plus_374.apk

```
08-01 10:55:43.068  3068  3096 F libc    : Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 3096 (Loader map obje)
08-01 10:55:43.068     9     9 W         : debuggerd: handling request: pid=3068 uid=10051 gid=10051 tid=3096
08-01 10:55:43.124  3106  3106 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-01 10:55:43.124  3106  3106 F DEBUG   : Build fingerprint: 'Android/anbox_x86_64/x86_64:7.1.1/N6F26Q/root07191722:userdebug/test-keys'
08-01 10:55:43.124  3106  3106 F DEBUG   : Revision: '0'
08-01 10:55:43.124  3106  3106 F DEBUG   : ABI: 'x86_64'
08-01 10:55:43.124  3106  3106 F DEBUG   : pid: 3068, tid: 3096, name: Loader map obje  >>> net.osmand.plus <<<
08-01 10:55:43.124  3106  3106 F DEBUG   : signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0
08-01 10:55:43.124  3106  3106 F DEBUG   :     rax ff000000ff000000  rbx 0000000000019000  rcx 000000000000003d  rdx ff000000ff000000
08-01 10:55:43.124  3106  3106 F DEBUG   :     rsi 0000000000000042  rdi 00007f2430312280
08-01 10:55:43.124  3106  3106 F DEBUG   :     r8  00000000ffffffe4  r9  00007f2415ec3400  r10 1e67e45b5565aaaf  r11 0000000000000000
08-01 10:55:43.124  3106  3106 F DEBUG   :     r12 00007f2430119080  r13 0000000000018000  r14 00007f2430312280  r15 0000000000000000
08-01 10:55:43.124  3106  3106 F DEBUG   :     cs  0000000000000033  ss  000000000000002b
08-01 10:55:43.124  3106  3106 F DEBUG   :     rip 00007f243075d973  rbp 000000000000002e  rsp 00007f24285fd3a8  eflags 0000000000010286
08-01 10:55:43.128  3106  3106 F DEBUG   : 
08-01 10:55:43.128  3106  3106 F DEBUG   : backtrace:
08-01 10:55:43.128  3106  3106 F DEBUG   :     #00 pc 00000000000a7973  /system/lib64/libc.so (arena_run_first_best_fit+115)
08-01 10:55:43.128  3106  3106 F DEBUG   :     #01 pc 00000000000a7a1e  /system/lib64/libc.so (arena_run_alloc_large_helper+62)
08-01 10:55:43.128  3106  3106 F DEBUG   :     #02 pc 00000000000a15fa  /system/lib64/libc.so (je_arena_malloc_large+122)
08-01 10:55:43.128  3106  3106 F DEBUG   :     #03 pc 00000000000b4683  /system/lib64/libc.so (je_malloc+1779)
08-01 10:55:43.128  3106  3106 F DEBUG   :     #04 pc 00000000000da359  /data/app/net.osmand.plus-1/lib/x86_64/libc++_shared.so (_Znwm+25)
08-01 10:55:43.128  3106  3106 F DEBUG   :     #05 pc 00000000001f28fb  /data/app/net.osmand.plus-1/lib/x86_64/libosmand.so (_ZNSt6__ndk16vectorI18FoundMapDataObjectNS_9allocatorIS1_EEE21__push_back_slow_pathIRKS1_EEvOT_+139)
08-01 10:55:43.128  3106  3106 F DEBUG   :     #06 pc 00000000001ec969  /data/app/net.osmand.plus-1/lib/x86_64/libosmand.so (_ZN15ResultPublisher7publishE18FoundMapDataObject+281)
08-01 10:55:43.128  3106  3106 F DEBUG   :     #07 pc 00000000001e8481  /data/app/net.osmand.plus-1/lib/x86_64/libosmand.so (_Z17readMapDataBlocksPN6google8protobuf2io16CodedInputStreamEP11SearchQueryP13MapTreeBoundsP8MapIndex+497)
08-01 10:55:43.128  3106  3106 F DEBUG   :     #08 pc 00000000001e892e  /data/app/net.osmand.plus-1/lib/x86_64/libosmand.so (_Z13searchMapDataPN6google8protobuf2io16CodedInputStreamEP7MapRootP8MapIndexP11SearchQuery+334)
08-01 10:55:43.128  3106  3106 F DEBUG   :     #09 pc 00000000001eb80a  /data/app/net.osmand.plus-1/lib/x86_64/libosmand.so (_Z14readMapObjectsP11SearchQueryP13BinaryMapFile+762)
08-01 10:55:43.128  3106  3106 F DEBUG   :     #10 pc 00000000001ebbc1  /data/app/net.osmand.plus-1/lib/x86_64/libosmand.so (_Z26readMapObjectsForRenderingP11SearchQueryRNSt6__ndk16vectorI18FoundMapDataObjectNS1_9allocatorIS3_EEEES7_S7_S7_S7_RiRbS8_+785)
08-01 10:55:43.128  3106  3106 F DEBUG   :     #11 pc 00000000001ed138  /data/app/net.osmand.plus-1/lib/x86_64/libosmand.so (_Z25searchObjectsForRenderingP11SearchQuerybNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERi+232)
08-01 10:55:43.128  3106  3106 F DEBUG   :     #12 pc 0000000000248b30  /data/app/net.osmand.plus-1/lib/x86_64/libosmand.so (Java_net_osmand_NativeLibrary_searchNativeObjectsForRendering+512)
08-01 10:55:43.128  3106  3106 F DEBUG   :     #13 pc 00000000019a290b  /data/app/net.osmand.plus-1/oat/x86_64/base.odex (offset 0x18cb000)
08-01 10:55:43.128  3106  3106 F DEBUG   :     #14 pc 000000000010103f  <anonymous:00007f24284fd000>
08-01 10:55:43.128  3106  3106 F DEBUG   :     #15 pc 00000000002e3e69  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+409)
08-01 10:55:43.128  3106  3106 F DEBUG   :     #16 pc 0000000000000000  <unknown>
08-01 10:55:43.128  3106  3106 F DEBUG   :     #17 pc 00000000001201ff  <anonymous:00007f242fffd000>
08-01 10:55:43.438   114  3111 W ActivityManager:   Force finishing activity net.osmand.plus/.activities.MapActivity
08-01 10:55:43.439   114  3111 W ActivityManager:   Force finishing activity net.osmand.plus/.activities.MapActivity
08-01 10:55:43.439   114  3111 W ActivityManager: Duplicate finish request for ActivityRecord{da0e989 u0 net.osmand.plus/.activities.MapActivity t36 f}
08-01 10:55:43.440     9     9 W         : debuggerd: resuming target 3068
08-01 10:55:43.440   114   132 I BootReceiver: Copying /data/tombstones/tombstone_02 to DropBox (SYSTEM_TOMBSTONE)
08-01 10:55:43.464   114   149 W InputDispatcher: channel '771c86 net.osmand.plus/net.osmand.plus.activities.MapActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
08-01 10:55:43.464   114   149 E InputDispatcher: channel '771c86 net.osmand.plus/net.osmand.plus.activities.MapActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
08-01 10:55:43.465    32    32 I Zygote  : Process 3068 exited due to signal (11)
08-01 10:55:43.470   114   299 D         : HostConnection::get() New Host Connection established 0x7f2411e20a80, tid 299
08-01 10:55:43.478   114  1358 D GraphicsStats: Buffer count: 3
08-01 10:55:43.508    31    31 E EGL_emulation: tid 31: eglCreateSyncKHR(1315): error 0x3004 (EGL_BAD_ATTRIBUTE)
08-01 10:55:43.606   114   441 I WindowManager: WIN DEATH: Window{771c86 u0 net.osmand.plus/net.osmand.plus.activities.MapActivity}
08-01 10:55:43.606   114   441 W InputDispatcher: Attempted to unregister already unregistered input channel '771c86 net.osmand.plus/net.osmand.plus.activities.MapActivity (server)'
08-01 10:55:43.607   114   441 W WindowManager: Force-removing child win Window{c5812e3 u0 SurfaceView - net.osmand.plus/net.osmand.plus.activities.MapActivity} from container Window{771c86 u0 net.osmand.plus/net.osmand.plus.activities.MapActivity}
08-01 10:55:43.608   114  1275 W WindowManager: Failed looking up window
08-01 10:55:43.608   114  1275 W WindowManager: java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@4987b12 does not exist
08-01 10:55:43.608   114  1275 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9425)
08-01 10:55:43.608   114  1275 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9416)
08-01 10:55:43.608   114  1275 W WindowManager: 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1800)
08-01 10:55:43.608   114  1275 W WindowManager: 	at android.os.BinderProxy.sendDeathNotice(Binder.java:688)
08-01 10:55:43.608   114  1275 I WindowManager: WIN DEATH: null
08-01 10:55:43.618   114   125 I ActivityManager: Process net.osmand.plus (pid 3068) has died
08-01 10:55:43.618   114   125 D ActivityManager: cleanUpApplicationRecord -- 3068
08-01 10:55:43.619   114   125 I AnboxPlatformServiceProxy: Task removed id=36
```

<details>
<summary>anbox system-info output</summary>

```
version: 0.0~git20200526-1+b2-Debian
cpu:
  arch:  x86
  brand:       Intel(R) Xeon(R) CPU E3-1240 V2 @ 3.40GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
os:
  name: Debian GNU/Linux
  version: 
  snap-based: false
kernel:
  version: Linux version 5.7.0-2-amd64 (debian-kernel@lists.debian.org) (gcc version 9.3.0 (Debian 9.3.0-16), GNU ld (GNU Binutils for Debian) 2.35) #1 SMP Debian 5.7.10-1 (2020-07-26)
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: X.Org
    vendor: OpenGL ES 3.1 Mesa 20.1.4
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_rgtc
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_texture_3D
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float
      - GL_EXT_draw_instanced
      - GL_EXT_texture_sRGB_decode
      - GL_OES_EGL_image
      - GL_OES_depth_texture
      - GL_AMD_performance_monitor
      - GL_OES_packed_depth_stencil
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_NV_conditional_render
      - GL_OES_get_program_binary
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_EXT_frag_depth
      - GL_NV_fbo_color_attachments
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_OES_viewport_array
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_robustness
      - GL_EXT_texture_rg
      - GL_EXT_unpack_subimage
      - GL_NV_draw_buffers
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_EXT_draw_buffers
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_KHR_robustness
      - GL_KHR_texture_compression_astc_ldr
      - GL_NV_pixel_buffer_object
      - GL_OES_depth_texture_cube_map
      - GL_OES_required_internalformat
      - GL_OES_surfaceless_context
      - GL_EXT_color_buffer_float
      - GL_EXT_sRGB_write_control
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_implicit_conversions
      - GL_EXT_shader_integer_mix
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_base_instance
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_gpu_shader5
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_render_snorm
      - GL_EXT_shader_io_blocks
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_norm16
      - GL_EXT_texture_view
      - GL_KHR_context_flush_control
      - GL_KHR_robust_buffer_access_behavior
      - GL_NV_image_formats
      - GL_OES_copy_image
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_gpu_shader5
      - GL_OES_primitive_bounding_box
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_texture_view
      - GL_EXT_blend_func_extended
      - GL_EXT_buffer_storage
      - GL_EXT_float_blend
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_KHR_no_error
      - GL_KHR_texture_compression_astc_sliced_3d
      - GL_OES_EGL_image_external_essl3
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_shader_image_atomic
      - GL_EXT_clip_cull_distance
      - GL_EXT_disjoint_timer_query
      - GL_EXT_texture_compression_s3tc_srgb
      - GL_MESA_shader_integer_functions
      - GL_EXT_clip_control
      - GL_EXT_texture_compression_bptc
      - GL_KHR_parallel_shader_compile
      - GL_EXT_EGL_image_storage
      - GL_EXT_texture_sRGB_R8
      - GL_MESA_framebuffer_flip_y
      - GL_EXT_depth_clamp
      - GL_EXT_texture_query_lod
```
</details>
