### ISSUE TITLE
Application Launch: (EGL_BAD_ATTRIBUTE)

### ISSUE THREAD

**Issue by DrCorndog** [anbox/anbox#1557]
```
[version: 4
snap-revision: 186
cpu:
  arch:  x86
  brand: AMD Ryzen Threadripper 3970X 32-Core Processor 
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 20.04.1 LTS (Focal Fossa)
  snap-based: true
kernel:
  version: Linux version 5.4.0-26-generic (buildd@lcy01-amd64-029) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)) #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: X.Org
    vendor: OpenGL ES 3.1 Mesa 18.0.5
    extensions:
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_base_instance
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_read_format_bgra
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_image_formats
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_get_program_binary
      - GL_OES_gpu_shader5
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_primitive_bounding_box
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array]
```
</details>

**Please describe your problem:**
Unable to Launch Application "Dungeon Boss" through the Application Manager. No output. Generated log files:

Snipped Below as to what I believe is pointing to the issue (EGL_emulation: tid 29: eglCreateSyncKHR(1315): error 0x3004 (EGL_BAD_ATTRIBUTE))

```
08-07 18:54:34.016   167   266 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.bigfishgames.dungeonbossf2pgoogle cmp=com.bigfishgames.dungeonbossf2pgoogle/com.bossfightentertainment.hammer.HammerNativeActivity} from uid 10000 on display 0
08-07 18:54:34.019   141   161 I MediaPlayerService: MediaPlayerService::getOMX
08-07 18:54:34.019   167  1248 I OMXClient: MuxOMX ctor
08-07 18:54:34.020   167  1248 E ACodec  : Unable to instantiate a decoder for type 'audio/vorbis' with err 0xfffffffe.
08-07 18:54:34.020   167  1248 E ACodec  : signalError(omxError 0xfffffffe, internalError -2)
08-07 18:54:34.020   167  1248 E MediaCodec: Codec reported err 0xfffffffe, actionCode 0, while in state 1
08-07 18:54:34.020   167  1246 E SoundPool: Unable to load sample
08-07 18:54:34.020   167   224 W AudioService: onLoadSoundEffects(), Error -2147483648 while loading samples
08-07 18:54:34.022   141   161 I MediaPlayerService: MediaPlayerService::getOMX
08-07 18:54:34.022   167  1249 I OMXClient: MuxOMX ctor
08-07 18:54:34.022   167  1249 E ACodec  : Unable to instantiate a decoder for type 'audio/vorbis' with err 0xfffffffe.
08-07 18:54:34.022   167  1249 E ACodec  : signalError(omxError 0xfffffffe, internalError -2)
08-07 18:54:34.022   167  1249 E MediaCodec: Codec reported err 0xfffffffe, actionCode 0, while in state 1
08-07 18:54:34.022   167  1246 E SoundPool: Unable to load sample
08-07 18:54:34.045  1250  1250 D houdini : [1250] Initialize library(version: 7.1.0a_y.49344 RELEASE)... successfully.
08-07 18:54:34.046  1250  1250 W art     : Unexpected CPU variant for X86 using defaults: x86
08-07 18:54:34.052   167   375 I ActivityManager: Start proc 1250:com.bigfishgames.dungeonbossf2pgoogle/u0a52 for activity com.bigfishgames.dungeonbossf2pgoogle/com.bossfightentertainment.hammer.HammerNativeActivity
08-07 18:54:34.058    29  1206 D PermissionCache: checking android.permission.READ_FRAME_BUFFER for uid=1000 => granted (116 us)
08-07 18:54:34.060   167   375 D         : HostConnection::get() New Host Connection established 0x7fc64a379540, tid 375
08-07 18:54:34.062    29    29 E EGL_emulation: tid 29: eglCreateSyncKHR(1315): error 0x3004 (EGL_BAD_ATTRIBUTE)
08-07 18:54:34.192  1250  1250 I MultiDex: VM with version 2.1.0 has multidex support
08-07 18:54:34.192  1250  1250 I MultiDex: Installing application
08-07 18:54:34.192  1250  1250 I MultiDex: VM has multidex support, MultiDex support library is disabled.
08-07 18:54:34.204  1250  1250 D FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
08-07 18:54:34.205  1250  1250 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
08-07 18:54:34.205  1250  1250 I FirebaseInitProvider: FirebaseApp initialization successful
08-07 18:54:34.213  1250  1271 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-07 18:54:34.218  1250  1270 I FA      : App measurement is starting up, version: 13001
08-07 18:54:34.218  1250  1270 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
08-07 18:54:34.218  1250  1270 I FA      : To enable faster debug mode event logging run:
08-07 18:54:34.218  1250  1270 I FA      :   adb shell setprop debug.firebase.analytics.app com.bigfishgames.dungeonbossf2pgoogle
08-07 18:54:34.222  1250  1250 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 1250 (onbossf2pgoogle)
08-07 18:54:34.222     8     8 W         : debuggerd: handling request: pid=1250 uid=10052 gid=10052 tid=1250
08-07 18:54:34.276  1283  1283 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-07 18:54:34.276  1283  1283 F DEBUG   : Build fingerprint: 'Android/anbox_x86_64/x86_64:7.1.1/N6F26Q/root07191722:userdebug/test-keys'
08-07 18:54:34.276  1283  1283 F DEBUG   : Revision: '0'
08-07 18:54:34.276  1283  1283 F DEBUG   : ABI: 'x86'
08-07 18:54:34.276  1283  1283 F DEBUG   : pid: 1250, tid: 1250, name: onbossf2pgoogle  >>> com.bigfishgames.dungeonbossf2pgoogle <<<
08-07 18:54:34.276  1283  1283 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
08-07 18:54:34.276  1283  1283 F DEBUG   :     eax 00000000  ebx d93656ec  ecx e6743530  edx 00000000
08-07 18:54:34.276  1283  1283 F DEBUG   :     esi e675a5b8  edi e65a2390
08-07 18:54:34.276  1283  1283 F DEBUG   :     xcs 00000023  xds 0000002b  xes 0000002b  xfs 0000006b  xss 0000002b
08-07 18:54:34.276  1283  1283 F DEBUG   :     eip d92973ad  ebp ffd64be8  esp ffd64b60  flags 00010246
08-07 18:54:34.281  1283  1283 F DEBUG   : 
08-07 18:54:34.281  1283  1283 F DEBUG   : backtrace:
08-07 18:54:34.281  1283  1283 F DEBUG   :     #00 pc 000253ad  /system/lib/libc.so (_Z19__libc_init_globalsR19KernelArgumentBlock+109)
08-07 18:54:34.281  1283  1283 F DEBUG   :     #01 pc 00015ce7  /system/lib/libc.so (_ZL14__libc_preinitv+39)
08-07 18:54:34.281  1283  1283 F DEBUG   :     #02 pc 0000bf89  /system/bin/linker (__dl__ZN6soinfo13call_functionEPKcPFvvE+137)
08-07 18:54:34.281  1283  1283 F DEBUG   :     #03 pc 0000be73  /system/bin/linker (__dl__ZN6soinfo10call_arrayEPKcPPFvvEjb+323)
08-07 18:54:34.281  1283  1283 F DEBUG   :     #04 pc 00009aa1  /system/bin/linker (__dl__ZN6soinfo17call_constructorsEv+369)
08-07 18:54:34.281  1283  1283 F DEBUG   :     #05 pc 00009825  /system/bin/linker (__dl__Z9do_dlopenPKciPK17android_dlextinfoPv+2725)
08-07 18:54:34.281  1283  1283 F DEBUG   :     #06 pc 00005276  /system/bin/linker (__dl_dlopen+70)
08-07 18:54:34.281  1283  1283 F DEBUG   :     #07 pc 00209252  /system/lib/libhoudini.so
08-07 18:54:34.631   167  1288 W ActivityManager:   Force finishing activity com.bigfishgames.dungeonbossf2pgoogle/com.bossfightentertainment.hammer.HammerNativeActivity
08-07 18:54:34.634   167   185 I BootReceiver: Copying /data/tombstones/tombstone_03 to DropBox (SYSTEM_TOMBSTONE)
08-07 18:54:34.636     8     8 W         : debuggerd: resuming target 1250
08-07 18:54:34.659   167  1290 D         : HostConnection::get() New Host Connection established 0x7fc642aeb3c0, tid 1290
08-07 18:54:34.662   167  1290 I OpenGLRenderer: Initialized EGL, version 1.4
08-07 18:54:34.662   167  1290 D OpenGLRenderer: Swap behavior 1
08-07 18:54:34.743   142   148 E FrameworkListener: read() failed (Connection reset by peer)
08-07 18:54:34.744   167   266 I ActivityManager: Process com.bigfishgames.dungeonbossf2pgoogle (pid 1250) has died
```

**What were you expecting?:**

Successful Launch
[anbox-system-diagnostics-2020-08-07.zip](https://github.com/anbox/anbox/files/5043240/anbox-system-diagnostics-2020-08-07.zip)

**Additional info:**
