### ISSUE TITLE
App in Anbox loads but crashes soon after

### ISSUE THREAD

**Issue by whatthe345** [anbox/anbox#1593]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `
[anbox-system-diagnostics-2020-09-01.zip](https://github.com/anbox/anbox/files/5159487/anbox-system-diagnostics-2020-09-01.zip)

6. ** Please paste the result of `anbox system-info` below:**

```
version: local-5ab92ef
snap-revision: 198
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 18.04.5 LTS (Bionic Beaver)
  snap-based: true
kernel:
  version: Linux version 4.15.0-39-generic (buildd@lgw01-amd64-054) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel
    vendor: OpenGL ES 3.2 Mesa 20.0.8
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_rgtc
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_texture_3D
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float
      - GL_EXT_texture_sRGB_decode
      - GL_OES_EGL_image
      - GL_OES_depth_texture
      - GL_AMD_performance_monitor
      - GL_OES_packed_depth_stencil
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_NV_conditional_render
      - GL_OES_get_program_binary
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_EXT_frag_depth
      - GL_NV_fbo_color_attachments
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_OES_viewport_array
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_robustness
      - GL_EXT_texture_rg
      - GL_EXT_unpack_subimage
      - GL_NV_draw_buffers
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_EXT_draw_buffers
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_KHR_robustness
      - GL_KHR_texture_compression_astc_ldr
      - GL_OES_depth_texture_cube_map
      - GL_OES_required_internalformat
      - GL_OES_surfaceless_context
      - GL_EXT_color_buffer_float
      - GL_EXT_sRGB_write_control
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_implicit_conversions
      - GL_EXT_shader_integer_mix
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_INTEL_performance_query
      - GL_ANDROID_extension_pack_es31a
      - GL_EXT_base_instance
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_gpu_shader5
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_render_snorm
      - GL_EXT_shader_io_blocks
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_norm16
      - GL_EXT_texture_view
      - GL_KHR_blend_equation_advanced
      - GL_KHR_context_flush_control
      - GL_KHR_robust_buffer_access_behavior
      - GL_NV_image_formats
      - GL_OES_copy_image
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_gpu_shader5
      - GL_OES_primitive_bounding_box
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_texture_view
      - GL_EXT_blend_func_extended
      - GL_EXT_buffer_storage
      - GL_EXT_float_blend
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_shader_samples_identical
      - GL_KHR_no_error
      - GL_KHR_texture_compression_astc_sliced_3d
      - GL_OES_EGL_image_external_essl3
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_shader_image_atomic
      - GL_EXT_clip_cull_distance
      - GL_EXT_disjoint_timer_query
      - GL_EXT_texture_compression_s3tc_srgb
      - GL_MESA_shader_integer_functions
      - GL_EXT_clip_control
      - GL_EXT_texture_compression_bptc
      - GL_KHR_parallel_shader_compile
      - GL_EXT_EGL_image_storage
      - GL_EXT_shader_framebuffer_fetch_non_coherent
      - GL_EXT_texture_sRGB_R8
      - GL_EXT_texture_shadow_lod
      - GL_MESA_framebuffer_flip_y
      - GL_NV_compute_shader_derivatives
      - GL_EXT_demote_to_helper_invocation
      - GL_EXT_depth_clamp
      - GL_EXT_texture_query_lod

```

**Please describe your problem:**
the app starts to load but crashes after the first loading creen

**What were you expecting?:**
the app to not crash

**Additional info:**
This is the only app that des something like this the others work fine.
Here is the `logcat` info
```
09-02 01:16:32.234    32   101 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(671)
09-02 01:16:48.200   115   263 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.innersloth.spacemafia cmp=com.innersloth.spacemafia/com.unity3d.player.UnityPlayerActivity} from uid 10000 on display 0
09-02 01:16:48.204    40    40 I MediaPlayerService: MediaPlayerService::getOMX
09-02 01:16:48.204   115  1546 I OMXClient: MuxOMX ctor
09-02 01:16:48.204   115  1546 E ACodec  : Unable to instantiate a decoder for type 'audio/vorbis' with err 0xfffffffe.
09-02 01:16:48.204   115  1546 E ACodec  : signalError(omxError 0xfffffffe, internalError -2)
09-02 01:16:48.204   115  1546 E MediaCodec: Codec reported err 0xfffffffe, actionCode 0, while in state 1
09-02 01:16:48.204   115  1544 E SoundPool: Unable to load sample
09-02 01:16:48.205   115   171 W AudioService: onLoadSoundEffects(), Error -2147483648 while loading samples
09-02 01:16:48.207    40   227 I MediaPlayerService: MediaPlayerService::getOMX
09-02 01:16:48.207   115  1547 I OMXClient: MuxOMX ctor
09-02 01:16:48.207   115  1547 E ACodec  : Unable to instantiate a decoder for type 'audio/vorbis' with err 0xfffffffe.
09-02 01:16:48.207   115  1547 E ACodec  : signalError(omxError 0xfffffffe, internalError -2)
09-02 01:16:48.207   115  1547 E MediaCodec: Codec reported err 0xfffffffe, actionCode 0, while in state 1
09-02 01:16:48.207   115  1544 E SoundPool: Unable to load sample
09-02 01:16:48.236  1548  1548 D houdini : [1548] Initialize library(version: 7.1.0a_y.49344 RELEASE)... successfully.
09-02 01:16:48.237  1548  1548 W art     : Unexpected CPU variant for X86 using defaults: x86
09-02 01:16:48.239   115   126 I ActivityManager: Start proc 1548:com.innersloth.spacemafia/u0a53 for activity com.innersloth.spacemafia/com.unity3d.player.UnityPlayerActivity
09-02 01:16:48.416  1548  1563 W System  : ClassLoader referenced unknown path: /system/priv-app/PrebuiltGmsCore/lib/x86
09-02 01:16:48.418  1548  1563 D ApplicationLoaders: ignored Vulkan layer search path /system/priv-app/PrebuiltGmsCore/lib/x86:/system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/x86:/system/lib:/vendor/lib for namespace 0xf7c7f090
09-02 01:16:48.438  1548  1548 D houdini : [1548] Added shared library /data/app/com.innersloth.spacemafia-1/lib/arm/libmain.so for ClassLoader by Native Bridge.
09-02 01:16:48.440  1548  1563 I DynamiteModule: Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:21800
09-02 01:16:48.440  1548  1563 I DynamiteModule: Selected remote version of com.google.android.gms.ads.dynamite, version >= 21800
09-02 01:16:48.440  1548  1565 W DynamiteModule: Local module descriptor class for com.google.android.gms.measurement.dynamite not found.
09-02 01:16:48.440  1548  1563 V DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
09-02 01:16:48.442  1548  1565 I DynamiteModule: Considering local module com.google.android.gms.measurement.dynamite:0 and remote module com.google.android.gms.measurement.dynamite:17
09-02 01:16:48.442  1548  1565 I DynamiteModule: Selected remote version of com.google.android.gms.measurement.dynamite, version >= 17
09-02 01:16:48.442  1548  1565 V DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
09-02 01:16:48.457  1548  1565 W System  : ClassLoader referenced unknown path: 
09-02 01:16:48.457  1548  1565 W System  : ClassLoader referenced unknown path: /system/priv-app/PrebuiltGmsCore/lib/x86
09-02 01:16:48.458  1548  1565 D ApplicationLoaders: ignored Vulkan layer search path /system/priv-app/PrebuiltGmsCore/lib/x86:/system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/x86:/system/lib:/vendor/lib for namespace 0xf7c7f0d0
09-02 01:16:48.473  1548  1563 I DynamiteLoaderV2Impl: [70] AdsFdrDynamite.integ
09-02 01:16:48.555  1548  1563 W System  : ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/00000000/n/x86
09-02 01:16:48.555  1548  1563 W System  : ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/00000000/n/armeabi-v7a
09-02 01:16:48.555  1548  1563 W System  : ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/00000000/n/armeabi
09-02 01:16:48.559  1548  1565 I DynamiteLoaderV2Impl: [70] Measurementdynamite
09-02 01:16:48.569  1548  1565 W System  : ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/00000007/n/x86
09-02 01:16:48.569  1548  1565 W System  : ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/00000007/n/armeabi-v7a
09-02 01:16:48.569  1548  1565 W System  : ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/00000007/n/armeabi
09-02 01:16:48.569  1548  1548 D         : HostConnection::get() New Host Connection established 0xf3bb70d0, tid 1548
09-02 01:16:48.582  1548  1565 W DynamiteModule: Local module descriptor class for com.google.android.gms.measurement.dynamite not found.
09-02 01:16:48.673  1548  1571 I FA-Ads  : App measurement initialized, version: 32000
09-02 01:16:48.673  1548  1571 I FA-Ads  : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
09-02 01:16:48.687   115   136 I ActivityManager: Displayed com.innersloth.spacemafia/com.unity3d.player.UnityPlayerActivity: +458ms
09-02 01:16:48.754  1548  1570 I Unity   : SystemInfo CPU = ARMv7 VFPv3 NEON VMH, Cores = 2, Memory = 11883mb
09-02 01:16:48.755  1548  1570 I Unity   : SystemInfo ARM big.LITTLE configuration: 2 big (mask: 0x3), 0 little (mask: 0x0)
09-02 01:16:48.755  1548  1570 I Unity   : ApplicationInfo com.innersloth.spacemafia version 2020.8.31 build 4882500e-71d4-44ba-8e3b-430267cf3177
09-02 01:16:48.756  1548  1570 I Unity   : Built from '2019.4/staging' branch, Version '2019.4.9f1 (50fe8a171dd9)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'armeabi-v7a', Stripping 'Enabled'
09-02 01:16:48.924  1548  1570 D         : HostConnection::get() New Host Connection established 0xd3ef3770, tid 1570
09-02 01:16:48.926  1548  1570 E EGL_emulation: tid 1570: eglCreateContext(919): error 0x3005 (EGL_BAD_CONFIG)
09-02 01:16:48.926  1548  1570 E EGL_emulation: tid 1570: eglCreateContext(919): error 0x3005 (EGL_BAD_CONFIG)
09-02 01:16:48.930  1548  1570 E EGL_emulation: [getAttribValue] Bad attribute idx
09-02 01:16:48.930  1548  1570 E EGL_emulation: tid 1570: eglGetConfigAttrib(613): error 0x3004 (EGL_BAD_ATTRIBUTE)
09-02 01:16:48.930  1548  1570 E EGL_emulation: [getAttribValue] Bad attribute idx
09-02 01:16:48.930  1548  1570 E EGL_emulation: tid 1570: eglGetConfigAttrib(613): error 0x3004 (EGL_BAD_ATTRIBUTE)
09-02 01:16:48.930  1548  1570 E EGL_emulation: [getAttribValue] Bad attribute idx
09-02 01:16:48.930  1548  1570 E EGL_emulation: tid 1570: eglGetConfigAttrib(613): error 0x3004 (EGL_BAD_ATTRIBUTE)
09-02 01:16:48.930  1548  1570 E EGL_emulation: tid 1570: eglCreateContext(919): error 0x3005 (EGL_BAD_CONFIG)
09-02 01:16:48.931  1548  1570 E Unity   : [EGL] Unable to create context!: EGL_BAD_CONFIG: An EGLConfig argument does not name a valid EGL frame buffer configuration. 
09-02 01:16:48.931  1548  1570 E Unity   : (Filename: ./Runtime/GfxDevice/egl/ContextEGL.cpp Line: 134)
09-02 01:16:48.931  1548  1570 E Unity   : 
09-02 01:16:48.935  1548  1570 E EGL_emulation: tid 1570: eglCreateContext(919): error 0x3005 (EGL_BAD_CONFIG)
09-02 01:16:48.935  1548  1570 E Unity   : [EGL] Unable to create context!: EGL_BAD_CONFIG: An EGLConfig argument does not name a valid EGL frame buffer configuration. 
09-02 01:16:48.935  1548  1570 E Unity   : (Filename: ./Runtime/GfxDevice/egl/ContextEGL.cpp Line: 134)
09-02 01:16:48.935  1548  1570 E Unity   : 
09-02 01:16:48.954  1548  1570 D Unity   :  GL_EXT_debug_marker GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_depth_texture GL_OES_packed_depth_stencil GL_OES_EGL_image_external
09-02 01:16:48.963  1548  1593 D         : HostConnection::get() New Host Connection established 0xf780fac0, tid 1593
09-02 01:16:49.003  1548  1594 I art     : Thread[12,tid=1594,Runnable,Thread*=0xebc32500,peer=0x12c6fdc0,"FMODAudioDevice"] setPriority(PRIO_PROCESS, 1594, -8) failed: Permission denied
09-02 01:16:49.006  1548  1594 D AudioTrack: Client defaulted notificationFrames to 682 for frameCount 2048
09-02 01:16:49.107  1548  1570 V MediaRouter: Adding route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=null types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
09-02 01:16:49.108  1548  1570 V MediaRouter: Updating audio routes: AudioRoutesInfo{ type=SPEAKER }
09-02 01:16:49.108  1548  1570 V MediaRouter: Selecting route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=null types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
09-02 01:16:49.151   115   378 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@4bfd0d6 attribute=null, token = android.os.BinderProxy@5b74e4d
09-02 01:16:51.486    32   101 W AudioFlinger: write blocked for 762 msecs, 30 delayed writes, thread 0xf6903180
09-02 01:16:51.487    32   101 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(1642)
09-02 01:16:52.925    32   101 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(671)
09-02 01:16:53.790   115   150 W InputDispatcher: channel '575fd02 com.innersloth.spacemafia/com.unity3d.player.UnityPlayerActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
09-02 01:16:53.790   115   150 E InputDispatcher: channel '575fd02 com.innersloth.spacemafia/com.unity3d.player.UnityPlayerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
09-02 01:16:53.790   115   293 I ActivityManager: Process com.innersloth.spacemafia (pid 1548) has died
09-02 01:16:53.790   115   293 D ActivityManager: cleanUpApplicationRecord -- 1548
09-02 01:16:53.791   115   293 W ActivityManager: Force removing ActivityRecord{822cea1 u0 com.innersloth.spacemafia/com.unity3d.player.UnityPlayerActivity t11}: app died, no saved state
09-02 01:16:53.791   115   378 I WindowManager: WIN DEATH: Window{2d14f57 u0 SurfaceView - com.innersloth.spacemafia/com.unity3d.player.UnityPlayerActivity}
09-02 01:16:53.792    31    31 I Zygote  : Process 1548 exited due to signal (11)
09-02 01:16:53.792    31    31 I Zygote  : Process 1548 dumped core.
09-02 01:16:53.793   115   964 I WindowManager: WIN DEATH: Window{575fd02 u0 com.innersloth.spacemafia/com.unity3d.player.UnityPlayerActivity}
09-02 01:16:53.793   115   964 W InputDispatcher: Attempted to unregister already unregistered input channel '575fd02 com.innersloth.spacemafia/com.unity3d.player.UnityPlayerActivity (server)'
09-02 01:16:53.795   115   293 I AnboxPlatformServiceProxy: Task removed id=11
09-02 01:16:54.365    32   101 D AudioFlinger: mixer(0xf6903180) throttle end: throttle time(671)
```
