### ISSUE TITLE
no anbox lunched

### ISSUE THREAD

**Issue by goraxmax** [anbox/anbox#16]
Make sure you are running the latest version of Anbox before reporting an issue.

**Anbox release (`anbox version`) and system info (`anbox system-info`):**
anbox version
anbox 0.1.0

 anbox system-info
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.10.9-041009-generic (kernel@gloin) (gcc version 6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12) ) #201704080516 SMP Sat Apr 8 09:17:54 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_swap_region
      - EGL_NOK_texture_from_pixmap
      - EGL_NV_post_sub_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp

**Description of the problem:**
when i clik on anbox icon in order to start it, nothing happened.
when i run  anbox session-manager, nothing happened
when i run sudo anbox session-manager
[EE 2017-04-11 21:21:11] [daemon.cpp:58@Run] org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message

**Expected:**
i excpected to run the main android windows to start and use anbox

**Additional info:**
very good concept, if it work's technically !

**Comment by morphis** [comment]
What does `sudo systemctl status snap.anbox.container-manager` , `anbox system-info` and `initctl status anbox` say?

Please don't try to run `anbox session-manager` with sudo. It's not meant to be run with root privileges.

**Comment by flexiondotorg** [comment]
Looks like I have the same issue.

## sudo systemctl status snap.anbox.container-manager

```
● snap.anbox.container-manager.service - Service for snap application anbox.container-manager
   Loaded: loaded (/etc/systemd/system/snap.anbox.container-manager.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2017-04-11 23:21:26 BST; 8min ago
 Main PID: 6286 (anbox)
    Tasks: 10
   Memory: 10.9M
      CPU: 331ms
   CGroup: /system.slice/snap.anbox.container-manager.service
           ├─6286 /snap/anbox/15/usr/bin/anbox container-manager --data-path=/var/snap/anbox/common/ --android-image=/snap/anbox/15/android.img
           └─6520 dnsmasq -u dnsmasq --strict-order --bind-interfaces --pid-file=/run/anbox/dnsmasq.pid --dhcp-no-override --except-interface=lo --interfa

Apr 11 23:23:09 skull dnsmasq-dhcp[6520]: DHCPOFFER(anboxbr0) 10.0.6.207 16:6d:93:47:86:21
Apr 11 23:23:09 skull dnsmasq-dhcp[6520]: DHCPREQUEST(anboxbr0) 10.0.6.207 16:6d:93:47:86:21
Apr 11 23:23:09 skull dnsmasq-dhcp[6520]: DHCPACK(anboxbr0) 10.0.6.207 16:6d:93:47:86:21 android-44bcdbf1de1fa8b6
Apr 11 23:23:09 skull dnsmasq-dhcp[6520]: RTR-ADVERT(anboxbr0) fd9d:e4dc:4e00:9e98::
Apr 11 23:23:10 skull dnsmasq-dhcp[6520]: SLAAC-CONFIRM(anboxbr0) fd9d:e4dc:4e00:9e98:146d:93ff:fe47:8621 android-44bcdbf1de1fa8b6
Apr 11 23:23:15 skull dnsmasq-dhcp[6520]: RTR-ADVERT(anboxbr0) fd9d:e4dc:4e00:9e98::
Apr 11 23:23:34 skull dnsmasq-dhcp[6520]: RTR-ADVERT(anboxbr0) fd9d:e4dc:4e00:9e98::
Apr 11 23:23:52 skull dnsmasq-dhcp[6520]: RTR-ADVERT(anboxbr0) fd9d:e4dc:4e00:9e98::
Apr 11 23:24:03 skull dnsmasq-dhcp[6520]: RTR-ADVERT(anboxbr0) fd9d:e4dc:4e00:9e98::
Apr 11 23:24:19 skull dnsmasq-dhcp[6520]: RTR-ADVERT(anboxbr0) fd9d:e4dc:4e00:9e98::
```

## anbox system-info

```
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.8.0-46-generic (buildd@lcy01-15) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #49~16.04.1-Ubuntu SMP Fri Mar 31 14:51:03 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
```

## initctl status anbox

    anbox stop/waiting
