### ISSUE TITLE
Message recipient disconnected from message bus without replying

### ISSUE THREAD

**Issue by alsoGAMER** [anbox/anbox#1600]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

I'm not using the snap version

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
version: local-c1e7550
cpu:
  arch:  x86
  brand:         Intel(R) Celeron(R) CPU 1000M @ 1.80GHz
  features: 
    - sse4_1
    - sse4_2
os:
  name: Manjaro Linux
  version: 
  snap-based: false
kernel:
  version: Linux version 5.4.62-1-MANJARO (builder@2f24f0cf99c2) (gcc version 10.2.0 (GCC)) #1 SMP PREEMPT Thu Sep 3 14:38:22 UTC 2020
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: 
    version: 1.4 (ANGLE 2.1.0.18ba41d789c1)
    extensions:
      - EGL_EXT_create_context_robustness
      - EGL_KHR_create_context
      - EGL_KHR_get_all_proc_addresses
      - EGL_ANGLE_create_context_webgl_compatibility
      - EGL_CHROMIUM_create_context_bind_generates_resource
      - EGL_EXT_pixel_format_float
      - EGL_KHR_surfaceless_context
      - EGL_ANGLE_display_texture_share_group
      - EGL_ANGLE_create_context_client_arrays
      - EGL_ANGLE_program_cache_control
      - EGL_ANGLE_robust_resource_initialization
      - EGL_ANGLE_create_context_extensions_enabled
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_recordable
      - EGL_ANGLE_create_context_backwards_compatible
  gles2:
    vendor: Google Inc.
    vendor: OpenGL ES 3.0.0 (ANGLE 2.1.0.18ba41d789c1)
    extensions:
      - GL_ANGLE_base_vertex_base_instance
      - GL_ANGLE_client_arrays
      - GL_ANGLE_depth_texture
      - GL_ANGLE_explicit_context
      - GL_ANGLE_explicit_context_gles1
      - GL_ANGLE_framebuffer_blit
      - GL_ANGLE_framebuffer_multisample
      - GL_ANGLE_instanced_arrays
      - GL_ANGLE_memory_size
      - GL_ANGLE_multi_draw
      - GL_ANGLE_multiview_multisample
      - GL_ANGLE_program_cache_control
      - GL_ANGLE_provoking_vertex
      - GL_ANGLE_request_extension
      - GL_ANGLE_robust_client_memory
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_ANGLE_texture_external_update
      - GL_ANGLE_texture_multisample
      - GL_ANGLE_texture_rectangle
      - GL_ANGLE_translated_shader_source
      - GL_CHROMIUM_bind_generates_resource
      - GL_CHROMIUM_bind_uniform_location
      - GL_CHROMIUM_color_buffer_float_rgb
      - GL_CHROMIUM_color_buffer_float_rgba
      - GL_CHROMIUM_copy_texture
      - GL_CHROMIUM_lose_context
      - GL_CHROMIUM_sync_query
      - GL_EXT_blend_minmax
      - GL_EXT_color_buffer_float
      - GL_EXT_color_buffer_half_float
      - GL_EXT_debug_marker
      - GL_EXT_discard_framebuffer
      - GL_EXT_disjoint_timer_query
      - GL_EXT_draw_buffers
      - GL_EXT_float_blend
      - GL_EXT_frag_depth
      - GL_EXT_instanced_arrays
      - GL_EXT_map_buffer_range
      - GL_EXT_multisample_compatibility
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_read_format_bgra
      - GL_EXT_robustness
      - GL_EXT_sRGB
      - GL_EXT_sRGB_write_control
      - GL_EXT_shader_texture_lod
      - GL_EXT_texture_compression_bptc
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_storage
      - GL_EXT_unpack_subimage
      - GL_KHR_debug
      - GL_KHR_parallel_shader_compile
      - GL_NV_fence
      - GL_NV_pack_subimage
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_depth32
      - GL_OES_depth_texture
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_get_program_binary
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_surfaceless_context
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_vertex_array_object
      - GL_OVR_multiview
      - GL_OVR_multiview2
      - OES_compressed_EAC_R11_signed_texture
      - OES_compressed_EAC_R11_unsigned_texture
      - OES_compressed_EAC_RG11_signed_texture
      - OES_compressed_EAC_RG11_unsigned_texture
      - OES_compressed_ETC2_RGB8_texture
      - OES_compressed_ETC2_RGBA8_texture
      - OES_compressed_ETC2_punchthroughA_RGBA8_texture
      - OES_compressed_ETC2_punchthroughA_sRGB8_alpha_texture
      - OES_compressed_ETC2_sRGB8_alpha8_texture
      - OES_compressed_ETC2_sRGB8_texture
```
</details>

**Please describe your problem:**
When i launch any application, this error comes out:
`Message recipient disconnected from message bus without replying`
