### ISSUE TITLE
EGL session-manager crash

### ISSUE THREAD

**Issue by danielzgtg** [anbox/anbox#1634]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`

I built from 170f1e029e753e782c66bffb05e91dd770d47dc3.

3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

[anbox-system-diagnostics-2020-10-08.zip](https://github.com/anbox/anbox/files/5346368/anbox-system-diagnostics-2020-10-08.zip)

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
version: local-170f1e0
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 20.04.1 LTS (Focal Fossa)
  snap-based: false
kernel:
  version: Linux version 5.8.12-surface (root@b20879272d4b) (gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #2 SMP Thu Oct 1 19:58:47 UTC 2020
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
```
</details>

**Please describe your problem:**

session-manager crashes with a stacktrace mentioning EGL.

<details>
<summary>console output</summary>

```
home@daniel-tablet1:~$ anbox session-manager
[ 2020-10-08 08:26:55] [Renderer.cpp:128@initialize] Failed to select EGL configuration
Stack trace (most recent call last) in thread 10405:
#7    Object "", at 0xffffffffffffffff, in 
#6    Source "../sysdeps/unix/sysv/linux/x86_64/clone.S", line 95, in __clone [0x7f1e3e12b292]
#5    Source "/build/glibc-ZN95T4/glibc-2.31/nptl/pthread_create.c", line 477, in start_thread [0x7f1e3e49b608]
#4    Source "/home/home/Downloads/anbox/external/android-emugl/shared/emugl/common/thread_pthread.cpp", line 124, in thread_main [0x560060cc8814]
        121: // static
        122: void* Thread::thread_main(void *arg) {
        123:     Thread* self = reinterpret_cast<Thread*>(arg);
      > 124:     intptr_t ret = self->main();
        125: 
        126:     pthread_mutex_lock(&self->mLock);
        127:     self->mIsRunning = false;
#3    Source "/home/home/Downloads/anbox/src/anbox/graphics/emugl/RenderThread.cpp", line 80, in main [0x560060bd42f8]
         77:         readBuf.consume(last);
         78:       }
         79: 
      >  80:       last = threadInfo.m_rcDec.decode(readBuf.buf(), readBuf.validData(), m_stream);
         81:       if (last > 0) {
         82:         readBuf.consume(last);
         83:         progress = true;
#2    Source "/home/home/Downloads/anbox/build/external/android-emugl/host/libs/GLESv1_dec/renderControl_dec.cpp", line 149, in decode [0x560060cc3560]
#1    Source "/home/home/Downloads/anbox/src/anbox/graphics/emugl/RenderControl.cpp", line 161, in rcGetNumConfigs [0x560060c43792]
        158: static EGLint rcGetNumConfigs(uint32_t *p_numAttribs) {
        159:   int numConfigs = 0, numAttribs = 0;
        160: 
      > 161:   renderer->getConfigs()->getPackInfo(&numConfigs, &numAttribs);
        162:   if (p_numAttribs) {
        163:     *p_numAttribs = static_cast<uint32_t>(numAttribs);
        164:   }
#0    Source "/home/home/Downloads/anbox/src/anbox/graphics/emugl/RendererConfig.cpp", line 214, in getPackInfo [0x560060c46649]
        211: void RendererConfigList::getPackInfo(EGLint* numConfigs,
        212:                                      EGLint* numAttributes) const {
        213:   if (numConfigs) {
      > 214:     *numConfigs = mCount;
        215:   }
        216:   if (numAttributes) {
        217:     *numAttributes = static_cast<EGLint>(kConfigAttributesLen);
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault (core dumped)
home@daniel-tablet1:~$
```
</details>

**What were you expecting?:**

It to not segfault.
