### ISSUE TITLE
session-manager segmentation fault

### ISSUE THREAD

**Issue by martins-pukitis** [anbox/anbox#1722]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
DONE
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
DONE
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
DONE
4. Reproduce the error while debug logs enabled.
DONE
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `
[anbox-system-diagnostics-2021-01-07.zip](https://github.com/anbox/anbox/files/5781654/anbox-system-diagnostics-2021-01-07.zip)
6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
lieta@lieta:~$ anbox system-info
version: local-165db5c
snap-revision: 207
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 20.04.1 LTS (Focal Fossa)
  snap-based: true
kernel:
  version: Linux version 5.4.0-59-generic (buildd@lcy01-amd64-028) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #65-Ubuntu SMP Thu Dec 10 12:01:51 UTC 2020
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
```
</details>

**Please describe your problem:**
```
lieta@lieta:~$ anbox session-manager &
[1] 16366
lieta@lieta:~$ [ 2021-01-07 12:39:12] [Renderer.cpp:128@initialize] Failed to select EGL configuration
Stack trace (most recent call last) in thread 16621:
#7    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#6    Object "/snap/anbox/207/lib/x86_64-linux-gnu/libc.so.6", at 0x7f273f85d292, in clone
#5    Object "/snap/anbox/207/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7f273fbcd608, in 
#4    Object "/snap/anbox/207/usr/bin/anbox", at 0x56434821ef34, in emugl::Thread::thread_main(void*)
#3    Object "/snap/anbox/207/usr/bin/anbox", at 0x56434812bf78, in RenderThread::main()
#2    Object "/snap/anbox/207/usr/bin/anbox", at 0x564348219c80, in renderControl_decoder_context_t::decode(void*, unsigned long, IOStream*)
#1    Object "/snap/anbox/207/usr/bin/anbox", at 0x564348199fe2, in 
#0    Object "/snap/anbox/207/usr/bin/anbox", at 0x56434819cea9, in RendererConfigList::getPackInfo(int*, int*) const
Segmentation fault (Address not mapped to object [(nil)])

[1]+  Segmentation fault      (core dumped) anbox session-manager
```
**What were you expecting?:**
No segmentation fault

**Additional info:**
I had an issue with /dev/binder - it didn't exist, although the kernel module is loaded. I did this to workaround it:
```
mkdir /dev/binder
mount -t binder binder /dev/binder
```
