### ISSUE TITLE
No network connectivity

### ISSUE THREAD

**Issue by martins-pukitis** [anbox/anbox#1724]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
DONE
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
DONE
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
DONE
4. Reproduce the error while debug logs enabled.
DONE
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `
[anbox-system-diagnostics-2021-01-08.zip](https://github.com/anbox/anbox/files/5785861/anbox-system-diagnostics-2021-01-08.zip)
6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
lieta@lieta:~$ anbox system-info
version: local-165db5c
snap-revision: 207
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 20.04.1 LTS (Focal Fossa)
  snap-based: true
kernel:
  version: Linux version 5.4.0-59-generic (buildd@lcy01-amd64-028) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #65-Ubuntu SMP Thu Dec 10 12:01:51 UTC 2020
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
```
</details>

**Please describe your problem:**
No network on anbox.
```
lieta@lieta:~$ sudo anbox.shell
NOTE: This shell will give you full root access inside the Android
      container. Be careful with what you're doing!

x86_64:/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
35: eth0@if36: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 46:56:cc:d6:0f:98 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.250.2/24 brd 192.168.250.255 scope global eth0
       valid_lft forever preferred_lft forever
2|x86_64:/ # ip route                                                                                                                                        
192.168.250.0/24 dev eth0  proto kernel  scope link  src 192.168.250.2 
x86_64:/ # ping 192.168.250.2
PING 192.168.250.2 (192.168.250.2) 56(84) bytes of data.
64 bytes from 192.168.250.2: icmp_seq=1 ttl=64 time=0.011 ms
64 bytes from 192.168.250.2: icmp_seq=2 ttl=64 time=0.052 ms
^C
--- 192.168.250.2 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1000ms
rtt min/avg/max/mdev = 0.011/0.031/0.052/0.021 ms
x86_64:/ # ping 192.168.250.1                                                                                                                                
connect: Network is unreachable
2|x86_64:/ # ip route add default dev eth0 via 192.168.250.1
RTNETLINK answers: Network is unreachable
```

**What were you expecting?:**
Network connectivity

**Additional info:**
I have IPv6 disabled on host with "ipv6.disable=1"  kernel command line option. However, that should't affect IPv4 connectivity on anbox.
If solution is hard to implement, please, provide a workaround.
