### ISSUE TITLE
Swiftshader directory is not present in anbox 207 snap after upgrade from beta

### ISSUE THREAD

**Issue by FoamScience** [anbox/anbox#1732]
Hi, first of all,  thanks for maintaining this awesome project.

So I tried to `snap refresh --devmode --edge anbox` from the beta channel.

I noticed that `/snap/186/lib/anbox/swiftshader` (from beta channel) exists and has the correct libraries
but it's not there for the edge snap.

```
ls /snap/anbox/207/lib
   apparmor  systemd  x86_64-linux-gnu
```

Of course, trying to enable software rendering results in "Swiftshader directory not found".

To fix this, first, I thought I had to compile swiftshader on my own, so I did that but there is actually no way to tell anbox
where to find the new libs.

I don't understand the logic in [Driver selection](https://github.com/anbox/anbox/blob/25e288436c937e7f4da56eac50167a549ac79294/src/anbox/graphics/gl_renderer_server.cpp#L80):

It's true that SWIFTSHADER_PATH is read
```
auto swiftshader_path = fs::path(utils::get_env_value("SWIFTSHADER_PATH"));
```
But then, it will get overwritten if SNAP is not empty (can we really get SNAP to become empty??):
```
if (!snap_path.empty())
      swiftshader_path = fs::path(snap_path) / "lib" / "anbox" / "swiftshader";
```

And that directory is not present when I upgraded from beta to edge!

Of course, If there is a way to symlink `$SNAP/lib/anbox/swiftshader` to my SwiftShader directory, this problem will be solved.

<details>
<summary>anbox system-info output</summary>

```
version: local-165db5c
snap-revision: 207
cpu:
  arch:  x86
  brand:        Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
os:
  name: Ubuntu
  version: 18.04.5 LTS (Bionic Beaver)
  snap-based: true
kernel:
  version: Linux version 4.15.0-130-generic (buildd@lcy01-amd64-018) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #134-Ubuntu SMP Tue Jan 5 20:46:26 UTC 2021
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_NOK_swap_region
      - EGL_NOK_texture_from_pixmap
      - EGL_NV_post_sub_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 3.0 Mesa 20.2.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_rgtc
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_texture_3D
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float
      - GL_EXT_draw_instanced
      - GL_EXT_texture_sRGB_decode
      - GL_OES_EGL_image
      - GL_OES_depth_texture
      - GL_OES_packed_depth_stencil
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_NV_conditional_render
      - GL_OES_get_program_binary
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_EXT_frag_depth
      - GL_NV_fbo_color_attachments
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_robustness
      - GL_EXT_texture_rg
      - GL_EXT_unpack_subimage
      - GL_NV_draw_buffers
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_EXT_draw_buffers
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_KHR_robustness
      - GL_NV_pixel_buffer_object
      - GL_OES_depth_texture_cube_map
      - GL_OES_required_internalformat
      - GL_OES_surfaceless_context
      - GL_EXT_color_buffer_float
      - GL_EXT_sRGB_write_control
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_group_vote
      - GL_EXT_shader_integer_mix
      - GL_INTEL_performance_query
      - GL_EXT_base_instance
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_texture_border_clamp
      - GL_KHR_blend_equation_advanced
      - GL_KHR_context_flush_control
      - GL_OES_copy_image
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_multisample_interpolation
      - GL_OES_texture_border_clamp
      - GL_EXT_blend_func_extended
      - GL_EXT_float_blend
      - GL_KHR_no_error
      - GL_OES_EGL_image_external_essl3
      - GL_EXT_clip_cull_distance
      - GL_EXT_disjoint_timer_query
      - GL_EXT_texture_compression_s3tc_srgb
      - GL_MESA_shader_integer_functions
      - GL_EXT_clip_control
      - GL_EXT_texture_compression_bptc
      - GL_KHR_parallel_shader_compile
      - GL_EXT_EGL_image_storage
      - GL_EXT_shader_framebuffer_fetch_non_coherent
      - GL_EXT_texture_sRGB_R8
      - GL_EXT_texture_shadow_lod
      - GL_INTEL_blackhole_render
      - GL_MESA_framebuffer_flip_y
      - GL_EXT_demote_to_helper_invocation
      - GL_EXT_depth_clamp
      - GL_EXT_texture_query_lod
```
</details>
