### ISSUE TITLE
[Renderer.cpp:102@initialize] Failed to Initialize backend EGL display (again)

### ISSUE THREAD

**Issue by OverShifted** [anbox/anbox#1774]
<details>
<summary>anbox system-info output</summary>

```
version: 4
snap-revision: 186
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 20.04.2 LTS (Focal Fossa)
  snap-based: true
kernel:
  version: Linux version 5.4.0-67-generic (buildd@lcy01-amd64-025) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #75-Ubuntu SMP Fri Feb 19 18:03:38 UTC 2021
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
```
</details>

Hi. I am new to Anbox and this is my laptop computer information:
os: Kubuntu 20.04.2 LTS
kernel version: 5.4.0
GPUs: 
1. Intel UHD Graphics 620
2. NVIDIA Geforce GTX 1050 with `nvidia-driver-460 (proprietary)` driver

When I run `anbox session-manager`; I get the folowing error:
```
[ 2021-03-24 15:21:03] [Renderer.cpp:102@initialize] Failed to Initialize backend EGL display
[ 2021-03-24 15:21:03] [service.cpp:41@Service] Successfully acquired DBus service name
Stack trace (most recent call last) in thread 85532:
#7    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#6    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f81d9f8c4dc, in clone
#5    Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7f81dba3e6b9, in 
#4    Object "/snap/anbox/186/usr/bin/anbox", at 0x5834b0, in emugl::Thread::thread_main(void*)
#3    Object "/snap/anbox/186/usr/bin/anbox", at 0x4a7e0c, in RenderThread::main()
#2    Object "/snap/anbox/186/usr/bin/anbox", at 0x57fdca, in renderControl_decoder_context_t::decode(void*, unsigned long, IOStream*)
#1    Object "/snap/anbox/186/usr/bin/anbox", at 0x504ebe, in 
#0    Object "/snap/anbox/186/usr/bin/anbox", at 0x507b75, in RendererConfigList::getPackInfo(int*, int*) const
Segmentation fault (Address not mapped to object [(nil)])
[1]    85341 segmentation fault (core dumped)  anbox session-manager
```

When I searched that; I found a few old issues and people reported it was fixed by switching to Intel GPU.
I was using the ‍`on-demand` profile for `prime` which should work fine but I was getting that error.
Then I tried to use `intel` profile and logged out. after logging in; I got the same result.

Here is output of a few command that might help:
```
$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) UHD Graphics 620 (KBL GT2) (0x5917)
    Version: 21.1.0
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.1.0-devel (git-5762aa4 2021-03-22 focal-oibaf-ppa)
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.1.0-devel (git-5762aa4 2021-03-22 focal-oibaf-ppa)
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.1.0-devel (git-5762aa4 2021-03-22 focal-oibaf-ppa)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

```
$ prime-select query
intel
```

```
$ uname -a 
Linux sepehr-book 5.4.0-67-generic #75-Ubuntu SMP Fri Feb 19 18:03:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

[anbox-system-diagnostics-2021-03-24.zip](https://github.com/anbox/anbox/files/6198408/anbox-system-diagnostics-2021-03-24.zip)
