### ISSUE TITLE
Anbox Couldn't work on lxc 4.0.8

### ISSUE THREAD

**Issue by STASWIT** [anbox/anbox#1801]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
version: local-9de4e87
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Arch Linux
  version: 
  snap-based: false
kernel:
  version: Linux version 5.12.0-xanmod1-2 (makepkg@archlinux) (gcc (GCC) 10.2.0, GNU ld (GNU Binutils) 2.36.1) #1 SMP PREEMPT Fri, 30 Apr 2021 11:40:51 +0000
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions:
      - n/a
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
```
</details>

**Please describe your problem:**
When I using latest anbox from ArchLinux(AUR), I followed ArchWiki's guidance, however, I have got this problem
when using `$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity`:

```
[ 2021-05-01 13:58:55] [daemon.cpp:61@Run] [org.freedesktop.DBus.Error.ServiceUnknown] The name org.anbox was not provided by any .service files
```

Then I pressed `$ anbox session-manager`, it outputed:

```
[ 2021-05-01 13:59:33] [Renderer.cpp:104@initialize] Failed to initialize EGL
[ 2021-05-01 13:59:33] [client.cpp:48@start] Failed to start container: Failed to start container: Failed to set config item lxc.group.devices.deny
[ 2021-05-01 13:59:33] [session_manager.cpp:164@operator()] Lost connection to container manager, terminating.
[ 2021-05-01 13:59:33] [daemon.cpp:61@Run] Container is not running
Stack trace (most recent call last) in thread 23046:
```

**What were you expecting?:**
I hope someone could fix it.

**Additional info:**
I'm Using `lxc-1:4.0.8-1` maybe the latest anbox haven't support it.
