### ISSUE TITLE
Anbox runs if manually invoked, does not run via systemd unit

### ISSUE THREAD

**Issue by keithzg** [anbox/anbox#184]
**Anbox release (`anbox version`): **
anbox 0.1.0

**and system info (`anbox system-info`):**
```
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.4.0-72-generic (buildd@lcy01-17) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_cl_event2
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_swap_region
      - EGL_NOK_texture_from_pixmap
      - EGL_NV_post_sub_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: X.Org
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
```

**Description of the problem:**
If invoked via a systemd user unit, `anbox session-manager` does not successfully run. It does run if invoked manually.

**Expected:**
The session manager should start the same via the systemd unit as it does when manually invoked.

**Additional info:**
Desktop environment: KDE (plasma-desktop version 4:5.8.5-0ubuntu1~ubuntu16.04~ppa1 from Kubuntu Backports PPA)
DISTRIB_DESCRIPTION: "Ubuntu 16.04.2 LTS"
Video hardware: Radeon HD 7450
Video driver: radeon

When I first installed anbox I encountered this, and commented on the seemingly-relevant issue #4. That has since been closed as a duplicate of #11. However, as I do not have any NVIDIA hardware or software involved here, my issue then is presumably different.

My systemd unit file is as follows:

```
[Unit]
Description=Anbox session manager
[Service]
Environment=ANBOX_LOG_LEVEL=debug 
ExecStart=/snap/bin/anbox session-manager
[Install]
WantedBy=default.target
```
As you can see I've edited it to try and add the log level environment setting to make the output more verbose, but otherwise it's the default provided systemd unit. Unfortunately it doesn't really end up very verbose in `journalctl --user-unit anbox`:

```
Apr 25 14:45:57 siddhartha systemd[6272]: Started Anbox session manager.
Apr 25 14:45:57 siddhartha /snap/bin/anbox[5301]: cmd.go:114: DEBUG: not restarting into "/snap/core/current/usr/bin/snap" ([VERSION=2.23.6 2.23.6]): older than "/usr/bin/snap" (2.24.1)
Apr 25 14:45:57 siddhartha systemd[6272]: anbox.service: Main process exited, code=exited, status=1/FAILURE
Apr 25 14:45:57 siddhartha systemd[6272]: anbox.service: Unit entered failed state.
Apr 25 14:45:57 siddhartha systemd[6272]: anbox.service: Failed with result 'exit-code'.
```
(This is identical to the output without the Environment line.)

Interestingly enough, while the other week I was noticing the following error:

```
Apr 17 14:25:08 siddhartha anbox[6824]: [EE 2017-04-17 20:25:08] [daemon.cpp:58@Run] Failed to initialize SDL: Failed to connect to the Mir Server
```

this no longer appears in my journalctl logs when trying things again today.

As aforementioned, things run fine if invoked manually from a terminal session:

```
keithzg@siddhartha:~$ ANBOX_LOG_LEVEL=debug  /snap/bin/anbox session-manager
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[DD 2017-04-25 20:52:51] [gl_renderer_server.cpp:82@GLRendererServer] Using GLES-to-GL translator for rendering
[DD 2017-04-25 20:52:51] [Renderer.cpp:113@initialize] EGL doesn't support surfaceless context
[DD 2017-04-25 20:52:51] [Renderer.cpp:249@initialize] Successfully initialized EGL
[DD 2017-04-25 20:52:58] [session_manager.cpp:208@operator()] Android successfully booted
```
