### ISSUE TITLE
binder not found (with v5.0+ kernels) - need to create device mount manually

### ISSUE THREAD

**Issue by iam-TJ** [anbox/anbox#1866]
<details>
<summary>anbox system-info output</summary>

```
version: local-ad377ff
snap-revision: 213
cpu:
  arch:  x86
  brand: AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx  
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 20.04.2 LTS (Focal Fossa)
  snap-based: true
kernel:
  version: Linux version 5.13.0-soggy-02735-g1da44a338f5b (tj@elloe000) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu
) 2.34) #43 SMP PREEMPT Mon Jul 12 15:46:13 BST 2021
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_EXT_buffer_age
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
```
</details>

Using the latest v5.13 kernel build which always makes binder a built-in, and ashmem as a loadable module, anbox fails to find the binder interface. I followed Christian Brauner's instructions for `binderfs` from [Android Binderfs](https://brauner.github.io/2019/01/09/android-binderfs.html)
```
$ sudo mount -t binder binder /dev/binderfs
 ls -l /dev/ashmem; grep binder /proc/filesystems; mount | grep binder; ls -latr /dev/binderfs/
crw------- 1 root root 10, 123 Jul 13 08:44 /dev/ashmem
nodev   binder
binder on /dev/binderfs type binder (rw,relatime,max=1048576)
total 0
drwxr-xr-x 25 root root   5360 Jul 13 08:31 ..
crw-------  1 root root 242, 7 Jul 13 08:31 vndbinder
crw-------  1 root root 242, 6 Jul 13 08:31 hwbinder
crw-------  1 root root 242, 4 Jul 13 08:31 binder-control
crw-------  1 root root 242, 5 Jul 13 08:31 binder
drwxr-xr-x  2 root root      0 Jul 13 08:31 .

```
When following Christian's guide we need to make an additional device node to keep `anbox` happy since it only expects to find the binder interface at `/dev/binder/`:
```
sudo ln -s /dev/binderfs /dev/binder
```
After which we see:
```
kernel:
  version: Linux version 5.13.0-soggy-02735-g1da44a338f5b (tj@elloe000) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #43 SMP PREEMPT Mon Jul 12 15:46:13 BST 2021
  binder: true
  ashmem: true
```
