### ISSUE TITLE
Runing Clubhouse on Anbox gives in-app error on login

### ISSUE THREAD

**Issue by RYNEQ** [anbox/anbox#1885]
<details>
<summary>anbox system-info output</summary>

```
version: local-ad377ff
snap-revision: 213
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz
  features: 
    - aes
os:
  name: Ubuntu
  version: 18.04.5 LTS (Bionic Beaver)
  snap-based: true
kernel:
  version: Linux version 4.15.0-153-generic (buildd@lgw01-amd64-004) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #160-Ubuntu SMP Thu Jul 29 06:54:29 UTC 2021
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_EXT_buffer_age
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
```
</details>

I'm trying to run [Clubhouse](https://play.google.com/store/apps/details?id=com.clubhouse.app) app on Anbox, It takes phone umber and sends login SMS but when I enter the code it gives an in-app error "There was an error, Please try again"  

The app works perfectly on both android phone and android x86 in VM but in Anbox I cannot login  
is there any known problems with this app?  
Is there any way to find out what is the actual detailed error?
