### ISSUE TITLE
The name org.anbox was not provided by any .service files

### ISSUE THREAD

**Issue by Kushagra-Srivastava** [anbox/anbox#1889]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `
[anbox-system-diagnostics-2021-08-21.zip](https://github.com/anbox/anbox/files/7024915/anbox-system-diagnostics-2021-08-21.zip)

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
version: local-ad377ff
snap-revision: 213
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 20.04.3 LTS (Focal Fossa)
  snap-based: true
kernel:
  version: Linux version 5.11.0-27-generic (buildd@lcy01-amd64-019) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

```
</details>

**Please describe your problem:**
When i am trying to run `anbox.appmgr`
It is giving this error-

`[ 2021-08-21 05:16:53] [daemon.cpp:61@Run] [org.freedesktop.DBus.Error.ServiceUnknown] The name org.anbox was not provided by any .service files`

**What were you expecting?:**
Was expecting a cool anbox window

**Additional info:**
It was working fine for 3 to 4 days but now this problem or bug or issue or error or whatever popped.
I had installed it with the command ` sudo snap install --devmode --edge anbox`
I am on Ubuntu 20.04 LTS 
For `snap info anbox`
It is giving this info--

```
name:      anbox
summary:   Android in a Box
publisher: Simon Fels (morphis)
store-url: https://snapcraft.io/anbox
contact:   https://anbox.io
license:   unset
description: |
  Runtime for Android applications which runs a full Android system
  in a container using Linux namespaces (user, ipc, net, mount) to
  separate the Android system fully from the host.
  
  You can find further details in our documentation at
  https://github.com/anbox/anbox/blob/master/README.md
commands:
  - anbox
  - anbox.android-settings
  - anbox.appmgr
  - anbox.collect-bug-info
  - anbox.shell
services:
  anbox.container-manager: simple, enabled, active
snap-id:      Nr9K6UJaIOD8wHpDEQl16nabFFt9LLEQ
tracking:     latest/edge
refresh-date: today at 10:39 IST
channels:
  latest/stable:    --                                   
  latest/candidate: --                                   
  latest/beta:      4-56c25f1     2020-01-02 (186) 391MB devmode
  latest/edge:      4+gitrad377ff 2021-05-27 (213) 405MB devmode
installed:          4+gitrad377ff            (213) 405MB devmode


```
`anbox session-manager` output

```
[ 2021-08-24 10:35:08] [Renderer.cpp:128@initialize] Failed to select EGL configuration
Stack trace (most recent call last) in thread 14628:
#7    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#6    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fb15af73292, in clone
#5    Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7fb15b2e4608, in 
#4    Object "/snap/anbox/213/usr/bin/anbox", at 0x55775608f314, in emugl::Thread::thread_main(void*)
#3    Object "/snap/anbox/213/usr/bin/anbox", at 0x557755f9b358, in RenderThread::main()
#2    Object "/snap/anbox/213/usr/bin/anbox", at 0x55775608a060, in renderControl_decoder_context_t::decode(void*, unsigned long, IOStream*)
#1    Object "/snap/anbox/213/usr/bin/anbox", at 0x557756009562, in 
#0    Object "/snap/anbox/213/usr/bin/anbox", at 0x55775600c429, in RendererConfigList::getPackInfo(int*, int*) const
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault (core dumped)

```
