### ISSUE TITLE
[Renderer.cpp:128@initialize] Failed to select EGL configuration

### ISSUE THREAD

**Issue by Phoxett** [anbox/anbox#1901]
**anbox system-info output:**

```
version: local-ad377ff
snap-revision: 213
cpu:
  arch:  x86
  brand:       Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz
  features: 
    - aes
os:
  name: GalliumOS
  version: 3.1 (Bismuth)
  snap-based: true
kernel:
  version: Linux version 4.16.18-galliumos (reynhout@galliumos) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #1 SMP PREEMPT Sun Jun 23 04:14:45 UTC 2019
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_EXT_buffer_age
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
```

I install:

```bash
sudo apt-get install libglfw3-dev libgles2-mesa-dev
```

Thing is that the problem.
[followed run-android-apps-games-linux](https://www.makeuseof.com/tag/run-android-apps-games-linux/)
[and how-to-run-android-apps-apk-files-in-ubuntu](https://hackthestuff.com/article/how-to-run-android-apps-apk-files-in-ubuntu)

At first I had problems with:

```
modprobe: FATAL: Module ashmem_linux not found in directory /lib/modules/<version>-galliumos
```

I sorted that out, now my problem is running:

```bash
anbox session-manager
```

outputs:
```
[ 2021-09-05 13:30:34] [Renderer.cpp:128@initialize] Failed to select EGL configuration
Stack trace (most recent call last) in thread 18649:
#7    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#6    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f2b38749292, in clone
#5    Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7f2b38aba608, in 
#4    Object "/snap/anbox/213/usr/bin/anbox", at 0x5562e37e5314, in emugl::Thread::thread_main(void*)
#3    Object "/snap/anbox/213/usr/bin/anbox", at 0x5562e36f1358, in RenderThread::main()
#2    Object "/snap/anbox/213/usr/bin/anbox", at 0x5562e37e0060, in renderControl_decoder_context_t::decode(void*, unsigned long, IOStream*)
#1    Object "/snap/anbox/213/usr/bin/anbox", at 0x5562e375f562, in 
#0    Object "/snap/anbox/213/usr/bin/anbox", at 0x5562e3762429, in RendererConfigList::getPackInfo(int*, int*) const
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault (core dumped)
[anbox-system-diagnostics-2021-09-05.zip](https://github.com/anbox/anbox/files/7111680/anbox-system-diagnostics-2021-09-05.zip)

```

```bash
anbox session-manager # not starting up, what seems to be the problem?
```
