### ISSUE TITLE
App wraps its text based on screen resolution not window size - any hack or fix?

### ISSUE THREAD

**Issue by mcarans** [anbox/anbox#1908]
<details>
<summary>anbox system-info output</summary>

```
version: local-ad377ff
snap-revision: 213
cpu:
  arch:  x86
  brand: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Linux Mint
  version: 20.2 (Uma)
  snap-based: true
kernel:
  version: Linux version 5.11.0-34-generic (buildd@lgw01-amd64-001) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
```
</details>

**Please describe your problem:**
I'm running an app ([MirrorWord Bible](https://apkpure.com/mirror-bible/com.mirrorword.mirrorbible)) that seems to wrap its text based on the resolution of my monitor not the size of the window in which it is running hence sentences are cut off at the edge of the window. Note that this happens once you go to read the Bible in the app. On the app's home screen, the text wraps but is huge.

I tried the following:
`adb shell am start --launch-bounds 0 0 800 1400 -n com.mirrorword.mirrorbible/com.mirrorword.mirrorbible.MainActivity`

Although the window was sized, the problem with the text being cut off at the edge of the window remained.

Is there any hack or fix to report to the app a different screen resolution?

**What were you expecting?:**
Text wraps according to window size
