### ISSUE TITLE
trying to make the android.img ext4

### ISSUE THREAD

**Issue by lnee94** [anbox/anbox#1909]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
version: local-ad377ff
snap-revision: 213
cpu:
  arch:  x86
  brand: Intel(R) Celeron(R) G4900 CPU @ 3.10GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
os:
  name: Ubuntu
  version: 21.04 (Hirsute Hippo)
  snap-based: true
kernel:
  version: Linux version 5.11.0-34-generic (buildd@lgw01-amd64-059) (gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0, GNU ld (GNU Binutils for Ubuntu) 2.36.1) #36-Ubuntu SMP Thu Aug 26 19:22:09 UTC 2021
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

```
</details>

**Please describe your problem:**
ok so i wont to get anbox in rw to root it heres what i tried

note i allretey made the .snap file you can download it here https://mega.nz/file/EF1xHSSL#Nf8LqCTmxM4PbLDDL_hMCh_dFK7rMl6y40tmC8Ce3c4
heres how to make the snap file

mkdir snapbuild
cd snapbuild
cp /snap/anbox/current/android.img .
dd if=/dev/zero of=fs.img bs=1k count=1572864
mkfs.ext4 fs.img
loop="/dev/loop$(($(ls -1 /dev | grep loop | grep -Eo "[0-9]\*" | sort -n | tail -1)+1))"
sudo losetup "$loop" fs.img
mkdir mount
sudo mount "$loop" "$PWD/mount"
sudo rm -r ./mount/*  
cd mount
sudo unsquashfs ../android.img
sudo mv ./squashfs-root/* .
sudo rm squashfs-root/ -r
sudo chown 0:0 .
cd ..
sudo umount mount
rm android.img mount -r
sudo cp "/var/lib/snapd/snaps/$(ls -1 /var/lib/snapd/snaps/ | grep anbox_ | tail -1)" .
sudo unsquashfs anbox_213.snap
sudo cp fs.img ./squashfs-root/android.img
sudo rm anbox_*.snap
sudo mksquashfs squashfs-root "$(ls -1 /var/lib/snapd/snaps/ | grep anbox_ | tail -1)"  -b 131072 -comp xz -Xbcj x86

ok now you have a snap file time to install
note you probly wont to make a backup of your snap file
sudo cp "/var/lib/snapd/snaps/$(ls -1 /var/lib/snapd/snaps/ | grep anbox_ | tail -1)" ./anbox_backup.snap

i=/path/to/your/snap/file/that/you/downloaded/or/build

sudo systemctl stop snap.anbox.container-manager.service
sudo systemctl stop "snap-anbox-$(basename "$i" | grep -Eo "[0-9]*").mount"
sudo cp "$i" /var/lib/snapd/snaps/
sudo chown 0:0 "/var/lib/snapd/snaps/$(basename "$i")"
sudo chmod 600 "/var/lib/snapd/snaps/$(basename "$i")"
sudo systemctl start "snap-anbox-$(basename "$i" | grep -Eo "[0-9]*").mount"
sudo systemctl start snap.anbox.container-manager.service

now run using this "env EGL_PLATFORM=x11 /snap/bin/anbox.appmgr" anbox it gives me this error "[ 2021-09-19 13:13:47] [daemon.cpp:61@Run] [org.freedesktop.DBus.Error.ServiceUnknown] The name org.anbox was not provided by any .service files"

first can i do this if  i can how do i make the anbox file system read wite

**What were you expecting?:**

**Additional info:**
