### ISSUE TITLE
Anbox keeps crashing reseting my network

### ISSUE THREAD

**Issue by nitanmarcel** [anbox/anbox#1915]
<details>
<summary>anbox system-info output</summary>

```
b
version: local-/bin/sh: 1: git: not found
cpu:
  arch:  
  brand: 
  features: 
os:
  name: Ubuntu
  version: 16.04.7 LTS (Xenial Xerus)
  snap-based: false
kernel:
  version: Linux version 4.14.117-perf+ (root@runner-0277ea0f-project-29511331-concurrent-0) (Android (5484270 based on r353983c) clang version 9.0.3 (https://android.googlesource.com/toolchain/clang 745b335211bb9eadfa6aa6301f84715cee4b37c5) (https://android.googlesource.com/toolchain/llvm 60cf23e54e46c807513f7a36d0a7b777920b5881) (based on LLVM 9.0.3svn)) #1 SMP PREEMPT Fri Sep 24 00:46:18 UTC 2021
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Android
    version: 1.5 Android META-EGL
    extensions:
      - EGL_KHR_get_all_proc_addresses
      - EGL_ANDROID_presentation_time
      - EGL_KHR_swap_buffers_with_damage
      - EGL_ANDROID_get_native_client_buffer
      - EGL_ANDROID_front_buffer_auto_refresh
      - EGL_ANDROID_get_frame_timestamps
      - EGL_EXT_surface_SMPTE2086_metadata
      - EGL_EXT_surface_CTA861_3_metadata
      - EGL_EXT_gl_colorspace_scrgb
      - EGL_EXT_gl_colorspace_scrgb_linear
      - EGL_EXT_gl_colorspace_display_p3_linear
      - EGL_EXT_gl_colorspace_display_p3
      - EGL_EXT_gl_colorspace_display_p3_passthrough
      - EGL_EXT_gl_colorspace_bt2020_linear
      - EGL_EXT_gl_colorspace_bt2020_pq
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_EXT_image_gl_colorspace
      - EGL_KHR_lock_surface
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_reusable_sync
      - EGL_KHR_fence_sync
      - EGL_KHR_create_context
      - EGL_KHR_surfaceless_context
      - EGL_EXT_create_context_robustness
      - EGL_ANDROID_image_native_buffer
      - EGL_KHR_wait_sync
      - EGL_ANDROID_recordable
      - EGL_KHR_partial_update
      - EGL_EXT_pixel_format_float
      - EGL_KHR_create_context_no_error
      - EGL_KHR_mutable_render_buffer
      - EGL_EXT_yuv_surface
      - EGL_EXT_protected_content
      - EGL_IMG_context_priority
      - EGL_KHR_no_config_context
      - EGL_HYBRIS_native_buffer2
      - EGL_HYBRIS_WL_acquire_native_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Qualcomm
    vendor: OpenGL ES 3.2 V@415.0 (GIT@57da73e, I82b4603a7a, 1607012310) (Date:12/03/20)
    extensions:
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_half_float
      - GL_OES_framebuffer_object
      - GL_OES_rgb8_rgba8
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_AMD_compressed_ATC_texture
      - GL_KHR_texture_compression_astc_ldr
      - GL_KHR_texture_compression_astc_hdr
      - GL_OES_texture_compression_astc
      - GL_OES_texture_npot
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_read_format_bgra
      - GL_OES_texture_3D
      - GL_EXT_color_buffer_float
      - GL_EXT_color_buffer_half_float
      - GL_QCOM_alpha_test
      - GL_OES_depth24
      - GL_OES_packed_depth_stencil
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_EXT_sRGB
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_format_sRGB_override
      - GL_OES_element_index_uint
      - GL_EXT_copy_image
      - GL_EXT_geometry_shader
      - GL_EXT_tessellation_shader
      - GL_OES_texture_stencil8
      - GL_EXT_shader_io_blocks
      - GL_OES_shader_image_atomic
      - GL_OES_sample_variables
      - GL_EXT_texture_border_clamp
      - GL_EXT_EGL_image_external_wrap_modes
      - GL_EXT_multisampled_render_to_texture
      - GL_EXT_multisampled_render_to_texture2
      - GL_OES_shader_multisample_interpolation
      - GL_EXT_texture_cube_map_array
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_gpu_shader5
      - GL_EXT_robustness
      - GL_EXT_texture_buffer
      - GL_EXT_shader_framebuffer_fetch
      - GL_ARM_shader_framebuffer_fetch_depth_stencil
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_sample_shading
      - GL_OES_get_program_binary
      - GL_EXT_debug_label
      - GL_KHR_blend_equation_advanced
      - GL_KHR_blend_equation_advanced_coherent
      - GL_QCOM_tiled_rendering
      - GL_ANDROID_extension_pack_es31a
      - GL_EXT_primitive_bounding_box
      - GL_OES_standard_derivatives
      - GL_OES_vertex_array_object
      - GL_EXT_disjoint_timer_query
      - GL_KHR_debug
      - GL_EXT_YUV_target
      - GL_EXT_sRGB_write_control
      - GL_EXT_texture_norm16
      - GL_EXT_discard_framebuffer
      - GL_OES_surfaceless_context
      - GL_OVR_multiview
      - GL_OVR_multiview2
      - GL_EXT_texture_sRGB_R8
      - GL_KHR_no_error
      - GL_EXT_debug_marker
      - GL_OES_EGL_image_external_essl3
      - GL_OVR_multiview_multisampled_render_to_texture
      - GL_EXT_buffer_storage
      - GL_EXT_external_buffer
      - GL_EXT_blit_framebuffer_params
      - GL_EXT_clip_cull_distance
      - GL_EXT_protected_textures
      - GL_EXT_shader_non_constant_global_initializers
      - GL_QCOM_texture_foveated
      - GL_QCOM_texture_foveated_subsampled_layout
      - GL_QCOM_shader_framebuffer_fetch_noncoherent
      - GL_QCOM_shader_framebuffer_fetch_rate
      - GL_EXT_memory_object
      - GL_EXT_memory_object_fd
      - GL_EXT_EGL_image_array
      - GL_NV_shader_noperspective_interpolation
      - GL_KHR_robust_buffer_access_behavior
      - GL_EXT_EGL_image_storage
      - GL_EXT_blend_func_extended
      - GL_EXT_clip_control
      - GL_OES_texture_view
      - GL_EXT_fragment_invocation_density
      - GL_QCOM_validate_shader_binary
      - GL_QCOM_YUV_texture_gather
```
</details>

**Please describe your problem:**

I'm porting Ubuntu Touch based on Halium 10 on my device and upon releasing a test version of it I got a lot of questions if WhatsApp is available as they use it a lot for school/work. I'm currently trying to make anbox as waydroid is unstable on Halium 10, but I've been hitting a dead end with anbox crashing after being enabled. That's not the full problem since this is also causing my network outside anbox to keep resetting.

**What were you expecting?:**
I was expecting it to run succesfully or at last to not break my network.

**Additional info:**
I keep getting this in dmesg:

```
[ 4995.485533] init: anbox-container main process (1753) terminated with status 1
[ 4995.485590] init: anbox-container main process ended, respawning
[ 4995.529778] IPv6: ADDRCONF(NETDEV_UP): anbox0: link is not ready

```
