### ISSUE TITLE
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found

### ISSUE THREAD

**Issue by IngwiePhoenix** [anbox/anbox#1939]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
  - Did, all are outdated.
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
  - Did, issue persists.
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
  - [anbox-system-diagnostics-2021-11-06.zip](https://github.com/anbox/anbox/files/7491140/anbox-system-diagnostics-2021-11-06.zip)

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
snap-revision: 213
cpu:
  arch:  x86
  brand: AMD Ryzen 9 3900X 12-Core Processor            
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 21.10 (Impish Indri)
  snap-based: true
kernel:
  version: Linux version 5.13.0-20-generic (buildd@lgw01-amd64-013) (gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0, GNU ld (GNU Binutils for Ubuntu) 2.37) #20-Ubuntu SMP Fri Oct 15 14:21:35 UTC 2021
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: n/a ## Should be NVIDIA
    version: n/a
    extensions: []
  gles2:
    vendor: n/a ## Should be NVIDIA
    vendor: n/a
    extensions: []
```
</details>

**Please describe your problem:**
I am on Ubuntu 21.10 and wanted to run Anbox after my try-out with Waydroid failed. I reverted back to my X11 session due to ongoing GBM issues with the NVIDIA drivers, but I have not removed `nvidia-drm.modeset=1` from my kernel arguments yet. 

However, although `binder: false` is stated above, I do have:
```
find /dev -name "binder*"
/dev/binder-control
/dev/binderfs
/dev/binderfs/binder-control
```

Trying to directly launch the App Manager results in the "Starting" screen to stick around for a good minute with a message saying that the application manager hasn't started yet showing up after the application quits. After trying to find logs of it and browsing Github, I found out that people were running `anbox session-manager` in a separate terminal window prior to starting an application. Well, I tried that, and found this:

```
~$ anbox session-manager
Failed to open libEGL.so.1: [/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /var/lib/snapd/lib/gl/libEGL.so.1)]
[ 2021-11-06 19:56:48] [daemon.cpp:61@Run] Failed to initialize OpenGL renderer
```

Odd, isn't it? I looked at my libc version and sure enough, it's actually a whole version *newer*:
```
~$ dpkg -l | grep -i "gnu c library"
ii  libc-bin                                      2.34-0ubuntu3                              amd64        GNU C Library: Binaries
ii  libc-dev-bin                                  2.34-0ubuntu3                              amd64        GNU C Library: Development binaries
ii  libc6:amd64                                   2.34-0ubuntu3                              amd64        GNU C Library: Shared libraries
ii  libc6:i386                                    2.34-0ubuntu3                              i386         GNU C Library: Shared libraries
ii  libc6-dbg:amd64                               2.34-0ubuntu3                              amd64        GNU C Library: detached debugging symbols
ii  libc6-dev:amd64                               2.34-0ubuntu3                              amd64        GNU C Library: Development Libraries and Header Files
ii  libc6-i386                                    2.34-0ubuntu3                              amd64        GNU C Library: 32-bit shared libraries for AMD64
```

I am not well experienced with snap just yet, so I had no idea how I could force it to use a different library version - because maybe there is an "internal" dependency that is causing issues? It shouldn't, but who knows.

**What were you expecting?:**
I was expecting to see the application manager so I could play around with it.

**Additional info:**
None - wish I had any... I am just straight up lost and confused, really. ^^;
