### ISSUE TITLE
Several anbox issues

### ISSUE THREAD

**Issue by mischa1807** [anbox/anbox#1943]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
ersion: local-ad377ff
snap-revision: 213
cpu:
  arch:  x86
  brand:       Intel(R) Atom(TM) x7-Z8700  CPU @ 1.60GHz
  features: 
    - aes
os:
  name: Linux Mint
  version: 20.2 (Uma)
  snap-based: true
kernel:
  version: Linux version 5.4.0-90-generic (buildd@lgw01-amd64-054) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

```
</details>

When Starting anbox.appmgr I'm receiving the error message: 

[ 2021-11-18 13:40:21] [daemon.cpp:61@Run] [org.freedesktop.DBus.Error.NoReply] Message recipient disconnected from message bus without replying

When starting anbox session-manager I'm receiving the error message:

[ 2021-11-18 13:41:11] [Renderer.cpp:128@initialize] Failed to select EGL configuration
Stack trace (most recent call last) in thread 10043:
#7    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#6    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fcc0df11292, in clone
#5    Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7fcc0e282608, in 
#4    Object "/snap/anbox/213/usr/bin/anbox", at 0x55ca5de4c314, in emugl::Thread::thread_main(void*)
#3    Object "/snap/anbox/213/usr/bin/anbox", at 0x55ca5dd58358, in RenderThread::main()
#2    Object "/snap/anbox/213/usr/bin/anbox", at 0x55ca5de47060, in renderControl_decoder_context_t::decode(void*, unsigned long, IOStream*)
#1    Object "/snap/anbox/213/usr/bin/anbox", at 0x55ca5ddc6562, in 
#0    Object "/snap/anbox/213/usr/bin/anbox", at 0x55ca5ddc9429, in RendererConfigList::getPackInfo(int*, int*) const
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault (core dumped)

**What were you expecting?:**
anbox to work

**Additional info:**
[anbox-system-diagnostics-2021-11-18.zip](https://github.com/anbox/anbox/files/7563204/anbox-system-diagnostics-2021-11-18.zip)
