### ISSUE TITLE
modprobe: ERROR: could not insert 'ashmem_linux': Operation not permitted

### ISSUE THREAD

**Issue by hjkvgg59-dev** [anbox/anbox#1959]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `
[anbox-system-diagnostics-2021-12-05.zip](https://github.com/anbox/anbox/files/7656783/anbox-system-diagnostics-2021-12-05.zip)

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
[please paste printout of `anbox system-info` here]
amdgpu_device_initialize: amdgpu_query_info(ACCEL_WORKING) failed (-13)
amdgpu: amdgpu_device_initialize failed.
version: local-ad377ff
snap-revision: 213
cpu:
  arch:  x86
  brand: AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx  
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Zorin OS
  version: 16
  snap-based: true
kernel:
  version: Linux version 5.11.0-41-generic (buildd@lgw01-amd64-005) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #45~20.04.1-Ubuntu SMP Wed Nov 10 10:20:10 UTC 2021
  binder: false
  ashmem: false
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_EXT_buffer_age
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

```
</details>

**Please describe your problem:**
I have a problem when starting ashmem_linux with command:
sudo modprobe ashmem_linux

**What were you expecting?:**
To run without errors

**Additional info:**
I have an error of:
modprobe: ERROR: could not insert 'ashmem_linux': Operation not permitted
although I used sudo 
Thank You
