### ISSUE TITLE
anbox session-manager Segmentation fault centos 7

### ISSUE THREAD

**Issue by gitWK86** [anbox/anbox#2017]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
version: 4
snap-revision: 186
cpu:
  arch:  x86
  brand: Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: CentOS Linux
  version: 7 (Core)
  snap-based: true
kernel:
  version: Linux version 3.10.0-1127.10.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Wed Jun 3 14:28:03 UTC 2020
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions:
      - n/a
  gles2:
    vendor: n/a
    vendor: n/a
    extensions:
```
</details>

**Please describe your problem:**
```
# anbox session-manager

realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
[ 2022-03-15 08:51:42] [service.cpp:84@new_client] Got connection from pid 6273
Stack trace (most recent call last):
#26   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#25   Object "/snap/anbox/186/usr/bin/anbox", at 0x4aa008, in _start
#24   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f3606aa083f, in __libc_start_main
#23   Object "/snap/anbox/186/usr/bin/anbox", at 0x4a524e, in main
#22   Object "/snap/anbox/186/usr/bin/anbox", at 0x4bc337, in anbox::Daemon::Run(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
#21   Object "/snap/anbox/186/usr/bin/anbox", at 0x4b153f, in anbox::cli::CommandWithSubcommands::run(anbox::cli::Command::Context const&)
#20   Object "/snap/anbox/186/usr/bin/anbox", at 0x4b1001, in anbox::cli::CommandWithFlagsAndAction::run(anbox::cli::Command::Context const&)
#19   Object "/snap/anbox/186/usr/bin/anbox", at 0x4df55d, in 
#18   Object "/snap/anbox/186/usr/bin/anbox", at 0x51e3f7, in anbox::platform::create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<anbox::input::Manager> const&, anbox::platform::Configuration const&)
#17   Object "/snap/anbox/186/usr/bin/anbox", at 0x5247a9, in anbox::platform::sdl::Platform::Platform(std::shared_ptr<anbox::input::Manager> const&, anbox::platform::Configuration const&)
#16   Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7f36083383e6, in 
#15   Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7f36083d10c0, in 
#14   Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7f36083e499c, in 
#13   Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7f36083e33a0, in 
#12   Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7f36083d2102, in 
#11   Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7f3607a2ffa0, in dlopen
#10   Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7f3607a30570, in 
#9    Object "/lib64/ld-linux-x86-64.so.2", at 0x7f3608fdc5a3, in 
#8    Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7f3607a2ff08, in 
#7    Object "/lib64/ld-linux-x86-64.so.2", at 0x7f3608fe0de8, in 
#6    Object "/lib64/ld-linux-x86-64.so.2", at 0x7f3608fdc5a3, in 
#5    Object "/lib64/ld-linux-x86-64.so.2", at 0x7f3608fe1921, in 
#4    Object "/lib64/ld-linux-x86-64.so.2", at 0x7f3608fdc80a, in 
#3    Object "/lib64/ld-linux-x86-64.so.2", at 0x7f3608fdc6f9, in 
#2    Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3", at 0x7f35fd9b3408, in 
#1    Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9", at 0x7f360780c832, in google::protobuf::internal::OnShutdown(void (*)())
#0    Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9", at 0x7f360780c516, in google::protobuf::internal::Mutex::Lock()
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault


# anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity

realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
[ 2022-03-15 08:55:35] [launch.cpp:182@operator()] Session manager is not yet running, trying to start it
[ 2022-03-15 08:55:35] [launch.cpp:116@launch_session_manager] Started session manager, will now try to connect ..
Stack trace (most recent call last):
#25   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#24   Object "/snap/anbox/186/usr/bin/anbox", at 0x4aa008, in _start
#23   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fb0473af83f, in __libc_start_main
#22   Object "/snap/anbox/186/usr/bin/anbox", at 0x4a524e, in main
#21   Object "/snap/anbox/186/usr/bin/anbox", at 0x4bc337, in anbox::Daemon::Run(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
#20   Object "/snap/anbox/186/usr/bin/anbox", at 0x4b153f, in anbox::cli::CommandWithSubcommands::run(anbox::cli::Command::Context const&)
#19   Object "/snap/anbox/186/usr/bin/anbox", at 0x4b1001, in anbox::cli::CommandWithFlagsAndAction::run(anbox::cli::Command::Context const&)
#18   Object "/snap/anbox/186/usr/bin/anbox", at 0x4da37c, in 
#17   Object "/snap/anbox/186/usr/bin/anbox", at 0x52be77, in anbox::ui::SplashScreen::SplashScreen()
#16   Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fb048c473e6, in 
#15   Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fb048ce00c0, in 
#14   Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fb048cf399c, in 
#13   Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fb048cf23a0, in 
#12   Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0", at 0x7fb048ce1102, in 
#11   Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7fb04833efa0, in dlopen
#10   Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7fb04833f570, in 
#9    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fb0498eb5a3, in 
#8    Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7fb04833ef08, in 
#7    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fb0498efde8, in 
#6    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fb0498eb5a3, in 
#5    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fb0498f0921, in 
#4    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fb0498eb80a, in 
#3    Object "/lib64/ld-linux-x86-64.so.2", at 0x7fb0498eb6f9, in 
#2    Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3", at 0x7fb03e2c2408, in 
#1    Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9", at 0x7fb04811b832, in google::protobuf::internal::OnShutdown(void (*)())
#0    Object "/snap/anbox/186/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9", at 0x7fb04811b516, in google::protobuf::internal::Mutex::Lock()
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault

```

**What were you expecting?:**

**Additional info:**
