### ISSUE TITLE
[Ubuntu 22.04 LTS] A strange thing about launching anbox.appmgr

### ISSUE THREAD

**Issue by K85** [anbox/anbox#2056]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
version: local-ad377ff
snap-revision: 213
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 22.04 LTS (Jammy Jellyfish)
  snap-based: true
kernel:
  version: Linux version 5.15.0-35-generic (buildd@lcy02-amd64-029) (gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #36-Ubuntu SMP Sat May 21 02:24:07 UTC 2022
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

```
</details>

**Please describe your problem:**
If i use `sudo anbox.appmgr` or `sudo snap run anbox.appmgr`  to launch the `anbox`, then i will get an eroor about `[daemon.cpp:61@Run] Failed to connect to DBus
`.
However, i found that i can `just` use `anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity` to `launch` the `Anbox`. (And it seems every apps inside the launched Anbox works well).
![image](https://user-images.githubusercontent.com/10484271/172753935-5b94b25c-adad-4b62-8fd8-002b8a39067a.png)
![image](https://user-images.githubusercontent.com/10484271/172754378-d84560c9-5224-4180-90ff-560f92f85c2a.png)

Besides, i just found that after i launched the `Anbox` using  `anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity` , the command `sudo snap run anbox.appmgr` shows the same error messages
![image](https://user-images.githubusercontent.com/10484271/172754099-aa85dd8b-e532-492b-8cb2-77a8cd3465cd.png)
while the command `sudo anbox.appmgr` doesn't show any error messages anymore !
![image](https://user-images.githubusercontent.com/10484271/172754197-b2ef5eed-e65f-4633-b417-0e97957ad8b9.png)

**What were you expecting?:**
I just want to know, so everything is ok and i can go to install some third-party apps ?

**Additional info:**
