### ISSUE TITLE
Session manager doesn't start with lxc 1:4.0.12

### ISSUE THREAD

**Issue by cafuneandchill** [anbox/anbox#2083]
<details>
<summary><i><code>anbox system-info</code> output</i></summary>

```
version: 0.0~git20191115-1build1-Ubuntu
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Linux Mint
  version: 20.3 (Una)
  snap-based: false
kernel:
  version: Linux version 5.14.0-1051-oem (buildd@lcy02-amd64-080) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #58-Ubuntu SMP Fri Aug 26 05:50:00 UTC 2022
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: NVIDIA
    version: 1.5
    extensions:
      - EGL_EXT_buffer_age
      - EGL_EXT_client_sync
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_MESA_image_dma_buf_export
      - EGL_EXT_output_base
      - EGL_EXT_stream_acquire_mode
      - EGL_EXT_sync_reuse
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context_no_error
      - EGL_KHR_context_flush_control
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_partial_update
      - EGL_KHR_swap_buffers_with_damage
      - EGL_KHR_no_config_context
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_stream
      - EGL_KHR_stream_attrib
      - EGL_KHR_stream_consumer_gltexture
      - EGL_KHR_stream_cross_process_fd
      - EGL_KHR_stream_fifo
      - EGL_KHR_stream_producer_eglsurface
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_NV_nvrm_fence_sync
      - EGL_NV_post_sub_buffer
      - EGL_NV_quadruple_buffer
      - EGL_NV_stream_consumer_eglimage
      - EGL_NV_stream_cross_display
      - EGL_NV_stream_cross_object
      - EGL_NV_stream_cross_process
      - EGL_NV_stream_cross_system
      - EGL_NV_stream_dma
      - EGL_NV_stream_flush
      - EGL_NV_stream_metadata
      - EGL_NV_stream_remote
      - EGL_NV_stream_reset
      - EGL_NV_stream_socket
      - EGL_NV_stream_socket_inet
      - EGL_NV_stream_socket_unix
      - EGL_NV_stream_sync
      - EGL_NV_stream_fifo_next
      - EGL_NV_stream_fifo_synchronous
      - EGL_NV_stream_consumer_gltexture_yuv
      - EGL_NV_stream_attrib
      - EGL_NV_stream_origin
      - EGL_NV_system_time
      - EGL_NV_output_drm_flip_event
      - EGL_NV_triple_buffer
      - EGL_NV_robustness_video_memory_purge
  gles2:
    vendor: NVIDIA Corporation
    vendor: OpenGL ES 3.2 NVIDIA 470.141.03
    extensions:
      - GL_EXT_base_instance
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clear_texture
      - GL_EXT_clip_control
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_color_buffer_half_float
      - GL_EXT_conservative_depth
      - GL_EXT_copy_image
      - GL_EXT_depth_clamp
      - GL_EXT_debug_label
      - GL_EXT_discard_framebuffer
      - GL_EXT_disjoint_timer_query
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_EGL_image_array
      - GL_EXT_EGL_image_storage
      - GL_EXT_EGL_image_external_wrap_modes
      - GL_EXT_float_blend
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_indirect
      - GL_EXT_multisample_compatibility
      - GL_EXT_multisampled_render_to_texture
      - GL_EXT_multisampled_render_to_texture2
      - GL_EXT_multiview_texture_multisample
      - GL_EXT_multiview_timer_query
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_post_depth_coverage
      - GL_EXT_primitive_bounding_box
      - GL_EXT_raster_multisample
      - GL_EXT_render_snorm
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_group_vote
      - GL_EXT_shader_implicit_conversions
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_shader_non_constant_global_initializers
      - GL_EXT_shader_texture_lod
      - GL_EXT_shadow_samplers
      - GL_EXT_sparse_texture
      - GL_EXT_sparse_texture2
      - GL_EXT_sRGB
      - GL_EXT_sRGB_write_control
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_bptc
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_rgtc
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_filter_minmax
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_mirror_clamp_to_edge
      - GL_EXT_texture_norm16
      - GL_EXT_texture_query_lod
      - GL_EXT_texture_rg
      - GL_EXT_texture_shadow_lod
      - GL_EXT_texture_sRGB_R8
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_storage
      - GL_EXT_texture_view
      - GL_EXT_draw_transform_feedback
      - GL_EXT_unpack_subimage
      - GL_EXT_window_rectangles
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_EXT_memory_object
      - GL_EXT_memory_object_fd
      - GL_NV_memory_object_sparse
      - GL_KHR_parallel_shader_compile
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_EXT_semaphore
      - GL_EXT_semaphore_fd
      - GL_NV_timeline_semaphore
      - GL_KHR_shader_subgroup
      - GL_KHR_texture_compression_astc_ldr
      - GL_KHR_texture_compression_astc_sliced_3d
      - GL_KHR_texture_compression_astc_hdr
      - GL_NV_bgr
      - GL_NV_bindless_texture
      - GL_NV_blend_equation_advanced
      - GL_NV_blend_equation_advanced_coherent
      - GL_NVX_blend_equation_advanced_multi_draw_buffers
      - GL_NV_blend_minmax_factor
      - GL_NV_clip_space_w_scaling
      - GL_NV_compute_shader_derivatives
      - GL_NV_conditional_render
      - GL_NV_conservative_raster
      - GL_NV_conservative_raster_pre_snap_triangles
      - GL_NV_copy_buffer
      - GL_NV_copy_image
      - GL_NV_draw_buffers
      - GL_NV_draw_instanced
      - GL_NV_draw_texture
      - GL_NV_draw_vulkan_image
      - GL_NV_EGL_stream_consumer_external
      - GL_NV_explicit_attrib_location
      - GL_NV_fbo_color_attachments
      - GL_NV_fill_rectangle
      - GL_NV_fragment_coverage_to_color
      - GL_NV_fragment_shader_barycentric
      - GL_NV_fragment_shader_interlock
      - GL_NV_framebuffer_blit
      - GL_NV_framebuffer_mixed_samples
      - GL_NV_framebuffer_multisample
      - GL_NV_generate_mipmap_sRGB
      - GL_NV_geometry_shader_passthrough
      - GL_NV_instanced_arrays
      - GL_NV_internalformat_sample_query
      - GL_NV_gpu_shader5
      - GL_NV_image_formats
      - GL_NV_memory_attachment
      - GL_NV_mesh_shader
      - GL_NV_occlusion_query_samples
      - GL_NV_non_square_matrices
      - GL_NV_pack_subimage
      - GL_NV_packed_float
      - GL_NV_packed_float_linear
      - GL_NV_path_rendering
      - GL_NV_path_rendering_shared_edge
      - GL_NV_pixel_buffer_object
      - GL_NV_polygon_mode
      - GL_NV_primitive_shading_rate
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_NV_representative_fragment_test
      - GL_NV_sample_locations
      - GL_NV_sample_mask_override_coverage
      - GL_NV_scissor_exclusive
      - GL_NV_shader_atomic_fp16_vector
      - GL_NV_shader_noperspective_interpolation
      - GL_NV_shader_subgroup_partitioned
      - GL_NV_shader_texture_footprint
      - GL_NV_shading_rate_image
      - GL_NV_shadow_samplers_array
      - GL_NV_shadow_samplers_cube
      - GL_NV_sRGB_formats
      - GL_NV_stereo_view_rendering
      - GL_NV_texture_array
      - GL_NV_texture_barrier
      - GL_NV_texture_border_clamp
      - GL_NV_texture_compression_latc
      - GL_NV_texture_compression_s3tc
      - GL_NV_texture_compression_s3tc_update
      - GL_NV_texture_dirty_tile_map
      - GL_NV_timer_query
      - GL_NV_viewport_array
      - GL_NV_viewport_array2
      - GL_NV_viewport_swizzle
      - GL_KHR_blend_equation_advanced
      - GL_KHR_blend_equation_advanced_coherent
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_OES_depth24
      - GL_OES_depth32
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_copy_image
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_texture_border_clamp
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_buffer
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_gpu_shader5
      - GL_OES_shader_io_blocks
      - GL_OES_texture_view
      - GL_OES_primitive_bounding_box
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_image_external_essl3
      - GL_OES_EGL_sync
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_get_program_binary
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_surfaceless_context
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_npot
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array
      - GL_OVR_multiview
      - GL_OVR_multiview2
      - GL_OVR_multiview_multisampled_render_to_texture
      - GL_ANDROID_extension_pack_es31a
```
</details>

**Please describe your problem:**

Session manager doesn't start.

<details>
<summary><i><code>anbox session-manager</code> output</i></summary>

```console
$ env ANBOX_LOG_LEVEL=debug anbox session-manager
[ 2022-09-04 18:41:55] [Renderer.cpp:168@initialize] Using a surfaceless EGL context
[ 2022-09-04 18:41:55] [Renderer.cpp:251@initialize] Successfully initialized EGL
[ 2022-09-04 18:41:55] [service.cpp:41@Service] Successfully acquired DBus service name
[ 2022-09-04 18:41:55] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to set config item lxc.group.devices.deny
[ 2022-09-04 18:41:55] [session_manager.cpp:148@operator()] Lost connection to container manager, terminating.
[ 2022-09-04 18:41:56] [daemon.cpp:61@Run] Container is not running
terminate called after throwing an instance of 'boost::wrapexcept<boost::log::v2_mt_posix::system_error>'
  what():  Failed to set TLS value: Invalid argument
Stack trace (most recent call last) in thread 54575:
#16   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#15   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f2b73133132, in clone
#14   Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7f2b734a6608, in 
#13   Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f2b732f7de3, in 
#12   Object "anbox", at 0x55c9e261b318, in 
#11   Object "anbox", at 0x55c9e264184c, in void anbox::Logger::Errorf<char const*>(boost::optional<anbox::Logger::Location> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*&&)
#10   Object "anbox", at 0x55c9e26437ce, in 
#9    Object "/lib/x86_64-linux-gnu/libboost_log.so.1.71.0", at 0x7f2b7393491a, in boost::log::v2_mt_posix::sources::aux::get_severity_level()
#8    Object "/lib/x86_64-linux-gnu/libboost_log.so.1.71.0", at 0x7f2b7395f239, in boost::log::v2_mt_posix::aux::thread_specific_base::set_content(void*) const
#7    Object "/lib/x86_64-linux-gnu/libboost_log.so.1.71.0", at 0x7f2b73913cdc, in 
#6    Object "/lib/x86_64-linux-gnu/libboost_log.so.1.71.0", at 0x7f2b73914fb2, in 
#5    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f2b732cb6a8, in __cxa_throw
#4    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f2b732cb3f6, in std::terminate()
#3    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f2b732cb38b, in 
#2    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f2b732bf910, in 
#1    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f2b73036858, in abort
#0    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f2b7305700b, in gsignal
Aborted (Signal sent by tkill() 54570 1000)
Aborted (core dumped)
```
</details>

**What were you expecting?:**

A working session manager.

**Additional info:**

<details>
<summary><i>LXC version</i></summary>

```console
$ apt list --installed | grep lxc

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

liblxc-common/focal-updates,now 1:4.0.12-0ubuntu1~20.04.1 amd64 [installed,automatic]
liblxc-dev/focal-updates,now 1:4.0.12-0ubuntu1~20.04.1 amd64 [installed,automatic]
liblxc1/focal-updates,now 1:4.0.12-0ubuntu1~20.04.1 amd64 [installed]
lxc-dev/focal-updates,focal-updates,now 1:4.0.12-0ubuntu1~20.04.1 all [installed]
lxc-utils/focal-updates,now 1:4.0.12-0ubuntu1~20.04.1 amd64 [installed,automatic]
lxc/focal-updates,focal-updates,now 1:4.0.12-0ubuntu1~20.04.1 all [installed,automatic]
lxcfs/focal,now 4.0.3-0ubuntu1 amd64 [installed,automatic]
```
</details>

<details>
<summary><i>Session manager service status</i></summary>

```
● anbox-session-manager.service - Anbox Session Manager
     Loaded: loaded (/usr/lib/systemd/user/anbox-session-manager.service; enabled; vendor preset: enabled)
     Active: failed (Result: signal) since Sun 2022-09-04 21:40:21 MSK; 8min ago
       Docs: man:anbox(1)
    Process: 53298 ExecStart=/usr/bin/anbox session-manager (code=killed, signal=ABRT)
   Main PID: 53298 (code=killed, signal=ABRT)

сен 04 21:40:21 echeveria anbox[53298]: #5    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f13328336a8, in __cxa_throw
сен 04 21:40:21 echeveria anbox[53298]: #4    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f13328333f6, in std::terminate()
сен 04 21:40:21 echeveria anbox[53298]: #3    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f133283338b, in
сен 04 21:40:21 echeveria anbox[53298]: #2    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f1332827910, in
сен 04 21:40:21 echeveria anbox[53298]: #1    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f133259e858, in abort
сен 04 21:40:21 echeveria anbox[53298]: #0    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f13325bf00b, in gsignal
сен 04 21:40:21 echeveria anbox[53298]: Aborted (Signal sent by tkill() 53298 1000)
сен 04 21:40:21 echeveria systemd[2351]: anbox-session-manager.service: Main process exited, code=killed, status=6/ABRT
сен 04 21:40:21 echeveria systemd[2351]: anbox-session-manager.service: Failed with result 'signal'.
сен 04 21:40:21 echeveria systemd-coredump[53316]: Process 53298 (anbox) of user 1000 dumped core.
                                                      
                                                      Stack trace of thread 53307:
                                                      #0  0x00007f1332a1a2ab raise (libpthread.so.0 + 0x142ab)
                                                      #1  0x000055796e1abc94 _ZN8backward14SignalHandling11sig_handlerEiP9siginfo_tPv (anbox + 0xe2c94)
                                                      #2  0x00007f1332a1a420 __restore_rt (libpthread.so.0 + 0x14420)
                                                      #3  0x00007f13325bf00b __GI_raise (libc.so.6 + 0x4300b)
                                                      #4  0x00007f133259e859 __GI_abort (libc.so.6 + 0x22859)
                                                      #5  0x00007f1332827911 n/a (libstdc++.so.6 + 0x9e911)
                                                      #6  0x00007f133283338c n/a (libstdc++.so.6 + 0xaa38c)
                                                      #7  0x00007f13328333f7 _ZSt9terminatev (libstdc++.so.6 + 0xaa3f7)
                                                      #8  0x00007f13328336a9 __cxa_throw (libstdc++.so.6 + 0xaa6a9)
                                                      #9  0x00007f1332e7cfb3 n/a (libboost_log.so.1.71.0 + 0x50fb3)
                                                      #10 0x00007f1332e7bcdd n/a (libboost_log.so.1.71.0 + 0x4fcdd)
                                                      #11 0x00007f1332ec723a _ZNK5boost3log11v2_mt_posix3aux20thread_specific_base11set_contentEPv (libboost_log.so.1.71.0 + 0x9b23a)
                                                      #12 0x00007f1332e9c91b _ZN5boost3log11v2_mt_posix7sources3aux18get_severity_levelEv (libboost_log.so.1.71.0 + 0x7091b)
                                                      #13 0x000055796e1c17cf n/a (anbox + 0xf87cf)
                                                      #14 0x000055796e1bf84d _ZN5anbox6Logger6ErrorfIJPKcEEEvRKN5boost8optionalINS0_8LocationEEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEDpOT_ (anbox + 0xf684d)
                                                      #15 0x000055796e199319 n/a (anbox + 0xd0319)
                                                      #16 0x00007f133285fde4 n/a (libstdc++.so.6 + 0xd6de4)
                                                      #17 0x00007f1332a0e609 start_thread (libpthread.so.0 + 0x8609)
                                                      #18 0x00007f133269b133 __clone (libc.so.6 + 0x11f133)
                                                      
                                                      Stack trace of thread 53311:
                                                      #0  0x00007f1332a15376 futex_wait_cancelable (libpthread.so.0 + 0xf376)
                                                      #1  0x000055796e1e777c _ZN5boost4asio6detail9scheduler3runERNS_6system10error_codeE (anbox + 0x11e77c)
                                                      #2  0x000055796e2359aa n/a (anbox + 0x16c9aa)
                                                      #3  0x00007f133285fde4 n/a (libstdc++.so.6 + 0xd6de4)
                                                      #4  0x00007f1332a0e609 start_thread (libpthread.so.0 + 0x8609)
                                                      #5  0x00007f133269b133 __clone (libc.so.6 + 0x11f133)
                                                      
                                                      Stack trace of thread 53312:
                                                      #0  0x00007f1332a15376 futex_wait_cancelable (libpthread.so.0 + 0xf376)
                                                      #1  0x000055796e1e777c _ZN5boost4asio6detail9scheduler3runERNS_6system10error_codeE (anbox + 0x11e77c)
                                                      #2  0x000055796e2359aa n/a (anbox + 0x16c9aa)
                                                      #3  0x00007f133285fde4 n/a (libstdc++.so.6 + 0xd6de4)
                                                      #4  0x00007f1332a0e609 start_thread (libpthread.so.0 + 0x8609)
                                                      #5  0x00007f133269b133 __clone (libc.so.6 + 0x11f133)
                                                      
                                                      Stack trace of thread 53313:
                                                      #0  0x00007f1332a15376 futex_wait_cancelable (libpthread.so.0 + 0xf376)
                                                      #1  0x000055796e1e777c _ZN5boost4asio6detail9scheduler3runERNS_6system10error_codeE (anbox + 0x11e77c)
                                                      #2  0x000055796e2359aa n/a (anbox + 0x16c9aa)
                                                      #3  0x00007f133285fde4 n/a (libstdc++.so.6 + 0xd6de4)
                                                      #4  0x00007f1332a0e609 start_thread (libpthread.so.0 + 0x8609)
                                                      #5  0x00007f133269b133 __clone (libc.so.6 + 0x11f133)
                                                      
                                                      Stack trace of thread 53303:
                                                      #0  0x00007f133268ea96 __ppoll (libc.so.6 + 0x112a96)
                                                      #1  0x00007f13322f78c1 pa_mainloop_poll (libpulse.so.0 + 0x268c1)
                                                      #2  0x00007f13322f7ec3 pa_mainloop_iterate (libpulse.so.0 + 0x26ec3)
                                                      #3  0x00007f13322f7f70 pa_mainloop_run (libpulse.so.0 + 0x26f70)
                                                      #4  0x00007f1332cefcb3 n/a (libSDL2-2.0.so.0 + 0xd3cb3)
                                                      #5  0x00007f1332c91720 n/a (libSDL2-2.0.so.0 + 0x75720)
                                                      #6  0x00007f1332d0a13d n/a (libSDL2-2.0.so.0 + 0xee13d)
                                                      #7  0x00007f1332a0e609 start_thread (libpthread.so.0 + 0x8609)
                                                      #8  0x00007f133269b133 __clone (libc.so.6 + 0x11f133)
                                                      
                                                      Stack trace of thread 53308:
                                                      #0  0x00007f1332a15376 futex_wait_cancelable (libpthread.so.0 + 0xf376)
                                                      #1  0x000055796e1e777c _ZN5boost4asio6detail9scheduler3runERNS_6system10error_codeE (anbox + 0x11e77c)
                                                      #2  0x000055796e2359aa n/a (anbox + 0x16c9aa)
                                                      #3  0x00007f133285fde4 n/a (libstdc++.so.6 + 0xd6de4)
                                                      #4  0x00007f1332a0e609 start_thread (libpthread.so.0 + 0x8609)
                                                      #5  0x00007f133269b133 __clone (libc.so.6 + 0x11f133)
                                                      
                                                      Stack trace of thread 53306:
                                                      #0  0x00007f1332a15376 futex_wait_cancelable (libpthread.so.0 + 0xf376)
                                                      #1  0x000055796e1e777c _ZN5boost4asio6detail9scheduler3runERNS_6system10error_codeE (anbox + 0x11e77c)
                                                      #2  0x000055796e2359aa n/a (anbox + 0x16c9aa)
                                                      #3  0x00007f133285fde4 n/a (libstdc++.so.6 + 0xd6de4)
                                                      #4  0x00007f1332a0e609 start_thread (libpthread.so.0 + 0x8609)
                                                      #5  0x00007f133269b133 __clone (libc.so.6 + 0x11f133)
                                                      
                                                      Stack trace of thread 53310:
                                                      #0  0x00007f1332a15376 futex_wait_cancelable (libpthread.so.0 + 0xf376)
                                                      #1  0x000055796e1e777c _ZN5boost4asio6detail9scheduler3runERNS_6system10error_codeE (anbox + 0x11e77c)
                                                      #2  0x000055796e2359aa n/a (anbox + 0x16c9aa)
                                                      #3  0x00007f133285fde4 n/a (libstdc++.so.6 + 0xd6de4)
                                                      #4  0x00007f1332a0e609 start_thread (libpthread.so.0 + 0x8609)
                                                      #5  0x00007f133269b133 __clone (libc.so.6 + 0x11f133)
                                                      
                                                      Stack trace of thread 53309:
                                                      #0  0x00007f133269b46e epoll_wait (libc.so.6 + 0x11f46e)
                                                      #1  0x000055796e1e6b7b _ZN5boost4asio6detail13epoll_reactor3runElRNS1_8op_queueINS1_19scheduler_operationEEE (anbox + 0x11db7b)
                                                      #2  0x000055796e1e7596 _ZN5boost4asio6detail9scheduler3runERNS_6system10error_codeE (anbox + 0x11e596)
                                                      #3  0x000055796e2359aa n/a (anbox + 0x16c9aa)
                                                      #4  0x00007f133285fde4 n/a (libstdc++.so.6 + 0xd6de4)
                                                      #5  0x00007f1332a0e609 start_thread (libpthread.so.0 + 0x8609)
                                                      #6  0x00007f133269b133 __clone (libc.so.6 + 0x11f133)
                                                      
                                                      Stack trace of thread 53298:
                                                      #0  0x00007f13326903ab ioctl (libc.so.6 + 0x1143ab)
                                                      #1  0x00007f1317203fb9 n/a (libnvidia-eglcore.so.470.141.03 + 0x10fdfb9)
                                                      #2  0x00007f1317205652 n/a (libnvidia-eglcore.so.470.141.03 + 0x10ff652)
                                                      #3  0x00007f13172061f1 n/a (libnvidia-eglcore.so.470.141.03 + 0x11001f1)
                                                      #4  0x00007f1316f5e79c n/a (libnvidia-eglcore.so.470.141.03 + 0xe5879c)
                                                      #5  0x00007f1316f5ff77 n/a (libnvidia-eglcore.so.470.141.03 + 0xe59f77)
                                                      #6  0x00007f1316f6017c n/a (libnvidia-eglcore.so.470.141.03 + 0xe5a17c)
                                                      #7  0x00007f1316f370c8 n/a (libnvidia-eglcore.so.470.141.03 + 0xe310c8)
                                                      #8  0x00007f1316f395c0 n/a (libnvidia-eglcore.so.470.141.03 + 0xe335c0)
                                                      #9  0x00007f1316ea3015 n/a (libnvidia-eglcore.so.470.141.03 + 0xd9d015)
                                                      #10 0x00007f131c961618 n/a (libEGL_nvidia.so.0 + 0xa3618)
                                                      #11 0x00007f131c95fc2b n/a (libEGL_nvidia.so.0 + 0xa1c2b)
                                                      #12 0x00007f13325c28a7 __run_exit_handlers (libc.so.6 + 0x468a7)
                                                      #13 0x00007f13325c2a60 __GI_exit (libc.so.6 + 0x46a60)
                                                      #14 0x00007f13325a008a __libc_start_main (libc.so.6 + 0x2408a)
                                                      #15 0x000055796e1a815e _start (anbox + 0xdf15e)
```
</details>
