### ISSUE TITLE
Failed to start as either binder or ashmem kernel drivers are not loaded

### ISSUE THREAD

**Issue by marioguerriero** [anbox/anbox#211]
Hi. I have installed anbox through the snap package on Ubuntu 16.04 but it suddenly stopped working since a few days. When I try to run the session manager I get the following error
```
[EE 2017-04-30 21:14:48] [session_manager.cpp:119@operator()] Failed to start as either binder or ashmem kernel drivers are not loaded
```

Here is my system-info:

```
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.4.0-75-generic (buildd@lgw01-21) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_swap_region
      - EGL_NOK_texture_from_pixmap
      - EGL_NV_post_sub_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
```

**Comment by Oceankenny** [comment]
If you ever rebooted your ubuntu, you may get that failure.

1. run  "sudo modprobe binder_linux" and "sudo modprobe ashmem_linux" 

 If it fails, try the following way:
1. go to "/usr/src/anbox-modules-ashmem-6~xenial1" and  "usr/src/anbox-modules-binder-6~xenial1",
    run "make & make install"
    ps: the directory name may vary according to the module version and system.
2. "sudo insmod /binder_linux.ko" & "sudo insmod /ashmem_linux.ko"

**Comment by sguilly** [comment]
Same issue after my first installation : [EE 2017-04-30 21:14:48] [session_manager.cpp:119@operator()] Failed to start as either binder or ashmem kernel drivers are not loaded

Fix with the second solution of @Oceankenny by re-compile  :

cd /usr/src/anbox-modules-binder-6~xenial1/
sudo make
sudo make install
sudo insmod /binder_linux.ko
anbox session-manager

But i need always after a reboot do : sudo insmod /binder_linux.ko
and run manually : anbox session-manager

**Comment by Pyrathar** [comment]
Kernel: 4.10 Ubuntu 17.04.

Had the same problem used @Oceankenny  solution and worked

**Comment by loveleen15029** [comment]
I have used @oceankenny solution but it's still showing the same error message. I am using ubuntu 17.04.

**Comment by ryanleesipes** [comment]
@loveleen15029 What's the error?

**Comment by loveleen15029** [comment]
[session_manager.cpp:119@operator()] Failed to start as either binder or ashmem kernel drivers are not loaded.

**Comment by dillanjwilding** [comment]
Where are you guys getting the binder_linux.ko? Also when I run sudo insmod /ashmen_linux.ko I get an error "could not insert module /ashmen_linux.ko: Required key not available"

**Comment by jackwish** [comment]
For "installing binder and ashmem" on Ubuntu, you can refer to https://github.com/anbox/anbox-installer/blob/master/installer.sh

More precisely (maybe you need to update your apt source via `sudo add-apt-repository -y 'ppa:morphis/anbox-support'`):
```
    sudo apt install -y linux-headers-generic anbox-modules-dkms
    sudo modprobe binder_linux
    sudo modprobe ashmem_linux
```

**Comment by flynn16** [comment]
> Where are you guys getting the binder_linux.ko

The directory name varies depending on your anbox version and system version.

```bash
cd /usr/src/anbox-modules-[tab][tab]
```

And you will find the source code of the modules.

**Comment by meki383** [comment]
no such files or directory /usr/src/anbox********************

**Comment by dreamcat4** [comment]
Hmm... upgraded my kernel version (still on a low latency kernel). to .19.4. Rebooted... and now the binder.ko module loaded up no fuss.

This behaviour has been observed before by other people. The true cause of the issue still not known...

**Comment by damian101** [comment]
@Oceankenny Folder /usr/src/anbox-modules-binder-6~xenial1/ does not exist.

**Comment by makkasi** [comment]
I have installed these and it worked:
$ sudo add-apt-repository ppa:morphis/anbox-support
$ sudo apt update
$ sudo apt install anbox-modules-dkms

**Comment by nindolabs** [comment]
This solution worked for me:

in binder.c:

change 
  BINDER_DKMS_MAJOR 511 
to 
  BINDER_DKMS_MAJOR 512 
or any other major

511 was taken in my situation.

**Comment by Entropy512** [comment]
On Ubuntu 19.10 - ashmem_linux and binder_linux are included with the system.

However, anbox is not detecting binder, despite it being loaded:
```
adodd@andyslaptop:~$ anbox system-info
version: 4
snap-revision: 185
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 19.10 (Eoan Ermine)
  snap-based: true
kernel:
  version: Linux version 5.3.0-24-generic (buildd@lgw01-amd64-035) (gcc version 9.2.1 20191008 (Ubuntu 9.2.1-9ubuntu2)) #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
```
```
adodd@andyslaptop:~$ lsmod |grep linux
binder_linux          163840  0
ashmem_linux           20480  0
```
