### ISSUE TITLE
I see Anbox UI once immediately after updating to Rev23, but never afterwards. [Previous title: "adb devices" shows no devices (Mint 18.1 Xfce)]

### ISSUE THREAD

**Issue by hub2git** [anbox/anbox#225]
I'm running Mint 18.1 Xfce. 
When I run `adb devices` I don't get any device.

```
anbox system-info
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.4.0-71-generic (buildd@lcy01-05) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_swap_region
      - EGL_NOK_texture_from_pixmap
      - EGL_NV_post_sub_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
```

```
anbox session-manager
[EE 2017-05-04 17:02:56] [daemon.cpp:58@Run] bind: Address already in use
```

```
adb devices
List of devices attached
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
```

```
~ $ systemctl --user restart anbox
~ $ adb kill-server ; adb devices
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
List of devices attached 

~ $ adb shell
error: device not found
```
`dmesg` gave the following: https://gist.github.com/anonymous/db7de6abec720e28d02bac1a09c0a50c

my container.log https://gist.github.com/hub2git/c2e661e6691ea6358e2685c62178e34d
```
ps ax | grep anbox
 1463 ?        Ssl    0:00 /snap/anbox/16/usr/bin/anbox container-manager --data-path=/var/snap/anbox/common/ --android-image=/snap/anbox/16/android.img
 1823 ?        S      0:00 dnsmasq -u dnsmasq --strict-order --bind-interfaces --pid-file=/run/anbox/dnsmasq.pid --dhcp-no-override --except-interface=lo --interface=anboxbr0 --dhcp-leasefile=/var/lib/anbox/dnsmasq.anboxbr0.leases --dhcp-authoritative --listen-address 10.0.6.1 --dhcp-range 10.0.6.2,10.0.6.254 --dhcp-lease-max=252 --dhcp-range=fd9d:e4dc:4e00:9e98::1,ra-stateless,ra-names --listen-address fd9d:e4dc:4e00:9e98::1
 2325 ?        Ssl    0:02 /snap/anbox/16/usr/bin/anbox session-manager
4086 pts/6 S+ 0:00 grep --color=auto anbox
```

```
 $ cat /etc/linuxmint/info
RELEASE=18.1
CODENAME=serena
EDITION="Xfce 64-bit"
DESCRIPTION="Linux Mint 18.1 Serena"
DESKTOP=Xfce
TOOLKIT=GTK
NEW_FEATURES_URL=http://www.linuxmint.com/rel_serena_xfce_whatsnew.php
RELEASE_NOTES_URL=http://www.linuxmint.com/rel_serena_xfce.php
USER_GUIDE_URL=help:linuxmint
GRUB_TITLE=Linux Mint 18.1 Xfce 64-bit
```
**Please describe your problem:**
I don't see Anbox when I try to start it from the Mint Menu.

**What were you expecting?:**

I expect that when I click Anbox from the Mint Menu, I will see Anbox GUI window. But I see nothing.

**Comment by hub2git** [comment]
Would this help: https://github.com/anbox/anbox/issues/143#issuecomment-296835826? I'm too scared to run that code.

**Comment by hub2git** [comment]
I was informed by developer staff that this week's Anbox updates should fix this issue. Developers pointed me to https://github.com/anbox/anbox/pull/257 which has been merged on May 14.

**Comment by hub2git** [comment]
I  upgraded Anbox by `sudo snap refresh --edge --devmode anbox`. I learned this from #287. 
I went to Mint menu and clicked on Anbox icon. I then, for my very first time, see a box pop up with the Android outline in the middle. Below him is the word "Loading...". But after a few minutes, it disappeared. (Crashed?). Now, when I try to run anbox (by clicking it from Mint Menu or through `anbox launch`), nothing happens.


**adb devices**
```
List of devices attached 
????????????	no permissions
```


 snap info anbox
```
name:      anbox
summary:   "Android in a Box"
publisher: morphis
description: |
  Runtime for Android applications which runs a full Android system
  in a container using Linux namespaces (user, ipc, net, mount) to
  separate the Android system fully from the host.
  
commands:
  - anbox
tracking:      edge
installed:     2 (23) 358MB devmode
refreshed:     2017-05-23 00:00:42 -0700 PDT
channels:                 
  latest/beta: 1-dev (15) 357MB devmode
  latest/edge: 2     (23) 358MB devmode
```

**anbox system-info**
```
version: 2
snap-revision: 23
os:
  name: Linux Mint
  version: 18.1 (Serena)
  snap-based: true
kernel:
  version: Linux version 4.4.0-71-generic (buildd@lcy01-05) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_swap_region
      - EGL_NOK_texture_from_pixmap
      - EGL_NV_post_sub_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp

```
