### ISSUE TITLE
segfaults related to networking

### ISSUE THREAD

**Issue by Saren-Arterius** [anbox/anbox#235]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
version: 0.1.0
os:
  name: Apricity OS
  version: 
  snap-based: false
kernel:
  version: Linux version 4.10.14-1-ck (saren@Saren-Workstation) (gcc version 6.3.1 20170306 (GCC) ) #1 SMP PREEMPT Thu May 4 10:50:03 HKT 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: NVIDIA
    version: 1.4
    extensions:
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_output_base
      - EGL_EXT_stream_acquire_mode
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context_no_error
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_partial_update
      - EGL_KHR_swap_buffers_with_damage
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_stream
      - EGL_KHR_stream_consumer_gltexture
      - EGL_KHR_stream_cross_process_fd
      - EGL_KHR_stream_fifo
      - EGL_KHR_stream_producer_eglsurface
      - EGL_KHR_surfaceless_context
      - EGL_NV_post_sub_buffer
      - EGL_NV_stream_metadata
      - EGL_NV_stream_sync
      - EGL_NV_stream_consumer_gltexture_yuv
      - EGL_NV_stream_attrib
      - EGL_NV_sync
      - EGL_NV_system_time
      - EGL_NV_output_drm_flip_event
      - EGL_WL_bind_wayland_display
      - EGL_WL_wayland_eglstream
  gles2:
    vendor: NVIDIA Corporation
    vendor: OpenGL ES 1.1 NVIDIA 378.13
    extensions:
      - GL_EXT_debug_label
      - GL_EXT_map_buffer_range
      - GL_EXT_robustness
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_format_BGRA8888
      - GL_KHR_debug
      - GL_NV_texture_compression_s3tc
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_compressed_paletted_texture
      - GL_OES_draw_texture
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_element_index_uint
      - GL_OES_extended_matrix_palette
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_matrix_get
      - GL_OES_matrix_palette
      - GL_OES_packed_depth_stencil
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_OES_rgb8_rgba8
      - GL_OES_read_format
      - GL_OES_stencil8
      - GL_OES_texture_cube_map
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float
```

**Please describe your problem:**
`anbox session-manager --gles-driver=host` after `sudo /usr/bin/anbox container-manager --privileged` never finishes. `anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity` does not work because of timeout.

**What were you expecting?:**
`anbox session-manager --gles-driver=host` gives out boot success message and `anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity` works.

**Additional info:**
Coredump files
[core.anbox.1001.d88deeaf27de4df3ad75ec5b836cd6ac.5741.1494072054000000000000.zip](https://github.com/anbox/anbox/files/980902/core.anbox.1001.d88deeaf27de4df3ad75ec5b836cd6ac.5741.1494072054000000000000.zip)
[core.anbox.1001.d88deeaf27de4df3ad75ec5b836cd6ac.40770.1494071151000000000000.zip](https://github.com/anbox/anbox/files/980901/core.anbox.1001.d88deeaf27de4df3ad75ec5b836cd6ac.40770.1494071151000000000000.zip)
[core.anbox.1001.d88deeaf27de4df3ad75ec5b836cd6ac.44895.1494071557000000000000.zip](https://github.com/anbox/anbox/files/980900/core.anbox.1001.d88deeaf27de4df3ad75ec5b836cd6ac.44895.1494071557000000000000.zip)
[core.anbox.1001.d88deeaf27de4df3ad75ec5b836cd6ac.51451.1494071583000000000000.zip](https://github.com/anbox/anbox/files/980904/core.anbox.1001.d88deeaf27de4df3ad75ec5b836cd6ac.51451.1494071583000000000000.zip)
[core.anbox.1001.d88deeaf27de4df3ad75ec5b836cd6ac.56629.1494072006000000000000.zip](https://github.com/anbox/anbox/files/980903/core.anbox.1001.d88deeaf27de4df3ad75ec5b836cd6ac.56629.1494072006000000000000.zip)

Some stack trace:
```
                Stack trace of thread 40785:
                #0  0x000000000055ee7e _ZN5anbox7network18TcpSocketConnectorC1ERKN5boost4asio2ip10address_v4EtRKSt10shared_ptrINS_7RuntimeEERKS8_INS0_17ConnectionCreatorINS4_3tcpEEEE (anbox)
                #1  0x0000000000536ece _ZN5anbox4qemu19AdbMessageProcessor24wait_for_host_connectionEv (anbox)
                #2  0x00000000005375f9 n/a (anbox)
                #3  0x00000000004e7165 n/a (anbox)
                #4  0x00007fa22e05758f execute_native_thread_routine (libstdc++.so.6)
                #5  0x00007fa22eba32e7 start_thread (libpthread.so.0)
                #6  0x00007fa22dacd54f __clone (libc.so.6)
```

```
                Stack trace of thread 51459:
                #0  0x000000000055c188 _ZN5anbox7network18TcpSocketMessengerC1ERKN5boost4asio2ip10address_v4EtRKSt10shared_ptrINS_7RuntimeEE (anbox)
                #1  0x00000000005367ab _ZN5anbox4qemu19AdbMessageProcessor24wait_for_host_connectionEv (anbox)
                #2  0x00000000005375f9 n/a (anbox)
                #3  0x00000000004e7165 n/a (anbox)
                #4  0x00007f71ac3df58f execute_native_thread_routine (libstdc++.so.6)
                #5  0x00007f71acf2b2e7 start_thread (libpthread.so.0)
                #6  0x00007f71abe5554f __clone (libc.so.6)
```

```
                Stack trace of thread 56636:
                #0  0x000000000055ee7e _ZN5anbox7network18TcpSocketConnectorC1ERKN5boost4asio2ip10address_v4EtRKSt10shared_ptrINS_7RuntimeEERKS8_INS0_17ConnectionCreatorINS4_3tcpEEEE (anbox)
                #1  0x0000000000536ece _ZN5anbox4qemu19AdbMessageProcessor24wait_for_host_connectionEv (anbox)
                #2  0x00000000005375f9 n/a (anbox)
                #3  0x00000000004e7165 n/a (anbox)
                #4  0x00007f2f2695e58f execute_native_thread_routine (libstdc++.so.6)
                #5  0x00007f2f274aa2e7 start_thread (libpthread.so.0)
                #6  0x00007f2f263d454f __clone (libc.so.6)
```
