### ISSUE TITLE
Anbox not working

### ISSUE THREAD

**Issue by ryaniskira** [anbox/anbox#255]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.10.0-20-generic (buildd@lcy01-05) (gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) ) #22-Ubuntu SMP Thu Apr 20 09:22:42 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

```

**Please describe your problem:**
Anbox will not run

**What were you expecting?:**
Anbox functioning

**Additional info:**
