### ISSUE TITLE
ADB: no devices/emulators found 

### ISSUE THREAD

**Issue by ench4nt3r** [anbox/anbox#258]
[please paste printout of `anbox system-info` here]
```
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.10.0-20-generic (buildd@lcy01-05) (gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) ) #22-Ubuntu SMP Thu Apr 20 09:22:42 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
```

**Please describe your problem:**
```
$ adb devices
List of deives attached

$ adb shell 
error: no devices/emulators found
```

**What were you expecting?:**
Be able to run adb shell

**Additional info:**

The android.img used by anbox is built by myself, the system.img come from Android Sdk 19,　randisk.img is same.

In addition, in order to build the android.img, I modified create-package.sh.

```
diff --git a/scripts/create-package.sh b/scripts/create-package.sh
index fff030a..be2770d 100755
--- a/scripts/create-package.sh
+++ b/scripts/create-package.sh
@@ -18,6 +18,9 @@ mkdir -p $rootfs
 # Extract ramdisk and preserve ownership of files
 (cd $rootfs ; cat $ramdisk | gzip -d | sudo cpio -i)
 
+mkdir -p $rootfs/cache
+mkdir -p $rootfs/data
+
 mkdir $workdir/system
 sudo mount -o loop,ro $system $workdir/system
 sudo cp -ar $workdir/system/* $rootfs/system
@@ -27,6 +30,7 @@ gcc -o $workdir/uidmapshift external/nsexec/uidmapshift.c
 sudo $workdir/uidmapshift -b $rootfs 0 100000 65536
 
 # FIXME
+sudo cp scripts/anbox-init.sh $rootfs/
 sudo chmod +x $rootfs/anbox-init.sh
 
 sudo mksquashfs $rootfs android.img -comp xz -no-xattrs
```

anbox   container-manager 
```
$ sudo ANBOX_LOG_LEVEL=debug anbox container-manager \
    --data-path=/path/data/ \
    --android-image=/path/android.img
[DD 2017-05-13 03:08:52] [service.cpp:49@create] Everything setup. Waiting for incoming connections.
[DD 2017-05-13 03:09:12] [service.cpp:76@new_client] Got connection from pid 7466
[DD 2017-05-13 03:09:13] [lxc_container.cpp:90@start] Containers are stored in /path/containers
[DD 2017-05-13 03:09:13] [lxc_container.cpp:127@start] Using rootfs path /path/data/rootfs
[DD 2017-05-13 03:09:13] [lxc_container.cpp:194@start] Container successfully started
```

anbox session-manager

```
$ ANBOX_LOG_LEVEL=debug anbox session-manager
[DD 2017-05-13 03:09:13] [gl_renderer_server.cpp:82@GLRendererServer] Using GLES-to-GL translator for rendering
[DD 2017-05-13 03:09:13] [Renderer.cpp:113@initialize] EGL doesn't support surfaceless context
[DD 2017-05-13 03:09:13] [Renderer.cpp:249@initialize] Successfully initialized EGL
```

thanks.
