### ISSUE TITLE
change language

### ISSUE THREAD

**Issue by babayaga94** [anbox/anbox#259]
i use latest version of anbox on ubuntu 17.04. when i change language to persian anbox window black... i restart anbox and system but still open black window instead of anbox

**Comment by shakram02** [comment]
same here for Arabic, on Arch
Any ideas how to reset the device to English?

System info:
```
version: local-df774db
os:
  name: Manjaro Linux
  version: 
  snap-based: false
kernel:
  version: Linux version 4.9.48-1-MANJARO (builduser@manjaro) (gcc version 7.1.1 20170630 (GCC) ) #1 SMP PREEMPT Thu Sep 7 10:44:53 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: NVIDIA
    version: 1.4
    extensions:
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_output_base
      - EGL_EXT_stream_acquire_mode
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context_no_error
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_partial_update
      - EGL_KHR_swap_buffers_with_damage
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_stream
      - EGL_KHR_stream_consumer_gltexture
      - EGL_KHR_stream_cross_process_fd
      - EGL_KHR_stream_fifo
      - EGL_KHR_stream_producer_eglsurface
      - EGL_KHR_surfaceless_context
      - EGL_NV_post_sub_buffer
      - EGL_NV_stream_metadata
      - EGL_NV_stream_sync
      - EGL_NV_stream_consumer_gltexture_yuv
      - EGL_NV_stream_attrib
      - EGL_NV_sync
      - EGL_NV_system_time
      - EGL_NV_output_drm_flip_event
      - EGL_WL_bind_wayland_display
      - EGL_WL_wayland_eglstream
  gles2:
    vendor: NVIDIA Corporation
    vendor: OpenGL ES 1.1 NVIDIA 375.82
    extensions:
      - GL_EXT_debug_label
      - GL_EXT_map_buffer_range
      - GL_EXT_robustness
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_format_BGRA8888
      - GL_KHR_debug
      - GL_NV_texture_compression_s3tc
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_compressed_paletted_texture
      - GL_OES_draw_texture
      - GL_OES_EGL_image
      - GL_OES_EGL_sync
      - GL_OES_element_index_uint
      - GL_OES_extended_matrix_palette
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_matrix_get
      - GL_OES_matrix_palette
      - GL_OES_packed_depth_stencil
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_OES_rgb8_rgba8
      - GL_OES_read_format
      - GL_OES_stencil8
      - GL_OES_texture_cube_map
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float
```
