### ISSUE TITLE
Network functionality will not be available

### ISSUE THREAD

**Issue by Th3Manu** [anbox/anbox#270]
** Please paste the result of `anbox system-info` below:**
```
version: 2
os:
  name: Arch Linux
  version: 
  snap-based: false
kernel:
  version: Linux version 4.10.13-1-ARCH (builduser@tobias) (gcc version 6.3.1 20170306 (GCC) ) #1 SMP PREEMPT Thu Apr 27 12:15:09 CEST 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 17.0.5
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
```

**Please describe your problem:**
Anbox can't connect to internet.

**Additional info:**
```
 anbox-container-manager.service - Anbox Container Manager
   Loaded: loaded (/usr/lib/systemd/system/anbox-container-manager.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-05-16 18:51:15 CEST; 1h 20min ago
 Main PID: 395 (anbox)
   CGroup: /system.slice/anbox-container-manager.service
           ├─  395 /usr/bin/anbox container-manager --privileged
           └─22958 /usr/bin/anbox container-manager --privileged

mag 16 19:38:04 emanuele anbox[395]: [WW 2017-05-16 16:51:18] [container_manager.cpp:62@operator()]
mag 16 19:38:04 emanuele anbox[395]: [WW 2017-05-16 17:11:18] [lxc_container.cpp:90@setup_network] Anbox bridge interface 'anbox0' doesn't exist. Network functionality will not be available
mag 16 19:38:04 emanuele anbox[395]: [WW 2017-05-16 17:12:28] [lxc_container.cpp:90@setup_network] Anbox bridge interface 'anbox0' doesn't exist. Network functionality will not be available
mag 16 19:38:04 emanuele anbox[395]: [WW 2017-05-16 17:12:33] [lxc_container.cpp:90@setup_network] Anbox bridge interface 'anbox0' doesn't exist. Network functionality will not be available
mag 16 19:38:04 emanuele anbox[395]: [WW 2017-05-16 17:12:38] [lxc_container.cpp:90@setup_network] Anbox bridge interface 'anbox0' doesn't exist. Network functionality will not be available
mag 16 19:38:04 emanuele anbox[395]: [WW 2017-05-16 17:12:53] [lxc_container.cpp:90@setup_network] Anbox bridge interface 'anbox0' doesn't exist. Network functionality will not be available
mag 16 19:38:04 emanuele anbox[395]: [WW 2017-05-16 17:22:03] [lxc_container.cpp:90@setup_network] Anbox bridge interface 'anbox0' doesn't exist. Network functionality will not be available
mag 16 19:38:04 emanuele anbox[395]: [WW 2017-05-16 17:23:14] [lxc_container.cpp:90@setup_network] Anbox bridge interface 'anbox0' doesn't exist. Network functionality will not be available
mag 16 19:38:04 emanuele anbox[395]: [WW 2017-05-16 17:25:46] [lxc_container.cpp:90@setup_network] Anbox bridge interface 'anbox0' doesn't exist. Network functionality will not be available
mag 16 19:38:04 emanuele anbox[395]: [WW 2017-05-16 17:38:04] [lxc_container.cpp:90@setup_network] Anbox bridge interface 'anbox0' doesn't exist. Network functionality will not be available
```
