### ISSUE TITLE
Anbox won't start on Ubuntu Gnome 16.04 LTS

### ISSUE THREAD

**Issue by hydargos123** [anbox/anbox#283]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
version: 2
snap-revision: 18
os:
  name: Ubuntu
  version: 16.04.2 LTS (Xenial Xerus)
  snap-based: true
kernel:
  version: Linux version 4.8.0-52-generic (buildd@lgw01-59) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #55~16.04.1-Ubuntu SMP Fri Apr 28 14:36:29 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
```

**Please describe your problem:**
When i try to launch Anbox, nothing happen.
When i try to launch Anbox using the Terminal _**hydargos123@Vydar:~$** anbox_ , i got this:
```
Unknown command 'run'
```
and it display a short help message with a list of commands (like with _anbox help_).
It's same using _sudo_.
**What were you expecting?:**
I don't know, cause the command "_run_" is i think used in a lot of program, but my computer is working perfectly... maybe i need to install a package or something ?

**Additional info:**
My computer is a HP Envy 15-ae112nf: https://support.hp.com/us-en/document/c04933755/?openCLC=true
Sorry, i dont speak English very well.
