### ISSUE TITLE
libsdl2-dev conflict?

### ISSUE THREAD

**Issue by supaplextor** [anbox/anbox#306]
I did a git pull and retraced my steps on installing anbox to update it.

supaplex@hydrogen:~/anbox/build$ make
-- No build type selected, default to release
-- Treat warnings as errors
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   log
--   serialization
--   system
--   thread
--   program_options
--   log_setup
--   date_time
--   regex
--   chrono
--   atomic
-- Checking for module 'SDL2_image'
--   No package 'SDL2_image' found
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  CMakeLists.txt:67 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/home/supaplex/anbox/build/CMakeFiles/CMakeOutput.log".
See also "/home/supaplex/anbox/build/CMakeFiles/CMakeError.log".
Makefile:990: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
supaplex@hydrogen:~/anbox/build$ dpkg -l libsdl2-dev ; uname -a
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libsdl2-dev    2.0.4+dfsg1- amd64        Simple DirectMedia Layer developm

Linux hydrogen 4.8.0-52-generic #55~16.04.1-Ubuntu SMP Fri Apr 28 14:36:29 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

** Please paste the result of `anbox system-info` below:**
```
supaplex@hydrogen:~/anbox/build$ anbox system-info
version: 0.1.0
os:
  name: Ubuntu
  version: 16.04.2 LTS (Xenial Xerus)
  snap-based: false
kernel:
  version: Linux version 4.8.0-52-generic (buildd@lgw01-59) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #55~16.04.1-Ubuntu SMP Fri Apr 28 14:36:29 UTC 2017
  binder: false
  ashmem: false
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_KHR_create_context
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_MESA_configless_context
  gles2:
    vendor: VMware, Inc.
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
supaplex@hydrogen:~/anbox/build$ 

```

**Please describe your problem:**

Fails to build while libsdl2-dev is installed.

**What were you expecting?:**

**Additional info:**
