### ISSUE TITLE
Failed to launch activity: org.anbox.Error.Failed: write: Broken pipe

### ISSUE THREAD

**Issue by supaplextor** [anbox/anbox#317]
Make sure you are running the latest version of Anbox before reporting an issue.

This build is no more than a few days old.

** Please paste the result of `anbox system-info` below:**
```
supaplex@hydrogen:~$ anbox system-info
version: local-18a7930
os:
  name: Ubuntu
  version: 16.04.2 LTS (Xenial Xerus)
  snap-based: false
kernel:
  version: Linux version 4.8.0-54-generic (buildd@lgw01-13) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #57~16.04.1-Ubuntu SMP Wed May 24 16:22:28 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_KHR_create_context
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_MESA_configless_context
  gles2:
    vendor: VMware, Inc.
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp

```

**Please describe your problem:**

The new android.img and its installed apps. (fresh install). I was trying to figure out why my old img file was in use but that's a different issue.

supaplex@hydrogen:~$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
[EE 2017-06-11 22:18:48] [launch.cpp:48@try_launch_activity] Failed to launch activity: org.anbox.Error.Failed: write: Broken pipe

**Additional info:**

via dmesg:

[105792.101754] device vethDYKTCC left promiscuous mode
[105792.101758] anboxbr0: port 1(vethDYKTCC) entered disabled state
[105792.421681] IPv6: ADDRCONF(NETDEV_UP): anboxbr0: link is not ready
