### ISSUE TITLE
ubuntu 16.04 run error with patchoat segfault at libart.so

### ISSUE THREAD

**Issue by pinguo-ops** [anbox/anbox#330]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
root@puqiaoming:~# anbox system-info
version: 3
snap-revision: x1
os:
  name: Ubuntu
  version: 16.04.2 LTS (Xenial Xerus)
  snap-based: true
kernel:
  version: Linux version 4.8.0-54-generic (buildd@lgw01-13) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #57~16.04.1-Ubuntu SMP Wed May 24 16:22:28 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: NVIDIA
    version: 1.4
    extensions:
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_output_base
      - EGL_EXT_stream_acquire_mode
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context_no_error
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_partial_update
      - EGL_KHR_swap_buffers_with_damage
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_stream
      - EGL_KHR_stream_consumer_gltexture
      - EGL_KHR_stream_cross_process_fd
      - EGL_KHR_stream_fifo
      - EGL_KHR_stream_producer_eglsurface
      - EGL_KHR_surfaceless_context
      - EGL_NV_post_sub_buffer
      - EGL_NV_stream_metadata
      - EGL_NV_stream_sync
      - EGL_NV_stream_consumer_gltexture_yuv
      - EGL_NV_stream_attrib
      - EGL_NV_sync
      - EGL_NV_system_time
      - EGL_NV_output_drm_flip_event
      - EGL_WL_bind_wayland_display
      - EGL_WL_wayland_eglstream
  gles2:
    vendor: NVIDIA Corporation
    vendor: OpenGL ES 1.1 NVIDIA 375.66
    extensions:
      - GL_EXT_debug_label
      - GL_EXT_map_buffer_range
      - GL_EXT_robustness
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_format_BGRA8888
      - GL_KHR_debug
      - GL_NV_texture_compression_s3tc
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_compressed_paletted_texture
      - GL_OES_draw_texture
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_element_index_uint
      - GL_OES_extended_matrix_palette
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_matrix_get
      - GL_OES_matrix_palette
      - GL_OES_packed_depth_stencil
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_OES_rgb8_rgba8
      - GL_OES_read_format
      - GL_OES_stencil8
      - GL_OES_texture_cube_map
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float

```

**Please describe your problem:**
run anbox session-manager  the kernel output the error  below:

Jun 21 08:56:21 puqiaoming kernel: [42633.505867] patchoat[30817]: segfault at 9c ip 00000000f71918c6 sp 00000000ff82d0a0 error 4 in libart.so[f6c50000+722000]
Jun 21 08:56:21 puqiaoming kernel: [42633.764921] zygote[30727]: segfault at 9c ip 00000000f31928c6 sp 00000000ffd83f60 error 4 in libart.so[f2c51000+722000]
Jun 21 08:56:24 puqiaoming kernel: [42635.910642] audit_printk_skb: 12 callbacks suppressed
Jun 21 08:56:24 puqiaoming kernel: [42635.910644] audit: type=1400 audit(1498006584.054:737): apparmor="ALLOWED" operation="create" profile="snap.anbox.anbox" pid=29744 comm="anbox" family="inet" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
Jun 21 08:56:24 puqiaoming kernel: [42635.910672] audit: type=1400 audit(1498006584.054:738): apparmor="ALLOWED" operation="connect" profile="snap.anbox.anbox" pid=29744 comm="anbox" family="inet" sock_type="stream" protocol=6 requested_mask="connect" denied_mask="connect"
Jun 21 08:56:25 puqiaoming kernel: [42636.910894] audit: type=1400 audit(1498006585.054:739): apparmor="ALLOWED" operation="create" profile="snap.anbox.anbox" pid=29745 comm="anbox" family="inet" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
Jun 21 08:56:25 puqiaoming kernel: [42636.910919] audit: type=1400 audit(1498006585.054:740): apparmor="ALLOWED" operation="connect" profile="snap.anbox.anbox" pid=29745 comm="anbox" family="inet" sock_type="stream" protocol=6 requested_mask="connect" denied_mask="connect"
Jun 21 08:56:26 puqiaoming kernel: [42637.911162] audit: type=1400 audit(1498006586.054:741): apparmor="ALLOWED" operation="create" profile="snap.anbox.anbox" pid=29749 comm="anbox" family="inet" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
Jun 21 08:56:26 puqiaoming kernel: [42637.911194] audit: type=1400 audit(1498006586.054:742): apparmor="ALLOWED" operation="connect" profile="snap.anbox.anbox" pid=29749 comm="anbox" family="inet" sock_type="stream" protocol=6 requested_mask="connect" denied_mask="connect"
Jun 21 08:56:26 puqiaoming kernel: [42638.410442] patchoat[30906]: segfault at 9c ip 00000000f714e8c6 sp 00000000ffe8a3a0 error 4 in libart.so[f6c0d000+722000]
Jun 21 08:56:26 puqiaoming kernel: [42638.637513] zygote[30832]: segfault at 9c ip 00000000f31928c6 sp 00000000ffeb51c0 error 4 in libart.so[f2c51000+722000]
Jun 21 08:56:27 puqiaoming kernel: [42638.911471] audit: type=1400 audit(1498006587.054:743): apparmor="ALLOWED" operation="create" profile="snap.anbox.anbox" pid=29750 comm="anbox" family="inet" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
Jun 21 08:56:27 puqiaoming kernel: [42638.911503] audit: type=1400 audit(1498006587.054:744): apparmor="ALLOWED" operation="connect" profile="snap.anbox.anbox" pid=29750 comm="anbox" family="inet" sock_type="stream" protocol=6 requested_mask="connect" denied_mask="connect"

**What were you expecting?:**

**Additional info:**
