### ISSUE TITLE
Android hasn't fully booted yet, stuck on starting screen

### ISSUE THREAD

**Issue by FliiFe** [anbox/anbox#343]
** Please paste the result of `anbox system-info` below:**
```
version: local-0d45f80
os:
  name: Gentoo
  version: 
  snap-based: false
kernel:
  version: Linux version 4.9.34-gentoo (root@fliife-computer) (gcc version 5.4.0 (Gentoo 5.4.0-r3 p1.3, pie-0.6.5) ) #3 SMP Thu Jul 6 20:24:18 CEST 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
  gles2:
    vendor: X.Org
    vendor: OpenGL ES-CM 1.1 Mesa 17.1.3
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_polygon_offset_clamp
```

**Please describe your problem:**

Stuck on "Starting..." screen, until anbox dies.

**What were you expecting?:**

AppMgr to launch

**Additional info:**

I have installed anbox through (handmade) ebuilds (installation seems correct).
I **did not** use the kernel modules because the gentoo kernel has `CONFIG_ASHMEM` and `CONFIG_ANDROID_BINDER_IPC`.

I start the container manager as follows:
```
$ sudo env ANBOX_LOG_LEVEL=debug anbox container-manager --privileged --daemon --data-path=/var/lib/anbox
[DD 2017-07-08 20:28:46] [service.cpp:49@create] Everything setup. Waiting for incoming connections.
[DD 2017-07-08 20:28:48] [service.cpp:76@new_client] Got connection from pid 11757
[DD 2017-07-08 20:28:49] [lxc_container.cpp:171@start] Containers are stored in /var/lib/anbox/containers
[DD 2017-07-08 20:28:49] [lxc_container.cpp:208@start] Using rootfs path /var/lib/anbox/rootfs
[WW 2017-07-08 20:28:49] [lxc_container.cpp:93@setup_network] Anbox bridge interface 'anbox0' doesn't exist. Network functionality will not be available
[DD 2017-07-08 20:28:49] [lxc_container.cpp:271@start] Container successfully started
```

then start the session manager (non root user)
```
$ env ANBOX_LOG_LEVEL=debug anbox session-manager
[DD 2017-07-08 20:28:49] [gl_renderer_server.cpp:82@GLRendererServer] Using GLES-to-GL translator for rendering
[DD 2017-07-08 20:28:49] [Renderer.cpp:112@initialize] EGL doesn't support surfaceless context
[DD 2017-07-08 20:28:49] [Renderer.cpp:248@initialize] Successfully initialized EGL
```

then start the anbox app manager

```
$ env ANBOX_LOG_LEVEL=debug anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
[DD 2017-07-08 20:32:19] [launch.cpp:180@operator()] Android hasn't fully booted yet. Waiting a bit ..
```

**Note that if I start anbox this way, I have no window at all opening**, however, if I don't start the session-manager and let anbox launch do it, then I have a window.

Eventually, `anbox launch` fails with this error message
```
[WW 2017-07-07 11:28:40] [launch.cpp:194@operator()] Stopped waiting as we've already waited for too long. Something
[WW 2017-07-07 11:28:40] [launch.cpp:195@operator()] is wrong with your setup or the container has failed to boot.
[WW 2017-07-07 11:28:40] [launch.cpp:196@operator()] If you think you found a bug please don't hesitate to file on
[WW 2017-07-07 11:28:40] [launch.cpp:197@operator()] at https://github.com/anbox/anbox/issues/new
```

**Few additionnal notes**

- I have not set up networking at all.
- The android image comes from [here](https://build.anbox.io/android-images/2017/04/12/android_1_amd64.img)
- [Here](https://pastebin.com/n2HvVcgQ) is the full container.log
