### ISSUE TITLE
Anbox can not run

### ISSUE THREAD

**Issue by MonikaKoutna** [anbox/anbox#376]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
[version: 3
snap-revision: 44
os:
  name: Linux Mint
  version: 18.2 (Sonya)
  snap-based: true
kernel:
  version: Linux version 4.8.0-53-generic (buildd@lgw01-56) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_swap_region
      - EGL_NOK_texture_from_pixmap
      - EGL_NV_post_sub_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
]
```

**Please describe your problem:**
Computer opens the windows witch the android logo. Windows close in five minutes.

**What were you expecting?:**
I was expecting, that it will run

**Additional info:**
![snimek obrazovky porizeny 2017-07-20 17-50-37](https://user-images.githubusercontent.com/30322865/28460913-89a2f41e-6e14-11e7-8c7a-17d7357a3d98.png)

**Comment by tuxutku** [comment]
#370 is my issue, this issue is similar with my issue but developer is not responded to me for days, now i am trying to disable apparmor and test but i don't know  how to do it.

**Comment by morphis** [comment]
> #370 is my issue, this issue is similar with my issue but developer is not responded to me for days, now i am trying to disable apparmor and test but i don't know how to do it.

Please forgive me but this is still a personal side project so responding to all incoming requests takes a bit. Disabling AppArmor just for getting Anbox to work sounds a bit crazy. I wouldn't give up any security on my system just for that :-) However having AppArmor in your system is not the problem. We're running AppArmor in complaining mode so no rule is enforced just reported.

**Comment by tuxutku** [comment]
i wish i could helped more, i realy want this project to succeed

**Comment by hiseni** [comment]
Same here :cry: 
Keep getting
```
[EE 2017-07-25 04:18:43] [container_manager.cpp:98@operator()]
        boost::filesystem::create_directory: No such file or directory
```
from ```anbox container-manager```

**container_manager.cpp:98** seems like a reasonable start point to investigate :mag:

**Comment by morphis** [comment]
@hiseni If you're about to start the container-manager manually you're already doing something wrong. If you use the snap version it's start by a systemd unit. With this it's unrelated to the actual bug report here.

**Comment by morphis** [comment]
@tuxutku Can you attach the output of either `adb shell logcat -d` or the file `/var/snap/anbox/common/data/system.log` if present?

**Comment by tuxutku** [comment]
[installition_log.txt](https://github.com/anbox/anbox/files/1183484/installition_log.txt)
[logcat.txt](https://github.com/anbox/anbox/files/1183485/logcat.txt)
[system.log.txt](https://github.com/anbox/anbox/files/1183486/system.log.txt)

its working again

utku@utku-Satellite-C655:~$ ANBOX_LOG_LEVEL=debug anbox session-manager
[DD 2017-07-28 15:10:12] [gl_renderer_server.cpp:82@GLRendererServer] Using GLES-to-GL translator for rendering
[DD 2017-07-28 15:10:12] [Renderer.cpp:112@initialize] EGL doesn't support surfaceless context
[DD 2017-07-28 15:10:12] [Renderer.cpp:248@initialize] Successfully initialized EGL
[DD 2017-07-28 15:10:52] [session_manager.cpp:228@operator()] Android successfully booted

and started from dektop entry works fine
can install apks and applications work fine

**Comment by napoli1890** [comment]
as @tuxutku says, running session-manager with `ANBOX_LOG_LEVEL=debug` worked for me.

**Comment by yougane** [comment]
I tried to run Anbox on Archlinux, Ubuntu 17.04, Ubuntu 16.04 and elementary OS 0.4.1 and I had the same issue on all of them.
Anbox gets stuck at the splash screen for some minutes and then the window closes leaving the session manager running in the background.
When I run the session manager in the single window mode width `snap run anbox session-manager --rootfs=android-rootfs --single-window --window-size=360,640` I get a black screen and Android doesn't boot.

This is the only file I have in /var/snap/anbox/common/data after running the session manager:
`youssef@yougane:~$ cd /var/snap/anbox/common/data
youssef@yougane:/var/snap/anbox/common/data$ find .
.
./misc
./misc/ethernet
./misc/ethernet/ipconfig.txt
`

This is what I get from dmesg (no sign of the Android booting process):
`[ 1273.163079] audit: type=1400 audit(1503314240.467:651): apparmor="ALLOWED" operation="open" profile="snap.anbox.anbox" name="/proc/3715/cgroup" pid=3715 comm="anbox" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
[ 1273.163126] audit: type=1400 audit(1503314240.467:652): apparmor="ALLOWED" operation="open" profile="snap.anbox.anbox" name="/proc/3715/mountinfo" pid=3715 comm="anbox" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
[ 1273.163127] audit: type=1400 audit(1503314240.467:653): apparmor="ALLOWED" operation="open" profile="snap.anbox.anbox" name="/proc/3715/cgroup" pid=3715 comm="anbox" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
[ 1273.164616] audit: type=1400 audit(1503314240.471:654): apparmor="ALLOWED" operation="connect" profile="snap.anbox.anbox" name="/run/anbox-container.socket" pid=3715 comm="anbox" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=0
[ 1273.164938] audit: type=1400 audit(1503314240.471:655): apparmor="ALLOWED" operation="connect" profile="snap.anbox.anbox" pid=3715 comm="anbox" family="unix" sock_type="stream" protocol=0 requested_mask="send receive connect" denied_mask="send connect" addr=none peer_addr="@/tmp/.X11-unix/X0" peer="unconfined"
[ 1273.165006] audit: type=1400 audit(1503314240.471:656): apparmor="ALLOWED" operation="open" profile="snap.anbox.anbox" name="/home/youssef/.Xauthority" pid=3715 comm="anbox" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
[ 1273.165117] audit: type=1400 audit(1503314240.471:657): apparmor="ALLOWED" operation="file_perm" profile="snap.anbox.anbox" pid=3715 comm="anbox" family="unix" sock_type="stream" protocol=0 requested_mask="send receive" denied_mask="send" addr=none peer_addr="@/tmp/.X11-unix/X0" peer="unconfined"
[ 1273.165119] audit: type=1400 audit(1503314240.471:658): apparmor="ALLOWED" operation="file_perm" profile="snap.anbox.anbox" pid=3715 comm="anbox" family="unix" sock_type="stream" protocol=0 requested_mask="send receive" denied_mask="send" addr=none peer_addr="@/tmp/.X11-unix/X0" peer="unconfined"
[ 1273.166101] audit: type=1400 audit(1503314240.471:659): apparmor="ALLOWED" operation="connect" profile="snap.anbox.anbox" pid=3715 comm="anbox" family="unix" sock_type="stream" protocol=0 requested_mask="send receive connect" denied_mask="send connect" addr=none peer_addr="@/tmp/.X11-unix/X0" peer="unconfined"
[ 1273.166129] audit: type=1400 audit(1503314240.471:660): apparmor="ALLOWED" operation="open" profile="snap.anbox.anbox" name="/home/youssef/.Xauthority" pid=3715 comm="anbox" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
[ 1274.114493] anbox0: port 1(vethL3K15L) entered blocking state
[ 1274.114496] anbox0: port 1(vethL3K15L) entered disabled state
[ 1274.114725] device vethL3K15L entered promiscuous mode
[ 1274.115179] IPv6: ADDRCONF(NETDEV_UP): vethL3K15L: link is not ready
[ 1274.166078] eth0: renamed from vethHN0714
[ 1274.184171] IPv6: ADDRCONF(NETDEV_CHANGE): vethL3K15L: link becomes ready
[ 1274.184265] anbox0: port 1(vethL3K15L) entered blocking state
[ 1274.184268] anbox0: port 1(vethL3K15L) entered forwarding state
[ 1274.517342] anbox0: port 1(vethL3K15L) entered disabled state
[ 1274.519089] device vethL3K15L left promiscuous mode
[ 1274.519097] anbox0: port 1(vethL3K15L) entered disabled state
`

My system info:
`version: 3
snap-revision: 52
os:
  name: elementary OS
  version: 0.4.1 Loki
  snap-based: true
kernel:
  version: Linux version 4.10.0-32-generic (buildd@lcy01-01) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 17.0.7
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
`

**Comment by yougane** [comment]
I tried to run Anbox on Archlinux, Ubuntu 17.04, Ubuntu 16.04 and elementary OS 0.4.1 and I had the same issue on all of them.
Anbox gets stuck at the splash screen for some minutes and then the window closes leaving the session manager running in the background.
When I run the session manager in the single window mode width `snap run anbox session-manager --rootfs=android-rootfs --single-window --window-size=360,640` I get a black screen and Android doesn't boot.

This is the only file I have in /var/snap/anbox/common/data after running the session manager:
```
youssef@yougane:~$ cd /var/snap/anbox/common/data
youssef@yougane:/var/snap/anbox/common/data$ find .
.
./misc
./misc/ethernet
./misc/ethernet/ipconfig.txt
```

This is what I get from dmesg (no sign of the Android booting process):
```
[ 1273.163079] audit: type=1400 audit(1503314240.467:651): apparmor="ALLOWED" operation="open" profile="snap.anbox.anbox" name="/proc/3715/cgroup" pid=3715 comm="anbox" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
[ 1273.163126] audit: type=1400 audit(1503314240.467:652): apparmor="ALLOWED" operation="open" profile="snap.anbox.anbox" name="/proc/3715/mountinfo" pid=3715 comm="anbox" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
[ 1273.163127] audit: type=1400 audit(1503314240.467:653): apparmor="ALLOWED" operation="open" profile="snap.anbox.anbox" name="/proc/3715/cgroup" pid=3715 comm="anbox" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
[ 1273.164616] audit: type=1400 audit(1503314240.471:654): apparmor="ALLOWED" operation="connect" profile="snap.anbox.anbox" name="/run/anbox-container.socket" pid=3715 comm="anbox" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=0
[ 1273.164938] audit: type=1400 audit(1503314240.471:655): apparmor="ALLOWED" operation="connect" profile="snap.anbox.anbox" pid=3715 comm="anbox" family="unix" sock_type="stream" protocol=0 requested_mask="send receive connect" denied_mask="send connect" addr=none peer_addr="@/tmp/.X11-unix/X0" peer="unconfined"
[ 1273.165006] audit: type=1400 audit(1503314240.471:656): apparmor="ALLOWED" operation="open" profile="snap.anbox.anbox" name="/home/youssef/.Xauthority" pid=3715 comm="anbox" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
[ 1273.165117] audit: type=1400 audit(1503314240.471:657): apparmor="ALLOWED" operation="file_perm" profile="snap.anbox.anbox" pid=3715 comm="anbox" family="unix" sock_type="stream" protocol=0 requested_mask="send receive" denied_mask="send" addr=none peer_addr="@/tmp/.X11-unix/X0" peer="unconfined"
[ 1273.165119] audit: type=1400 audit(1503314240.471:658): apparmor="ALLOWED" operation="file_perm" profile="snap.anbox.anbox" pid=3715 comm="anbox" family="unix" sock_type="stream" protocol=0 requested_mask="send receive" denied_mask="send" addr=none peer_addr="@/tmp/.X11-unix/X0" peer="unconfined"
[ 1273.166101] audit: type=1400 audit(1503314240.471:659): apparmor="ALLOWED" operation="connect" profile="snap.anbox.anbox" pid=3715 comm="anbox" family="unix" sock_type="stream" protocol=0 requested_mask="send receive connect" denied_mask="send connect" addr=none peer_addr="@/tmp/.X11-unix/X0" peer="unconfined"
[ 1273.166129] audit: type=1400 audit(1503314240.471:660): apparmor="ALLOWED" operation="open" profile="snap.anbox.anbox" name="/home/youssef/.Xauthority" pid=3715 comm="anbox" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
[ 1274.114493] anbox0: port 1(vethL3K15L) entered blocking state
[ 1274.114496] anbox0: port 1(vethL3K15L) entered disabled state
[ 1274.114725] device vethL3K15L entered promiscuous mode
[ 1274.115179] IPv6: ADDRCONF(NETDEV_UP): vethL3K15L: link is not ready
[ 1274.166078] eth0: renamed from vethHN0714
[ 1274.184171] IPv6: ADDRCONF(NETDEV_CHANGE): vethL3K15L: link becomes ready
[ 1274.184265] anbox0: port 1(vethL3K15L) entered blocking state
[ 1274.184268] anbox0: port 1(vethL3K15L) entered forwarding state
[ 1274.517342] anbox0: port 1(vethL3K15L) entered disabled state
[ 1274.519089] device vethL3K15L left promiscuous mode
[ 1274.519097] anbox0: port 1(vethL3K15L) entered disabled state
```

My system info:
```
version: 3
snap-revision: 52
os:
  name: elementary OS
  version: 0.4.1 Loki
  snap-based: true
kernel:
  version: Linux version 4.10.0-32-generic (buildd@lcy01-01) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 17.0.7
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
```
