### ISSUE TITLE
Can't install APKs; getting error "Could not access package manager. Is the system running?"

### ISSUE THREAD

**Issue by navedcoded** [anbox/anbox#380]
Make sure you are running the latest version of Anbox before reporting an issue.
**Yes.**

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

**I saw some slightly similar ones, but not precisely. I'm putting details below**

** Please paste the result of `anbox system-info` below:**
```
version: 3
snap-revision: 44
os:
  name: KDE neon
  version: 5.10
  snap-based: true
kernel:
  version: Linux version 4.10.0-27-generic (buildd@lgw01-60) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #30~16.04.2-Ubuntu SMP Thu Jun 29 16:07:46 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp

```

**Please describe your problem:**

Running anbox from the launcher opens a window with the "Starting..." text and the logo. After about 5 minutes the window disappears disappears, but to verify, I ran `anbox session-manager`, and got `[EE 2017-07-26 15:38:09] [daemon.cpp:58@Run] bind: Address already in use`. So anbox is running. `adb devices` returns:

    List of devices attached 
    emulator-6663   device
 
But the problem is when I try to install using adb. I ran `adb install file.apk`, (obviously with a proper apk) and got back:

    22557 KB/s (2721726 bytes in 0.117s)
    Error: Could not access the Package Manager.  Is the system running?

Googling got me advice for other emulators, and they said to wait a few minutes and then "unlock" the emulated android device. 

**What were you expecting?:**

* An anbox GUI window: Is there supposed to be an anbox GUI at all? Because the window closed after starting the session-manager.

* I was also expecting to be able to install apps with adb, let alone run them, but I explained above what is happening instead.

**Additional info:**

I am running KDE Neon, based off of Ubuntu 16.04
