### ISSUE TITLE
Client is not authorized to connect to Server

### ISSUE THREAD

**Issue by licx** [anbox/anbox#394]
```
version: 3
snap-revision: 46
os:
  name: Ubuntu
  version: 14.04.5 LTS, Trusty Tahr
  snap-based: true
kernel:
  version: Linux version 4.4.0-87-generic (buildd@lcy01-02) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) ) #110~14.04.1-Ubuntu SMP Tue Jul 18 14:51:32 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
```

**Please describe your problem:**
When running `anbox session-manager` I get a message `client is not authorized to connect to Server ` and nothing happens.

**What were you expecting?:**
I am expecting the Anbox to start.

**Additional info:**
I'm using to my Linux box through VNC
