### ISSUE TITLE
Open Anbox can not run

### ISSUE THREAD

**Issue by iHad169** [anbox/anbox#40]
Make sure you are running the latest version of Anbox before reporting an issue.

**Anbox release (`anbox 0.1.0`) and system info (`
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.8.0-46-generic (buildd@lcy01-15) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #49~16.04.1-Ubuntu SMP Fri Mar 31 14:51:03 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
`):**

**Description of the problem:**
On install is done in after. Reboot the computer. I immediate open Anbox. However, the Anbox not run. Not any windown show.

https://www.youtube.com/watch?v=ylnp-NimAnE

**Expected:**

**Additional info:**

**Comment by kimusan** [comment]
I have just installed and experience the same. looks like the android image is not installed. 
try to run 
anbox container-manager
this shows that /var/lib/anbox/android.img is missing

**Comment by mimfgg** [comment]
same here

**Comment by WassiliaPL** [comment]
same here, it's just weird

**Comment by DimensionsGaming** [comment]
I get the same thing

**Comment by MrObvious** [comment]
Add me to the list.

**Comment by nergdron** [comment]
Me too. Also, on my system (ubu 16.10, fresh install of anbox using anbox-installer snap), /var/lib/anbox itself doesn't exist either.

**Comment by paulbrycki** [comment]
I was able to get it to run by running the following in terminal:
snap run anbox container-manager

Then selecting it from my Cinnamon Menu, under "other"

**Comment by aoxley** [comment]
Getting the same issue on Ubuntu 16.04 LTS.

the android.img file seems to be sitting in /snap/anbox/current

I try running the above mentioned "snap run anbox container-manager" but still get the same issue:
[container_manager.cpp:90@setup_mounts] Android image does not exist at path "/var/lib/anbox/android.img"

**Comment by DrPugsley** [comment]
Having the same issue here. I even tried copying the android.img from /snap/anbox/current to /var/lib/anbox and it still won't work.

**Comment by PhoenixGR** [comment]
I have the same problem too.

**Comment by J-Ahlers** [comment]
Same issue - copying android.img to /varlib/anbox did not make any difference whatsover for me. Regardless of chmod/chown properties set to android.img:

:~$ anbox launch
[EE 2017-04-13 07:49:15] [launch.cpp:76@operator()] Anbox session manager service isn't running!

:~$ anbox session-manager
[EE 2017-04-13 07:49:22] [Renderer.cpp:100@initialize] Failed to Initialize backend EGL display
Segmentation fault

:~$ anbox system-info
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.4.0-72-generic (buildd@lcy01-17) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

**Comment by YoranSys** [comment]
Same here,
It's seem that android.img on chroot it's on /android.img and not in /var/lib/anbox (inside the chroot).

**Comment by tosho** [comment]
Same here
```
tosho@T440:~$ anbox system-info
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.7.0-040700-generic (kernel@gloin) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1) ) #201607241632 SMP Sun Jul 24 20:34:30 UTC 2016
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_swap_region
      - EGL_NOK_texture_from_pixmap
      - EGL_NV_post_sub_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
```
``
tosho@T440:~$ anbox session-manager
[EE 2017-04-13 11:00:27] [daemon.cpp:58@Run] bind: Address already in use
``
``
tosho@T440:~$ anbox container-manager
[EE 2017-04-13 10:58:49] [container_manager.cpp:90@setup_mounts] Android image does not exist at path "/var/lib/anbox/android.img"
``
``
tosho@T440:~$ anbox launch
[WW 2017-04-13 11:02:37] [launch.cpp:115@operator()] Stop waiting as we're already waiting for too long. Something is wrong
[WW 2017-04-13 11:02:37] [launch.cpp:116@operator()] with your setup and the container may have failed to boot.
``
copying 'android.img' to "/var/lib/anbox/" didn't solve anything (the 'anbox' directory didn't even existed)

**Comment by PhoenixGR** [comment]
All right folks i managed to make it work .. i dont know why exactly but it works now.
So first i uninstalled anbox using the installer and then i reinstalled anbox after that in terminal typed anbox session-manager and then i clicked the anbox icon from the menu and now its running. I can run normaly the pre installed apps.

**Comment by tosho** [comment]
@PhoenixGR solution doesn't work for me

**Comment by PhoenixGR** [comment]
@tosho  hmm i m running on ubuntu 16.04 LTS  i really dont know why it worked with what i did so i cant say why it doesnt do the trick for you ..

**Comment by WassiliaPL** [comment]
After some reboots it just worked for me but after killing it issue is there again.

**Comment by aurium** [comment]
@PhoenixGR solution doesn't work for me

**Comment by DimensionsGaming** [comment]
@PhoenixGR Your solution isn't working for me either.

**Comment by property-live** [comment]
@PhoenixGR It worked for me. After reboot I opened a terminal
`anbox session-manager`
after that, a click on the Anbox-Icon opened the Anbox Application Manager 

Uninstalling and reinstalling anbox was not required!

I'm running Ubuntu 16.10 with an i7-4500U, no graphics card 

`$ anbox system-info
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.8.0-46-generic (buildd@lcy01-16) (gcc version 6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12) ) #49-Ubuntu SMP Fri Mar 31 13:57:14 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
`
![screenshot from 2017-04-14 14-13-06](https://cloud.githubusercontent.com/assets/5918526/25043018/ea5c590c-211c-11e7-90e4-3da2ebede398.png)

**Comment by HougeLangley** [comment]
`anbox session-manager
ERROR: ld.so: object '/lib/$LIB/liblsp.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/$LIB/liblsp.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/$LIB/liblsp.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/$LIB/liblsp.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
[EE 2017-04-14 14:12:04] [daemon.cpp:58@Run] bind: Address already in use`

**Comment by Rminsh** [comment]
when i type anbox session-manager this shows up :|
`$ anbox session-manager`
`[EE 2017-04-14 14:58:40] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to start container`
`[WW 2017-04-14 14:58:40] [session_manager.cpp:140@operator()] Lost connection to container manager, terminating.`
`Segmentation fault (core dumped)`
`

**Comment by anidotnet** [comment]
I am getting the same error too.

```bash
$anbox container-manager
[EE 2017-04-14 17:54:40] [container_manager.cpp:90@setup_mounts] Android image does not exist at path "/var/lib/anbox/android.img"
```
```bash
$anbox session-manager
[EE 2017-04-14 17:52:48] [Renderer.cpp:100@initialize] Failed to Initialize backend EGL display
[1]    32473 segmentation fault (core dumped)  anbox session-manager

```
```bash
$anbox launch 
[EE 2017-04-14 17:52:28] [launch.cpp:76@operator()] Anbox session manager service isn't running!

```

```bash
$anbox system-info
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.4.0-72-generic (buildd@lcy01-17) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

```

**Comment by Curtman** [comment]
I hit this problem as well, and found that this got things going without needing to reboot or uninstall.

```
$ sudo killall -9 anbox
$ anbox session-manager &
[2] 6087
[1]   Killed                  anbox session-manager
$ anbox container-manager --data-path=/var/snap/anbox/common/ --android-image=/snap/anbox/current/android.img
```

**Comment by hemangjoshi37a** [comment]
@Curtman 
Does it runs after trying your code??

**Comment by kirner** [comment]
same issue here on Ubuntu 16.04.2 LTS, anbox doesn't start if i try: 
anbox session-manager &
i get: EE 2017-04-17 18:32:05] [daemon.cpp:58@Run] Failed to connect to socket /run/anbox-container.socket: Connection refused

**Comment by hub2git** [comment]
Hooray! @morphis has seen this issue and has confirmed that it is a bug. With 22  participants on this thread (and an unknown number of subscribers), I'm guessing this bug affects a lot of users. Hope this bug gets quashed soon. 😀

**Comment by dani0001414** [comment]
I started the session-manager and the container-manager and later tried with the @Curtman suggested code. But when i start AnBox the "or.anbox.appmgr" window freeze immediately. :( 
I haven't any idea what's wrong.

I'm tried run from Linux Mint 18.1 Kde.

**Comment by hub2git** [comment]
Does anybody know if https://github.com/anbox/anbox/pull/152 will solve this issue of ours?

**Comment by ZatsuneNoMokou** [comment]
Maybe what's written in the #77 is linked to all this? I'm on Xubuntu 16.10 and same issue on 17.04

```
Failed to reload daemon: Process org.freedesktop.systemd1 exited with status 1
Failed to enable unit: Process org.freedesktop.systemd1 exited with status 1
```

**Comment by thomas-zaffran-gumi** [comment]
Affected by this as well. Tried @Curtman solution but it didn't work for me.

**Comment by vukasin0** [comment]
Still doesn't work - for more details I've opened https://github.com/anbox/anbox/issues/126

**Comment by lieff** [comment]
Someone tried build it from source and run without snap? To prove that it's snap nvidia issue.

**Comment by hub2git** [comment]
@lieff, huh? My computer doesn't have nvidia but I have this issue.

**Comment by ZatsuneNoMokou** [comment]
Could it be linked to this libEGL issue?
https://bugs.launchpad.net/ubuntu/+source/nvidia-graphics-drivers-375/+bug/1662860

**Comment by thomas-zaffran-gumi** [comment]
@lieff I tried building from source but I'm getting this error:

**Comment by lieff** [comment]
Looks like cmake gtest/gmock link issue.

**Comment by thomas-zaffran-gumi** [comment]
yes, tried rebuilding gtest from googletest source but that didn't seem to work...

**Comment by morphis** [comment]
https://github.com/anbox/anbox/pull/195 should help problem regarding gtest

**Comment by thomas-zaffran-gumi** [comment]
So I built from source and now I'm getting this error https://github.com/anbox/anbox/issues/202. I installed anbox-modules-dkms from the ppa but it doesn't look like it fixed it.

**Comment by ZatsuneNoMokou** [comment]
I made it running
1/  `sudo apt install anbox-modules-dkms` and then I restarted
2/  `sudo snap install --classic anbox-installer && anbox-installer`  and then I restarted again
3/ `anbox session-manager` left running in a terminal
4/ Opened anbox, system / x11 dunno froze, I dirty restarted (the RIESUB way)
Now when I open the anbox session-manager in a terminal, it work

**Comment by thomas-zaffran-gumi** [comment]
@ZatsuneNoMokou yeah that doesn't work for me here...

**Comment by JoseBarakat** [comment]
@ZatsuneNoMokou 

``~$ anbox session-manager``
``[EE 2017-06-02 19:51:06] [session_manager.cpp:135@operator()] Failed to start as either binder or ashmem kernel drivers are not loaded``

**Comment by girst** [comment]
This can be solved by installing the drivers. On Ubuntu 16.04: 

    sudo apt install --reinstall anbox-modules-dkms

you need to `--reinstall` this package after a kernel update. 

Then you can try to load them with `sudo modprobe binder ashmem`, or if that fails, 
    sudo insmod /lib/modules/$(uname -r)/updates/dkms/{ashmem,binder}_linux.ko

**Comment by JoseBarakat** [comment]
Hi @girst, I followed your suggestion without luck (at least `ashmem` is now installed):

```
jose@jose-Lenovo-G400s:~$ sudo apt install --reinstall anbox-modules-dkms
[sudo] password for jose: 
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
0 actualizados, 0 nuevos se instalarán, 1 reinstalados, 0 para eliminar y 8 no actualizados.
Se necesita descargar 34,0 kB de archivos.
Se utilizarán 0 B de espacio de disco adicional después de esta operación.
Des:1 http://ppa.launchpad.net/morphis/anbox-support/ubuntu zesty/main amd64 anbox-modules-dkms all 6~zesty1 [34,0 kB]
Descargados 34,0 kB en 0s (59,9 kB/s)       
(Leyendo la base de datos ... 493122 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar .../anbox-modules-dkms_6~zesty1_all.deb ...
Desempaquetando anbox-modules-dkms (6~zesty1) sobre (6~zesty1) ...
Configurando anbox-modules-dkms (6~zesty1) ...
Removing old anbox-modules-ashmem-6~zesty1 DKMS files...

-------- Uninstall Beginning --------
Module:  anbox-modules-ashmem
Version: 6~zesty1
Kernel:  4.10.0-20-generic (x86_64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

ashmem_linux.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.10.0-20-generic/
rmdir: fallo al borrar '': No existe el archivo o el directorio
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod...

DKMS: uninstall completed.

------------------------------
Deleting module version: 6~zesty1
completely from the DKMS tree.
------------------------------
Done.
Loading new anbox-modules-ashmem-6~zesty1 DKMS files...
Building for 4.10.0-22-generic
Building for architecture x86_64
Building initial module for 4.10.0-22-generic
Done.

ashmem_linux:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.10.0-22-generic/updates/dkms/

depmod......

DKMS: install completed.
Removing old anbox-modules-binder-6~zesty1 DKMS files...

-------- Uninstall Beginning --------
Module:  anbox-modules-binder
Version: 6~zesty1
Kernel:  4.10.0-20-generic (x86_64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

binder_linux.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.10.0-20-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod...

DKMS: uninstall completed.

------------------------------
Deleting module version: 6~zesty1
completely from the DKMS tree.
------------------------------
Done.
Loading new anbox-modules-binder-6~zesty1 DKMS files...
Building for 4.10.0-22-generic
Building for architecture x86_64
Building initial module for 4.10.0-22-generic
Done.

binder_linux:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.10.0-22-generic/updates/dkms/

depmod.....

DKMS: install completed.
```
```
jose@jose-Lenovo-G400s:~$ sudo modprobe binder ashmem
modprobe: FATAL: Module binder not found in directory /lib/modules/4.10.0-22-generic
```
``insmod`` command without output.
```
jose@jose-Lenovo-G400s:~$ sudo insmod /lib/modules/$(uname -r)/updates/dkms/{ashmem,binder}_linux.ko
```
Then...
```
jose@jose-Lenovo-G400s:~$ anbox session-manager
[EE 2017-06-05 02:53:14] [session_manager.cpp:135@operator()] Failed to start as either binder or ashmem kernel drivers are not loaded
```

```
jose@jose-Lenovo-G400s:~$ anbox system-info
version: 2
snap-revision: 25
os:
  name: Ubuntu
  version: 17.04 (Zesty Zapus)
  snap-based: true
kernel:
  version: Linux version 4.10.0-22-generic (buildd@lcy01-08) (gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) ) #24-Ubuntu SMP Mon May 22 17:43:20 UTC 2017
  binder: false
  ashmem: true
```
Leaving out the EGL extensions part.

**Comment by girst** [comment]
whoops, I made a wrong assumption about `insmod`. (apparently, it won't load multiple modules at once)

```
sudo insmod /lib/modules/$(uname -r)/updates/dkms/ashmem_linux.ko
sudo insmod /lib/modules/$(uname -r)/updates/dkms/binder_linux.ko
```

**Comment by JoseBarakat** [comment]
YES! Now it launches!
Thanks @girst 

```
jose@jose-Lenovo-G400s:~$ sudo insmod /lib/modules/$(uname -r)/updates/dkms/ashmem_linux.ko
[sudo] password for jose: 
insmod: ERROR: could not insert module /lib/modules/4.10.0-22-generic/updates/dkms/ashmem_linux.ko: File exists
jose@jose-Lenovo-G400s:~$ sudo insmod /lib/modules/$(uname -r)/updates/dkms/binder_linux.ko
jose@jose-Lenovo-G400s:~$ anbox session-manager
```
</br>
First, I left "anbox  session-manager" terminal session open and launched anbox from Ubuntu's 17.04 system launcher

</br></br>

![captura de pantalla de 2017-06-06 10-24-26](https://user-images.githubusercontent.com/15618933/26837482-23857e84-4aa3-11e7-87a3-53a24694ccfa.png)

I'll try it out and leave my first time impressions. 

My ``anbox system-info`` that may be useful:

```
jose@jose-Lenovo-G400s:~$ anbox system-info
version: 2
snap-revision: 25
os:
  name: Ubuntu
  version: 17.04 (Zesty Zapus)
  snap-based: true
kernel:
  version: Linux version 4.10.0-22-generic (buildd@lcy01-08) (gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) ) #24-Ubuntu SMP Mon May 22 17:43:20 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
```
