### ISSUE TITLE
Support for Latest Stable version is missing

### ISSUE THREAD

**Issue by JoseBarakat** [anbox/anbox#401]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
N/A (It won't install)
```

**Please describe your problem:**
Anbox won't install after upgrading to 4.12.5 kernel version
```
jose@jose-Lenovo-G400s:~$ anbox-installer
Anbox (Android in a Box) - Installer


IMPORTANT: THIS IS ALPHA LEVEL SOFTWARE. EXPECT INSTABILITY AND
           BUGS !!!!!

IMPORTANT: ALSO PLEASE BE AWARE THAT WE DON'T PROVIDE FULL
           CONFINEMENT FOR THE SNAP YET !!!!


PLEASE NOTE: This script will require root access on your system
to install all necessary things. It will prompt you to enter your
password when required.



What do you want to do?

 1. Install Anbox
 2. Uninstall Anbox

Please enter your choice [1-2]: 
1


This is the installer for the anbox runtime environment. It will
install certain things on your system to ensure all requirements
are available for anbox to work correctly.

In summary we will install the following things:

 * Add the anbox-support ppa ppa:morphis/anbox-support to the
   host system
 * Install the anbox-modules-dkms deb package from the ppa
   which will add kernel modules for ashmem and binder which are
   required for the Android container to work.
 * Configure binder and ashmem kernel modules to be loaded
   automatically on boot.
 * Install the anbox-common package from the ppa which will
   - Add an upstart job for the current user jose which will
     start the anbox runtime on login.
   - Add a X11 session configuration file to allow the system
     application launcher (Unity7, Gnome Shell, ..) to find
     available Android applications.

Please type 'I AGREE' followed by pressing ENTER to continue
or type anything else to abort:
I AGREE


Starting installation process ...

+ sudo add-apt-repository -y ppa:morphis/anbox-support
gpg: keybox '/tmp/tmp7kgr_o5o/pubring.gpg' created
gpg: /tmp/tmp7kgr_o5o/trustdb.gpg: se ha creado base de datos de confianza
gpg: clave 21C6044A875B67B7: clave pública "Launchpad PPA for morphis" importada
gpg: Cantidad total procesada: 1
gpg:               importadas: 1
OK
+ sudo apt update
Des:1 http://co.archive.ubuntu.com/ubuntu zesty InRelease [243 kB]
Obj:2 http://repo.steampowered.com/steam precise InRelease                                                                                    
Des:3 http://security.ubuntu.com/ubuntu zesty-security InRelease [89,2 kB]                                                                    
Obj:4 http://archive.ubuntu.com/ubuntu zesty InRelease                                                                                        
Obj:5 http://archive.canonical.com/ubuntu zesty InRelease                                                                                     
Obj:6 http://ppa.launchpad.net/daveg/attract/ubuntu yakkety InRelease                                                                         
Obj:7 http://repository.spotify.com stable InRelease                                                                                          
Obj:8 http://packages.microsoft.com/repos/vscode stable InRelease                                                                             
Obj:9 http://ppa.launchpad.net/docky-core/stable/ubuntu yakkety InRelease                                                                     
Obj:10 https://deb.nodesource.com/node_7.x zesty InRelease                                                                
Obj:11 https://dl.yarnpkg.com/debian stable InRelease                                                                     
Obj:12 http://ppa.launchpad.net/emulationstation/ppa/ubuntu yakkety InRelease                                      
Des:13 http://security.ubuntu.com/ubuntu zesty-security/universe Sources [15,0 kB]                                                            
Obj:14 https://deb.opera.com/opera-beta stable InRelease                                                                                      
Obj:15 https://dl.winehq.org/wine-builds/ubuntu zesty InRelease                                                                               
Obj:16 http://ppa.launchpad.net/lazka/dumpingplace/ubuntu zesty InRelease                                                                     
Des:17 http://security.ubuntu.com/ubuntu zesty-security/universe i386 Packages [57,8 kB]                                                      
Obj:18 http://ppa.launchpad.net/libretro/testing/ubuntu zesty InRelease                                                                       
Des:19 http://security.ubuntu.com/ubuntu zesty-security/universe amd64 Packages [57,6 kB]                                                     
Obj:20 http://ppa.launchpad.net/me-davidsansome/clementine-dev/ubuntu yakkety InRelease                                                       
Des:21 http://security.ubuntu.com/ubuntu zesty-security/universe Translation-en [37,4 kB]                                                     
Obj:22 http://ppa.launchpad.net/morphis/anbox-support/ubuntu zesty InRelease                                                                  
Obj:23 http://ppa.launchpad.net/ppsspp/testing/ubuntu zesty InRelease                                                                         
Obj:24 http://ppa.launchpad.net/team-xbmc/unstable/ubuntu zesty InRelease                                                                     
Obj:25 http://ppa.launchpad.net/webupd8team/java/ubuntu zesty InRelease                                                                       
Obj:26 http://ppa.launchpad.net/wine/wine-builds/ubuntu zesty InRelease                                                                       
Obj:27 http://ppa.launchpad.net/zeal-developers/ppa/ubuntu yakkety InRelease                                                                  
Des:28 http://co.archive.ubuntu.com/ubuntu zesty-updates InRelease [89,2 kB]                                                                  
Obj:29 http://co.archive.ubuntu.com/ubuntu zesty-backports InRelease                                                                          
Des:30 http://co.archive.ubuntu.com/ubuntu zesty-proposed InRelease [240 kB]                                                                  
Descargados 830 kB en 20s (40,9 kB/s)                                                                                                         
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
Todos los paquetes están actualizados.
N: Omitiendo el uso del fichero configurado «main/binary-i386/Packages» ya que el repositorio «http://packages.microsoft.com/repos/vscode stable InRelease» no admite la arquitectura «i386»
+ sudo apt install -y anbox-common
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
anbox-common ya está en su versión más reciente (8~zesty1).
Los paquetes indicados a continuación se instalaron de forma automática y ya no son necesarios.
  linux-headers-4.10.0-29 linux-headers-4.10.0-29-generic linux-image-4.10.0-29-generic linux-image-extra-4.10.0-29-generic
  linux-tools-4.10.0-29 linux-tools-4.10.0-29-generic
Utilice «sudo apt autoremove» para eliminarlos.
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 0 no actualizados.
+ '[' -c /dev/binder ']'
+ sudo apt install -y linux-headers-generic anbox-modules-dkms
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
linux-headers-generic ya está en su versión más reciente (4.10.0.30.31).
anbox-modules-dkms ya está en su versión más reciente (8~zesty1).
Los paquetes indicados a continuación se instalaron de forma automática y ya no son necesarios.
  linux-headers-4.10.0-29 linux-headers-4.10.0-29-generic linux-image-4.10.0-29-generic linux-image-extra-4.10.0-29-generic
  linux-tools-4.10.0-29 linux-tools-4.10.0-29-generic
Utilice «sudo apt autoremove» para eliminarlos.
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 0 no actualizados.
+ sudo modprobe binder_linux
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/4.12.5-041205-generic
+ cleanup
+ local err=1
+ trap - EXIT
+ echo 'ERROR: Installation failed. Removing all parts of Anbox again.'
ERROR: Installation failed. Removing all parts of Anbox again.
+ uninstall
+ set -x
+ sudo snap remove anbox
snap "anbox" is not installed
+ '[' -e /etc/apt/sources.list.d/morphis-ubuntu-anbox-support-xenial.list ']'
+ set +x
```
```
jose@jose-Lenovo-G400s:~$ sudo apt install --reinstall anbox-modules-dkms
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
Los paquetes indicados a continuación se instalaron de forma automática y ya no son necesarios.
  linux-headers-4.10.0-29 linux-headers-4.10.0-29-generic linux-image-4.10.0-29-generic linux-image-extra-4.10.0-29-generic
  linux-tools-4.10.0-29 linux-tools-4.10.0-29-generic
Utilice «sudo apt autoremove» para eliminarlos.
0 actualizados, 0 nuevos se instalarán, 1 reinstalados, 0 para eliminar y 0 no actualizados.
Se necesita descargar 34,1 kB de archivos.
Se utilizarán 0 B de espacio de disco adicional después de esta operación.
Des:1 http://ppa.launchpad.net/morphis/anbox-support/ubuntu zesty/main amd64 anbox-modules-dkms all 8~zesty1 [34,1 kB]
Descargados 34,1 kB en 1s (19,7 kB/s)       
(Leyendo la base de datos ... 562755 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar .../anbox-modules-dkms_8~zesty1_all.deb ...
Desempaquetando anbox-modules-dkms (8~zesty1) sobre (8~zesty1) ...
Configurando anbox-modules-dkms (8~zesty1) ...
Removing old anbox-modules-ashmem-8~zesty1 DKMS files...

-------- Uninstall Beginning --------
Module:  anbox-modules-ashmem
Version: 8~zesty1
Kernel:  4.10.0-28-generic (x86_64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

ashmem_linux.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.10.0-28-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod...

DKMS: uninstall completed.

------------------------------
Deleting module version: 8~zesty1
completely from the DKMS tree.
------------------------------
Done.
Loading new anbox-modules-ashmem-8~zesty1 DKMS files...
Building for 4.12.5-041205-generic
Building for architecture x86_64
Building initial module for 4.12.5-041205-generic
Done.

ashmem_linux:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.12.5-041205-generic/updates/dkms/

depmod......

DKMS: install completed.
Removing old anbox-modules-binder-8~zesty1 DKMS files...

-------- Uninstall Beginning --------
Module:  anbox-modules-binder
Version: 8~zesty1
Kernel:  4.10.0-28-generic (x86_64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

binder_linux.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.10.0-28-generic/
rmdir: fallo al borrar '': No existe el archivo o el directorio
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod...

DKMS: uninstall completed.

------------------------------
Deleting module version: 8~zesty1
completely from the DKMS tree.
------------------------------
Done.
Loading new anbox-modules-binder-8~zesty1 DKMS files...
Building for 4.12.5-041205-generic
Building for architecture x86_64
Building initial module for 4.12.5-041205-generic
ERROR (dkms apport): kernel package linux-headers-4.12.5-041205-generic is not supported
Error! Bad return status for module build on kernel: 4.12.5-041205-generic (x86_64)
Consult /var/lib/dkms/anbox-modules-binder/8~zesty1/build/make.log for more information.
```

**What were you expecting?:**
Succesfull installation of Anbox after upgrade to a stable kernel version

**Additional info:**
Atached file make.log (renamed to make.txt) from "/var/lib/dkms/anbox-modules-binder/8~zesty1/build/make.log"
[make.txt](https://github.com/anbox/anbox/files/1205268/make.txt)

Thanks!

**Comment by morphis** [comment]
We've landed a fix for this with https://github.com/anbox/anbox/pull/397 and I didn't uploaded a new debian package to the ppa yet. Will do that most likely tomorrow.

**Comment by JoseBarakat** [comment]
Thanks for adding support for Ubuntu kernel version 4.12.5-041205-generic.

Although everything seems OK, Anbox won't start. Is there a way I can post a verbose log of Anbox trying to start? It loads on the Unity dock for a few seconds, but it doesn't start.

```
jose@jose-Lenovo-G400s:~$ anbox system-info
version: 3
snap-revision: 50
os:
  name: Ubuntu
  version: 17.04 (Zesty Zapus)
  snap-based: true
kernel:
  version: Linux version 4.12.5-041205-generic (kernel@tangerine) (gcc version 6.3.0 20170618 (Ubuntu 6.3.0-19ubuntu1) ) #201708061334 SMP Sun Aug 6 17:35:26 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 17.0.7
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp

```
