### ISSUE TITLE
Can't get Anbox to run, not opening, no device to install apk

### ISSUE THREAD

**Issue by dzek69** [anbox/anbox#413]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
dzek@dzek-Mint17 ~ $ anbox system-info
version: 3
snap-revision: 50
os:
  name: Linux Mint
  version: 18.2 (Sonya)
  snap-based: true
kernel:
  version: Linux version 4.10.0-30-generic (buildd@lcy01-17) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #34~16.04.1-Ubuntu SMP Wed Aug 2 02:13:56 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

```

**Please describe your problem:**
I can't run Anbox from system menu.
I can't install apk app via adb.

**What were you expecting?:**
Anbox should work, I should be able to install and use the apps.

**Additional info:**
Steps taken:
Notice, I had real device connected with USB Debugging during these steps, until mentioned.

1) installed snapd - no issues here
2) `anbox-installer` wasn't on system PATH, even in new terminal, so I went with /snap/bin/anbox-installer - no issues
3) restart - no issues
4) tried to run Anbox from system menu - it showed white box and disappeared instantly
5) tried to run `adb install ./music.apk` to install downloaded apk, I was prompted to confirm on device
6) realized I've got real device connected. I disconnected it and restarted terminal.
7) got `device not found` error since then
```
dzek@dzek-Mint17 ~/Pulpit $ adb install ./music.apk
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
error: device not found
- waiting for device -
```
8) tried adding symlink, as suggested in another issue: `sudo ln -s /snap/bin/anbox /usr/bin/anbox`
9) still no devices:
```
dzek@dzek-Mint17 ~/Pulpit $ adb devices
List of devices attached 
```
10) found another command to un in another issue:
```
dzek@dzek-Mint17 ~/Pulpit $ anbox session-manager&
[1] 4809
dzek@dzek-Mint17 ~/Pulpit $ [EE 2017-08-19 13:04:28] [Renderer.cpp:99@initialize] Failed to Initialize backend EGL display
```
I kept the process open
11) And tried one more
```
dzek@dzek-Mint17 ~ $ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity&
[1] 5078
dzek@dzek-Mint17 ~ $ [WW 2017-08-19 13:04:42] [launch.cpp:123@operator()] Anbox session manager service isn't running, trying to start it.
[EE 2017-08-19 13:04:42] [daemon.cpp:58@Run] Could not create renderer
```
12) When trying to call `session-manager` again after closing previous process I've got this:
```
anbox session-manager
[EE 2017-08-19 13:07:17] [Renderer.cpp:99@initialize] Failed to Initialize backend EGL display
Naruszenie ochrony pamięci
```

`Naruszenie ochrony pamięci` means `Memory protection violation`

Any ideas what to do to make it work?
