### ISSUE TITLE
The anbox container can not connect to the network

### ISSUE THREAD

**Issue by gmg137** [anbox/anbox#443]
anbox system-info:
```
version: local-/bin/sh: git: command not found
os:
  name: openSUSE Tumbleweed
  version: 
  snap-based: false
kernel:
  version: Linux version 4.12.8-1-default (geeko@buildhost) (gcc version 7.1.1 20170629 [gcc-7-branch revision 249772] (SUSE Linux) ) #1 SMP PREEMPT Thu Aug 17 05:30:12 UTC 2017 (4d7933a)
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: X.Org
    vendor: OpenGL ES-CM 1.1 Mesa 17.1.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_polygon_offset_clamp
```

I use the openSUSE TumbleWeed + GNOME + 4.12.8 kernel, the installation of anbox after the application can start normally, but the anbox container can not connect to the network.

ifconfig:
```
anbox0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.250.1  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fe80::bc94:4ff:fec0:3194  prefixlen 64  scopeid 0x20<link>
        ether fe:55:1d:8f:50:72  txqueuelen 1000  (Ethernet)
        RX packets 8  bytes 544 (544.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 57  bytes 10404 (10.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.2  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::4055:8b36:96f9:9c0f  prefixlen 64  scopeid 0x20<link>
        ether 40:8d:5c:78:d2:3d  txqueuelen 1000  (Ethernet)
        RX packets 1235496  bytes 1549309366 (1.4 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 727902  bytes 58273190 (55.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 38844  bytes 444556554 (423.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 38844  bytes 444556554 (423.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethEA4JQQ: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::fc55:1dff:fe8f:5072  prefixlen 64  scopeid 0x20<link>
        ether fe:55:1d:8f:50:72  txqueuelen 1000  (Ethernet)
        RX packets 8  bytes 656 (656.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 30  bytes 5582 (5.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

adb shell ifconfig:
```
eth0      Link encap:Ethernet  HWaddr ae:3e:ec:f8:f8:6f
          inet addr:192.168.250.2  Bcast:192.168.250.255  Mask:255.255.255.0 
          inet6 addr: fe80::ac3e:ecff:fef8:f86f/64 Scope: Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:52 errors:0 dropped:0 overruns:0 frame:0 
          TX packets:13 errors:0 dropped:0 overruns:0 carrier:0 
          collisions:0 txqueuelen:1000 
          RX bytes:9317 TX bytes:1006 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0 
          inet6 addr: ::1/128 Scope: Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:12 errors:0 dropped:0 overruns:0 frame:0 
          TX packets:12 errors:0 dropped:0 overruns:0 carrier:0 
          collisions:0 txqueuelen:1000 
          RX bytes:800 TX bytes:800
```

sudo brcli show:
```
bridge name	bridge id		STP enabled	interfaces
anbox0		8000.fe551d8f5072	no		vethEA4JQQ
```

sudo systemctl status anbox-container-manager.service : 

```
● anbox-container-manager.service - Anbox container manager
   Loaded: loaded (/usr/lib/systemd/system/anbox-container-manager.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2017-09-01 17:21:17 CST; 12min ago
  Process: 16798 ExecStartPre=/sbin/modprobe -v -a ashmem_linux binder_linux (code=exited, status=0/SUCCESS)
 Main PID: 16829 (anbox)
    Tasks: 10 (limit: 4915)
   CGroup: /system.slice/anbox-container-manager.service
           ├─16829 anbox container-manager --data-path=/var/lib/anbox --android-image=/var/lib/anbox/android.img --privileged
           ├─16948 [lxc monitor] /var/lib/anbox/containers default
           ├─16959 /system/bin/sh /anbox-init.sh
           ├─16972 /init --second-stage
           ├─16973 /sbin/ueventd
           ├─16975 /system/bin/logd
           ├─16976 /system/bin/debuggerd
           ├─16977 /system/bin/debuggerd64
           ├─16978 /system/bin/vold --blkid_context=u:r:blkid:s0 --blkid_untrusted_context=u:r:blkid_untrusted:s0 --fsck_context=u:r:fsck:s0 --fsck_untrusted_
           ├─16984 debuggerd64:signaller
           ├─16989 debuggerd:signaller
           ├─16991 /sbin/healthd
           ├─16993 /system/bin/anboxd
           ├─16994 /system/bin/logcat -f /data/system.log -r 2048 -n 4
           ├─16995 /system/bin/lmkd
           ├─16996 /system/bin/servicemanager
           ├─16997 /system/bin/surfaceflinger
           ├─16998 zygote64
           ├─16999 zygote
           ├─17000 /system/bin/audioserver
           ├─17001 /system/bin/cameraserver
           ├─17002 /system/bin/drmserver
           ├─17003 /system/bin/installd
           ├─17004 /system/bin/keystore /data/misc/keystore
           ├─17005 media.codec mediacodec
           ├─17006 /system/bin/mediadrmserver
           ├─17007 media.extractor aextractor
           ├─17008 /system/bin/mediaserver
           ├─17009 /system/bin/netd
           ├─17010 /system/bin/fingerprintd
           ├─17011 /system/bin/gatekeeperd /data/misc/gatekeeper
           ├─17015 /system/xbin/perfprofd
           ├─17019 /system/bin/sh
           ├─17020 /sbin/adbd --root_seclabel=u:r:su:s0
           ├─17101 system_server
           ├─17183 com.android.systemui
           ├─17189 /system/bin/sdcard -u 1023 -g 1023 -m -w /data/media emulated
           ├─17246 com.android.phone
           ├─17260 com.android.settings
           ├─17350 android.ext.services
           ├─17373 org.anbox.appmgr
           ├─17400 com.android.smspush
           ├─17415 com.android.deskclock
           ├─17439 android.process.media
           ├─17471 com.android.calendar
           ├─17500 com.android.providers.calendar
           ├─17523 com.android.email
           ├─17547 com.android.managedprovisioning
           ├─17562 com.android.onetimeinitializer
           └─17583 android.process.acore

9月 01 17:21:17 linux-bnry.suse anbox[16829]: You are running the container manager manually which is most likely not
9月 01 17:21:17 linux-bnry.suse anbox[16829]: what you want. The container manager is normally started by systemd or
9月 01 17:21:17 linux-bnry.suse anbox[16829]: another init system. If you still want to run the container-manager
9月 01 17:21:17 linux-bnry.suse anbox[16829]: you can get rid of this warning by starting with the --daemon option.
9月 01 17:21:17 linux-bnry.suse anbox[16829]: 
9月 01 17:21:17 linux-bnry.suse anbox[16829]: Everything setup. Waiting for incoming connections.
9月 01 17:21:39 linux-bnry.suse anbox[16829]: Got connection from pid 16928
9月 01 17:21:39 linux-bnry.suse anbox[16829]: Containers are stored in /var/lib/anbox/containers
9月 01 17:21:39 linux-bnry.suse anbox[16829]: Using rootfs path /var/lib/anbox/rootfs
9月 01 17:21:39 linux-bnry.suse anbox[16829]: Container successfully started
```

sudo systemctl status anbox-bridge.service : 

```
● anbox-bridge.service - Anbox network bridge
   Loaded: loaded (/usr/lib/systemd/system/anbox-bridge.service; enabled; vendor preset: enabled)
   Active: active (exited) since Fri 2017-09-01 17:21:17 CST; 13min ago
  Process: 16797 ExecStart=/usr/lib/anbox/anbox-bridge.sh start (code=exited, status=0/SUCCESS)
 Main PID: 16797 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/anbox-bridge.service

9月 01 17:21:17 linux-bnry.suse systemd[1]: Starting Anbox network bridge...
9月 01 17:21:17 linux-bnry.suse systemd[1]: Started Anbox network bridge.
```

**Comment by velemas** [comment]
Same issue in ARCH. There is no default gateway in the container (adb shell) and bridge 192.168.250.1 is not accessible.

**Comment by ephemient** [comment]
If you `adb shell` into the Anbox container, you can see that not only is the default gateway missing, but the default routing policies are somehow missing too.

```
x86_64:/ # ip route
192.168.250.0/24 dev eth0  proto kernel  scope link  src 192.168.250.2 
x86_64:/ # ip rule
0:      from all lookup local 
10000:  from all fwmark 0xc0000/0xd0000 lookup 99 
13000:  from all fwmark 0x10063/0x1ffff lookup 97 
13000:  from all fwmark 0x10064/0x1ffff lookup 1055 
15000:  from all fwmark 0x0/0x10000 lookup 99 
16000:  from all fwmark 0x0/0x10000 lookup 98 
17000:  from all fwmark 0x0/0x10000 lookup 97 
```

This can be manually fixed (either as root inside the container, or using `ip -netns` from outside).

```
x86_64:/ # ip route add default dev eth0 via 192.168.250.1
x86_64:/ # ip rule add pref 32766 table main
x86_64:/ # ip rule add pref 32767 table local                                  
```

I don't understand how it would have ended up in this state, though.

**Comment by velemas** [comment]
@ephemient how do you run commands as root in adb shell? I have issue #429 :
`x86_64:/ $ /system/xbin/su -c "echo test"`
`/system/bin/sh: /system/xbin/su: can't execute: Permission denied`

`x86_64:/ $ ls -l /system/xbin/su                                                                                                                
-rwsr-x--- 1 u1_root u1_shell 10344 2017-07-13 11:19 /system/xbin/su`

`x86_64:/ $ id
uid=2000(shell) gid=2000(shell) groups=2000(shell),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc)`

Additionally `ip netns list` gives nothing. But maybe it's because of my arch installation.

**Comment by ephemient** [comment]
Yeah, and `adb root` seems to crash too. 😞

@velemas I was using my own [anbox-shell](https://gist.github.com/ephemient/5351b1afa681ca67823fe2e11190e721) script to enter the Anbox container.

**Comment by velemas** [comment]
@ephemient thanks a lot, now it works with your script.

Last time I tried anbox in May and it was working fine but now we have this issue.

**Comment by easezhi** [comment]
@ephemient it works,thx.在adb shell中，切换到root，用上面的ip route和ip rule命令执行，就能连上网了。

**Comment by webmagnets** [comment]
I am using your script, but when I type ```ip route add default dev eth0 via 192.168.250.1``` I get an error that says: ```RTNETLINK answers: Operation not permitted```

**Comment by velemas** [comment]
@webmagnets you might have done it very early when eth0 address hasn't yet been set to 192.168.250.2.

Try using `ip addr show eth0` to check address of eth0 and after it has been changed to 192.168.250.2 you may set the default route.

**Comment by webmagnets** [comment]
This is what I see:

```
2|x86_64:/system/bin $ ip addr show eth0
17: eth0@if18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 16:68:33:34:9f:ae brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.250.2/24 brd 192.168.250.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::1468:33ff:fe34:9fae/64 scope link 
       valid_lft forever preferred_lft forever
x86_64:/system/bin $ ip route add default dev eth0 via 192.168.250.1                     
RTNETLINK answers: Operation not permitted
2|x86_64:/system/bin $ 
```

**Comment by ephemient** [comment]
@webmagnets You're not root.

**Comment by webmagnets** [comment]
I just now ran this ```webmagnets@dellinux:~$ sudo python3 ~/Downloads/5351b1afa681ca67823fe2e11190e721-db9d4528a3e8b376ec90c820ca694b5fb124da77/anbox-shell```

```
x86_64:/ $ ip route change default eth0 via 192.168.250.1                      
Error: either "to" is duplicate, or "eth0" is a garbage.
255|x86_64:/ $ ip rule add pref 32766 table main                               
RTNETLINK answers: Operation not permitted
2|x86_64:/ $ ip rule add pref 32767 table local
RTNETLINK answers: Operation not permitted
```

**Comment by ephemient** [comment]
You're not root inside the container. Maybe a userns uid mapping issue or something. Not sure how your system is set up, though, the script works elsewhere.

**Comment by webmagnets** [comment]
I really appreciate you taking the time to help me.

Does this help?:

```
webmagnets@dellinux:~$ anbox --command system-info
version: 3
snap-revision: 64
os:
  name: Ubuntu
  version: 17.10 (Artful Aardvark)
  snap-based: true
kernel:
  version: Linux version 4.13.0-16-generic (buildd@lcy01-02) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu2)) #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 17.0.7
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
```
