### ISSUE TITLE
Anbox is only loading Android, making AppArmor berserk

### ISSUE THREAD

**Issue by qohelet** [anbox/anbox#445]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
version: 3
snap-revision: 58
os:
  name: Ubuntu
  version: 17.04 (Zesty Zapus)
  snap-based: true
kernel:
  version: Linux version 4.10.0-33-generic (buildd@lgw01-52) (gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) ) #37-Ubuntu SMP Fri Aug 11 10:55:28 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 17.0.7
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp


```

**Please describe your problem:**

Anbox is installed in the newest version. I checked most of the recommendations in the forum, but so far no luck. The installation via snap or regular apt-get is equally not working.

1. I try to start Anbox regularly by clicking on the icon. A window appears, telling me Android is loading. Window dies.
2. I start `anbox session-manager`. Nothing happens, terminal is left open, i open another terminal `mario@thinkgood:~$ anbox launch
[ 2017-09-03 00:04:25] [launch.cpp:101@operator()] The intent you provided is invalid. Please provide a correct launch intent.
[ 2017-09-03 00:04:25] [launch.cpp:102@operator()] For example to launch the application manager, run:
[ 2017-09-03 00:04:25] [launch.cpp:103@operator()] $ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity`
Ok... time to run that suggested command:
```
mario@thinkgood:~$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
[ 2017-09-03 00:09:31] [launch.cpp:234@operator()] Stopped waiting as we've already waited for too long. Something
[ 2017-09-03 00:09:31] [launch.cpp:235@operator()] is wrong with your setup or the container has failed to boot.
[ 2017-09-03 00:09:31] [launch.cpp:236@operator()] If you think you found a bug please don't hesitate to file on
[ 2017-09-03 00:09:31] [launch.cpp:237@operator()] at https://github.com/anbox/anbox/issues/new

```
3. I use Ubuntu Gnome. Somewhere it's recommended to use Unity. I install Unity. No difference. Just 700Mb less space. 
4. Another recommendation: Install apparmor-notify. Typing any `anbox` command really seems to make AppArmor go berserk. It tells me to look up /var/log/kern.log
Quite a few times I get that message, seems to be the most important one:
`Sep  3 04:10:07 thinkgood kernel: [14169.508855] binder_linux: 23253 RLIMIT_NICE not set`
There are some other messages too, but I don't want to put that RLIMIT_NICE a few hundred times here.
5. I'm not really familiar with the usage of AppArmor but try a little...` sudo aa-genprof anbox` is protocoling a bit but so far no changes. `sudo aa-complain anbox` doesn't work and `sudo aa-enforce anbox` either. 

**What were you expecting?:**
Not to sit until 4am in front of my notebook debugging AppArmor and making Anbox at least start or give me an error-message I can work with...

**Additional info:**
