### ISSUE TITLE
Anbox on Archlinux doesn't work, Binder not running. I must use custom kernel due to hw bugs

### ISSUE THREAD

**Issue by timofonic** [anbox/anbox#453]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
version: local-df774db
os:
  name: Arch Linux
  version:
  snap-based: false
kernel:
  version: Linux version 4.13.0-1035f22af3e97 (timofonic@timolaptop) (gcc versio
n 7.1.1 20170630 (GCC)) #1 SMP PREEMPT Fri Sep 1 06:05:09 CEST 2017
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 17.3.0-devel (git-43145bbf09)
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_polygon_offset_clamp
      - GL_KHR_no_error

```

**Please describe your problem:**

# systemctl start anbox-container-manager.service
$ systemctl --user start anbox-session-manager.service

$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
[ 2017-09-08 13:46:23] [launch.cpp:134@operator()] Anbox session manager service isn't running, trying to start it.
[ 2017-09-08 13:46:28] [launch.cpp:134@operator()] Anbox session manager service isn't running, trying to start it.
[ 2017-09-08 13:46:33] [launch.cpp:134@operator()] Anbox session manager service isn't running, trying to start it.
[ 2017-09-08 13:46:38] [launch.cpp:206@operator()] Couldn't get a connection with the session manager

* binder isn't working
  *  Am I doing something wrong? 
  * I can't use LTS kernel releases but a custom kernel (drm-tip, [aur/linux-drm-tip-git](https://aur.archlinux.org/packages/linux-drm-tip-git/) was orphan so I adopted it) because of GPU and other hardware bugs in my laptop (and still debugging them).

**What were you expecting?:**

* Binder running.
* Able to use Anbox.

**Additional info:**

Please ask and I'll provide them here.
