### ISSUE TITLE
failed to write while installing apk

### ISSUE THREAD

**Issue by asm2620** [anbox/anbox#458]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
version: 3
snap-revision: 60
os:
  name: Ubuntu
  version: 17.04 (Zesty Zapus)
  snap-based: true
kernel:
  version: Linux version 4.10.0-19-generic (buildd@lcy01-13) (gcc version 6.3.0 20170321 (Ubuntu 6.3.0-10ubuntu1) ) #21-Ubuntu SMP Thu Apr 6 17:04:57 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_swap_region
      - EGL_NOK_texture_from_pixmap
      - EGL_NV_post_sub_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: nouveau
    vendor: OpenGL ES-CM 1.1 Mesa 17.0.7
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp

```

I have this problem in Ubuntu 17.04,
with any apks
```

mohammad@mohammadpc:~/Downloads$ adb install Bazaar-7.12.1.apk 
Failed to install Bazaar-7.12.1.apk: Error: failed to write; posix_fallocate failed: ENOTSUP (Operation not supported on transport endpoint)

```

EDIT:

I think the file system is mounted RO and we can't write anything on it.
```
x86_64:/ $ su
x86_64:/ # mount 
/dev/loop3 on / type squashfs (ro,relatime)
/dev/sda8 on /cache type ext3 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda8 on /data type ext3 (rw,relatime,errors=remount-ro,data=ordered)
none on /dev type tmpfs (rw,relatime,size=492k,mode=755,uid=100000,gid=100000)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
proc on /proc/sys/net type proc (rw,nosuid,nodev,noexec,relatime)
proc on /proc/sys type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/sysrq-trigger type proc (ro,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)
sysfs on /sys/devices/virtual/net type sysfs (rw,relatime)
sysfs on /sys/devices/virtual/net type sysfs (rw,nosuid,nodev,noexec,relatime)
udev on /dev/ashmem type devtmpfs (rw,nosuid,relatime,size=1978800k,nr_inodes=494700,mode=755)
udev on /dev/binder type devtmpfs (rw,nosuid,relatime,size=1978800k,nr_inodes=494700,mode=755)
udev on /dev/console type devtmpfs (rw,nosuid,relatime,size=1978800k,nr_inodes=494700,mode=755)
udev on /dev/full type devtmpfs (rw,nosuid,relatime,size=1978800k,nr_inodes=494700,mode=755)
udev on /dev/fuse type devtmpfs (rw,nosuid,relatime,size=1978800k,nr_inodes=494700,mode=755)
udev on /dev/null type devtmpfs (rw,nosuid,relatime,size=1978800k,nr_inodes=494700,mode=755)
udev on /dev/random type devtmpfs (rw,nosuid,relatime,size=1978800k,nr_inodes=494700,mode=755)
udev on /dev/tty type devtmpfs (rw,nosuid,relatime,size=1978800k,nr_inodes=494700,mode=755)
udev on /dev/urandom type devtmpfs (rw,nosuid,relatime,size=1978800k,nr_inodes=494700,mode=755)
udev on /dev/zero type devtmpfs (rw,nosuid,relatime,size=1978800k,nr_inodes=494700,mode=755)
tmpfs on /dev/input type tmpfs (rw,nosuid,nodev,relatime,size=400324k,mode=700,uid=1000,gid=1000)
tmpfs on /dev/anbox_audio type tmpfs (rw,nosuid,nodev,relatime,size=400324k,mode=700,uid=1000,gid=1000)
tmpfs on /dev/anbox_bridge type tmpfs (rw,nosuid,nodev,relatime,size=400324k,mode=700,uid=1000,gid=1000)
tmpfs on /dev/qemu_pipe type tmpfs (rw,nosuid,nodev,relatime,size=400324k,mode=700,uid=1000,gid=1000)
devpts on /dev/console type devpts (rw,relatime,gid=5,mode=620,ptmxmode=666)
devpts on /dev/pts type devpts (rw,relatime,gid=100005,mode=620,ptmxmode=666)
tmpfs on /mnt type tmpfs (rw,relatime,mode=755,uid=100000,gid=1000)
none on /dev/memcg type cgroup (rw,relatime,memory)
none on /dev/cpuset type cgroup (rw,relatime,cpuset)
tmpfs on /storage type tmpfs (rw,relatime,mode=755,uid=100000,gid=1000)
/dev/fuse on /mnt/runtime/default/emulated type fuse (rw,nosuid,nodev,noexec,noatime,user_id=1023,group_id=1023,default_permissions,allow_other)
/dev/fuse on /storage/emulated type fuse (rw,nosuid,nodev,noexec,noatime,user_id=1023,group_id=1023,default_permissions,allow_other)
/dev/fuse on /mnt/runtime/read/emulated type fuse (rw,nosuid,nodev,noexec,noatime,user_id=1023,group_id=1023,default_permissions,allow_other)
/dev/fuse on /mnt/runtime/write/emulated type fuse (rw,nosuid,nodev,noexec,noatime,user_id=1023,group_id=1023,default_permissions,allow_other)
x86_64:/ # 
```
Can't remount:
```
x86_64:/ # mount -o remount,rw /data
mount: '/dev/sda8'->'/data': No such file or directory

```

The /data/test will exist 'till a reboot
```
x86_64:/ # touch /data/test
x86_64:/ # ls /data/test
/data/test
```
Also `pm install` doesn't works:
```
x86_64:/ # pm install /sdcard/Bazaar-7.12.1.apk                              
Error: failed to write; posix_fallocate failed: ENOTSUP (Operation not supported on transport endpoint)
```

**Additional info:**
