### ISSUE TITLE
binder_linux: 2914 RLIMIT_NICE not set (syslog spam)

### ISSUE THREAD

**Issue by supaplextor** [anbox/anbox#462]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
supaplex@supaplex-gtx760m:~$ anbox system-info
version: 3
snap-revision: 60
os:
  name: Ubuntu
  version: 16.04.2 LTS (Xenial Xerus)
  snap-based: true
kernel:
  version: Linux version 4.8.0-36-generic (buildd@lgw01-18) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 17.0.7
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp

```

**Please describe your problem:**

[ 1391.447789] binder_linux: 2912 RLIMIT_NICE not set
[ 1391.447846] binder_linux: 3175 RLIMIT_NICE not set
[ 1391.457376] binder_linux: 4241 RLIMIT_NICE not set
[ 1391.475416] binder_linux: 3443 RLIMIT_NICE not set
[ 1391.487911] binder_linux: 3176 RLIMIT_NICE not set
[ 1391.850336] binder_linux: 3050 RLIMIT_NICE not set
[ 1391.850414] binder_linux: 2975 RLIMIT_NICE not set
[ 1391.850768] binder_linux: 2914 RLIMIT_NICE not set
[ 1391.864162] binder_linux: 3367 RLIMIT_NICE not set
[ 1391.864215] binder_linux: 3367 RLIMIT_NICE not set
[ 1391.864233] binder_linux: 3367 RLIMIT_NICE not set
[ 1391.864287] binder_linux: 3366 RLIMIT_NICE not set
[ 1391.864313] binder_linux: 3366 RLIMIT_NICE not set
[ 1391.864319] binder_linux: 3366 RLIMIT_NICE not set
[ 1391.864370] binder_linux: 2976 RLIMIT_NICE not set
[ 1391.874010] binder_linux: 4250 RLIMIT_NICE not set
[ 1391.890914] binder_linux: 3175 RLIMIT_NICE not set
[ 1391.904438] binder_linux: 3443 RLIMIT_NICE not set

**What were you expecting?:**

less noise

what's rlimit_nice humm... *shrug*
**Additional info:**
