### ISSUE TITLE
anbox session-manager doesn't start on Ubuntu 16.04.03 LTS... lxc problem?

### ISSUE THREAD

**Issue by rogc** [anbox/anbox#474]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
version: 3
snap-revision: 60
os:
  name: Ubuntu
  version: 16.04.3 LTS (Xenial Xerus)
  snap-based: true
kernel:
  version: Linux version 4.4.0-97-generic (buildd@lcy01-33) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_NOK_swap_region
      - EGL_NOK_texture_from_pixmap
      - EGL_NV_post_sub_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 17.0.7
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
```

**Please describe your problem:**
$ tail /var/snap/anbox/common/logs/container.log 
            lxc 20170921175811.125 INFO     lxc_conf - conf.c:setup_tty:1053 - 0 tty(s) has been setup
            lxc 20170921175811.127 DEBUG    lxc_conf - conf.c:setup_caps:2144 - capabilities have been setup
            lxc 20170921175811.127 NOTICE   lxc_conf - conf.c:lxc_setup:3977 - 'default' is setup.
            lxc 20170921175811.127 INFO     lxc_start - start.c:do_start:836 - Unshared CLONE_NEWCGROUP.
            lxc 20170921175811.127 NOTICE   lxc_start - start.c:start:1428 - Exec'ing "/anbox-init.sh".
            lxc 20170921175811.129 NOTICE   lxc_start - start.c:post_start:1439 - Started "/anbox-init.sh" with pid "20292".
            lxc 20170921175811.129 WARN     lxc_start - start.c:signal_handler:322 - Invalid pid for SIGCHLD. Received pid 20284, expected pid 20292.
            lxc 20170921175811.129 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:893 - Peer has disconnected.
            lxc 20170921175811.129 DEBUG    lxc_commands - commands.c:lxc_cmd_get_state:578 - Container "default" is in "RUNNING" state.
            lxc 20170921175811.129 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:893 - Peer has disconnected.
$ lxc list
+------+---------+------+------+------------+-----------+
| NAME |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+------+---------+------+------+------------+-----------+
| ub1  | STOPPED |      |      | PERSISTENT | 0         |
+------+---------+------+------+------------+-----------+

**What were you expecting?:**
I expected Anbox to start. :-)

**Additional info:**
$ sudo sudo tail -80 /var/snap/anbox/common/data/system.log
09-21 18:10:57.037  5849  5849 I Netd    : Netd 1.0 starting
09-21 18:10:57.037  5849  5849 D TetherController: Setting IP forward enable = 0
09-21 18:10:57.061  5849  5849 E Netd    : cannot find interface dummy0
09-21 18:10:57.063  5849  5849 E Netd    : Unable to create netlink socket: Protocol not supported
09-21 18:10:57.063  5849  5849 W Netd    : Unable to open qlog quota socket, check if xt_quota2 can send via UeventHandler
09-21 18:10:57.063  5849  5849 D MDnsDS  : MDnsSdListener::Hander starting up
09-21 18:10:57.063  5849  5856 D MDnsDS  : MDnsSdListener starting to monitor
09-21 18:10:57.063  5849  5856 D MDnsDS  : Going to poll with pollCount 1
09-21 18:11:01.149  5865  5865 I cameraserver: ServiceManager: 0xf671af20
09-21 18:11:01.149  5865  5865 I CameraService: CameraService started (pid=5865)
09-21 18:11:01.149  5865  5865 I CameraService: CameraService process starting
09-21 18:11:01.150  5865  5865 W BatteryNotifier: batterystats service unavailable!
09-21 18:11:01.150  5865  5865 W BatteryNotifier: batterystats service unavailable!
09-21 18:11:01.151  5865  5865 E EmulatedCamera_QemuClient: receiveMessage: Unable to obtain payload size: Invalid argument
09-21 18:11:01.151  5865  5865 E EmulatedCamera_QemuClient: doQuery Response to query 'list' has failed: Invalid argument
09-21 18:11:01.151  5865  5865 E EmulatedCamera_QemuClient: listCameras: List cameras query failed: No error message
09-21 18:11:01.151  5865  5865 E cutils-trace: Error opening trace file: No such file or directory (2)
09-21 18:11:01.151  5865  5865 I CameraService: Loaded "Emulated Camera Module" camera module
09-21 18:11:01.151  5865  5865 E CameraService: setUpVendorTags: Vendor tag operations not fully defined. Ignoring definitions.
09-21 18:11:01.151  5865  5865 I ServiceManager: Waiting for service media.camera.proxy...
09-21 18:11:01.198  5864  5864 I         : sMaxFastTracks = 8
09-21 18:11:01.199  5864  5864 I audioserver: ServiceManager: 0xf661af20
09-21 18:11:01.200  5864  5864 W BatteryNotifier: batterystats service unavailable!
09-21 18:11:01.200  5864  5864 I AudioFlinger: Using default 3000 mSec as standby time.
09-21 18:11:01.200  5864  5864 I AudioPolicyService: AudioPolicyService CSTOR in new mode
09-21 18:11:01.200  5864  5864 F libc    : Fatal signal 4 (SIGILL), code 2, fault addr 0xf6ee4ea6 in tid 5864 (audioserver)
09-21 18:11:01.201    14    14 W         : debuggerd: handling request: pid=5864 uid=1041 gid=1005 tid=5864
09-21 18:11:01.204  5871  5871 E         : debuggerd: Unable to connect to activity manager (connect failed: No such file or directory)
09-21 18:11:01.204  5871  5871 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-21 18:11:01.204  5871  5871 F DEBUG   : Build fingerprint: 'Android/anbox_x86_64/x86_64:7.1.1/N6F26Q/ubuntu07131118:userdebug/test-keys'
09-21 18:11:01.204  5871  5871 F DEBUG   : Revision: '0'
09-21 18:11:01.204  5871  5871 F DEBUG   : ABI: 'x86'
09-21 18:11:01.204  5871  5871 F DEBUG   : pid: 5864, tid: 5864, name: audioserver  >>> /system/bin/audioserver <<<
09-21 18:11:01.205  5871  5871 F DEBUG   : signal 4 (SIGILL), code 2 (ILL_ILLOPN), fault addr 0xf6ee4ea6
09-21 18:11:01.205  5871  5871 F DEBUG   :     eax f661a9a0  ebx f6f0b27c  ecx 00000002  edx f6efc682
09-21 18:11:01.205  5871  5871 F DEBUG   :     esi 00000002  edi f663a000
09-21 18:11:01.205  5871  5871 F DEBUG   :     xcs 00000023  xds 0000002b  xes 0000002b  xfs 00000003  xss 0000002b
09-21 18:11:01.205  5871  5871 F DEBUG   :     eip f6ee4ea6  ebp ffb66558  esp ffb66510  flags 00010202
09-21 18:11:01.206  5871  5871 F DEBUG   : 
09-21 18:11:01.206  5871  5871 F DEBUG   : backtrace:
09-21 18:11:01.219  5866  5866 I mediaserver: ServiceManager: 0xf5f9afa0
09-21 18:11:01.220  5866  5866 W BatteryNotifier: batterystats service unavailable!
09-21 18:11:01.228    14    14 W         : debuggerd: resuming target 5864
09-21 18:11:01.325  5862  5862 D AndroidRuntime: >>>>>> START com.android.internal.os.ZygoteInit uid 0 <<<<<<
09-21 18:11:01.334  5862  5862 D AndroidRuntime: CheckJNI is OFF
09-21 18:11:01.334  5862  5862 E cutils-trace: Error opening trace file: No such file or directory (2)
09-21 18:11:01.334  5862  5862 I art     : option[0]=-Xzygote
09-21 18:11:01.334  5862  5862 I art     : option[1]=-Xstacktracefile:/data/anr/traces.txt
09-21 18:11:01.334  5862  5862 I art     : option[2]=exit
09-21 18:11:01.334  5862  5862 I art     : option[3]=vfprintf
09-21 18:11:01.334  5862  5862 I art     : option[4]=sensitiveThread
09-21 18:11:01.334  5862  5862 I art     : option[5]=-verbose:gc
09-21 18:11:01.334  5862  5862 I art     : option[6]=-Xms16m
09-21 18:11:01.334  5862  5862 I art     : option[7]=-Xmx512m
09-21 18:11:01.334  5862  5862 I art     : option[8]=-XX:HeapGrowthLimit=192m
09-21 18:11:01.335  5862  5862 I art     : option[13]=-Xjitsaveprofilinginfo
09-21 18:11:01.335  5862  5862 I art     : option[14]=-agentlib:jdwp=transport=dt_android_adb,suspend=n,server=y
09-21 18:11:01.335  5862  5862 I art     : option[15]=-Xlockprofthreshold:500
09-21 18:11:01.335  5862  5862 I art     : option[16]=-Ximage-compiler-option
09-21 18:11:01.335  5862  5862 I art     : option[17]=--runtime-arg
09-21 18:11:01.335  5862  5862 I art     : option[18]=-Ximage-compiler-option
09-21 18:11:01.352  5863  5863 D AndroidRuntime: >>>>>> START com.android.internal.os.ZygoteInit uid 0 <<<<<<
09-21 18:11:01.354  5863  5863 D AndroidRuntime: CheckJNI is OFF
09-21 18:11:01.354  5863  5863 E cutils-trace: Error opening trace file: No such file or directory (2)
09-21 18:11:01.354  5863  5863 I art     : option[0]=-Xzygote
09-21 18:11:01.354  5863  5863 I art     : option[1]=-Xstacktracefile:/data/anr/traces.txt
09-21 18:11:01.354  5863  5863 I art     : option[2]=exit
09-21 18:11:01.354  5863  5863 I art     : option[3]=vfprintf
09-21 18:11:01.354  5863  5863 I art     : option[4]=sensitiveThread
09-21 18:11:01.354  5863  5863 I art     : option[5]=-verbose:gc
09-21 18:11:01.354  5863  5863 I art     : option[6]=-Xms16m
09-21 18:11:01.354  5863  5863 I art     : option[7]=-Xmx512m
09-21 18:11:01.354  5863  5863 I art     : option[8]=-XX:HeapGrowthLimit=192m
09-21 18:11:01.354  5863  5863 I art     : option[9]=-XX:HeapMinFree=512k
09-21 18:11:01.354  5863  5863 I art     : option[10]=-XX:HeapMaxFree=8m
09-21 18:11:01.354  5863  5863 I art     : option[11]=-XX:HeapTargetUtilization=0.75
09-21 18:11:01.354  5863  5863 I art     : option[12]=-Xusejit:true
09-21 18:11:01.354  5863  5863 I art     : option[13]=-Xjitsaveprofilinginfo
09-21 18:11:01.354  5863  5863 I art     : option[20]=-Ximage-compiler-option
09-21 18:11:01.354  5863  5863 I art     : option[43]=--instruction-set-features=default
09-21 18:11:01.371  5862  5862 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
09-21 18:11:01.373  5862  5862 F libc    : Fatal signal 4 (SIGILL), code 2, fault addr 0x7f2778850df4 in tid 5862 (main)
09-21 18:11:01.373    15    15 W         : debuggerd: handling request: pid=5862 uid=0 gid=0 tid=5862
09-21 18:11:01.382  5877  5877 E         : debuggerd: Unable to connect to activity manager (connect failed: No such file or directory)
09-21 18:11:01.393    34    34 I ServiceManager: service 'media.audio_flinger' died
09-21 18:11:01.420  5863  5863 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
09-21 18:11:01.421  5863  5863 F libc    : Fatal signal 4 (SIGILL), code 2, fault addr 0xf2ddcf7f in tid 5863 (main)
09-21 18:11:01.421    14    14 W         : debuggerd: handling request: pid=5863 uid=0 gid=0 tid=5863
09-21 18:11:01.424  5878  5878 E         : debuggerd: Unable to connect to activity manager (connect failed: No such file or directory)
09-21 18:11:01.432  5877  5877 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-21 18:11:01.432  5877  5877 F DEBUG   : Build fingerprint: 'Android/anbox_x86_64/x86_64:7.1.1/N6F26Q/ubuntu07131118:userdebug/test-keys'
09-21 18:11:01.432  5877  5877 F DEBUG   : Revision: '0'
09-21 18:11:01.432  5877  5877 F DEBUG   : ABI: 'x86_64'
09-21 18:11:01.432  5877  5877 F DEBUG   : pid: 5862, tid: 5862, name: main  >>> zygote64 <<<
09-21 18:11:01.432  5877  5877 F DEBUG   : signal 4 (SIGILL), code 2 (ILL_ILLOPN), fault addr 0x7f2778850df4
09-21 18:11:01.432  5877  5877 F DEBUG   :     rax 0000000000000000  rbx 0000000000000006  rcx 0000000000000303  rdx 0000000000000000
09-21 18:11:01.432  5877  5877 F DEBUG   :     rsi 0000000000000003  rdi 0000000070a8f0e4
09-21 18:11:01.432  5877  5877 F DEBUG   :     r8  0000000000000004  r9  0000000070a8f0e4  r10 000000006fb0bec0  r11 00007ffcf3756b84
09-21 18:11:01.432  5877  5877 F DEBUG   :     r12 000000006facc2d8  r13 00007ffcf375663f  r14 0000000000000000  r15 00007ffcf3756660
09-21 18:11:01.432  5877  5877 F DEBUG   :     cs  0000000000000033  ss  000000000000002b
09-21 18:11:01.437  5877  5877 F DEBUG   : 
09-21 18:11:01.437  5877  5877 F DEBUG   : backtrace:
09-21 18:11:01.437  5877  5877 F DEBUG   :     #00 pc 0000000000149df4  /system/lib64/libart.so (_ZN3art9BitVector10NumSetBitsEPKjj+756)
09-21 18:11:01.437  5877  5877 F DEBUG   :     #01 pc 000000000045116e  /system/lib64/libart.so (_ZNK3art7OatFile8OatClass19GetOatMethodOffsetsEj+94)
09-21 18:11:01.437  5877  5877 F DEBUG   :     #02 pc 0000000000451717  /system/lib64/libart.so (_ZNK3art7OatFile8OatClass12GetOatMethodEj+23)
09-21 18:11:01.437  5877  5877 F DEBUG   :     #03 pc 0000000000195d3e  /system/lib64/libart.so (_ZN3art11ClassLinker16FindOatMethodForEPNS_9ArtMethodEPb+62
2)
09-21 18:11:01.437  5877  5877 F DEBUG   :     #04 pc 0000000000195dcc  /system/lib64/libart.so (_ZN3art11ClassLinker18GetQuickOatCodeForEPNS_9ArtMethodE+76
)
09-21 18:11:01.437  5877  5877 F DEBUG   :     #05 pc 0000000000611f3e  /system/lib64/libart.so (artQuickResolutionTrampoline+4238)
09-21 18:11:01.437  5877  5877 F DEBUG   :     #06 pc 000000000014294c  /system/lib64/libart.so (art_quick_resolution_trampoline+140)
09-21 18:11:01.437  5877  5877 F DEBUG   :     #07 pc 0000000000138516  /system/lib64/libart.so (art_quick_invoke_static_stub+806)
09-21 18:11:01.437  5877  5877 F DEBUG   :     #08 pc 00000000001463ec  /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+268
)
09-21 18:11:01.458    15    15 W         : debuggerd: resuming target 5862
09-21 18:11:01.474  5878  5878 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-21 18:11:01.474  5878  5878 F DEBUG   : Build fingerprint: 'Android/anbox_x86_64/x86_64:7.1.1/N6F26Q/ubuntu07131118:userdebug/test-keys'
09-21 18:11:01.474  5878  5878 F DEBUG   : Revision: '0'
09-21 18:11:01.474  5878  5878 F DEBUG   : ABI: 'x86'
09-21 18:11:01.474  5878  5878 F DEBUG   : pid: 5863, tid: 5863, name: main  >>> zygote <<<
09-21 18:11:01.474  5878  5878 F DEBUG   : signal 4 (SIGILL), code 2 (ILL_ILLOPN), fault addr 0xf2ddcf7f
09-21 18:11:01.474  5878  5878 F DEBUG   :     eax 00000000  ebx f33fbb84  ecx 715590a8  edx 00000006
09-21 18:11:01.475  5878  5878 F DEBUG   :     esi 00000000  edi 00000003
09-21 18:11:01.475  5878  5878 F DEBUG   :     xcs 00000023  xds 0000002b  xes 0000002b  xfs 0000006b  xss 0000002b
09-21 18:11:01.475  5878  5878 F DEBUG   :     eip f2ddcf7f  ebp ffc76818  esp ffc767d0  flags 00010206
09-21 18:11:01.482  5878  5878 F DEBUG   : 
09-21 18:11:01.482  5878  5878 F DEBUG   : backtrace:
09-21 18:11:01.482  5878  5878 F DEBUG   :     #00 pc 00116f7f  /system/lib/libart.so (_ZN3art9BitVector10NumSetBitsEPKjj+399)
09-21 18:11:01.482  5878  5878 F DEBUG   :     #01 pc 00477163  /system/lib/libart.so (_ZNK3art7OatFile8OatClass19GetOatMethodOffsetsEj+99)
09-21 18:11:01.482  5878  5878 F DEBUG   :     #02 pc 004778d9  /system/lib/libart.so (_ZNK3art7OatFile8OatClass12GetOatMethodEj+41)
09-21 18:11:01.482  5878  5878 F DEBUG   :     #03 pc 0016f38c  /system/lib/libart.so (_ZN3art11ClassLinker16FindOatMethodForEPNS_9ArtMethodEPb+764)
09-21 18:11:01.482  5878  5878 F DEBUG   :     #04 pc 0016f41c  /system/lib/libart.so (_ZN3art11ClassLinker18GetQuickOatCodeForEPNS_9ArtMethodE+92)
09-21 18:11:01.482  5878  5878 F DEBUG   :     #05 pc 0066a67a  /system/lib/libart.so (artQuickResolutionTrampoline+7210)
09-21 18:11:01.482  5878  5878 F DEBUG   :     #06 pc 0010f10d  /system/lib/libart.so (art_quick_resolution_trampoline+77)
09-21 18:11:01.482  5878  5878 F DEBUG   :     #07 pc 00109332  /system/lib/libart.so (art_quick_invoke_static_stub+418)
09-21 18:11:01.482  5878  5878 F DEBUG   :     #08 pc 00112cd9  /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+313)
09-21 18:11:01.482  5878  5878 F DEBUG   :     #09 pc 0031b066  /system/lib/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadE
PNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+294)
09-21 18:11:01.552    14    14 W         : debuggerd: resuming target 5863
09-21 18:11:01.653    34    34 I ServiceManager: service 'media.player' died
09-21 18:11:01.653    34    34 I ServiceManager: service 'media.resource_manager' died
09-21 18:11:01.657    34    34 I ServiceManager: service 'netd' died
