### ISSUE TITLE
Session manager restart cycle - Ubuntu 17.10 - com_android_internal_os_Zygote.cpp:182: setgroups failed

### ISSUE THREAD

**Issue by thritter** [anbox/anbox#508]
** Please paste the result of `anbox system-info` below:**
```
version: 3
snap-revision: 64
os:
  name: Ubuntu
  version: 17.10 (Artful Aardvark)
  snap-based: true
kernel:
  version: Linux version 4.13.0-16-generic (buildd@lcy01-02) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu2)) #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: NVIDIA
    version: 1.4
    extensions:
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_output_base
      - EGL_EXT_stream_acquire_mode
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context_no_error
      - EGL_KHR_create_context
      - EGL_KHR_display_reference
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_partial_update
      - EGL_KHR_swap_buffers_with_damage
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_stream
      - EGL_KHR_stream_consumer_gltexture
      - EGL_KHR_stream_cross_process_fd
      - EGL_KHR_stream_fifo
      - EGL_KHR_stream_producer_eglsurface
      - EGL_KHR_surfaceless_context
      - EGL_NV_nvrm_fence_sync
      - EGL_NV_post_sub_buffer
      - EGL_NV_stream_metadata
      - EGL_NV_stream_reset
      - EGL_NV_stream_sync
      - EGL_NV_stream_consumer_gltexture_yuv
      - EGL_NV_stream_attrib
      - EGL_NV_sync
      - EGL_NV_system_time
      - EGL_NV_output_drm_flip_event
  gles2:
    vendor: NVIDIA Corporation
    vendor: OpenGL ES 1.1 NVIDIA 387.22
    extensions:
      - GL_EXT_debug_label
      - GL_EXT_map_buffer_range
      - GL_EXT_robustness
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_format_BGRA8888
      - GL_KHR_debug
      - GL_EXT_memory_object
      - GL_EXT_memory_object_fd
      - GL_EXT_semaphore
      - GL_EXT_semaphore_fd
      - GL_NV_texture_compression_s3tc
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_OES_compressed_paletted_texture
      - GL_OES_draw_texture
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_element_index_uint
      - GL_OES_extended_matrix_palette
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_matrix_get
      - GL_OES_matrix_palette
      - GL_OES_packed_depth_stencil
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_OES_rgb8_rgba8
      - GL_OES_read_format
      - GL_OES_stencil8
      - GL_OES_texture_cube_map
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float
```

**Please describe your problem:**
starting anbox desktop hangs in start screen.
I guess since zygote is not started successfully.

**Additional info:**

Starting session manager reports OK.
>ANBOX_LOG_LEVEL=debug anbox session-manager
[ 2017-11-05 20:37:00] [Renderer.cpp:165@initialize] Using a surfaceless EGL context
[ 2017-11-05 20:37:00] [Renderer.cpp:248@initialize] Successfully initialized EGL

But looking @ /var/snap/anbox/common/data/system.log shows a restart cycle:

I suppose the line with "com_android_internal_os_Zygote.cpp:182: setgroups failed" is not so good.

'''
11-05 20:38:10.868   617   617 E /sbin/adbd: libminijail: setgroups: Invalid argument
11-05 20:38:12.980   622   622 I Netd    : Netd 1.0 starting
11-05 20:38:12.980   622   622 D TetherController: Setting IP forward enable = 0
11-05 20:38:12.987   622   622 E Netd    : netlink response contains error (Invalid argument)
11-05 20:38:12.987   622   622 E CommandListener: failed to initialize RouteController (Invalid argument)
11-05 20:38:12.988   622   622 E Netd    : Unable to create netlink socket: Protocol not supported
11-05 20:38:12.988   622   622 W Netd    : Unable to open qlog quota socket, check if xt_quota2 can send via UeventHandler
11-05 20:38:12.988   622   622 D MDnsDS  : MDnsSdListener::Hander starting up
11-05 20:38:12.988   622   629 D MDnsDS  : MDnsSdListener starting to monitor
11-05 20:38:12.988   622   629 D MDnsDS  : Going to poll with pollCount 1
11-05 20:38:12.997   620   620 I cameraserver: ServiceManager: 0xf6e1af20
11-05 20:38:12.997   620   620 I CameraService: CameraService started (pid=620)
11-05 20:38:12.997   620   620 I CameraService: CameraService process starting
11-05 20:38:12.997   620   620 W BatteryNotifier: batterystats service unavailable!
11-05 20:38:12.997   620   620 W BatteryNotifier: batterystats service unavailable!
11-05 20:38:12.998   620   620 E EmulatedCamera_QemuClient: receiveMessage: Unable to obtain payload size: Invalid argument
11-05 20:38:12.998   620   620 E EmulatedCamera_QemuClient: doQuery Response to query 'list' has failed: Invalid argument
11-05 20:38:12.998   620   620 E EmulatedCamera_QemuClient: listCameras: List cameras query failed: No error message
11-05 20:38:12.998   620   620 E cutils-trace: Error opening trace file: No such file or directory (2)
11-05 20:38:12.998   620   620 I CameraService: Loaded "Emulated Camera Module" camera module
11-05 20:38:12.998   620   620 E CameraService: setUpVendorTags: Vendor tag operations not fully defined. Ignoring definitions.
11-05 20:38:12.998   620   620 I ServiceManager: Waiting for service media.camera.proxy...
11-05 20:38:13.004   619   619 I         : sMaxFastTracks = 8
11-05 20:38:13.004   619   619 I audioserver: ServiceManager: 0xf6e1af20
11-05 20:38:13.004   619   619 W BatteryNotifier: batterystats service unavailable!
11-05 20:38:13.004   619   619 I AudioFlinger: Using default 3000 mSec as standby time.
11-05 20:38:13.004   619   619 I AudioPolicyService: AudioPolicyService CSTOR in new mode
11-05 20:38:13.004   619   619 I APM::ConfigParsingUtils: loadAudioPolicyConfig() loaded /system/etc/audio_policy.conf
11-05 20:38:13.005   619   619 I AudioFlinger: loadHwModule() Loaded primary audio interface from Anbox audio HW HAL (audio) handle 10
11-05 20:38:13.005   619   619 I AudioFlinger: openOutput(), module 10 Device 2, SamplingRate 44100, Format 0x000001, Channels 3, flags 2
11-05 20:38:13.005   619   619 E audio_hw_generic: Successfully connected Anbox audio server
11-05 20:38:13.005   619   619 I AudioFlinger: HAL output buffer size 1024 frames, normal sink buffer size 1024 frames
11-05 20:38:13.005   619   619 I BufferProvider: found effect "Multichannel Downmix To Stereo" from The Android Open Source Project
11-05 20:38:13.005   619   639 I AudioFlinger: AudioFlinger's thread 0xf6983b80 ready to run
11-05 20:38:13.005   619   619 I AudioFlinger: Using module 10 has the primary audio interface
11-05 20:38:13.005   619   639 W BatteryNotifier: batterystats service unavailable!
11-05 20:38:13.005   619   639 W BatteryNotifier: batterystats service unavailable!
11-05 20:38:13.005   619   639 W BatteryNotifier: batterystats service unavailable!
11-05 20:38:13.005   619   639 W AudioFlinger: no wake lock to update, system not ready yet
11-05 20:38:13.005   619   639 E cutils-trace: Error opening trace file: No such file or directory (2)
11-05 20:38:13.005   619   619 E audio_hw_generic: Error opening input stream format 1, channel_mask 0010, sample_rate 16000
11-05 20:38:13.005   619   619 E audio_hw_generic: Successfully connected Anbox audio server
11-05 20:38:13.006   619   640 I AudioFlinger: AudioFlinger's thread 0xf6783400 ready to run
11-05 20:38:13.006   619   619 E AudioFlinger: int android::load_audio_interface(const char *, audio_hw_device_t **) couldn't load audio hw module audio.r_submix (No such file or directory)
11-05 20:38:13.006   619   619 E AudioFlinger: loadHwModule() error -2 loading module r_submix
11-05 20:38:13.006   619   619 W APM_AudioPolicyManager: could not open HW module r_submix
11-05 20:38:13.006   619   619 W APM_AudioPolicyManager: Input device 80000100 unreachable
11-05 20:38:13.006   619   619 I RadioService: RadioService
11-05 20:38:13.006   619   619 I RadioService: onFirstRef
11-05 20:38:13.007   619   619 E RadioService: couldn't load radio module radio.primary (No such file or directory)
11-05 20:38:13.007   619   619 E SoundTriggerHwService: couldn't load sound trigger module sound_trigger.primary (No such file or directory)
11-05 20:38:13.028   621   621 I mediaserver: ServiceManager: 0xf679afa0
11-05 20:38:13.028   621   621 W BatteryNotifier: batterystats service unavailable!
11-05 20:38:13.081   618   618 D AndroidRuntime: >>>>>> START com.android.internal.os.ZygoteInit uid 0 <<<<<<
11-05 20:38:13.082   618   618 D AndroidRuntime: CheckJNI is OFF
11-05 20:38:13.082   618   618 E cutils-trace: Error opening trace file: No such file or directory (2)
11-05 20:38:13.082   618   618 I art     : option[0]=-Xzygote
11-05 20:38:13.082   618   618 I art     : option[1]=-Xstacktracefile:/data/anr/traces.txt
11-05 20:38:13.082   618   618 I art     : option[2]=exit
11-05 20:38:13.082   618   618 I art     : option[3]=vfprintf
11-05 20:38:13.082   618   618 I art     : option[4]=sensitiveThread
11-05 20:38:13.082   618   618 I art     : option[5]=-verbose:gc
11-05 20:38:13.082   618   618 I art     : option[6]=-Xms16m
11-05 20:38:13.082   618   618 I art     : option[7]=-Xmx512m
11-05 20:38:13.082   618   618 I art     : option[8]=-XX:HeapGrowthLimit=192m
11-05 20:38:13.082   618   618 I art     : option[9]=-XX:HeapMinFree=512k
11-05 20:38:13.082   618   618 I art     : option[10]=-XX:HeapMaxFree=8m
11-05 20:38:13.082   618   618 I art     : option[11]=-XX:HeapTargetUtilization=0.75
11-05 20:38:13.082   618   618 I art     : option[12]=-Xusejit:true
11-05 20:38:13.082   618   618 I art     : option[14]=-agentlib:jdwp=transport=dt_android_adb,suspend=n,server=y
11-05 20:38:13.082   618   618 I art     : option[20]=-Ximage-compiler-option
11-05 20:38:13.082   618   618 I art     : option[33]=--runtime-arg
11-05 20:38:13.107   618   618 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
11-05 20:38:13.112   618   618 E memtrack: Couldn't load memtrack module (No such file or directory)
11-05 20:38:13.112   618   618 E android.os.Debug: failed to load memtrack module: -2
11-05 20:38:13.112   618   618 I Radio-JNI: register_android_hardware_Radio DONE
11-05 20:38:13.113   618   618 I SamplingProfilerIntegration: Profiling disabled.
11-05 20:38:13.113   618   618 D Zygote  : begin preload
11-05 20:38:13.113   618   618 I Zygote  : Installing ICU cache reference pinning...
11-05 20:38:13.113   618   618 I Zygote  : Preloading ICU data...
11-05 20:38:13.115   618   618 I Zygote  : Preloading classes...
11-05 20:38:13.116   618   618 W Zygote  : Class not found for preloading: [Landroid.view.Display$ColorTransform;
11-05 20:38:13.130   618   618 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
11-05 20:38:13.151   618   618 I art     : Thread[1,tid=618,Native,Thread*=0x7fc817495a00,peer=0x12c060d0,"main"] recursive attempt to load library "/system/lib64/libmedia_jni.so"
11-05 20:38:13.151   618   618 D MtpDeviceJNI: register_android_mtp_MtpDevice
11-05 20:38:13.152   618   618 I art     : Thread[1,tid=618,Native,Thread*=0x7fc817495a00,peer=0x12c060d0,"main"] recursive attempt to load library "/system/lib64/libmedia_jni.so"
11-05 20:38:13.152   618   618 I art     : Thread[1,tid=618,Native,Thread*=0x7fc817495a00,peer=0x12c060d0,"main"] recursive attempt to load library "/system/lib64/libmedia_jni.so"
11-05 20:38:13.160   618   618 W Zygote  : Class not found for preloading: android.view.Display$ColorTransform
11-05 20:38:13.160   618   618 W Zygote  : Class not found for preloading: android.view.Display$ColorTransform$1
11-05 20:38:13.176   618   618 I System  : Loaded time zone names for "" in 6ms (6ms in ICU)
11-05 20:38:13.179   618   618 I System  : Loaded time zone names for "en_US" in 3ms (2ms in ICU)
11-05 20:38:13.183   618   618 I Zygote  : ...preloaded 4158 classes in 68ms.
11-05 20:38:13.183   618   618 I art     : VMRuntime.preloadDexCaches starting
11-05 20:38:13.199   618   618 I art     : VMRuntime.preloadDexCaches strings total=283703 before=39618 after=39618
11-05 20:38:13.199   618   618 I art     : VMRuntime.preloadDexCaches types total=23582 before=7877 after=7904
11-05 20:38:13.199   618   618 I art     : VMRuntime.preloadDexCaches fields total=111999 before=40899 after=41113
11-05 20:38:13.199   618   618 I art     : VMRuntime.preloadDexCaches methods total=197524 before=82450 after=83010
11-05 20:38:13.199   618   618 I art     : VMRuntime.preloadDexCaches finished
11-05 20:38:13.200   618   618 I Zygote  : Preloading resources...
11-05 20:38:13.202   618   618 W Resources: Preloaded drawable resource #0x108025c (android:drawable/dialog_background_material) that varies with configuration!!
11-05 20:38:13.202   618   618 W Resources: Preloaded drawable resource #0x1080298 (android:drawable/editbox_dropdown_background_dark) that varies with configuration!!
11-05 20:38:13.203   618   618 W Resources: Preloaded color resource #0x10600e2 (android:color/material_grey_800) that varies with configuration!!
11-05 20:38:13.203   618   618 W Resources: Preloaded drawable resource #0x10802c9 (android:drawable/floating_popup_background_dark) that varies with configuration!!
11-05 20:38:13.204   618   618 W Resources: Preloaded drawable resource #0x108030b (android:drawable/ic_clear_disabled) that varies with configuration!!
11-05 20:38:13.204   618   618 W Resources: Preloaded drawable resource #0x1080310 (android:drawable/ic_clear_normal) that varies with configuration!!
11-05 20:38:13.205   618   618 W Resources: Preloaded drawable resource #0x1080359 (android:drawable/ic_go) that varies with configuration!!
11-05 20:38:13.206   618   618 W Resources: Preloaded drawable resource #0x1080038 (android:drawable/ic_menu_close_clear_cancel) that varies with configuration!!
11-05 20:38:13.206   618   618 W Resources: Preloaded drawable resource #0x1080045 (android:drawable/ic_menu_more) that varies with configuration!!
11-05 20:38:13.207   618   618 W Resources: Preloaded drawable resource #0x10804e8 (android:drawable/menu_background_fill_parent_width) that varies with configuration!!
11-05 20:38:13.213   618   618 W Resources: Preloaded drawable resource #0x108077e (android:drawable/text_edit_paste_window) that varies with configuration!!
11-05 20:38:13.214   618   618 W Resources: Preloaded drawable resource #0x1080096 (android:drawable/toast_frame) that varies with configuration!!
11-05 20:38:13.214   618   618 I Zygote  : ...preloaded 114 resources in 14ms.
11-05 20:38:13.214   618   618 W Resources: Preloaded color resource #0x106010b (android:color/background_cache_hint_selector_material_dark) that varies with configuration!!
11-05 20:38:13.214   618   618 W Resources: Preloaded color resource #0x1060110 (android:color/btn_default_material_dark) that varies with configuration!!
11-05 20:38:13.215   618   618 I Zygote  : ...preloaded 41 resources in 1ms.
11-05 20:38:13.215   618   618 I Zygote  : ...preloaded 2 resource in 0ms.
11-05 20:38:13.215   618   618 D libEGL  : Emulator has host GPU support, qemu.gles is set to 1.
11-05 20:38:13.215   618   618 E libEGL  : load_driver(/system/lib64/egl/libGLES_emulation.so): dlopen failed: library "/system/lib64/egl/libGLES_emulation.so" not found
11-05 20:38:13.216   618   618 D libEGL  : loaded /system/lib64/egl/libEGL_emulation.so
11-05 20:38:13.216   618   618 D libEGL  : loaded /system/lib64/egl/libGLESv1_CM_emulation.so
11-05 20:38:13.220   618   618 D libEGL  : loaded /system/lib64/egl/libGLESv2_emulation.so
11-05 20:38:13.224   618   618 I Zygote  : Preloading shared libraries...
11-05 20:38:13.226   618   618 I Zygote  : Uninstalled ICU cache reference pinning...
11-05 20:38:13.226   618   618 I Zygote  : Installed AndroidKeyStoreProvider in 1ms.
11-05 20:38:13.229   618   618 I Zygote  : Warmed up JCA providers in 2ms.
11-05 20:38:13.229   618   618 D Zygote  : end preload
11-05 20:38:13.229   618   618 I art     : Starting a blocking GC Explicit
11-05 20:38:13.234   618   618 I art     : Explicit concurrent mark sweep GC freed 55679(6MB) AllocSpace objects, 133(2MB) LOS objects, 39% free, 2MB/4MB, paused 20us total 5.434ms
11-05 20:38:13.235   618   618 I art     : Starting a blocking GC Explicit
11-05 20:38:13.237   618   618 I art     : Explicit concurrent mark sweep GC freed 4919(199KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 2MB/3MB, paused 19us total 2.386ms
11-05 20:38:13.256   618   646 I art     : Starting a blocking GC HeapTrim
11-05 20:38:13.257   618   618 I art     : Starting a blocking GC Background
11-05 20:38:13.269   618   618 I Zygote  : System server process 648 has been created
11-05 20:38:13.269   648   648 F art     : art/runtime/jni_internal.cc:492] JNI FatalError called: frameworks/base/core/jni/com_android_internal_os_Zygote.cpp:182: setgroups failed: Invalid argument, gids.size=20
11-05 20:38:13.269   618   618 I Zygote  : Accepting command socket connections
11-05 20:38:13.273   648   648 F art     : art/runtime/runtime.cc:422] Runtime aborting...
11-05 20:38:13.273   648   648 F art     : art/runtime/runtime.cc:422] Aborting thread:
11-05 20:38:13.273   648   648 F art     : art/runtime/runtime.cc:422] "main" prio=5 tid=1 Native
11-05 20:38:13.273   648   648 F art     : art/runtime/runtime.cc:422]   | group="" sCount=0 dsCount=0 obj=0x75544850 self=0x7fc817495a00
11-05 20:38:13.273   648   648 F art     : art/runtime/runtime.cc:422]   | sysTid=618 nice=0 cgrp=default sched=0/0 handle=0x7fc81bedfb40
11-05 20:38:13.273   648   648 F art     : art/runtime/runtime.cc:422]   | state=? schedstat=( 0 0 0 ) utm=0 stm=0 core=0 HZ=100
11-05 20:38:13.273   648   648 F art     : art/runtime/runtime.cc:422]   | stack=0x7fff7c274000-0x7fff7c276000 stackSize=8MB
11-05 20:38:13.273   648   648 F art     : art/runtime/runtime.cc:422]   | held mutexes= "abort lock"
11-05 20:38:13.273   648   648 F art     : art/runtime/runtime.cc:422]   kernel: (couldn't read /proc/self/task/618/stack)
11-05 20:38:13.273   648   648 F art     : art/runtime/runtime.cc:422]   native: (backtrace::Unwind failed for thread 618: Thread doesn't exist)
11-05 20:38:13.273   648   648 F art     : art/runtime/runtime.cc:422]   at com.android.internal.os.Zygote.nativeForkSystemServer(Native method)
11-05 20:38:13.273   648   648 F art     : art/runtime/runtime.cc:422]   at com.android.internal.os.Zygote.forkSystemServer(Zygote.java:139)
11-05 20:38:13.273   648   648 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 648 (main)
11-05 20:38:13.273    15    15 W         : debuggerd: handling request: pid=648 uid=0 gid=0 tid=648
11-05 20:38:13.275   653   653 E         : debuggerd: Unable to connect to activity manager (connect failed: No such file or directory)
11-05 20:38:13.275   653   653 E         : debuggerd: failed to setgroups: Invalid argument
11-05 20:38:13.275   653   653 E         : debuggerd: failed to drop privileges, exiting
11-05 20:38:13.275    15    15 W         : debuggerd: resuming target 648
11-05 20:38:13.380   618   618 I Zygote  : Process 648 exited due to signal (6)
11-05 20:38:13.380   618   618 I Zygote  : Process 648 dumped core.
11-05 20:38:13.380   618   618 E Zygote  : Exit zygote because system server (648) has terminated
11-05 20:38:13.398    33    33 I ServiceManager: service 'media.player' died
11-05 20:38:13.398    33    33 I ServiceManager: service 'media.resource_manager' died
11-05 20:38:13.398    33    33 I ServiceManager: service 'media.audio_flinger' died
11-05 20:38:13.398    33    33 I ServiceManager: service 'media.audio_policy' died
11-05 20:38:13.398    33    33 I ServiceManager: service 'media.sound_trigger_hw' died
11-05 20:38:13.398    33    33 I ServiceManager: service 'media.radio' died
11-05 20:38:13.398    33    33 I ServiceManager: service 'netd' died

'''
