### ISSUE TITLE
Anbox 3 not working on Ubuntu 17.04, Nvidia GPU

### ISSUE THREAD

**Issue by kotatsuman** [anbox/anbox#515]
I am running the latest version, just downloaded it using snap and following the instructions on your site.
If I run anbox -version from terminal, I simply get:
anbox 3

** Please paste the result of `anbox system-info` below:**
```
version: 3
snap-revision: 64
os:
  name: Ubuntu
  version: 17.04 (Zesty Zapus)
  snap-based: true
kernel:
  version: Linux version 4.10.0-40-generic (buildd@lgw01-amd64-036) (gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) ) #44-Ubuntu SMP Thu Nov 9 14:49:09 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

```

**Please describe your problem:**

I installed Anbox and reboot Ubuntu.
I tried to run Anbox from app menu in Ubuntu. It displays a gray windows with an Android "guy" on it and "Starting..." on screen for some seconds, then does nothing.

I tried with terminal. I ran:

dario@casa:~$ env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/anbox_anbox.desktop /snap/bin/anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
[ 2017-11-12 23:05:41] [launch.cpp:134@operator()] Anbox session manager service isn't running, trying to start it.
[ 2017-11-12 23:05:46] [launch.cpp:134@operator()] Anbox session manager service isn't running, trying to start it.
[ 2017-11-12 23:05:51] [launch.cpp:134@operator()] Anbox session manager service isn't running, trying to start it.
[ 2017-11-12 23:05:56] [launch.cpp:206@operator()] Couldn't get a connection with the session manager

Then:

**dario@casa:~$ anbox session-manager
[ 2017-11-12 22:59:50] [Renderer.cpp:99@initialize] Failed to Initialize backend EGL display
Errore di segmentazione (core dump creato)**

(it's Italian... I think that you would translate as "Segmentation error" or "chunking error" or something else I can't say in English.)

Then it does nothing.

**What were you expecting?:**

Run Anbox.

**Additional info:**

Ask me for any additonal info at dwilyo@posta.it (I'll answer in 3-4 days probably, I don't check email everyday). Thank you
