### ISSUE TITLE
Error when trying to launch "anbox session-manager", failed to start container.

### ISSUE THREAD

**Issue by hacker1024** [anbox/anbox#516]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
version: 3
snap-revision: 64
os:
  name: KDE neon
  version: Developer Edition
  snap-based: true
kernel:
  version: Linux version 4.14.0-041400-generic (kernel@kathleen) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3)) #201711122031 SMP Sun Nov 12 20:32:29 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 17.0.7
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp

```

**Please describe your problem:**
When I run ```anbox session-manager```, I get this:
```
[ 2017-11-13 13:38:56] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to start container
[ 2017-11-13 13:38:56] [session_manager.cpp:162@operator()] Lost connection to container manager, terminating.
[ 2017-11-13 13:38:56] [daemon.cpp:58@Run] Container is not running
[WW 2017-11-13 13:38:56] [session_manager.cpp:162@operator()] Lost connection to container manager, terminating.
```
And the process ends. As root, I get this:
```
No protocol specified
Segmentation fault
```
**What were you expecting?:**
Normal behavior

**Additional info:**
I am using [this commit](https://github.com/anbox/anbox/pull/504/files) so the module works on kernel 4.14.

**Comment by jo-wu** [comment]
I think u may not reboot your system, just restart your OS.
and then u can find a anbox icon.

**Comment by hacker1024** [comment]
Rebooting doesn't do anything, why would it?

**Comment by seamus-45** [comment]
+1

```
[ 2017-12-14 09:36:29] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to start container
[ 2017-12-14 09:36:29] [session_manager.cpp:162@operator()] Lost connection to container manager, terminating.
[ 2017-12-14 09:36:29] [daemon.cpp:58@Run] Container is not running
[1]    16013 segmentation fault  /usr/bin/anbox session-manager
```

Another one:

```
[ 2017-12-14 09:33:50] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to start container
[ 2017-12-14 09:33:50] [session_manager.cpp:162@operator()] Lost connection to container manager, terminating.
[ 2017-12-14 09:33:50] [daemon.cpp:58@Run] Container is not running
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::log::v2_mt_posix::system_error> >'
  what():  Failed to set TLS value: Invalid argument
```

**Comment by major0** [comment]
Running into the same problem.  Curiously, the segfault is showing up in dmesg:
```
[ 6824.274818] anbox[18656]: segfault at 0 ip 00007f3b1422dcfc sp 00007f3af2ed0f50 error 4 in libboost_log.so.1.58.0[7f3b141d7000+d2000]
```

**Comment by mauron85** [comment]
Same anbox session-manager outpit, but ny dmesg error is different:

```
anbox[14341] trap invalid opcode ip:7fae1a944edc sp:7fadf2ffbe10 error:0 in libpthread-2.23.so[7fae1a938000+18000]

```

**Comment by GreyDireWolf** [comment]
I'm also experiencing same issue on arch linux
```[ 2018-05-12 15:02:37] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to configure LXC container
[ 2018-05-12 15:02:37] [session_manager.cpp:162@operator()] Lost connection to container manager, terminating.
[ 2018-05-12 15:02:37] [daemon.cpp:58@Run] Container is not running
[ 2018-05-12 15:02:37] [session_manager.cpp:162@operator()] Lost connection to container manager, terminating.
[1]    3548 segmentation fault (core dumped)  anbox session-manager

```

**Comment by rasperin** [comment]
Ditto to above:
```
$ anbox session-manager
[ 2018-05-22 18:10:48] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to configure LXC container
[ 2018-05-22 18:10:48] [session_manager.cpp:162@operator()] Lost connection to container manager, terminating.
[ 2018-05-22 18:10:48] [daemon.cpp:58@Run] Container is not running
Segmentation fault (core dumped)
```

Dmesg:
```
[50270.493038] anbox[36462]: segfault at 0 ip 0000000000000000 sp 00007f686d8e1188 error 14 in anbox[562945286000+24e000]
[50276.741209] anbox[36531]: segfault at 0 ip 0000000000000000 sp 00007f3a7cce1188 error 14 in anbox[55f5442dc000+24e000]
```

**Comment by mduft** [comment]
I get:

 $ anbox session-manager
[ 2018-07-02 13:04:56] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to start container
[ 2018-07-02 13:04:56] [session_manager.cpp:145@operator()] Lost connection to container manager, terminating.
[ 2018-07-02 13:04:56] [daemon.cpp:59@Run] Container is not running
Stack trace (most recent call last) in thread 24873:
#10   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#9    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fbdfe01c41c, in clone
#8    Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7fbdffaaf6b9, in 
#7    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7fbdfe5adc7f, in 
#6    Object "/snap/anbox/92/usr/bin/anbox", at 0x4e7070, in 
#5    Object "/snap/anbox/92/usr/bin/anbox", at 0x5466cd, in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, std::function<void (boost::system::error_code const&, unsigned long)> >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long)
#4    Object "/snap/anbox/92/usr/bin/anbox", at 0x4f13f6, in anbox::container::Client::on_read_size(boost::system::error_code const&, unsigned long)
#3    Object "/snap/anbox/92/usr/bin/anbox", at 0x4c0a5e, in 
#2    Object "/snap/anbox/92/usr/bin/anbox", at 0x4dd2cd, in 
#1    Object "/snap/anbox/92/usr/lib/x86_64-linux-gnu/libboost_log.so.1.58.0", at 0x7fbe001c4a43, in boost::log::v2_mt_posix::core::open_record(boost::log::v2_mt_posix::attribute_set const&)
#0    Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7fbdffab4edc, in pthread_rwlock_unlock
Segmentation fault (Signal sent by the kernel [(nil)])
Segmentation fault (core dumped)

It's fedora 28 (Linux fril0041.wamas.com 4.17.2-200.fc28.x86_64 #1 SMP Mon Jun 18 20:09:31 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux) with ashmem and binder modules compiled using DKMS from today's repository master state.

**Comment by goodevilgenius** [comment]
I have this issue with a current release of `anbox`

Output from `anbox session-manager`:

```
Stack trace (most recent call last) in thread 19133:
#10   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#9    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7efe32aad41c, in clone
#8    Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7efe3455f6b9, in 
#7    Object "/snap/anbox/167/usr/bin/anbox", at 0x57c550, in emugl::Thread::thread_main(void*)
#6    Object "/snap/anbox/167/usr/bin/anbox", at 0x4a6940, in RenderThread::main()
#5    Object "/snap/anbox/167/usr/bin/anbox", at 0x5993ff, in gles2_decoder_context_t::decode(void*, unsigned long, IOStream*)
#4    Object "/snap/anbox/167/usr/lib/x86_64-linux-gnu/dri/i965_dri.so", at 0x7efe27ccc2d7, in 
#3    Object "/snap/anbox/167/usr/lib/x86_64-linux-gnu/dri/i965_dri.so", at 0x7efe27ccc007, in 
#2    Object "/snap/anbox/167/usr/lib/x86_64-linux-gnu/dri/i965_dri.so", at 0x7efe27f0bc0a, in 
#1    Object "/snap/anbox/167/usr/lib/x86_64-linux-gnu/dri/i965_dri.so", at 0x7efe27f1a948, in 
#0    Object "/snap/anbox/167/usr/lib/x86_64-linux-gnu/dri/i965_dri.so", at 0x7efe27f22691, in 
Segmentation fault (Address not mapped to object [0x7c])
Segmentation fault (core dumped)
```

System info:

```
version: 4
snap-revision: 167
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Fedora
  version: 29 (Workstation Edition)
  snap-based: true
kernel:
  version: Linux version 4.19.15-300.fc29.x86_64 (mockbuild@bkernel03.phx2.fedoraproject.org) (gcc version 8.2.1 20181215 (Red Hat 8.2.1-6) (GCC)) #1 SMP Mon Jan 14 16:32:35 UTC 2019
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 3.2 Mesa 18.0.5
    extensions:
      - GL_ANDROID_extension_pack_es31a
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_disjoint_timer_query
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_read_format_bgra
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_framebuffer_fetch
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_shader_samples_identical
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_INTEL_conservative_rasterization
      - GL_INTEL_performance_query
      - GL_KHR_blend_equation_advanced
      - GL_KHR_blend_equation_advanced_coherent
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_KHR_texture_compression_astc_ldr
      - GL_KHR_texture_compression_astc_sliced_3d
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_image_formats
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_get_program_binary
      - GL_OES_gpu_shader5
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_primitive_bounding_box
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array
```
