### ISSUE TITLE
container-manager assumes AppArmor is available and functional

### ISSUE THREAD

**Issue by PedroArvela** [anbox/anbox#54]
Make sure you are running the latest version of Anbox before reporting an issue.

**Anbox release (`anbox version`) and system info (`anbox system-info`):**
`anbox 0.1.0`

```
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.10.8-200.fc25.x86_64 (mockbuild@bkernel02.phx2.fedoraproject.org) (gcc version 6.3.1 20161221 (Red Hat 6.3.1-1) (GCC) ) #1 SMP Fri Mar 31 13:20:22 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_cl_event2
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: X.Org
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
```

**Description of the problem:**

Running the anbox container manager fails because it tries to use the aa-exec command on Fedora, which does not support AppArmor Profiles at all (the kernel is built without AppArmor support).

```
~ $ snap run anbox.container-manager
+ DATA_PATH=/var/snap/anbox/common/
+ ROOTFS_PATH=/var/snap/anbox/common//rootfs
+ ANDROID_IMG=/var/lib/snapd/snap/anbox/15/android.img
+ [ ! -e /var/lib/snapd/snap/anbox/15/android.img ]
+ start
+ mkdir -p /var/snap/anbox/common/lxc
+ /var/lib/snapd/snap/anbox/15/bin/anbox-bridge.sh start
anbox-bridge is already running
+ echo Y
+ sudo tee /sys/module/fuse/parameters/userns_mounts
tee: /sys/module/fuse/parameters/userns_mounts: No such file or directory
Y
+ echo WARNING: kernel doesn't support fuse in user namespaces
WARNING: kernel doesn't support fuse in user namespaces
+ exec /var/lib/snapd/snap/anbox/15/usr/sbin/aa-exec -p unconfined -- /var/lib/snapd/snap/anbox/15/bin/anbox-wrapper.sh container-manager --data-path=/var/snap/anbox/common/ --android-image=/var/lib/snapd/snap/anbox/15/android.img
aa-exec: ERROR: AppArmor interface not available
```

**Expected:**

The container manager should run successfully despite the lack of AppArmor security module.

**Additional info:**

I installed the required modules for binder and ashmem and then installed anbox through snap after checking what the installation script did.

The problem is in [line 31 of the container-manager.sh script](https://github.com/anbox/anbox/blob/f96c150d56e6f9a2fb67c7fefacd117e59923628/scripts/container-manager.sh#L31), which runs `aa-exec` without checking if the system supports AppArmor.

The simplest solution would be to run the command without `aa-exec` if the security module used in not AppArmor.
