### ISSUE TITLE
No starting Anbox (Please provide a correct launch intent)

### ISSUE THREAD

**Issue by Liza898** [anbox/anbox#544]
** Please paste the result of `anbox system-info` below:**
```
libEGL warning: DRI2: failed to authenticate
version: 3
snap-revision: 65
os:
  name: Ubuntu
  version: 16.04.3 LTS (Xenial Xerus)
  snap-based: true
kernel:
  version: Linux version 4.10.0-28-generic (buildd@lgw01-12) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_MESA_configless_context
  gles2:
    vendor: VMware, Inc.
    vendor: OpenGL ES-CM 1.1 Mesa 17.0.7
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp

```

**Please describe your problem:**
After clicking on the program shortcut: the application starts and hangs on the first page "Starting...". Nothing else happens. Tell me how to solve the problem. Pls

**What were you expecting?:**
long time

**Additional info:**
```
> gorilloid@gorilloid:~$ **anbox session-manager**
> [ 2017-12-09 21:07:54] [daemon.cpp:58@Run] bind: Address already in use
```
```
> gorilloid@gorilloid:~$ **anbox launch**
> [ 2017-12-09 21:09:13] [launch.cpp:101@operator()] The intent you provided is invalid. Please provide a correct launch intent.
> [ 2017-12-09 21:09:13] [launch.cpp:102@operator()] For example to launch the application manager, run:
> [ 2017-12-09 21:09:13] [launch.cpp:103@operator()] $ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
```
```
> gorilloid@gorilloid:~$ **sudo anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity**
> [ 2017-12-09 21:09:53] [daemon.cpp:58@Run] org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error messagе
```
