### ISSUE TITLE
Unable to start Anbox due to unloaded drivers (binder/ashmem)

### ISSUE THREAD

**Issue by ShalokShalom** [anbox/anbox#546]
I run the git build.
```
➜  ~ anbox system-info    
version: local-7266fe2
os:
  name: KaOS
  version: 2017
  snap-based: false
kernel:
  version: Linux version 4.13.12-1 (k@x86_64.kaosx.us) (gcc version 6.4.0 (GCC)) #1 SMP PREEMPT Thu Nov 9 11:17:33 UTC 2017
  binder: false
  ashmem: false
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 17.2.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_polygon_offset_clamp
      - GL_KHR_no_error
➜  ~ 

```

➜  binder make       
make -C /lib/modules/4.13.12-1/build V=0 M=$PWD
make[1]: Verzeichnis „/usr/src/linux-4.13.12-1“ wird betreten
  AR      /home/matthias/Projekte/KaOS/Zeug/anbox-master/kernel/binder/built-in.o
  CC [M]  /home/matthias/Projekte/KaOS/Zeug/anbox-master/kernel/binder/deps.o
  CC [M]  /home/matthias/Projekte/KaOS/Zeug/anbox-master/kernel/binder/binder.o
  LD [M]  /home/matthias/Projekte/KaOS/Zeug/anbox-master/kernel/binder/binder_linux.o
  Building modules, stage 2.
  MODPOST 1 modules
WARNING: modpost: Found 15 writable function pointer(s).
To see full details build your kernel with:
'make CONFIG_DEBUG_SECTION_MISMATCH=y'
  CC      /home/matthias/Projekte/KaOS/Zeug/anbox-master/kernel/binder/binder_linux.mod.o
  LD [M]  /home/matthias/Projekte/KaOS/Zeug/anbox-master/kernel/binder/binder_linux.ko
make[1]: Verzeichnis „/usr/src/linux-4.13.12-1“ wird verlassen
➜  binder anbox        
Unknown command 'run'
NAME:
    anbox - anbox

USAGE:
    anbox [command options] [arguments...]

COMMANDS:
    help                 prints a short help message                                                                         
    system-info          Print various information about the system we're running on                                         
    version              print the version of the daemon                                                                     
    session-manager      Run the the anbox session manager                                                                   
    launch               Launch an Activity by sending an intent                                                             
➜  binder anbox launch
[ 2017-12-09 22:49:22] [launch.cpp:101@operator()] The intent you provided is invalid. Please provide a correct launch intent.
[ 2017-12-09 22:49:22] [launch.cpp:102@operator()] For example to launch the application manager, run:
[ 2017-12-09 22:49:22] [launch.cpp:103@operator()] $ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
➜  binder anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
[ 2017-12-09 22:49:41] [launch.cpp:134@operator()] Anbox session manager service isn't running, trying to start it.
[ 2017-12-09 22:49:46] [launch.cpp:134@operator()] Anbox session manager service isn't running, trying to start it.
[ 2017-12-09 22:49:51] [launch.cpp:134@operator()] Anbox session manager service isn't running, trying to start it.
[ 2017-12-09 22:49:56] [launch.cpp:206@operator()] Couldn't get a connection with the session manager
➜  binder anbox session-manager                                                               
[ 2017-12-09 22:50:19] [session_manager.cpp:147@operator()] Failed to start as either binder or ashmem kernel drivers are not loaded
➜  binder 

**Additional info:**

I installed this by running make in kernel/binder
