### ISSUE TITLE
Bug: Both 2 slots are defined as system DBus

### ISSUE THREAD

**Issue by liuqun** [anbox/anbox#551]
Both the two slots are defined as system DBus. The wrong code are here:

https://github.com/anbox/anbox/blob/7266fe2d4741051bcdd41c09a425c4d6383a33cd/snapcraft.yaml#L17-L28

which should be: 
```
  dbus-session:
    interface: dbus
    bus: session
    name: org.anbox
```
