### ISSUE TITLE
Help with the port to jetson TX1

### ISSUE THREAD

**Issue by Atomicchipmonk** [anbox/anbox#552]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
version: local-e05ca24
os:
  name: Ubuntu
  version: 16.04 LTS (Xenial Xerus)
  snap-based: false
kernel:
  version: Linux version 4.4.38 (heisty@glados-laptop) (gcc version 4.8.5 (GCC) ) #1 SMP PREEMPT Sat Dec 9 21:38:05 EST 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: NVIDIA
    version: 1.5
    extensions:
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_output_base
      - EGL_EXT_stream_acquire_mode
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context_no_error
      - EGL_KHR_create_context
      - EGL_KHR_display_reference
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_partial_update
      - EGL_KHR_swap_buffers_with_damage
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_stream
      - EGL_KHR_stream_attrib
      - EGL_KHR_stream_consumer_gltexture
      - EGL_KHR_stream_cross_process_fd
      - EGL_KHR_stream_fifo
      - EGL_KHR_stream_producer_eglsurface
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_NV_cuda_event
      - EGL_NV_nvrm_fence_sync
      - EGL_NV_post_sub_buffer
      - EGL_NV_stream_metadata
      - EGL_NV_stream_reset
      - EGL_NV_stream_sync
      - EGL_NV_stream_consumer_gltexture_yuv
      - EGL_NV_stream_attrib
      - EGL_NV_sync
      - EGL_NV_system_time
      - EGL_NV_output_drm_flip_event
      - EGL_WL_bind_wayland_display
      - EGL_WL_wayland_eglstream
  gles2:
    vendor: NVIDIA Corporation
    vendor: OpenGL ES 1.1 NVIDIA 28.1.0
    extensions:
      - GL_EXT_debug_label
      - GL_EXT_map_buffer_range
      - GL_EXT_robustness
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_format_BGRA8888
      - GL_KHR_debug
      - GL_NV_texture_compression_s3tc
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_OES_compressed_paletted_texture
      - GL_OES_draw_texture
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_element_index_uint
      - GL_OES_extended_matrix_palette
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_matrix_get
      - GL_OES_matrix_palette
      - GL_OES_packed_depth_stencil
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_OES_rgb8_rgba8
      - GL_OES_read_format
      - GL_OES_stencil8
      - GL_OES_texture_cube_map
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float
```

This saga began several weeks ago with a simple thought of getting anbox working on the Jetson TX1. The Jetson is arm64 with some armhf libraries. This meant building from scratch, although you do have ubuntu 16.04 to get any packages you need.

Steps so far:
Built anbox - not too bad
Built kernel modules, also not terrible
Downloaded a 64 bit android image
Tried to run container-manager, realized there was a bug in the loopback mounting, had to force squashfs mounting
Noticed masquerade was not built into the kernel
Rebuilt the TX1 kernel with masq
Running container manager and session-manager now, but getting errors.

First - can I get a check on how I am kicking things off?
Window 1: sudo anbox container-manager --daemon --data-path=/home/nvidia/development/anbox/ --privileged
Window 2: anbox session-manager

Now - here is the output:
Window 1 (I added a bit of verbosity):
[ 2016-02-11 17:08:46] [mount_entry.cpp:68@create] CREATE3
[ 2016-02-11 17:08:46] [mount_entry.cpp:29@create] CREATE1: called
[ 2016-02-11 17:08:46] [mount_entry.cpp:32@create] CREATE1: entry valid
[ 2016-02-11 17:08:46] [mount_entry.cpp:38@create] CREATE1: SRC:/home/nvidia/development/anbox/cache
[ 2016-02-11 17:08:46] [mount_entry.cpp:39@create] CREATE1: TAR:/home/nvidia/development/anbox/rootfs/cache
[ 2016-02-11 17:08:46] [mount_entry.cpp:40@create] CREATE1: FSTYPE:
[ 2016-02-11 17:08:46] [mount_entry.cpp:41@create] CREATE1: DATA:
[ 2016-02-11 17:08:46] [mount_entry.cpp:46@create] CREATE1: mounted
[ 2016-02-11 17:08:46] [mount_entry.cpp:29@create] CREATE1: called
[ 2016-02-11 17:08:46] [mount_entry.cpp:32@create] CREATE1: entry valid
[ 2016-02-11 17:08:46] [mount_entry.cpp:38@create] CREATE1: SRC:/home/nvidia/development/anbox/data
[ 2016-02-11 17:08:46] [mount_entry.cpp:39@create] CREATE1: TAR:/home/nvidia/development/anbox/rootfs/data
[ 2016-02-11 17:08:46] [mount_entry.cpp:40@create] CREATE1: FSTYPE:
[ 2016-02-11 17:08:46] [mount_entry.cpp:41@create] CREATE1: DATA:
[ 2016-02-11 17:08:46] [mount_entry.cpp:46@create] CREATE1: mounted

Window 2:
[ 2016-02-11 16:46:22] [session_manager.cpp:159@operator()] session_manager.cpp: running make_shared container
[ 2016-02-11 16:46:22] [session_manager.cpp:168@operator()] session_manager.cpp: Client Created
[ 2016-02-11 16:46:22] [session_manager.cpp:172@operator()] session_manager.cpp: Input Manager created
[ 2016-02-11 16:46:22] [session_manager.cpp:176@operator()] session_manager.cpp: androidApiStupd created
[ 2016-02-11 16:46:23] [session_manager.cpp:187@operator()] session_manager.cpp: platform created
[ 2016-02-11 16:46:23] [session_manager.cpp:192@operator()] session_manager.cpp: platform created
[ 2016-02-11 16:46:23] [Renderer.cpp:165@initialize] Using a surfaceless EGL context
[ 2016-02-11 16:46:23] [Renderer.cpp:248@initialize] Successfully initialized EGL
[ 2016-02-11 16:46:23] [management_api_stub.cpp:36@start_container] management_api_stup: protobuf requested
[ 2016-02-11 16:46:23] [management_api_stub.cpp:45@start_container] management_api_stup: bindmounts
[ 2016-02-11 16:46:23] [management_api_stub.cpp:56@start_container] management_api_stup: start container
[ 2016-02-11 16:46:28] [management_api_stub.cpp:59@start_container] management_api_stup: waited, got past
[ 2016-02-11 16:46:28] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to start container
[ 2016-02-11 16:46:28] [session_manager.cpp:163@operator()] Lost connection to container manager, terminating.
[ 2016-02-11 16:46:28] [daemon.cpp:58@Run] Container is not running
[ 2016-02-11 16:46:28] [session_manager.cpp:163@operator()] Lost connection to container manager, terminating.

**What were you expecting?:**
Really hoping I am on the right path. I think there may still be issues with the networking side of things. Can someone tell me what exactly the containers are relying on nat, masq, netfiler, iptables wise? I have to build it into the kernel.

Also - if there I would love some confirmation that I am building and running the right stuff. I tried finding documentation on how developers of anbox did run time development without snap and I could not find it. What order do you run things, how many things are required? Container, session, launch? Or am I missing a step?

**Additional info:**

Thanks all - getting android apps running next to gpu accelerated image processing will be freakin sweet if this all works.
