### ISSUE TITLE
Launched container ends with unspecified error

### ISSUE THREAD

**Issue by PedroArvela** [anbox/anbox#58]
Make sure you are running the latest version of Anbox before reporting an issue.

**Anbox release (`anbox version`) and system info (`anbox system-info`):**

```
version: 0.1.0                                                                                                                                                                                                                                                                 
os:                                                                                                                                                                                                                                                                            
  name: Ubuntu Core                                                                                                                                                                                                                                                            
  version: 16                                                                                                                                                                                                                                                                  
  snap-based: true                                                                                                                                                                                                                                                             
kernel:                                                                                                                                                                                                                                                                        
  version: Linux version 4.10.8-200.fc25.x86_64 (mockbuild@bkernel02.phx2.fedoraproject.org) (gcc version 6.3.1 20161221 (Red Hat 6.3.1-1) (GCC) ) #1 SMP Fri Mar 31 13:20:22 UTC 2017                                                                                         
  binder: true                                                                                                                                                                                                                                                                 
  ashmem: true                                                                                                                                                                                                                                                                 
graphics:                                                                                                                                                                                                                                                                      
  egl:                                                                                                                                                                                                                                                                         
    vendor: Mesa Project                                                                                                                                                                                                                                                       
    version: 1.5 (DRI2)                                                                                                                                                                                                                                                        
    extensions:                                                                                                                                                                                                                                                                
      - EGL_CHROMIUM_sync_control                                                                                                                                                                                                                                              
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_cl_event2
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: X.Org
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
```

**Description of the problem:**

When launching an activity, the android container dies unexpectedly.

**Expected:**

The activity should launch

**Additional info:**

Running on Fedora 25.

```
~ # ANBOX_LOG_LEVEL=debug anbox container-manager --data-path=/var/snap/anbox/common/ --android-image=/var/lib/snapd/snap/anbox/15/android.img
[DD 2017-04-12 16:58:22] [service.cpp:49@create] Everything setup. Waiting for incoming connections.
[DD 2017-04-12 16:58:32] [service.cpp:76@new_client] Got connection from pid 6961
[DD 2017-04-12 16:58:33] [lxc_container.cpp:90@start] Containers are stored in /var/snap/anbox/common/containers
[DD 2017-04-12 16:58:33] [lxc_container.cpp:127@start] Using rootfs path /var/snap/anbox/common/rootfs
[DD 2017-04-12 16:58:33] [lxc_container.cpp:194@start] Container successfully started
```

```
~ $ ANBOX_LOG_LEVEL=debug anbox session-manager
[DD 2017-04-12 16:58:32] [gl_renderer_server.cpp:82@GLRendererServer] Using GLES-to-GL translator for rendering
[DD 2017-04-12 16:58:32] [Renderer.cpp:113@initialize] EGL doesn't support surfaceless context
[DD 2017-04-12 16:58:33] [Renderer.cpp:249@initialize] Successfully initialized EGL
```

```
~ $ ANBOX_LOG_LEVEL=debug anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
[DD 2017-04-12 17:11:49] [launch.cpp:96@operator()] Android hasn't fully booted yet. Waiting a bit..
[WW 2017-04-12 17:12:19] [launch.cpp:115@operator()] Stop waiting as we're already waiting for too long. Something is wrong
[WW 2017-04-12 17:12:19] [launch.cpp:116@operator()] with your setup and the container may have failed to boot.
```

Snippet of `/var/snap/anbox/common/logs/container.log`:

```
            lxc 20170412165833.923 INFO     lxc_conf - conf.c:mount_file_entries:1985 - mount points have been setup
            lxc 20170412165833.923 INFO     lxc_conf - conf.c:fill_autodev:1199 - Creating initial consoles under container /dev
            lxc 20170412165833.923 INFO     lxc_conf - conf.c:fill_autodev:1210 - Populating container /dev
            lxc 20170412165833.924 INFO     lxc_conf - conf.c:fill_autodev:1247 - Populated container /dev
            lxc 20170412165833.924 INFO     lxc_conf - conf.c:setup_dev_console:1495 - console has been setup
            lxc 20170412165833.925 INFO     lxc_utils - utils.c:mount_proc_if_needed:1785 - I am 1, /proc/self points to '1'
            lxc 20170412165833.109 DEBUG    lxc_conf - conf.c:setup_rootfs_pivot_root:1108 - pivot_root syscall to '/var/snap/anbox/common/lxc/' successful
            lxc 20170412165833.109 INFO     lxc_conf - conf.c:setup_tty:1053 - 0 tty(s) has been setup
            lxc 20170412165833.109 DEBUG    lxc_conf - conf.c:setup_caps:2144 - capabilities have been setup
            lxc 20170412165833.109 NOTICE   lxc_conf - conf.c:lxc_setup:3977 - 'default' is setup.
            lxc 20170412165833.109 INFO     lxc_start - start.c:do_start:836 - Unshared CLONE_NEWCGROUP.
            lxc 20170412165833.109 NOTICE   lxc_start - start.c:start:1428 - Exec'ing "/anbox-init.sh".
            lxc 20170412165833.138 NOTICE   lxc_start - start.c:post_start:1439 - Started "/anbox-init.sh" with pid "6991".
            lxc 20170412165833.138 WARN     lxc_start - start.c:signal_handler:322 - Invalid pid for SIGCHLD. Received pid 6985, expected pid 6991.
            lxc 20170412165833.138 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:893 - Peer has disconnected.
            lxc 20170412165833.138 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:893 - Peer has disconnected.
            lxc 20170412165833.138 DEBUG    lxc_commands - commands.c:lxc_cmd_get_state:578 - Container "default" is in "RUNNING" state.
            lxc 20170412165833.483 DEBUG    lxc_start - start.c:signal_handler:326 - Container init process 6991 exited.
            lxc 20170412165833.483 DEBUG    lxc_start - start.c:__lxc_start:1387 - Pushing physical nics back to host namespace
            lxc 20170412165833.483 DEBUG    lxc_start - start.c:__lxc_start:1390 - Tearing down virtual network devices used by container "default".
            lxc 20170412165833.483 INFO     lxc_conf - conf.c:lxc_delete_network:3005 - Interface "(null)" with index 13 already deleted or existing in different network namespace.
            lxc 20170412165833.518 INFO     lxc_conf - conf.c:lxc_delete_network:3040 - Removed interface "vethVQ02IG" from host.
            lxc 20170412165833.518 INFO     lxc_error - error.c:lxc_error_set_and_log:49 - Child <6991> ended on error (1).
```
