### ISSUE TITLE
No runtime directory specified

### ISSUE THREAD

**Issue by tuxutku** [anbox/anbox#597]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
[utku@utku ~]$ sudo anbox system-info
version: local-b21e5d9
os:
  name: Antergos Linux
  version: 18.1-ISO-Rolling
  snap-based: false
kernel:
  version: Linux version 4.14.15-1-ARCH (builduser@heftig) (gcc version 7.2.1 20180116 (GCC)) #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 17.3.3
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_required_internalformat
      - GL_OES_surfaceless_context
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_polygon_offset_clamp
      - GL_KHR_no_error

```

**Please describe your problem:**
First i had: `Couldn't get a connection with the session manager`
```
[utku@utku ~]$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
[ 2018-01-29 18:36:43] [launch.cpp:134@operator()] Anbox session manager service isn't running, trying to start it.
^C[ 2018-01-29 18:36:48] [launch.cpp:134@operator()] Anbox session manager service isn't running, trying to start it.
^X[ 2018-01-29 18:36:53] [launch.cpp:134@operator()] Anbox session manager service isn't running, trying to start it.
[ 2018-01-29 18:36:58] [launch.cpp:206@operator()] Couldn't get a connection with the session manager
```
Then i have fallowed #123 and #270 , downloaded https://github.com/anbox/anbox/blob/master/scripts/anbox-bridge.sh and runned:
```
[utku@utku ~]$ sudo  '/home/utku/Programlar/anbox-bridge.sh' start
[sudo] password for utku: 
```
Lastly i stuck at `No runtime directory specified`:
```
[utku@utku ~]$ sudo  anbox session-manager
[ 2018-01-29 18:47:03] [daemon.cpp:58@Run] No runtime directory specified
```

**Additional info:**
output of `anbox session-manager` is:
```
[utku@utku ~]$ anbox session-manager
[ 2018-01-29 19:18:51] [daemon.cpp:58@Run] Failed to connect to socket /run/anbox-container.socket: Connection refused
```

I have builded anbox with patch given here: https://aur.archlinux.org/packages/anbox-git/

also someone else had this problem before but with different system and time: #282 

>Here's a fixed up build. I've combined everything here along with a couple of really hacky changes I had to make (namely copying a boost header and editing it, and including that edited copy instead).
I realize that Ubuntu/Debian are stable, but it's at a point with boost right now that they're using very diverged versions.
https://gist.github.com/ilikenwf/77cb7aedb8ab02c6fcd8b3fb3679f6c7
