### ISSUE TITLE
system.log: Could not register INotify for /dev/input.  errno=13

### ISSUE THREAD

**Issue by pellaeon** [anbox/anbox#603]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
version: 3
snap-revision: 67
os:
  name: Ubuntu
  version: 16.04.3 LTS (Xenial Xerus)
  snap-based: true
kernel:
  version: Linux version 4.4.0-112-generic (buildd@lgw01-amd64-010) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) ) #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_swap_region
      - EGL_NOK_texture_from_pixmap
      - EGL_NV_post_sub_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: nouveau
    vendor: OpenGL ES-CM 1.1 Mesa 17.2.4
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_polygon_offset_clamp
      - GL_KHR_no_error
```

**Please describe your problem:**
`anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity` would yield the generic `Stop waiting as we're already waiting for too long. Something is wrong` error.

Digging deeper into `system.log`, I found:
```
02-01 00:35:11.248  9712  9712 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 9712 (system_server)
02-01 00:35:11.248    15    15 W         : debuggerd: handling request: pid=9712 uid=1000 gid=1000 tid=9712
02-01 00:35:11.252  9742  9742 E         : debuggerd: Unable to connect to activity manager (connect failed: No such file or directory)
02-01 00:35:11.302  9742  9742 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-01 00:35:11.302  9742  9742 F DEBUG   : Build fingerprint: 'Android/anbox_x86_64/x86_64:7.1.1/N6F26Q/ubuntu07131118:userdebug/test-keys'
02-01 00:35:11.302  9742  9742 F DEBUG   : Revision: '0'
02-01 00:35:11.302  9742  9742 F DEBUG   : ABI: 'x86_64'
02-01 00:35:11.302  9742  9742 F DEBUG   : pid: 9712, tid: 9712, name: system_server  >>> system_server <<<
02-01 00:35:11.302  9742  9742 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
02-01 00:35:11.303  9742  9742 F DEBUG   : Abort message: 'Could not register INotify for /dev/input.  errno=13'
02-01 00:35:11.303  9742  9742 F DEBUG   :     rax 0000000000000000  rbx 00007f597be1fbe8  rcx 00007f597942ea07  rdx 0000000000000006
02-01 00:35:11.303  9742  9742 F DEBUG   :     rsi 00000000000025f0  rdi 00000000000025f0
02-01 00:35:11.303  9742  9742 F DEBUG   :     r8  0000000000000000  r9  00007f597bc74090  r10 0000000000000008  r11 0000000000000206
02-01 00:35:11.303  9742  9742 F DEBUG   :     r12 00000000000025f0  r13 0000000000000006  r14 00007f5978351ddd  r15 00007ffda105f0d8
02-01 00:35:11.303  9742  9742 F DEBUG   :     cs  0000000000000033  ss  000000000000002b
02-01 00:35:11.303  9742  9742 F DEBUG   :     rip 00007f597942ea07  rbp 000000000000000d  rsp 00007ffda105ea28  eflags 0000000000000206
02-01 00:35:11.304  9742  9742 F DEBUG   :
02-01 00:35:11.304  9742  9742 F DEBUG   : backtrace:
02-01 00:35:11.304  9742  9742 F DEBUG   :     #00 pc 000000000008da07  /system/lib64/libc.so (tgkill+7)
02-01 00:35:11.304  9742  9742 F DEBUG   :     #01 pc 000000000008a4a1  /system/lib64/libc.so (pthread_kill+65)
02-01 00:35:11.304  9742  9742 F DEBUG   :     #02 pc 00000000000302c1  /system/lib64/libc.so (raise+17)
02-01 00:35:11.304  9742  9742 F DEBUG   :     #03 pc 00000000000287fd  /system/lib64/libc.so (abort+77)
02-01 00:35:11.304  9742  9742 F DEBUG   :     #04 pc 000000000001011f  /system/lib64/libcutils.so (__android_log_assert+287)
02-01 00:35:11.304  9742  9742 F DEBUG   :     #05 pc 00000000000298e5  /system/lib64/libinputflinger.so (_ZN7android8EventHubC1Ev+629)
02-01 00:35:11.304  9742  9742 F DEBUG   :     #06 pc 0000000000019036  /system/lib64/libandroid_servers.so (_ZN7android18NativeInputManagerC1EP8_jobjectS2_RKNS_2spINS_6LooperEEE+358)
02-01 00:35:11.304  9742  9742 F DEBUG   :     #07 pc 000000000001d340  /system/lib64/libandroid_servers.so
02-01 00:35:11.304  9742  9742 F DEBUG   :     #08 pc 000000000136f880  /system/framework/oat/x86_64/services.odex (offset 0xd00000)
02-01 00:35:11.416    15    15 W         : debuggerd: resuming target 9712
02-01 00:35:11.519    33    33 I lowmemorykiller: ActivityManager disconnected
02-01 00:35:11.519    33    33 I lowmemorykiller: Closing Activity Manager data connection
02-01 00:35:11.519    41    41 E         : eof
02-01 00:35:11.519    41    41 E         : failed to read size
02-01 00:35:11.519    41    41 I         : closing connection
02-01 00:35:11.519    34    34 I ServiceManager: service 'otadexopt' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'package' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'user' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'activity' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'procstats' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'meminfo' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'gfxinfo' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'dbinfo' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'cpuinfo' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'permission' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'processinfo' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'sensorservice' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'battery' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'usagestats' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'webviewupdate' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'scheduling_policy' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'telephony.registry' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'media.camera.proxy' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'account' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'content' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'consumer_ir' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'alarm' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'batterystats' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'appops' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'power' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'display' died
02-01 00:35:11.519    34    34 I ServiceManager: service 'vibrator' died
02-01 00:35:11.519  9681  9681 I Zygote  : Process 9712 exited due to signal (6)
02-01 00:35:11.519  9681  9681 I Zygote  : Process 9712 dumped core.
02-01 00:35:11.519  9681  9681 E Zygote  : Exit zygote because system server (9712) has terminated
```

**What were you expecting?:**
Activity manager starts.

**Additional info:**
