### ISSUE TITLE
Problem building anbox-modules-binder against 4.15.2

### ISSUE THREAD

**Issue by neroita** [anbox/anbox#608]
Hi , I've a laptop that need latest 4.15 series kernel to work well ( touchpad hangs with previous kernel ).
I have a ubuntu 17.10 stock with 4.15.2 kernel , when I try to install anbox it hangs on compiling anbox-modules-binder .

When I build the module I get:

make -C /lib/modules/4.15.2-041502-lowlatency/build V=0 M=$PWD
make[1]: ingresso nella directory "/usr/src/linux-headers-4.15.2-041502-lowlatency"
  CC [M]  /usr/src/anbox-modules-binder-9.orig/deps.o
  CC [M]  /usr/src/anbox-modules-binder-9.orig/binder.o
In file included from ./include/linux/module.h:18:0,
                 from /usr/src/anbox-modules-binder-9.orig/binder.c:28:
/usr/src/anbox-modules-binder-9.orig/binder.c:140:39: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
 module_param_call(stop_on_user_error, binder_set_stop_on_user_error,
                                       ^
./include/linux/moduleparam.h:233:24: note: in definition of macro ‘module_param_call’
   { .flags = 0, .set = _set, .get = _get };  \
                        ^~~~
/usr/src/anbox-modules-binder-9.orig/binder.c:140:39: note: (near initialization for ‘__param_ops_stop_on_user_error.set’)
 module_param_call(stop_on_user_error, binder_set_stop_on_user_error,
                                       ^
./include/linux/moduleparam.h:233:24: note: in definition of macro ‘module_param_call’
   { .flags = 0, .set = _set, .get = _get };  \
                        ^~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:316: set di istruzioni per l'obiettivo "/usr/src/anbox-modules-binder-9.orig/binder.o" non riuscito
make[2]: *** [/usr/src/anbox-modules-binder-9.orig/binder.o] Errore 1
Makefile:1514: set di istruzioni per l'obiettivo "_module_/usr/src/anbox-modules-binder-9.orig" non riuscito
make[1]: *** [_module_/usr/src/anbox-modules-binder-9.orig] Errore 2
make[1]: uscita dalla directory "/usr/src/linux-headers-4.15.2-041502-lowlatency"
Makefile:8: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2

Are there any patch available to build against 4.15 series ?
thank's.

```
anbox system-info
version: 3
snap-revision: 69
os:
  name: Ubuntu
  version: 17.10 (Artful Aardvark)
  snap-based: true
kernel:
  version: Linux version 4.15.2-041502-lowlatency (kernel@kathleen) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3.1)) #201802072230 SMP PREEMPT Wed Feb 7 22:34:21 UTC 2018
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 17.2.4
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_polygon_offset_clamp
      - GL_KHR_no_error
```
