### ISSUE TITLE
Segmentation Error and Can't Run Apps.

### ISSUE THREAD

**Issue by isogit123** [anbox/anbox#664]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
[version: 3
snap-revision: 72
os:
  name: Ubuntu
  version: 16.04.4 LTS (Xenial Xerus)
  snap-based: true
kernel:
  version: Linux version 4.13.0-37-generic (buildd@lcy01-amd64-012) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)) #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_swap_region
      - EGL_NOK_texture_from_pixmap
      - EGL_NV_post_sub_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 17.2.8
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_polygon_offset_clamp
      - GL_KHR_no_error]
```

**Please describe your problem:**
When I run Anbox, it opens for a while then a segmentation error happens, and when I run it and try to run an app, the app opens but in a freezing state and it doesn't respond to any mouse or keyboard input.

**What were you expecting?:**
I should be able to run an app but this is not the case.

**Additional info:**
Here is the gdb output and back trace after core dumping the segmentation fault.
```
           PID: 13116 (anbox)
           UID: 1000 (islam)
           GID: 1000 (islam)
        Signal: 11 (SEGV)
     Timestamp: Wed 2018-03-28 18:05:59 EET (17s ago)
  Command Line: /snap/anbox/72/usr/bin/anbox session-manager
    Executable: /snap/anbox/72/usr/bin/anbox
 Control Group: /
         Slice: -.slice
       Boot ID: f60b030fdb66418e895cc60417343356
    Machine ID: 0b1ed51f153c490e8d46eddcc797a1eb
      Hostname: islam-Inspiron-5537
      Coredump: /var/lib/systemd/coredump/core.anbox.1000.f60b030fdb66418e895cc60417343356.13116.1522253159000000000000.xz
       Message: Process 13116 (anbox) of user 1000 dumped core.
                
                Stack trace of thread 13136:
                #0  0x00007fad2e56ee27 __memmove_avx_unaligned (libc.so.6)
                #1  0x000000000057bd7a _ZN5anbox4qemu21QemudMessageProcessor16process_commandsEv (anbox)
                #2  0x000000000057be56 _ZN5anbox4qemu21QemudMessageProcessor12process_dataERKSt6vectorIhSaIhEE (anbox)
                #3  0x000000000050e601 _ZN5anbox7network16SocketConnection12on_read_sizeERKN5boost6system10error_codeEm (anbox)
                #4  0x00000000005671be _ZN5boost4asio6detail23reactive_socket_recv_opINS0_17mutable_buffers_1ESt8functionIFvRKNS_6system10error_codeEmEEE11do_completeEPNS1_15task_io_serviceEPNS1_25task_io_service_operationES8_m (anbox)
                #5  0x00000000004f5e95 _ZN12_GLOBAL__N_118exception_safe_runERN5boost4asio10io_serviceE (anbox)
                #6  0x00007fad2eab9c80 n/a (/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21)

GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /snap/anbox/72/usr/bin/anbox...(no debugging symbols found)...done.
[New LWP 13136]
[New LWP 13116]
[New LWP 13245]
[New LWP 13130]
[New LWP 13133]
[New LWP 13132]
[New LWP 13135]
[New LWP 13134]
[New LWP 13139]
[New LWP 13137]
[New LWP 13131]
[New LWP 13138]
[New LWP 13246]

warning: .dynamic section for "/usr/lib/x86_64-linux-gnu/libstdc++.so.6" is not at the expected address (wrong library or version mismatch?)

warning: .dynamic section for "/lib/x86_64-linux-gnu/libgcc_s.so.1" is not at the expected address (wrong library or version mismatch?)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/snap/anbox/72/usr/bin/anbox session-manager'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __memmove_avx_unaligned ()
    at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:351
351	../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S: No such file or directory.
[Current thread is 1 (Thread 0x7fad127fc700 (LWP 13136))]
(gdb) bt
#0  __memmove_avx_unaligned ()
    at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:351
#1  0x000000000057bd7a in anbox::qemu::QemudMessageProcessor::process_commands() ()
#2  0x000000000057be56 in anbox::qemu::QemudMessageProcessor::process_data(std::vector<unsigned char, std::allocator<unsigned char> > const&) ()
#3  0x000000000050e601 in anbox::network::SocketConnection::on_read_size(boost::system::error_code const&, unsigned long) ()
#4  0x00000000005671be in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, std::function<void (boost::system::error_code const&, unsigned long)> >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) ()
#5  0x00000000004f5e95 in (anonymous namespace)::exception_safe_run(boost::asio::io_service&) ()
#6  0x00007fad2eab9c80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00000000016cdd20 in ?? ()
#8  0x628488d2db14a5be in ?? ()
#9  0x6284cc6dcd2ea5be in ?? ()
#10 0x0000000000000000 in ?? ()
```
