### ISSUE TITLE
Latest git doesn't run on Solus

### ISSUE THREAD

**Issue by A-Shahbazi** [anbox/anbox#689]
** Please paste the result of `anbox system-info` below:**
```
version: local-b5ea0b4
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7 CPU       Q 740  @ 1.73GHz
  features: 
os:
  name: Solus
  version: 3.9999
  snap-based: false
kernel:
  version: Linux version 4.16.15-76.current (root@builder.solus-project.com) (gcc version 7.3.0 (Solus)) #1 SMP PREEMPT Tue Jun 12 20:51:13 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_EXT_buffer_age
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_image_dma_buf_export
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
```
I managed to compile latest git version on Solus distro.
Here's what I had to change for the source to compile(after installing the dependencies):
```diff
--- a/CMakeLists.txt	2018-04-22 10:08:04.186672000 +0430
+++ b/CMakeLists.txt	2018-04-22 22:45:29.813934750 +0430
@@ -113,7 +113,7 @@
 
 add_subdirectory(external)
 add_subdirectory(src)
-add_subdirectory(tests)
+#add_subdirectory(tests)
 add_subdirectory(android)
 
 if (NOT "${HOST_CMAKE_C_COMPILER}" STREQUAL "")
```

I also had to change the destination of kernel modules install path:
```diff
--- a/kernel/ashmem/Makefile	2018-04-22 22:51:00.021926475 +0430
+++ b/kernel/ashmem/Makefile	2018-04-21 22:05:18.592788940 +0430
@@ -8,7 +8,8 @@
 	$(MAKE) -C $(KERNEL_SRC) V=0 M=$$PWD
 
 install:
-	cp ashmem_linux.ko $(DESTDIR)/
+#	cp ashmem_linux.ko $(DESTDIR)/
+	cp ashmem_linux.ko /lib/modules/$(shell uname -r)/extra
 
 clean:
 	rm -rf deps.h *.o *.ko *.mod.c *.symvers *.order .*.cmd .tmp_versions
--- a/kernel/binder/Makefile	2018-04-22 22:53:26.024922816 +0430
+++ b/kernel/binder/Makefile	2018-04-21 22:03:25.501791774 +0430
@@ -8,7 +8,8 @@
 	$(MAKE) -C $(KERNEL_SRC) V=0 M=$$PWD
 
 install:
-	cp binder_linux.ko $(DESTDIR)/
+#	cp binder_linux.ko $(DESTDIR)/
+	cp binder_linux.ko /lib/modules/$(shell uname -r)/extra
 
 clean:
 	rm -rf deps.h *.o *.ko *.mod.c *.symvers *.order .*.cmd .tmp_versions
```

After compiling and installing the anbox I placed android.img in /var/lib/anbox/ and ran the following:
```bash
sudo modprobe binder_linux
sudo modprobe ashmem_linux
sudo anbox container-manager --daemon --privileged --data-path=/var/lib/anbox
anbox session-manager
```
The output of the recent command is the following:
```bash
[ 2018-08-25 10:02:45] [Renderer.cpp:141@initialize] Failed to create context: error=0x3005
Stack trace (most recent call last) in thread 27502:
#7    Object "", at 0xffffffffffffffff, in 
#6    Object "/usr/lib64/libc.so.6", at 0x7f59c13e0cee, in clone
#5    Object "/usr/lib64/libpthread.so.0", at 0x7f59c21536c9, in __pthread_get_minstack
#4    Source "/home/*****/src/Anbox/source/anbox/external/android-emugl/shared/emugl/common/thread_pthread.cpp", line 124, in emugl::Thread::thread_main(void*) [0x57d830]
        121: // static
        122: void* Thread::thread_main(void *arg) {
        123:     Thread* self = reinterpret_cast<Thread*>(arg);
      > 124:     intptr_t ret = self->main();
        125: 
        126:     pthread_mutex_lock(&self->mLock);
        127:     self->mIsRunning = false;
#3    Source "/home/*****/src/Anbox/source/anbox/src/anbox/graphics/emugl/RenderThread.cpp", line 80, in RenderThread::main() [0x4a7f4a]
         77:         readBuf.consume(last);
         78:       }
         79: 
      >  80:       last = threadInfo.m_rcDec.decode(readBuf.buf(), readBuf.validData(), m_stream);
         81:       if (last > 0) {
         82:         readBuf.consume(last);
         83:         progress = true;
#2    Source "/home/*****/src/Anbox/source/anbox/build/external/android-emugl/host/libs/renderControl_dec/renderControl_dec.cpp", line 149, in renderControl_decoder_context_t::decode(void*, unsigned long, IOStream*) [0x579ad3]
#1    Source "/home/*****/src/Anbox/source/anbox/src/anbox/graphics/emugl/RenderControl.cpp", line 161, in rcGetNumConfigs(unsigned int*) [0x503cb1]
        158: static EGLint rcGetNumConfigs(uint32_t *p_numAttribs) {
        159:   int numConfigs = 0, numAttribs = 0;
        160: 
      > 161:   renderer->getConfigs()->getPackInfo(&numConfigs, &numAttribs);
        162:   if (p_numAttribs) {
        163:     *p_numAttribs = static_cast<uint32_t>(numAttribs);
        164:   }
#0    Source "/home/*****/src/Anbox/source/anbox/src/anbox/graphics/emugl/RendererConfig.cpp", line 214, in RendererConfigList::getPackInfo(int*, int*) const [0x506865]
        211: void RendererConfigList::getPackInfo(EGLint* numConfigs,
        212:                                      EGLint* numAttributes) const {
        213:   if (numConfigs) {
      > 214:     *numConfigs = mCount;
        215:   }
        216:   if (numAttributes) {
        217:     *numAttributes = static_cast<EGLint>(kConfigAttributesLen);
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault
```
What is exactly wrong!?
