### ISSUE TITLE
anbox session-manager Failed to Initialize backend EGL display 

### ISSUE THREAD

**Issue by meshwara** [anbox/anbox#72]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the
list of open bugs at https://github.com/anbox/anbox/issues

**Anbox release (`anbox version`) and system info (`anbox system-info`):**

version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.4.0-72-generic (buildd@lcy01-17) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

**Description of the problem:**
Graphics egl or gles2 not available, so when I run anbox session-manager, it failed
`anbox session-manager`
`[EE 2017-04-13 05:31:33] [Renderer.cpp:100@initialize] Failed to Initialize backend EGL display
Segmentation fault`

**Expected:**
anbox session-manager running without error

**Additional info:**
I'm using Nvidia GeForce 930M with additional driver active, on Ubuntu 16.04 64bit

**Comment by jbevren** [comment]
Same here.  My system-info matches meshwara's.  Can provide additional information on request.
My hardware varies slightly:
GPU0: NVIDIA GPU GeForce GTX 650 Ti (GK106) at PCI:1:0:0 (GPU-0)
 Two 1920x1080 displays, landscape (standard) orientation
GPU1: NVIDIA GPU GeForce GT 610 (GF119) at PCI:2:0:0 (GPU-1)
 Two 900x1440 displays (1440x900 rotated 90 ccw for document review)

**Comment by jbevren** [comment]
I found the issue:  It's not an issue with Anbox it seems.  I'm in a 64-bit system so this may need to be done differently in x86/32bit systems.  The fix for myself was:
root@epicfail:/usr/lib/nvidia-375# mv libEGL.so.1 libEGL.so.1.orig
root@epicfail:/usr/lib/nvidia-375# ln -sf libEGL.so.375.39 libEGL.so.1

Seems like NVidia are their usual masters of "standards" :-1: 

As always, more info is available upon request

**Comment by canDry** [comment]
@jbevren I'm using the 367 release and there are no libEGL.so files in /usr/lib/nvidia-367.  The error I'm seeing is:
[EE 2017-04-12 20:36:26] [Renderer.cpp:191@initialize] Failed: Missing egl_image related extension(s)
Segmentation fault

**Comment by lieff** [comment]
Same here, 16.04 and 17.04 cannot initialize egl with nvidia.

**Comment by zarinfam** [comment]
Thanks @jbevren . your solution works for me.

**Comment by daedroza** [comment]
If anyone is using the solution provided by @jbevren on Linux Mint 18.1, it is possible that it will break your Cinnamon DE at early boot causing Cinnamon to run in fall back mode (with auto login turned ON).

**Comment by kholisrag** [comment]
The solution by @jbevren is working
If you use nvdia gpu, just install nvdia 375, because it's the LTS support, when I use the latest driver from ppa nvdia 38x , it not work...
I using elemntary os loki 0.4.1 based on ubuntu 16.04.2 with my asus x450jb with nvidia 940M, here is my `anbox system-info ` : 

version: local-19547a3
snap-revision: 26
os:
  name: elementary OS
  version: 0.4.1 Loki
  snap-based: true
kernel:
  version: Linux version 4.4.0-78-generic (buildd@lgw01-11) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: NVIDIA
    version: 1.4
    extensions:
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_output_base
      - EGL_EXT_stream_acquire_mode
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context_no_error
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_partial_update
      - EGL_KHR_swap_buffers_with_damage
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_stream
      - EGL_KHR_stream_consumer_gltexture
      - EGL_KHR_stream_cross_process_fd
      - EGL_KHR_stream_fifo
      - EGL_KHR_stream_producer_eglsurface
      - EGL_KHR_surfaceless_context
      - EGL_NV_post_sub_buffer
      - EGL_NV_stream_metadata
      - EGL_NV_stream_sync
      - EGL_NV_stream_consumer_gltexture_yuv
      - EGL_NV_stream_attrib
      - EGL_NV_sync
      - EGL_NV_system_time
      - EGL_NV_output_drm_flip_event
      - EGL_WL_bind_wayland_display
      - EGL_WL_wayland_eglstream
  gles2:
    vendor: NVIDIA Corporation
    vendor: OpenGL ES 1.1 NVIDIA 375.66
    extensions:
      - GL_EXT_debug_label
      - GL_EXT_map_buffer_range
      - GL_EXT_robustness
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_format_BGRA8888
      - GL_KHR_debug
      - GL_NV_texture_compression_s3tc
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_compressed_paletted_texture
      - GL_OES_draw_texture
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_element_index_uint
      - GL_OES_extended_matrix_palette
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_matrix_get
      - GL_OES_matrix_palette
      - GL_OES_packed_depth_stencil
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_OES_rgb8_rgba8
      - GL_OES_read_format
      - GL_OES_stencil8
      - GL_OES_texture_cube_map
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float

So it's not the anbox problem... its nvidia driver problem...

**Comment by D0048** [comment]
The same even after nvidia-375 installed. A possible work around is just to switch to the build-in graphic card on the mother board.

**Comment by saitejalakkimsetty** [comment]
Got the same problem.

```
libEGL warning: DRI2: failed to authenticate
version: 3
snap-revision: 52
os:
  name: Ubuntu
  version: 17.04 (Zesty Zapus)
  snap-based: true
kernel:
  version: Linux version 4.10.0-32-generic (buildd@lcy01-05) (gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) ) #36-Ubuntu SMP Tue Aug 8 12:10:06 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_MESA_configless_context
  gles2:
    vendor: VMware, Inc.
    vendor: OpenGL ES-CM 1.1 Mesa 17.0.7
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
```
**Additional info:**
Windows 10 Pro 1703 Build 15063.540
Oracle VirtualBox Version 5.1.26 r117224 (Qt5.6.2)
Intel HD Graphics 530

Any help is appreciated!

**Comment by saitejalakkimsetty** [comment]
Interestingly, ***anbox (53)*** opens up on VMware. But when apps are opened, anbox UI crashes.
```
version: 3
snap-revision: 53
os:
  name: Ubuntu
  version: 17.04 (Zesty Zapus)
  snap-based: true
kernel:
  version: Linux version 4.10.0-32-generic (buildd@lcy01-05) (gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) ) #36-Ubuntu SMP Tue Aug 8 12:10:06 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_swap_region
      - EGL_NOK_texture_from_pixmap
      - EGL_NV_post_sub_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: VMware, Inc.
    vendor: OpenGL ES-CM 1.1 Mesa 17.0.7
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
```
**Additional info:**
Windows 10 Pro 1703 Build 15063.540
VMware Workstation Pro 12.5.7 build-5813279
Intel HD Graphics 530

I installed anbox (53) on VirtualBox, but it still crashes. (behavior is different from VMware)

**Comment by HaluDeCassia** [comment]
Hello, guys
I have the same issue. But I'm not use a Nvidia driver. My driver is a Intel Graphics. So what's happening
?

The error is:
`[Renderer.cpp:191@initialize] Failed: Missing egl_image related extension(s)
Segmentation fault`

What the problem here, any idea?

**Comment by nanu-c** [comment]
shame on nvidia

**Comment by salamanderrake** [comment]
Since HaluDeCassia pointed out its not an NVidia issue, it must be an anbox issue.

**Comment by lieff** [comment]
I think in case of Nvidia card it's snap sandbox issue: driver works badly in that sandbox. In case of Intel - it can be sandbox or missed egl extension.

**Comment by gotwig** [comment]
Still broken. Nothing works. broken software.

**Comment by GrigorievNick** [comment]
Same here 
$ anbox system-info
version: 3
snap-revision: 65
os:
  name: Ubuntu
  version: 17.10 (Artful Aardvark)
  snap-based: true
kernel:
  version: Linux version 4.13.0-17-generic (buildd@lcy01-amd64-011) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3)) #20-Ubuntu SMP Mon Nov 6 10:04:08 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

**Comment by LiangPingPiJiu** [comment]
Hi,

I have similiar problems and I'm kind of frustrated after trying for hours to get anbox run.
I have a virtualBox running on a debian stretch host (64Bit).
As guests I first tried Ubuntu 17.10 and 16.04 later, installed with snap. The errors seemed to be more or less the same, so that I assume a specific virtualBox problem.
Of course, I have guest additions installed on both guests systems and reinstalled them several times, rebooted a lot...
In the beginning I the had same errors on both systems after starting anbox session-manager:
`
$ anbox session-manager
libEGL warning: DRI2: failed to authenticate
[ 2017-12-28 19:33:54] [Renderer.cpp:190@initialize] Failed: Missing egl_image related extension(s)
Segmentation fault (core dumped)
`

The hardware acceleration and guest additions seemed to be ok. As I tested on the 16.04:
`
OpenGL vendor string:   Humper
OpenGL renderer string: Chromium
OpenGL version string:  2.1 Chromium 1.9

Not software rendered:    yes
Not blacklisted:          yes
GLX fbconfig:             yes
GLX texture from pixmap:  yes
GL npot or rect textures: yes
GL vertex program:        yes
GL fragment program:      yes
GL vertex buffer object:  yes
GL framebuffer object:    yes
GL version is 1.4+:       yes

Unity 3D supported:       yes
`


So later I tried to disable 3D acceleration for the 16.04 guest, which changed "/usr/lib/nux/unity_support_test -p" to

`
OpenGL vendor string:   VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 4.0, 256 bits)
OpenGL version string:  3.0 Mesa 17.0.7

Not software rendered:    no
Not blacklisted:          yes
GLX fbconfig:             yes
GLX texture from pixmap:  yes
GL npot or rect textures: yes
GL vertex program:        yes
GL fragment program:      yes
GL vertex buffer object:  yes
GL framebuffer object:    yes
GL version is 1.4+:       yes

Unity 3D supported:       no
`

Also I tried to give more graphics memory, instead of 16MB in the beginning I tried with 64MB and even 128MB, didn't change anything.

After that the error on the call of anbox session-manager became:

`
$ anbox session-manager
[ 2017-12-28 19:43:40] [Renderer.cpp:190@initialize] Failed: Missing egl_image related extension(s)
Segmentation fault (core dumped)
`

Also I tried to install a lot of packages such as
mesa-utils,
mesa-utils-extra ,
libegl1-mesa-drivers,
libgles2-mesa-dev,
libegl1-mesa

anbox-modules-dkms I reinstalled several times,
`sudo modprobe ashmem_linux`
and
`sudo modprobe binder_linux`
seemed always to work after installation.

Here the output of anbox system-info:
1.) for ubuntu 17.10 (with 3D acceleration enabled):
`
libEGL warning: DRI2: failed to authenticate
version: 3
snap-revision: 65
os:
  name: Ubuntu
  version: 17.10 (Artful Aardvark)
  snap-based: true
kernel:
  version: Linux version 4.13.0-21-generic (buildd@lgw01-amd64-037) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3)) #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_MESA_configless_context
  gles2:
    vendor: VMware, Inc.
    vendor: OpenGL ES-CM 1.1 Mesa 17.0.7
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
`

2.) for ubuntu 16.04 (with 3D acceleration enabled):
`
libEGL warning: DRI2: failed to authenticate
version: 3
snap-revision: 65
os:
  name: Ubuntu
  version: 16.04.3 LTS (Xenial Xerus)
  snap-based: true
kernel:
  version: Linux version 4.10.0-42-generic (buildd@lgw01-amd64-007) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) ) #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_MESA_configless_context
  gles2:
    vendor: VMware, Inc.
    vendor: OpenGL ES-CM 1.1 Mesa 17.0.7
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp

`

3.) and for ubuntu 16.04 (without 3D acceleration enabled), which seems to be more or less the same, except the missing "libEGL warning: DRI2: failed to authenticate" in the beginning:
`
version: 3
snap-revision: 65
os:
  name: Ubuntu
  version: 16.04.3 LTS (Xenial Xerus)
  snap-based: true
kernel:
  version: Linux version 4.10.0-42-generic (buildd@lgw01-amd64-007) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) ) #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_MESA_configless_context
  gles2:
    vendor: VMware, Inc.
    vendor: OpenGL ES-CM 1.1 Mesa 17.0.7
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
`


So I tried a lot, but nothing worked out.
Does anyone have a hint what might be the problem? Would be nice, since I'm already quite frustrated.

LiangPingPiJiu

**Comment by voidplayer** [comment]
@LiangPingPiJiu  any luck? I have the exact same setup and issue

**Comment by LiangPingPiJiu** [comment]
@voidplayer Not yet :(
Thought I give it up first and try it a couple of month later again.

Actually to make it run on ubuntu in a virtual box would just be a test. Later I would love to run it on debian or on a raspbian for a kind of "PiPhone" or raspberry pi tablet, or some other single board computer-phone. :)

LiangPingPiJiu

**Comment by lag-linaro** [comment]
Have you tried using '--gles-driver=translator' on the Session Manager cmdline?

**Comment by chiragtaunk13** [comment]
@lag-linaro solution worked for me, Thanks.

**Comment by 50M3D0RK** [comment]
@lag-linaro can you please go into some more detail? please, sir. thank you.

**Comment by GreatBahram** [comment]
Same here on Ubuntu Bionic Beaver ( on Virtualbox to be honest )
`anbox version`: anbox 3
`anbox system-info`:
```
version: 3
snap-revision: 73
os:
  name: Ubuntu
  version: 16.04.4 LTS (Xenial Xerus)
  snap-based: true
kernel:
  version: Linux version 4.13.0-38-generic (buildd@lgw01-amd64-027) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)) #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
  gles2:
    vendor: VMware, Inc.
    vendor: OpenGL ES-CM 1.1 Mesa 17.2.8
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_polygon_offset_clamp
      - GL_KHR_no_error
```
`anbox session-manager`: 
```
[ 2018-04-10 08:37:51] [Renderer.cpp:190@initialize] Failed: Missing egl_image related extension(s)
Segmentation fault (core dumped)
```
How we should fix this ?
