### ISSUE TITLE
Fails to start on Ubuntu 18.04

### ISSUE THREAD

**Issue by alangibson-philips** [anbox/anbox#766]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info
[anbox-system-diagnostics-2018-06-21.tar.xz.zip](https://github.com/anbox/anbox/files/2122751/anbox-system-diagnostics-2018-06-21.tar.xz.zip)

 `

6. ** Please paste the result of `anbox system-info` below:**
```
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
version: 4
snap-revision: 108
os:
  name: Ubuntu
  version: 18.04 LTS (Bionic Beaver)
  snap-based: true
kernel:
  version: Linux version 4.15.0-23-generic (buildd@lgw01-amd64-055) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 3.2 Mesa 17.2.8
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_texture_3D
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float
      - GL_EXT_texture_sRGB_decode
      - GL_OES_EGL_image
      - GL_OES_depth_texture
      - GL_OES_packed_depth_stencil
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_OES_get_program_binary
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_EXT_frag_depth
      - GL_NV_fbo_color_attachments
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_OES_viewport_array
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_robustness
      - GL_EXT_texture_rg
      - GL_EXT_unpack_subimage
      - GL_NV_draw_buffers
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_EXT_draw_buffers
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_KHR_robustness
      - GL_KHR_texture_compression_astc_ldr
      - GL_OES_depth_texture_cube_map
      - GL_OES_surfaceless_context
      - GL_EXT_color_buffer_float
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_framebuffer_fetch
      - GL_EXT_shader_integer_mix
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_INTEL_conservative_rasterization
      - GL_INTEL_performance_query
      - GL_ANDROID_extension_pack_es31a
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_gpu_shader5
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_shader_io_blocks
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_cube_map_array
      - GL_KHR_blend_equation_advanced
      - GL_KHR_blend_equation_advanced_coherent
      - GL_KHR_context_flush_control
      - GL_KHR_robust_buffer_access_behavior
      - GL_NV_image_formats
      - GL_OES_copy_image
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_gpu_shader5
      - GL_OES_primitive_bounding_box
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_EXT_blend_func_extended
      - GL_EXT_buffer_storage
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_shader_samples_identical
      - GL_KHR_no_error
      - GL_KHR_texture_compression_astc_sliced_3d
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_shader_image_atomic
      - GL_EXT_clip_cull_distance
      - GL_MESA_shader_integer_functions
```

**Please describe your problem:**

`anbox system-manager` crashes

**What were you expecting?:**

`anbox system-manager` should run

**Additional info:**

```
$ anbox session-manager`
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
[ 2018-06-21 08:32:50] [Renderer.cpp:168@initialize] Using a surfaceless EGL context
[ 2018-06-21 08:32:50] [Renderer.cpp:251@initialize] Successfully initialized EGL
[ 2018-06-21 08:32:50] [service.cpp:41@Service] Successfully acquired DBus service name
[ 2018-06-21 08:32:50] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to start container
[ 2018-06-21 08:32:50] [session_manager.cpp:145@operator()] Lost connection to container manager, terminating.
[ 2018-06-21 08:32:50] [daemon.cpp:59@Run] Container is not running
[ 2018-06-21 08:32:50] [session_manager.cpp:145@operator()] Lost connection to container manager, terminating.
```

```
$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
[ 2018-06-21 08:34:57] [launch.cpp:178@operator()] Session manager is not yet running, trying to start it
[ 2018-06-21 08:34:57] [launch.cpp:112@launch_session_manager] Started session manager, will now try to connect ..
[ 2018-06-21 08:35:00] [splash_screen.cpp:50@SplashScreen] Window has no associated renderer yet, creating one ...
[ 2018-06-21 08:35:05] [daemon.cpp:59@Run] Failed to retrieve ready property from application manager
```

**Comment by givanse** [comment]
Adding my info in case it helps:

```
anbox session-manager
libEGL warning: DRI2: failed to authenticate
[ 2018-07-04 18:05:38] [Renderer.cpp:168@initialize] Using a surfaceless EGL context
[ 2018-07-04 18:05:38] [Renderer.cpp:193@initialize] Failed: Missing egl_image related extension(s)
[ 2018-07-04 18:05:38] [service.cpp:41@Service] Successfully acquired DBus service name
Stack trace (most recent call last) in thread 15444:
#7    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#6    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f1adbf6e41c, in clone
#5    Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7f1adda1e6b9, in 
#4    Object "/snap/anbox/114/usr/bin/anbox", at 0x576230, in emugl::Thread::thread_main(void*)
#3    Object "/snap/anbox/114/usr/bin/anbox", at 0x4a3d0c, in RenderThread::main()
#2    Object "/snap/anbox/114/usr/bin/anbox", at 0x5729ea, in renderControl_decoder_context_t::decode(void*, unsigned long, IOStream*)
#1    Object "/snap/anbox/114/usr/bin/anbox", at 0x4fcc3e, in 
#0    Object "/snap/anbox/114/usr/bin/anbox", at 0x4ff8f5, in RendererConfigList::getPackInfo(int*, int*) const
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault (core dumped)
```

```
anbox system-info
libEGL warning: DRI2: failed to authenticate
version: 4
snap-revision: 114
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  features: 
    - aes
    - ssse3
    - sse4_1
    - sse4_2
    - avx
    - ssse3
    - avx2
os:
  name: Ubuntu
  version: 18.04 LTS (Bionic Beaver)
  snap-based: true
kernel:
  version: Linux version 4.15.0-20-generic (buildd@lgw01-amd64-039) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
  gles2:
    vendor: VMware, Inc.
    vendor: OpenGL ES 3.0 Mesa 17.2.8
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_texture_3D
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float
      - GL_EXT_texture_sRGB_decode
      - GL_OES_EGL_image
      - GL_OES_depth_texture
      - GL_OES_packed_depth_stencil
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_OES_get_program_binary
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_EXT_frag_depth
      - GL_NV_fbo_color_attachments
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_texture_rg
      - GL_EXT_unpack_subimage
      - GL_NV_draw_buffers
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_EXT_draw_buffers
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_depth_texture_cube_map
      - GL_OES_surfaceless_context
      - GL_EXT_color_buffer_float
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_integer_mix
      - GL_EXT_base_instance
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_texture_border_clamp
      - GL_KHR_context_flush_control
      - GL_OES_copy_image
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_texture_border_clamp
      - GL_OES_texture_stencil8
      - GL_EXT_blend_func_extended
      - GL_KHR_no_error
      - GL_EXT_clip_cull_distance
      - GL_MESA_shader_integer_functions
```

**Comment by damko** [comment]
same problem here

**Comment by morphis** [comment]
@alangibson-philips Can you refresh to the latest snap revision 133 and give it another try?

**Comment by damko** [comment]
@alangibson-philips yes I already did. Please see #835. I forgot to report it here as well, I apologize

**Comment by kode54** [comment]
Failing here on Ubuntu 18.04.1, running with the kernel ppa version 4.17, so I can have AMDGPU DC enabled and still use DVI-D dual link.

`sudo snap set anbox debug.enable=true` reports:

```
error: cannot perform the following tasks:
- Run configure hook of "anbox" snap (snap "anbox" has no "configure" hook)
```

**Comment by billythakidd04** [comment]
I've tried to reproduce everything I can but I'm have a similar issue. If this doesn't belong in this ticket let me know and I will be sure to create a new one.

```
thakidd  ~  anbox.appmgr 
[ 2018-08-09 15:22:13] [daemon.cpp:59@Run] Application manager service is not running yet
 thakidd  ~  1  anbox.appmgr 
[ 2018-08-09 15:23:22] [daemon.cpp:59@Run] Application manager service is not running yet
 thakidd  ~  1  anbox.appmgr 
[ 2018-08-09 16:30:11] [launch.cpp:182@operator()] Session manager is not yet running, trying to start it
[ 2018-08-09 16:30:11] [launch.cpp:116@launch_session_manager] Started session manager, will now try to connect ..
[ 2018-08-09 16:30:11] [splash_screen.cpp:50@SplashScreen] Window has no associated renderer yet, creating one ...
[ 2018-08-09 16:31:01] [daemon.cpp:61@Run] Application manager service is not running yet
```
`sudo /snap/bin/anbox.collect-bug-info `
```
This script will collect a few interesting things which developers will
need to have a better insight into the Anbox system when something goes
wrong.

PLEASE NOTE: The collected log files may collect information about your
system. Please have a look before you're sending them to anyone!

Collecting anbox log files ... 
+ cp /var/snap/anbox/common/data/system.log /tmp/tmp.cdtpfwOUj3
cp: cannot stat '/var/snap/anbox/common/data/system.log': No such file or directory
+ true
+ cp /var/snap/anbox/common/containers/lxc-monitord.log /tmp/tmp.cdtpfwOUj3
cp: cannot stat '/var/snap/anbox/common/containers/lxc-monitord.log': No such file or directory
+ true
+ cp /var/snap/anbox/common/logs/container.log /tmp/tmp.cdtpfwOUj3
cp: cannot stat '/var/snap/anbox/common/logs/container.log': No such file or directory
+ true
+ cp /var/snap/anbox/common/logs/console.log* /tmp/tmp.cdtpfwOUj3
cp: cannot stat '/var/snap/anbox/common/logs/console.log*': No such file or directory
+ true
+ /snap/anbox/134/command-anbox.wrapper system-info
+ [ -e /etc/systemd/system/snap.anbox.container-manager.service ]
+ sudo journalctl --no-pager -u snap.anbox.container-manager.service
+ set +x

DONE!

Do you want to include the kernel log of your system? [y/N]
y
+ dmesg
+ set +x
Generating archive with all log files in /home/thakidd ...
  adding: container-manager.log (deflated 17%)
  adding: kernel.log (deflated 79%)
  adding: system-info.log (deflated 67%)
DONE!
```
`System-info`
```
 thakidd ~: anbox system-info
libEGL warning: DRI2: failed to authenticate
version: 4
snap-revision: 134
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 18.04.1 LTS (Bionic Beaver)
  snap-based: true
kernel:
  version: Linux version 4.15.0-30-generic (buildd@lgw01-amd64-060) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #32-Ubuntu SMP Thu Jul 26 17:42:43 UTC 2018
  binder: false
  ashmem: false
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_context_flush_control
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image_base
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
  gles2:
    vendor: VMware, Inc.
    vendor: OpenGL ES 3.0 Mesa 18.0.5
    extensions:
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_base_instance
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_read_format_bgra
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_integer_mix
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_get_program_binary
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
```
