### ISSUE TITLE
Instagram closes window after showing black and distorted part of previous window but keeps running

### ISSUE THREAD

**Issue by aryehklempner** [anbox/anbox#800]
Yes, I've seen issue #459, but that guy had nouveau, kernel 4.10, and Ubuntu 17.04, whereas I have Ubuntu 18.04, kernel 4.15, and Intel graphics drivers, so the situation may well be entirely different.
Trying to enable logs spits out from snappy:
 error: cannot perform the following tasks:
- Run configure hook of "anbox" snap (snap "anbox" has no "configure" hook)
version: 4
snap-revision: 92
os:
  name: Ubuntu
  version: 18.04 LTS (Bionic Beaver)
  snap-based: true
kernel:
  version: Linux version 4.15.0-23-generic (buildd@lgw01-amd64-055) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 3.0 Mesa 17.2.8
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_texture_3D
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float
      - GL_EXT_texture_sRGB_decode
      - GL_OES_EGL_image
      - GL_OES_depth_texture
      - GL_OES_packed_depth_stencil
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_OES_get_program_binary
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_EXT_frag_depth
      - GL_NV_fbo_color_attachments
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_robustness
      - GL_EXT_texture_rg
      - GL_EXT_unpack_subimage
      - GL_NV_draw_buffers
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_EXT_draw_buffers
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_KHR_robustness
      - GL_OES_depth_texture_cube_map
      - GL_OES_surfaceless_context
      - GL_EXT_color_buffer_float
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_integer_mix
      - GL_INTEL_performance_query
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_texture_border_clamp
      - GL_KHR_blend_equation_advanced
      - GL_KHR_context_flush_control
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_multisample_interpolation
      - GL_OES_texture_border_clamp
      - GL_EXT_blend_func_extended
      - GL_KHR_no_error
      - GL_EXT_clip_cull_distance
      - GL_MESA_shader_integer_functions
**Please describe your problem:**
When I launch Instagram, the window becomes black with the upper left part showing a distorted version of part of the session manager UI, then closes after a few seconds, but htop shows com.instagram.android to be still running.
**What were you expecting?:**
I expected Instagram to run, if not perfectly.
**Additional info:**
N/A

**Comment by elliott-wen** [comment]
Potentially it is because Instagram relies on a dynamic library built for
ARM CPU rather than x86.

**Comment by aryehklempner** [comment]
@elliott-wen I was careful to use the x86 APK, so I doubt it.

**Comment by Fratacchione** [comment]
I was about to write the same post. Except for the fact that this happens to me for every app I've installed:
Instagram, Clash Royale, Facebook Lite. ( all of which have been downloaded in x86, nodpi version )

**Comment by aryehklempner** [comment]
@Fratacchione I didn't try any other apps, so we're probably experiencing the same thing. The devs might want you to post the results of `anbox system-info` on your machine, though. I can't check if other apps have the same issue because unfortunately, since then my machine has broken (charger works but battery doesn't charge).

**Comment by elliott-wen** [comment]
Could you dump the logcat info? That would be helpful.

It is a bit weird coz I can run x86 version correctly.

**Comment by Fratacchione** [comment]
Ok. The log was so long I could only select a part of it. Used pastebin to not flood the page with log lines.

https://pastebin.com/1GpZ0Qvh

**Comment by elliott-wen** [comment]
Currently I don’t have too many clues, but for comparison, I attached the logcat info of my machine for reference. 


1.1], X-Android-Sent-Millis=[1531476553047]}
07-13 10:09:13.097    91   136 D ConnectivityService: NetworkAgentInfo [Ethernet () - 100] validation passed
07-13 10:09:14.700    91   143 W AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client; transfer 4, track 48000 Hz, output 44100 Hz
07-13 10:09:19.033    91   459 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.instagram.android/.activity.MainTabActivity (has extras)} from uid 10015 on display 0
07-13 10:09:19.099   927   927 I libprocessgroup: createProcessGroup 10053 927
07-13 10:09:19.099   927   927 E Zygote  : SetSchedulerPolicy not implemented
07-13 10:09:19.100   927   927 W art     : Unexpected CPU variant for X86 using defaults: x86
07-13 10:09:19.107    91   468 I ActivityManager: Start proc 927:com.instagram.android/u0a53 for activity com.instagram.android/.activity.MainTabActivity
07-13 10:09:19.167   927   927 E ACRA    : Initializing ANR detector for process: com.instagram.android
07-13 10:09:19.192   927   927 E SwitchOffConfiguration: Multi-version criteria odd-number of parts: 1
07-13 10:09:19.194   927   959 I art     : Thread[15,tid=959,Native,Thread*=0xe6e36e00,peer=0x12d913a0,"IgExecutor #2"] recursive attempt to load library "/data/app/com.instagram.android-1/lib/x86/libfb.so"
07-13 10:09:19.199   927   967 I art     : Thread[20,tid=967,Runnable,Thread*=0xe6e39100,peer=0x12e00310,"Thread-3"] setPriority(PRIO_PROCESS, 967, -4) failed: Permission denied
07-13 10:09:19.208    91   189 I ActivityManager: START u0 {flg=0x4000000 cmp=com.instagram.android/com.instagram.nux.activity.SignedOutFragmentActivity (has extras)} from uid 10053 on display 0
07-13 10:09:19.229   545   556 W GooglePlayServicesUtil: Google Play Store is missing.
07-13 10:09:19.319   927   993 I OpenGLRenderer: Initialized EGL, version 1.4
07-13 10:09:19.319   927   993 D OpenGLRenderer: Swap behavior 2
07-13 10:09:19.365    91   112 I ActivityManager: Displayed com.instagram.android/com.instagram.nux.activity.SignedOutFragmentActivity: +155ms (total +269ms)
07-13 10:09:19.394   927   927 W ColdStartPerformanceTracer: .                   TOTAL   THREAD
07-13 10:09:19.394   927   927 W ColdStartPerformanceTracer: ____0 00.000 Start    ...     ...   ColdStartPerformanceTracer
07-13 10:09:19.394   927   927 W ColdStartPerformanceTracer: ___27 00.027 Comment  ...     ...   |  init_to_app_created
07-13 10:09:19.394   927   927 W ColdStartPerformanceTracer: ____3 00.030 Comment  ...     ...   |  init_to_main_activity_started
07-13 10:09:19.394   927   927 W ColdStartPerformanceTracer: ___40 00.070 Comment  ...     ...   |  init_to_app_foregrounded
07-13 10:09:19.394   927   927 W ColdStartPerformanceTracer: __155 00.225 Done __225 ms ___60 ms ColdStartPerformanceTracer
07-13 10:09:19.396   927   932 I art     : Do partial code cache collection, code=27KB, data=24KB
07-13 10:09:19.396   927   932 I art     : After code cache collection, code=27KB, data=24KB
07-13 10:09:19.396   927   932 I art     : Increasing code cache capacity to 128KB
07-13 10:09:19.399    91   103 W ActivityManager: Unable to start service Intent { act=com.facebook.rti.fbns.intent.UNREGISTER cmp=com.instagram.android/com.facebook.rti.push.service.FbnsService (has extras) } U=0: not found
07-13 10:09:19.401    91   459 W ActivityManager: Unable to start service Intent { act=com.facebook.push.fbns.ipc.IFbnsAIDLService cmp=com.instagram.android/com.facebook.rti.push.service.FbnsService (has extras) } U=0: not found
07-13 10:09:19.401   927  1000 E FbnsAIDLClientManager: open failed: bindService failure, do unbind to let service shutdown
07-13 10:09:19.401    91   468 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@83c4b1b
07-13 10:09:19.603    91   492 W ActivityManager: Unable to start service Intent { act=com.facebook.push.fbns.ipc.IFbnsAIDLService cmp=com.instagram.android/com.facebook.rti.push.service.FbnsService (has extras) } U=0: not found
07-13 10:09:19.603   927  1000 E FbnsAIDLClientManager: open failed: bindService failure, do unbind to let service shutdown
07-13 10:09:19.603    91   103 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@27064b8
07-13 10:09:20.004    91   468 W ActivityManager: Unable to start service Intent { act=com.facebook.push.fbns.ipc.IFbnsAIDLService cmp=com.instagram.android/com.facebook.rti.push.service.FbnsService (has extras) } U=0: not found
07-13 10:09:20.005   927  1000 E FbnsAIDLClientManager: open failed: bindService failure, do unbind to let service shutdown
07-13 10:09:20.005    91   102 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@6db2291
07-13 10:09:20.806    91   102 W ActivityManager: Unable to start service Intent { act=com.facebook.push.fbns.ipc.IFbnsAIDLService cmp=com.instagram.android/com.facebook.rti.push.service.FbnsService (has extras) } U=0: not found
07-13 10:09:20.807   927  1000 E FbnsAIDLClientManager: open failed: bindService failure, do unbind to let service shutdown
07-13 10:09:20.807    91   492 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@cfc15f6
07-13 10:09:22.408    91   468 W ActivityManager: Unable to start service Intent { act=com.facebook.push.fbns.ipc.IFbnsAIDLService cmp=com.instagram.android/com.facebook.rti.push.service.FbnsService (has extras) } U=0: not found
07-13 10:09:22.408   927  1000 E FbnsAIDLClientManager: open failed: bindService failure, do unbind to let service shutdown
07-13 10:09:22.409    91   102 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@84a7df7
07-13 10:09:22.463   344   344 E PhoneInterfaceManager: [PhoneIntfMgr] getCarrierPackageNamesForIntent: No UICC
07-13 10:09:22.463   344   344 D CarrierSvcBindHelper: No carrier app for: 0
07-13 10:09:22.469    91   122 I InputReader: Reconfiguring input devices.  changes=0x00000010
07-13 10:09:22.512   472   472 I Launcher: Deferring update until onResume
07-13 10:09:22.512   472   472 I Launcher: Deferring update until onResume

**Comment by virajmalia** [comment]
I may be wrong in what I am about to write, but by reading the logs by @Fratacchione and @elliott-wen and googling a bit I have come to understand the following:

`07-13 10:09:19.099   927   927 E Zygote  : SetSchedulerPolicy not implemented`

This says that there is no policy implemented that would allow the application to perform CPU scheduling.
Then there are these messages that show problems with application threads trying to access the library "libfb.so". Someone should verify if this library is present in the directory in the message below.

`07-13 10:09:19.194   927   959 I art     : Thread[15,tid=959,Native,Thread*=0xe6e36e00,peer=0x12d913a0,"IgExecutor #2"] recursive attempt to load library "/data/app/com.instagram.android-1/lib/x86/libfb.so"
07-13 10:09:19.199   927   967 I art     : Thread[20,tid=967,Runnable,Thread*=0xe6e39100,peer=0x12e00310,"Thread-3"] setPriority(PRIO_PROCESS, 967, -4) failed: Permission denied`

`07-13 10:09:19.399    91   103 W ActivityManager: Unable to start service Intent { act=com.facebook.rti.fbns.intent.UNREGISTER cmp=com.instagram.android/com.facebook.rti.push.service.FbnsService (has extras) } U=0: not found`

Intents and Services are broken. Might be related to missing Google Play Store or missing dynamic libraries. If not, there are missing components in anbox that could make them work.

`07-13 10:09:20.005   927  1000 E FbnsAIDLClientManager: open failed: bindService failure, do unbind to let service shutdown`

"android.os.BinderProxy" is failing. BinderProxy is a used to bind across different process boundaries. This too indicates that there is some sort of problem with processes/IPC/thread scheduling.

An obvious question would be: Why do other applications work while some crash?
Answer: "Well, every application has a different implementation of processes and thread and also their creation during application's runtime. The inability of the application to schedule threads is something where we can start looking into. More logs of other applications and the same applications on working platforms (from a working ARM based phone) would give us more information about what is going on.

**Comment by morphis** [comment]
> This too indicates that there is some sort of problem with processes/IPC/thread scheduling.

The issues you outlined above about thread/scheduler issues are because the container used for the Android system does not have the permission to adjust the thread/process priority. This is not a real issue though an should not cause this bug.

> "android.os.BinderProxy" is failing. BinderProxy is a used to bind across different process boundaries.

The error message you pasted that a specific service is not available and can't be bound. Maybe one of the Google Play framework?

**Comment by elliott-wen** [comment]
I have to apologize because I tweaked the Anbox a little bit to suit my
need. That may cause some confusion.

My only change so far is to use minigbm + libdrm +  mesa + libsync  +
software layer composer as the graphics stack. I am indeed not using the
free form feature of the Anbox.

So could we infer that they may some bugs in the Anbox graphics stack?

**Comment by aryehklempner** [comment]
Well, if there are weird graphics effects, the graphics stack must be affected in some way. The question is whether the problem originates there, and not being a dev, I don't know and it would take ages to just understand the structure of the application due to codebase size not being trivial. Also, I don't know anything about Android; I installed the Anbox in the hope of getting non-web app IG features such as DMs.

**Comment by aryehklempner** [comment]
@elliott-wen How do I make the graphics stack modifications you did? I'm willing to get my hands dirty.

**Comment by elliott-wen** [comment]
I am definitely willing to share my code, possibly by sending a pulling request or creating a fork repo.

But caveats ahead, my code is not well tested and does not have the free form feature as anbox does. Most importantly, it is only tested for Intel-based GPUs.

Nevertheless it works for Facebook, Tinder, and Instagram. :)

**Comment by aryehklempner** [comment]
@elliott-wen please do. I have an Intel GPU and I can build stuff from source, given basic directions such as what make targets there are or whatever build system is used. Also, this is somewhat time-sensitive. Thank you.
P.S. I won't be using Tinder :) Or Facebook, for that matter.

**Comment by aryehklempner** [comment]
Thanks, I really am in a hurry, actually.

**Comment by elliott-wen** [comment]
@aryehklempner

kindly checkout the binary files below. I wish I had more time to create a
set of repos for sharing my changes on source codes. But I am also a bit
busy now.

https://github.com/elliott-wen/anbox-direct-gpu-access

**Comment by Crisdmc** [comment]
```
version: 4
snap-revision: 154
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 18.04.1 LTS (Bionic Beaver)
  snap-based: true
kernel:
  version: Linux version 4.15.0-34-generic (buildd@lgw01-amd64-047) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 3.2 Mesa 18.0.5
    extensions:
      - GL_ANDROID_extension_pack_es31a
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_disjoint_timer_query
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_read_format_bgra
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_framebuffer_fetch
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_shader_samples_identical
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_INTEL_conservative_rasterization
      - GL_INTEL_performance_query
      - GL_KHR_blend_equation_advanced
      - GL_KHR_blend_equation_advanced_coherent
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_KHR_texture_compression_astc_ldr
      - GL_KHR_texture_compression_astc_sliced_3d
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_image_formats
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_get_program_binary
      - GL_OES_gpu_shader5
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_primitive_bounding_box
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array

```

I have the same problem, I used this apk: [https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-63-0-0-17-94-124584-release/instagram-63-0-0-17-94-3-android-apk-download/download/](url)
