### ISSUE TITLE
Anbox said starting but nothing happens.

### ISSUE THREAD

**Issue by gitwasil** [anbox/anbox#821]
I don't know where the problem is. Here is my anbox system-info
```

version: 4
snap-revision: 125
cpu:
  arch:  x86
  brand: Intel(R) Core(TM)2 Duo CPU     E4700  @ 2.60GHz
  features: 
os:
  name: Ubuntu
  version: 16.04.4 LTS (Xenial Xerus)
  snap-based: true
kernel:
  version: Linux version 4.13.0-45-generic (buildd@lgw01-amd64-011) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)) #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions:
      - n/a
  gles2:
    vendor: NVIDIA Corporation
    vendor: OpenGL ES 3.2 NVIDIA 384.130
    extensions:
      - GL_EXT_base_instance
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_color_buffer_half_float
      - GL_EXT_copy_image
      - GL_EXT_debug_label
      - GL_EXT_discard_framebuffer
      - GL_EXT_disjoint_timer_query
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_float_blend
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_indirect
      - GL_EXT_multisample_compatibility
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_protected_textures
      - GL_EXT_render_snorm
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_group_vote
      - GL_EXT_shader_implicit_conversions
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_shader_non_constant_global_initializers
      - GL_EXT_shader_texture_lod
      - GL_EXT_shadow_samplers
      - GL_EXT_sparse_texture
      - GL_EXT_sRGB
      - GL_EXT_sRGB_write_control
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_norm16
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_R8
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_storage
      - GL_EXT_texture_view
      - GL_EXT_draw_transform_feedback
      - GL_EXT_unpack_subimage
      - GL_EXT_window_rectangles
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_NV_bgr
      - GL_NV_blend_equation_advanced
      - GL_NV_conditional_render
      - GL_NV_copy_buffer
      - GL_NV_copy_image
      - GL_NV_draw_buffers
      - GL_NV_draw_instanced
      - GL_NV_draw_texture
      - GL_NV_EGL_stream_consumer_external
      - GL_NV_explicit_attrib_location
      - GL_NV_fbo_color_attachments
      - GL_NV_framebuffer_blit
      - GL_NV_framebuffer_multisample
      - GL_NV_generate_mipmap_sRGB
      - GL_NV_instanced_arrays
      - GL_NV_internalformat_sample_query
      - GL_NV_gpu_shader5
      - GL_NV_image_formats
      - GL_NV_occlusion_query_samples
      - GL_NV_non_square_matrices
      - GL_NV_pack_subimage
      - GL_NV_packed_float
      - GL_NV_packed_float_linear
      - GL_NV_path_rendering
      - GL_NV_pixel_buffer_object
      - GL_NV_polygon_mode
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_NV_shader_noperspective_interpolation
      - GL_NV_shadow_samplers_array
      - GL_NV_shadow_samplers_cube
      - GL_NV_sRGB_formats
      - GL_NV_texture_array
      - GL_NV_texture_barrier
      - GL_NV_texture_border_clamp
      - GL_NV_texture_compression_latc
      - GL_NV_texture_compression_s3tc
      - GL_NV_texture_compression_s3tc_update
      - GL_NV_timer_query
      - GL_NV_viewport_array
      - GL_KHR_blend_equation_advanced
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_OES_depth24
      - GL_OES_depth32
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_copy_image
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_texture_border_clamp
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_buffer
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_gpu_shader5
      - GL_OES_shader_io_blocks
      - GL_OES_texture_view
      - GL_OES_primitive_bounding_box
      - GL_OES_EGL_image
      - GL_OES_EGL_sync
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_get_program_binary
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_surfaceless_context
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_npot
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array
      - GL_ANDROID_extension_pack_es31a

**Comment by gitwasil** [comment]
[anbox-system-diagnostics-2018-07-18.zip](https://github.com/anbox/anbox/files/2207023/anbox-system-diagnostics-2018-07-18.zip)

version: 4
snap-revision: 125
cpu:
  arch:  x86
  brand: Intel(R) Core(TM)2 Duo CPU     E4700  @ 2.60GHz
  features: 
os:
  name: Ubuntu
  version: 16.04.4 LTS (Xenial Xerus)
  snap-based: true
kernel:
  version: Linux version 4.13.0-45-generic (buildd@lgw01-amd64-011) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)) #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions:
      - n/a
  gles2:
    vendor: NVIDIA Corporation
    vendor: OpenGL ES 3.2 NVIDIA 384.130
    extensions:
      - GL_EXT_base_instance
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_color_buffer_half_float
      - GL_EXT_copy_image
      - GL_EXT_debug_label
      - GL_EXT_discard_framebuffer
      - GL_EXT_disjoint_timer_query
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_float_blend
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_indirect
      - GL_EXT_multisample_compatibility
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_protected_textures
      - GL_EXT_render_snorm
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_group_vote
      - GL_EXT_shader_implicit_conversions
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_shader_non_constant_global_initializers
      - GL_EXT_shader_texture_lod
      - GL_EXT_shadow_samplers
      - GL_EXT_sparse_texture
      - GL_EXT_sRGB
      - GL_EXT_sRGB_write_control
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_norm16
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_R8
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_storage
      - GL_EXT_texture_view
      - GL_EXT_draw_transform_feedback
      - GL_EXT_unpack_subimage
      - GL_EXT_window_rectangles
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_NV_bgr
      - GL_NV_blend_equation_advanced
      - GL_NV_conditional_render
      - GL_NV_copy_buffer
      - GL_NV_copy_image
      - GL_NV_draw_buffers
      - GL_NV_draw_instanced
      - GL_NV_draw_texture
      - GL_NV_EGL_stream_consumer_external
      - GL_NV_explicit_attrib_location
      - GL_NV_fbo_color_attachments
      - GL_NV_framebuffer_blit
      - GL_NV_framebuffer_multisample
      - GL_NV_generate_mipmap_sRGB
      - GL_NV_instanced_arrays
      - GL_NV_internalformat_sample_query
      - GL_NV_gpu_shader5
      - GL_NV_image_formats
      - GL_NV_occlusion_query_samples
      - GL_NV_non_square_matrices
      - GL_NV_pack_subimage
      - GL_NV_packed_float
      - GL_NV_packed_float_linear
      - GL_NV_path_rendering
      - GL_NV_pixel_buffer_object
      - GL_NV_polygon_mode
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_NV_shader_noperspective_interpolation
      - GL_NV_shadow_samplers_array
      - GL_NV_shadow_samplers_cube
      - GL_NV_sRGB_formats
      - GL_NV_texture_array
      - GL_NV_texture_barrier
      - GL_NV_texture_border_clamp
      - GL_NV_texture_compression_latc
      - GL_NV_texture_compression_s3tc
      - GL_NV_texture_compression_s3tc_update
      - GL_NV_timer_query
      - GL_NV_viewport_array
      - GL_KHR_blend_equation_advanced
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_OES_depth24
      - GL_OES_depth32
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_copy_image
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_texture_border_clamp
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_buffer
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_gpu_shader5
      - GL_OES_shader_io_blocks
      - GL_OES_texture_view
      - GL_OES_primitive_bounding_box
      - GL_OES_EGL_image
      - GL_OES_EGL_sync
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_get_program_binary
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_surfaceless_context
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_npot
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array
      - GL_ANDROID_extension_pack_es31a

**Comment by gitwasil** [comment]
Can you please tell me what is wrong ?

**Comment by LagHD** [comment]
For me, when I try opening Anbox it pops up with the starting screen but never loads and crashes after a while

**Comment by nachitox** [comment]
I have the same problem:

```
nachitox@xotihcan:~$ anbox.appmgr
[ 2018-08-22 13:45:29] [launch.cpp:182@operator()] Session manager is not yet running, trying to start it
[ 2018-08-22 13:45:29] [launch.cpp:116@launch_session_manager] Started session manager, will now try to connect ..
/usr/share/libdrm/amdgpu.ids: No such file or directory
[ 2018-08-22 13:45:30] [splash_screen.cpp:50@SplashScreen] Window has no associated renderer yet, creating one ...
[ 2018-08-22 13:46:20] [daemon.cpp:61@Run] Application manager service is not running yet
```

[anbox-system-diagnostics-2018-08-22.zip](https://github.com/anbox/anbox/files/2310577/anbox-system-diagnostics-2018-08-22.zip)

I installed the edge version.

**Comment by Canx** [comment]
Same here. with debug enabled I execute:

$ anbox session-manager
anbox session-manager
[ 2018-09-16 07:09:32] [Renderer.cpp:168@initialize] Using a surfaceless EGL context
[ 2018-09-16 07:09:32] [Renderer.cpp:251@initialize] Successfully initialized EGL
[ 2018-09-16 07:09:32] [service.cpp:41@Service] Successfully acquired DBus service name
[ 2018-09-16 07:09:35] [session_manager.cpp:228@operator()] Android successfully booted

but no Windows appear...

I attach logs.
[anbox-system-diagnostics-2018-09-16.zip](https://github.com/anbox/anbox/files/2386369/anbox-system-diagnostics-2018-09-16.zip)

**Comment by sawdustdood** [comment]
Same problem here.  May this is simply based in the snap image not having the /usr/share/libdrm/amdgpu.ids file which is present in the base OS image?  This file apparently appears to simply map the device nodes with the type of video card.  I'm curious if this is as simple as adding this file to the snap image.

e.g:
from dmesg:
`
[    2.613088] [drm] initializing kernel modesetting (POLARIS10 0x1002:0x67DF 0x1462:0x3418 0xE7).
`
from: amdgpu.ids
`
67DF,   EF,     Radeon RX 570 Series
`

`$ cat /usr/share/libdrm/amdgpu.ids
# List of AMDGPU IDs
#
# Syntax:
# device_id,	revision_id,	product_name        <-- single tab after comma

1.0.0
6600,	0,	AMD Radeon HD 8600/8700M
6600,	81,	AMD Radeon (TM) R7 M370
6601,	0,	AMD Radeon (TM) HD 8500M/8700M
6604,	0,	AMD Radeon R7 M265 Series
6604,	81,	AMD Radeon (TM) R7 M350
6605,	0,	AMD Radeon R7 M260 Series
6605,	81,	AMD Radeon (TM) R7 M340
6606,	0,	AMD Radeon HD 8790M
6607,	0,	AMD Radeon (TM) HD8530M
6608,	0,	AMD FirePro W2100
6610,	0,	AMD Radeon HD 8600 Series
6610,	81,	AMD Radeon (TM) R7 350
6610,	83,	AMD Radeon (TM) R5 340
6611,	0,	AMD Radeon HD 8500 Series
6613,	0,	AMD Radeon HD 8500 series
6617,	C7,	AMD Radeon R7 240 Series
6640,	0,	AMD Radeon HD 8950
6640,	80,	AMD Radeon (TM) R9 M380
6646,	0,	AMD Radeon R9 M280X
6646,	80,	AMD Radeon (TM) R9 M470X
6647,	0,	AMD Radeon R9 M270X
6647,	80,	AMD Radeon (TM) R9 M380
6649,	0,	AMD FirePro W5100
6658,	0,	AMD Radeon R7 200 Series
665C,	0,	AMD Radeon HD 7700 Series
665D,	0,	AMD Radeon R7 200 Series
665F,	81,	AMD Radeon (TM) R7 300 Series
6660,	0,	AMD Radeon HD 8600M Series
6660,	81,	AMD Radeon (TM) R5 M335
6660,	83,	AMD Radeon (TM) R5 M330
6663,	0,	AMD Radeon HD 8500M Series
6663,	83,	AMD Radeon (TM) R5 M320
6664,	0,	AMD Radeon R5 M200 Series
6665,	0,	AMD Radeon R5 M200 Series
6665,	83,	AMD Radeon (TM) R5 M320
6667,	0,	AMD Radeon R5 M200 Series
666F,	0,	AMD Radeon HD 8500M
6780,	0,	ATI FirePro V (FireGL V) Graphics Adapter
678A,	0,	ATI FirePro V (FireGL V) Graphics Adapter
6798,	0,	AMD Radeon HD 7900 Series
679A,	0,	AMD Radeon HD 7900 Series
679B,	0,	AMD Radeon HD 7900 Series
679E,	0,	AMD Radeon HD 7800 Series
67A0,	0,	AMD Radeon FirePro W9100
67A1,	0,	AMD Radeon FirePro W8100
67B0,	0,	AMD Radeon R9 200 Series
67B0,	80,	AMD Radeon (TM) R9 390 Series
67B1,	0,	AMD Radeon R9 200 Series
67B1,	80,	AMD Radeon (TM) R9 390 Series
67B9,	0,	AMD Radeon R9 200 Series
67DF,	C1,	Radeon RX 580 Series
67DF,	C2,	Radeon RX 570 Series
67DF,	C3,	Radeon RX 580 Series
67DF,	C4,	AMD Radeon (TM) RX 480 Graphics
67DF,	C5,	AMD Radeon (TM) RX 470 Graphics
67DF,	C6,	Radeon RX 570 Series
67DF,	C7,	AMD Radeon (TM) RX 480 Graphics
67DF,	CF,	AMD Radeon (TM) RX 470 Graphics
67DF,	D7,	Radeon(TM) RX 470 Graphics
67DF,	E3,	Radeon RX Series
67DF,	E7,	Radeon RX 580 Series
67DF,	EF,	Radeon RX 570 Series
67C2,	01,	AMD Radeon (TM) Pro V7350x2
67C2,	02,	AMD Radeon (TM) Pro V7300X
67C4,	00,	AMD Radeon (TM) Pro WX 7100 Graphics
67C7,	00,	AMD Radeon (TM) Pro WX 5100 Graphics
67C0,	00,	AMD Radeon (TM) Pro WX 7100 Graphics
67D0,	01,	AMD Radeon (TM) Pro V7350x2
67D0,	02,	AMD Radeon (TM) Pro V7300X
67E0,	00,	AMD Radeon (TM) Pro WX Series
67E3,	00,	AMD Radeon (TM) Pro WX 4100
67E8,	00,	AMD Radeon (TM) Pro WX Series
67E8,	01,	AMD Radeon (TM) Pro WX Series
67E8,	80,	AMD Radeon (TM) E9260 Graphics
67EB,	00,	AMD Radeon (TM) Pro V5300X
67EF,	C0,	AMD Radeon (TM) RX Graphics
67EF,	C1,	AMD Radeon (TM) RX 460 Graphics
67EF,	C3,	Radeon RX Series
67EF,	C5,	AMD Radeon (TM) RX 460 Graphics
67EF,	C7,	AMD Radeon (TM) RX Graphics
67EF,	CF,	AMD Radeon (TM) RX 460 Graphics
67EF,	E0,	Radeon RX 560 Series
67EF,	E1,	Radeon RX Series
67EF,	E3,	Radeon RX Series
67EF,	E5,	Radeon RX 560 Series
67EF,	EF,	AMD Radeon (TM) RX Graphics
67EF,	FF,	Radeon(TM) RX 460 Graphics
67FF,	C0,	AMD Radeon (TM) RX Graphics
67FF,	C1,	AMD Radeon (TM) RX Graphics
67FF,	CF,	Radeon RX 560 Series
67FF,	EF,	Radeon RX 560 Series
67FF,	FF,	Radeon RX 550 Series
6800,	0,	AMD Radeon HD 7970M
6801,	0,	AMD Radeon(TM) HD8970M
6808,	0,	ATI FirePro V(FireGL V) Graphics Adapter
6809,	0,	ATI FirePro V(FireGL V) Graphics Adapter
6810,	0,	AMD Radeon(TM) HD 8800 Series
6810,	81,	AMD Radeon (TM) R7 370 Series
6811,	0,	AMD Radeon(TM) HD8800 Series
6811,	81,	AMD Radeon (TM) R7 300 Series
6818,	0,	AMD Radeon HD 7800 Series
6819,	0,	AMD Radeon HD 7800 Series
6820,	0,	AMD Radeon HD 8800M Series
6820,	81,	AMD Radeon (TM) R9 M375
6820,	83,	AMD Radeon (TM) R9 M375X
6821,	0,	AMD Radeon HD 8800M Series
6821,	87,	AMD Radeon (TM) R7 M380
6821,	83,	AMD Radeon R9 (TM) M370X
6822,	0,	AMD Radeon E8860
6823,	0,	AMD Radeon HD 8800M Series
6825,	0,	AMD Radeon HD 7800M Series
6827,	0,	AMD Radeon HD 7800M Series
6828,	0,	ATI FirePro V(FireGL V) Graphics Adapter
682B,	0,	AMD Radeon HD 8800M Series
682B,	87,	AMD Radeon (TM) R9 M360
682C,	0,	AMD FirePro W4100
682D,	0,	AMD Radeon HD 7700M Series
682F,	0,	AMD Radeon HD 7700M Series
6835,	0,	AMD Radeon R7 Series / HD 9000 Series
6837,	0,	AMD Radeon HD7700 Series
683D,	0,	AMD Radeon HD 7700 Series
683F,	0,	AMD Radeon HD 7700 Series
6860,	00,	Radeon Instinct MI25
6860,	01,	Radeon Pro V320
6860,	02,	Radeon Instinct MI25
6860,	03,	Radeon Pro V340
6860,	04,	Radeon Instinct MI25x2
6861,	00,	Radeon(TM) Pro WX9100
6862,	00,	Radeon Pro SSG
6863,	00,	Radeon Vega Frontier Edition
6864,	03,	Radeon Pro V340
6864,	04,	Instinct MI25x2
6868,	00,	Radeon(TM) Pro WX8100
686C,	00,	GLXT (Radeon Instinct MI25) MxGPU VFID
686C,	01,	GLXT (Radeon Pro V320) MxGPU
686C,	02,	GLXT (Radeon Instinct MI25) MxGPU
686C,	03,	GLXT (Radeon Pro V340) MxGPU
686C,	04,	GLXT (Radeon Instinct MI25x2) MxGPU
687F,	C0,	Radeon RX Vega
687F,	C1,	Radeon RX Vega
687F,	C3,	Radeon RX Vega
6900,	0,	AMD Radeon R7 M260
6900,	81,	AMD Radeon (TM) R7 M360
6900,	83,	AMD Radeon (TM) R7 M340
6901,	0,	AMD Radeon R5 M255
6907,	0,	AMD Radeon R5 M255
6907,	87,	AMD Radeon (TM) R5 M315
6920,	0,	AMD RADEON R9 M395X
6920,	1,	AMD RADEON R9 M390X
6921,	0,	AMD Radeon R9 M295X
6929,	0,	AMD FirePro S7150
692B,	0,	AMD FirePro W7100
6938,	0,	AMD Radeon R9 200 Series
6938,	F0,	AMD Radeon R9 200 Series
6938,	F1,	AMD Radeon (TM) R9 380 Series
6939,	F0,	AMD Radeon R9 200 Series
6939,	0,	AMD Radeon R9 200 Series
6939,	F1,	AMD Radeon (TM) R9 380 Series
6980,	00,	Radeon Pro WX3100
6985,	00,	AMD Radeon Pro WX3100
6987,	80,	AMD Embedded Radeon E9171
6995,	00,	AMD Radeon Pro WX2100
6997,	00,	Radeon Pro WX2100
699F,	81,	AMD Embedded Radeon E9170 Series
699F,	C0,	Radeon 500 Series
699F,	C3,	Radeon 500 Series
699F,	C7,	Radeon RX 550 Series
7300,	C1,	AMD FirePro (TM) S9300 x2
7300,	C8,	AMD Radeon (TM) R9 Fury Series
7300,	C9,	Radeon (TM) Pro Duo
7300,	CB,	AMD Radeon (TM) R9 Fury Series
7300,	CA,	AMD Radeon (TM) R9 Fury Series
9874,	C4,	AMD Radeon R7 Graphics
9874,	C5,	AMD Radeon R6 Graphics
9874,	C6,	AMD Radeon R6 Graphics
9874,	C7,	AMD Radeon R5 Graphics
9874,	C8,	AMD Radeon R7 Graphics
9874,	81,	AMD Radeon R6 Graphics
9874,	87,	AMD Radeon R5 Graphics
9874,	85,	AMD Radeon R6 Graphics
9874,	84,	AMD Radeon R7 Graphics`

**Comment by simbiotiqu** [comment]
Experience similar issue in Solus with the anbox snap in edge version

6. ** Please paste the result of `anbox system-info` below:**
```
/usr/share/libdrm/amdgpu.ids: No such file or directory
version: 4
snap-revision: 158
cpu:
  arch:  x86
  brand: AMD Ryzen 5 2400G with Radeon Vega Graphics    
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Solus
  version: 3.9999
  snap-based: true
kernel:
  version: Linux version 4.18.12-94.current (root@paddedroom) (gcc version 8.2.0 (Solus)) #1 SMP PREEMPT Tue Oct 9 11:28:00 UTC 2018
  binder: false
  ashmem: false
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: X.Org
    vendor: OpenGL ES 3.1 Mesa 18.0.5
    extensions:
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_base_instance
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_memory_object
      - GL_EXT_memory_object_fd
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_read_format_bgra
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_image_formats
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_get_program_binary
      - GL_OES_gpu_shader5
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_primitive_bounding_box
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array
```
[anbox-system-diagnostics-2018-10-26.zip](https://github.com/anbox/anbox/files/2520603/anbox-system-diagnostics-2018-10-26.zip)
