### ISSUE TITLE
Invalid argument - Failed to write gid mapping

### ISSUE THREAD

**Issue by NyaMisty** [anbox/anbox#837]
Result of `sudo /snap/bin/anbox.collect-bug-info `:[GoogleDrive](https://drive.google.com/file/d/1AnMFDWmht1zpsWyNrgXc_GiN1V7_hamC/view?usp=sharing)

Result of `anbox system-info`:
```
version: 4
snap-revision: 133
cpu:
  arch:  x86
  brand: Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz
  features:
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 16.04.4 LTS (Xenial Xerus)
  snap-based: true
kernel:
  version: Linux version 4.15.0-29-generic (buildd@lcy01-amd64-024) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)) #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions:
      - n/a
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []
```

**Please describe your problem:**
I'm trying to run the anbox on a VPS without graphics card, because I noticed the newly introduced Software Rendering option.
After reading the source code for a while, I guess I can run the anbox with 
`ANBOX_PLATFORM="" anbox session-manager --software-rendering`
And it works fine until the program tries to start the container.
I've had a look at the containers.log and the failing step is:
```
lxc 20180728182451.902 WARN     lxc_conf - conf.c:lxc_map_ids:2855 - newuidmap binary is missing
lxc 20180728182451.902 WARN     lxc_conf - conf.c:lxc_map_ids:2861 - newgidmap binary is missing
lxc 20180728182451.902 DEBUG    lxc_conf - conf.c:lxc_map_ids:2875 - No newuidmap and newgidmap binary found. Trying to write directly with euid 0
lxc 20180728182451.902 TRACE    lxc_conf - conf.c:lxc_map_ids:2929 - Wrote mapping "0 100000 109
1000 110 1
1001 101001 65425
"
lxc 20180728182451.902 INFO     lxc_caps - caps.c:lxc_ambient_caps_up:175 - Last supported cap was 36
lxc 20180728182451.902 ERROR    lxc_conf - conf.c:write_id_mapping:2742 - Invalid argument - Failed to write gid mapping to "/proc/8227/gid_map"
lxc 20180728182451.902 ERROR    lxc_conf - conf.c:lxc_map_ids:2926 - Failed to write mapping: 0 100000 65533
1000 65534 1
1001 101001 1

lxc 20180728182451.902 ERROR    lxc_start - start.c:lxc_spawn:1661 - Failed to set up id mapping.
```
I doubt it's lxc's bug, but I can't find any helpful clues about that

**What were you expecting?:**
I'm expecting the container starting normally.

**Additional info:**
