### ISSUE TITLE
"Power off - Shutting down..." message when launching "anbox session-manager --single-window", likely due to BatteryService crash

### ISSUE THREAD

**Issue by jave27** [anbox/anbox#841]
5. Run the anbox logs collection utility and attach the tar file.

[anbox-system-diagnostics-2018-08-01.zip](https://github.com/anbox/anbox/files/2250622/anbox-system-diagnostics-2018-08-01.zip)

6. ** Please paste the result of `anbox system-info` below:**
```
version: 4
snap-revision: 133
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 16.04.5 LTS (Xenial Xerus)
  snap-based: true
kernel:
  version: Linux version 4.15.0-29-generic (buildd@lcy01-amd64-024) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)) #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: NVIDIA
    version: 1.4
    extensions:
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_output_base
      - EGL_EXT_stream_acquire_mode
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context_no_error
      - EGL_KHR_context_flush_control
      - EGL_KHR_create_context
      - EGL_KHR_display_reference
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_partial_update
      - EGL_KHR_swap_buffers_with_damage
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_stream
      - EGL_KHR_stream_consumer_gltexture
      - EGL_KHR_stream_cross_process_fd
      - EGL_KHR_stream_fifo
      - EGL_KHR_stream_producer_eglsurface
      - EGL_KHR_surfaceless_context
      - EGL_NV_nvrm_fence_sync
      - EGL_NV_post_sub_buffer
      - EGL_NV_stream_metadata
      - EGL_NV_stream_reset
      - EGL_NV_stream_sync
      - EGL_NV_stream_consumer_gltexture_yuv
      - EGL_NV_stream_attrib
      - EGL_NV_sync
      - EGL_NV_system_time
      - EGL_NV_output_drm_flip_event
  gles2:
    vendor: NVIDIA Corporation
    vendor: OpenGL ES 3.2 NVIDIA 396.24
    extensions:
      - GL_EXT_base_instance
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clear_texture
      - GL_EXT_clip_control
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_color_buffer_half_float
      - GL_EXT_conservative_depth
      - GL_EXT_copy_image
      - GL_EXT_debug_label
      - GL_EXT_discard_framebuffer
      - GL_EXT_disjoint_timer_query
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_float_blend
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_indirect
      - GL_EXT_multisample_compatibility
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_post_depth_coverage
      - GL_EXT_primitive_bounding_box
      - GL_EXT_raster_multisample
      - GL_EXT_render_snorm
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_group_vote
      - GL_EXT_shader_implicit_conversions
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_shader_non_constant_global_initializers
      - GL_EXT_shader_texture_lod
      - GL_EXT_shadow_samplers
      - GL_EXT_sparse_texture
      - GL_EXT_sparse_texture2
      - GL_EXT_sRGB
      - GL_EXT_sRGB_write_control
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_bptc
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_rgtc
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_filter_minmax
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_mirror_clamp_to_edge
      - GL_EXT_texture_norm16
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_R8
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_storage
      - GL_EXT_texture_view
      - GL_EXT_draw_transform_feedback
      - GL_EXT_unpack_subimage
      - GL_EXT_window_rectangles
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_EXT_memory_object
      - GL_EXT_memory_object_fd
      - GL_KHR_parallel_shader_compile
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_EXT_semaphore
      - GL_EXT_semaphore_fd
      - GL_NV_bgr
      - GL_NV_bindless_texture
      - GL_NV_blend_equation_advanced
      - GL_NV_blend_equation_advanced_coherent
      - GL_NVX_blend_equation_advanced_multi_draw_buffers
      - GL_NV_blend_minmax_factor
      - GL_NV_clip_space_w_scaling
      - GL_NV_conditional_render
      - GL_NV_conservative_raster
      - GL_NV_conservative_raster_pre_snap_triangles
      - GL_NV_copy_buffer
      - GL_NV_copy_image
      - GL_NV_draw_buffers
      - GL_NV_draw_instanced
      - GL_NV_draw_texture
      - GL_NV_draw_vulkan_image
      - GL_NV_EGL_stream_consumer_external
      - GL_NV_explicit_attrib_location
      - GL_NV_fbo_color_attachments
      - GL_NV_fill_rectangle
      - GL_NV_fragment_coverage_to_color
      - GL_NV_fragment_shader_interlock
      - GL_NV_framebuffer_blit
      - GL_NV_framebuffer_mixed_samples
      - GL_NV_framebuffer_multisample
      - GL_NV_generate_mipmap_sRGB
      - GL_NV_geometry_shader_passthrough
      - GL_NV_instanced_arrays
      - GL_NV_internalformat_sample_query
      - GL_NV_gpu_shader5
      - GL_NV_image_formats
      - GL_NV_occlusion_query_samples
      - GL_NV_non_square_matrices
      - GL_NV_pack_subimage
      - GL_NV_packed_float
      - GL_NV_packed_float_linear
      - GL_NV_path_rendering
      - GL_NV_path_rendering_shared_edge
      - GL_NV_pixel_buffer_object
      - GL_NV_polygon_mode
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_NV_sample_locations
      - GL_NV_sample_mask_override_coverage
      - GL_NV_shader_atomic_fp16_vector
      - GL_NV_shader_noperspective_interpolation
      - GL_NV_shadow_samplers_array
      - GL_NV_shadow_samplers_cube
      - GL_NV_sRGB_formats
      - GL_NV_stereo_view_rendering
      - GL_NV_texture_array
      - GL_NV_texture_barrier
      - GL_NV_texture_border_clamp
      - GL_NV_texture_compression_latc
      - GL_NV_texture_compression_s3tc
      - GL_NV_texture_compression_s3tc_update
      - GL_NV_timer_query
      - GL_NV_viewport_array
      - GL_NV_viewport_array2
      - GL_NV_viewport_swizzle
      - GL_KHR_blend_equation_advanced
      - GL_KHR_blend_equation_advanced_coherent
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_OES_depth24
      - GL_OES_depth32
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_copy_image
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_texture_border_clamp
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_buffer
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_gpu_shader5
      - GL_OES_shader_io_blocks
      - GL_OES_texture_view
      - GL_OES_primitive_bounding_box
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_image_external_essl3
      - GL_OES_EGL_sync
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_get_program_binary
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_surfaceless_context
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_npot
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array
      - GL_ANDROID_extension_pack_es31a
```

**Please describe your problem:**

When I run `anbox session-manager --single-window`, I get this screenshot:

 ![anbox_poweroff](https://user-images.githubusercontent.com/308079/43541001-e50bfc36-958e-11e8-89d1-143414040be5.png)

as well as this part of the logcat message which shows Android trying to shut down:

```
08-01 18:27:17.367   108   108 I SystemServiceManager: Starting com.android.server.BatteryService
08-01 18:27:17.367   108   108 I SystemServer: Error when trying to start BatteryService
08-01 18:27:17.367   108   108 E System  : ******************************************
08-01 18:27:17.368   108   108 E System  : ************ Failure starting system services
08-01 18:27:17.368   108   108 E System  : java.lang.RuntimeException: Failed to start service com.android.server.BatteryService: onStart threw an exception
08-01 18:27:17.368   108   108 E System  :      at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:114)
08-01 18:27:17.368   108   108 E System  :      at com.android.server.SystemServer.startCoreServices(SystemServer.java:510)
08-01 18:27:17.368   108   108 E System  :      at com.android.server.SystemServer.run(SystemServer.java:333)
08-01 18:27:17.368   108   108 E System  :      at com.android.server.SystemServer.main(SystemServer.java:219)
08-01 18:27:17.368   108   108 E System  :      at java.lang.reflect.Method.invoke(Native Method)
08-01 18:27:17.368   108   108 E System  :      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
08-01 18:27:17.368   108   108 E System  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
08-01 18:27:17.368   108   108 E System  : Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void android.os.IBatteryPropertiesRegistrar.registerListener(android.os.IBatteryPropertiesListener)' on a null object reference
08-01 18:27:17.368   108   108 E System  :      at com.android.server.BatteryService.onStart(BatteryService.java:196)
08-01 18:27:17.368   108   108 E System  :      at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:112)
08-01 18:27:17.368   108   108 E System  :      ... 6 more
08-01 18:27:17.368   108   108 D AndroidRuntime: Shutting down VM
--------- beginning of crash
08-01 18:27:17.368   108   108 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
08-01 18:27:17.368   108   108 E AndroidRuntime: java.lang.RuntimeException: Failed to start service com.android.server.BatteryService: onStart threw an exception
08-01 18:27:17.368   108   108 E AndroidRuntime:        at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:114)
08-01 18:27:17.368   108   108 E AndroidRuntime:        at com.android.server.SystemServer.startCoreServices(SystemServer.java:510)
08-01 18:27:17.368   108   108 E AndroidRuntime:        at com.android.server.SystemServer.run(SystemServer.java:333)
08-01 18:27:17.368   108   108 E AndroidRuntime:        at com.android.server.SystemServer.main(SystemServer.java:219)
08-01 18:27:17.368   108   108 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-01 18:27:17.368   108   108 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
08-01 18:27:17.368   108   108 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
08-01 18:27:17.368   108   108 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void android.os.IBatteryPropertiesRegistrar.registerListener(android.os.IBatteryPropertiesListener)' on a null object reference
08-01 18:27:17.368   108   108 E AndroidRuntime:        at com.android.server.BatteryService.onStart(BatteryService.java:196)
08-01 18:27:17.368   108   108 E AndroidRuntime:        at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:112)
```

**What were you expecting?:**

I expected to be able to launch Android applications, but the application manager is in a frozen state at this point, and I can't click on any of the icons or interact with Android in any way outside of basic "adb shell" type commands.

**Additional info:**

Things I've tried:
- Beta build, Edge build, compiling my own anbox
- Different NVIDIA driver versions (384 and 396)
- Recompiling the ashmem_linux and binder_linux kernel modules as well as trying the ones in the PPA
- Ubuntu 16.04 LTS and 18.04 LTS (started with 18.04, but these logs are from a fresh install of 16.04 on the same system).
- When running without "--single-window", nothing appears to happen on-screen. When running "anbox.appmgr", I don't see the "Power off" dialog, but none of the icons are clickable inside of the application manager, so I suspect the same crash is occurring.
