### ISSUE TITLE
Fortnite - Device Not Supported

### ISSUE THREAD

**Issue by Conzar** [anbox/anbox#856]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
version: 4
snap-revision: 136
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  features:
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 16.04.5 LTS (Xenial Xerus)
  snap-based: true
......
```
Remaining info here: https://pastebin.com/CzxKkuny

**Please describe your problem:**
Fortnite displays: 'Device Not Supported'

**What were you expecting?:**
Fortnite to load and run

**Additional info:**
