### ISSUE TITLE
*** stack smashing detected ***

### ISSUE THREAD

**Issue by Gooberpatrol66** [anbox/anbox#960]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
nathan@gentoolaptop ~ $ anbox system-info
version: local-e1ecd04
cpu:
  arch:  x86
  brand: AMD Phenom(tm) II N620 Dual-Core Processor
  features: 
os:
  name: Gentoo
  version: 
  snap-based: false
kernel:
  version: Linux version 4.14.65-gentoo (root@gentoolaptop) (gcc version 7.3.0 (Gentoo 7.3.0-r3 p1.4)) #6 SMP PREEMPT Tue Oct 23 22:26:11 CDT 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: X.Org
    vendor: OpenGL ES 3.0 Mesa 18.1.9
    extensions:
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_base_instance
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_read_format_bgra
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_integer_mix
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_image_external_essl3
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_get_program_binary
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float

```

**Please describe your problem:**
core dump

**What were you expecting?:**
app manager launch

**Additional info:**
```
nathan@gentoolaptop ~ $ ANBOX_LOG_LEVEL=debug anbox launch --package-org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
*** stack smashing detected ***: <unknown> terminated
Stack trace (most recent call last):
#15   Object "", at 0xffffffffffffffff, in 
#14   Object "/usr/bin/anbox", at 0x56078e1e3249, in _start
#13   Object "/lib64/libc-2.27.so", at 0x7f58f867bae6, in __libc_start_main
#12   Object "/usr/bin/anbox", at 0x56078e1de0fd, in main
#11   Object "/usr/bin/anbox", at 0x56078e1edb8e, in anbox::Daemon::Run(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
#10   Object "/usr/bin/anbox", at 0x56078e1e6e59, in anbox::cli::CommandWithSubcommands::run(anbox::cli::Command::Context const&)
#9    Object "/usr/bin/anbox", at 0x56078e1e71b3, in anbox::cli::CommandWithFlagsAndAction::run(anbox::cli::Command::Context const&)
#8    Object "/usr/bin/anbox", at 0x56078e1ff40e, in 
#7    Object "/usr/bin/anbox", at 0x56078e20eeff, in anbox::dbus::stub::ApplicationManager::create_for_bus(std::shared_ptr<anbox::dbus::Bus> const&)
#6    Object "/usr/bin/anbox", at 0x56078e20ee70, in anbox::dbus::stub::ApplicationManager::ApplicationManager(std::shared_ptr<anbox::dbus::Bus> const&)
#5    Object "/usr/bin/anbox", at 0x56078e20ec6e, in anbox::dbus::stub::ApplicationManager::update_properties()
#4    Object "/lib64/libc-2.27.so", at 0x7f58f87722f1, in __stack_chk_fail
#3    Object "/lib64/libc-2.27.so", at 0x7f58f8772345, in 
#2    Object "/lib64/libc-2.27.so", at 0x7f58f86d7086, in 
#1    Object "/lib64/libc-2.27.so", at 0x7f58f8692050, in abort
#0    Object "/lib64/libc-2.27.so", at 0x7f58f869080b, in raise
Aborted (Signal sent by tkill() 5548 1000)
Aborted (core dumped)
```
