### ISSUE TITLE
sudo anbox.appmgr crashes

### ISSUE THREAD

**Issue by neo-expert** [anbox/anbox#983]
[anbox-system-diagnostics-2018-11-21.zip](https://github.com/anbox/anbox/files/2604152/anbox-system-diagnostics-2018-11-21.zip)

6. ** Please paste the result of `anbox system-info` below:**
```
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
No protocol specified
No protocol specified
No protocol specified
No protocol specified
version: 4
snap-revision: 163
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 18.04.1 LTS (Bionic Beaver)
  snap-based: true
kernel:
  version: Linux version 4.15.0-39-generic (buildd@lgw01-amd64-054) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions:
      - n/a
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

```

**Please describe your problem:**
➜  ~ sudo anbox.appmgr                    
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
[ 2018-11-21 12:18:37] [daemon.cpp:61@Run] Failed to connect to DBus
➜  ~ 

**What were you expecting?:**
something else
